openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: moderation

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [moderation]
      summary: GenerateIdentifyToken
      description: |
        When you use third-party audio/video stream moderation services, you need to use this API to generate an `IdentifyToken` and pass it to the moderation service provider for authentication.

        Currently supported vendors include ShuMei, NetEase Yidun, TuPu, YiTu, and Volcengine. The complete integration process is as follows:

        ### ShuMei

        1. Complete the integration with ShuMei's [Intelligent Audio Stream Recognition](https://www.ishumei.com/new/product/tj/audio) and [Intelligent Video Stream Recognition](https://www.ishumei.com/new/product/tj/video) products.
        2. Call this server API to obtain the `IdentifyToken`.
        3. Call ShuMei's [Audio Stream Upload Request API](https://help.ishumei.com/docs/tj/audioStream/versionV4/async/developDoc) or [Video Stream Upload Request API](https://help.ishumei.com/docs/tj/videoStream/versionV4/requestInterface/developDoc) to initiate a request, and assign the `IdentifyToken` to the `Token` parameter in the request.

        ### NetEase Yidun

        1. Complete the integration with NetEase Yidun's moderation functionality [Audio/Video Solution](https://support.dun.163.com/documents/594247746924453888?docId=600827338598789120#%E5%8D%B3%E6%9E%84).
        2. Call this server API to obtain the `IdentifyToken`.
        3. Call NetEase Yidun's [Async Detection API](https://support.dun.163.com/documents/594247746924453888?docId=600827510305206272) to initiate a request, and assign the `IdentifyToken` to the `Token` parameter in the request.

        ### TuPu

        1. Complete the integration with TuPu's [ZEGO Audio Stream Async API](https://docs-site.cloud.tuputech.com/docs/api/speech/speech-stream/stream-zego/).
        2. Call this server API to obtain the `IdentifyToken`.
        3. Call TuPu's [ZEGO Audio Stream Async API](https://docs-site.cloud.tuputech.com/docs/api/speech/speech-stream/stream-zego/) to initiate a request, and assign the `IdentifyToken` to the `Token` parameter in the request.

        ### YiTu and Volcengine

        1. Complete the integration with these two service providers' moderation functionality. For details, please contact the service provider's technical support.
        2. Call this server API to obtain the `IdentifyToken`.
        3. Call these two service providers' audio/video moderation APIs (for details, please contact the service provider's technical support) to initiate a request, and assign the `IdentifyToken` to the `Token` parameter in the request.

        <Warning title="Note">
        - Each `IdentifyToken` can only be used for one moderation request. Before starting each moderation, please regenerate one `IdentifyToken` to use.
        - Different vendors may have differences from this document due to version updates or other reasons in actual use. It is recommended to confirm with technical support before use.

        </Warning>
        <Note title="Rate Limit">For all rooms under the same AppID: 100 times/second</Note>

      operationId: generate-identify-token
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameters
            >
            > https://rtc-api.zego.im?Action=GenerateIdentifyToken
          required: true
          schema: { type: string, enum: [GenerateIdentifyToken] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - name: EffectiveTime
          in: query
          required: false
          schema: { type: integer, format: int64 }
          description: |
            The validity period of the stream moderation authentication Token.

            Unit: seconds, default is 3600 seconds; maximum cannot exceed 30 days (i.e., the value cannot exceed 60 * 60 * 24 * 30).
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateIdentifyTokenResponse'

components:
  schemas:
    GenerateIdentifyTokenResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: |
            Return code.
            Please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).
          example: 0
        Message:
          type: string
          description: Operation result description
          example: "success"
        RequestId:
          type: string
          description: Request ID
          example: "TestRequestId1653536127853122000"
        Data:
          type: object
          description: Response data
          properties:
            IdentifyToken:
              type: string
              description: Authentication Token
              example: "1234567890asdfasdfzxcvxxxxxxxxxx"
            RemainTime:
              type: integer
              format: int64
              description: |
                The validity period of the Token, which means that within the "validity period", you can initiate audio/video stream moderation to "ShuMei"; after the moderation task starts, the moderation user will not experience disconnection during normal stream moderation.

                Unit: seconds, default is 1 hour (3600 seconds).
              example: 3600

