openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: moderation

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    post:
      tags: [moderation]
      summary: StopCensorVideoV2
      description: |
        Call this API to end video stream content moderation.

        <Warning title="Note">
        Before using this API, please refer to [Console - Cloud Market - Shumei Content Moderation](/console/cloud-market/shumei-moderation) and follow the on-page instructions to enable the relevant permissions for `Shumei Content Moderation`.
        </Warning>

        <Note title="Rate Limit">For all rooms under the same AppID: 100 times/second</Note>
        ## FAQ

        1. **What happens if I start audio/video stream moderation API but don't call the stop audio/video stream moderation API?**

            It will automatically end after pulling an empty stream for about 5 minutes. It is recommended to actively call the API to end moderation when you finish moderating.

        2. **How do I identify which stream violated the rules in the audio/video stream moderation result callback?**

            After completing moderation, ShuMei will return multiple callbacks based on 10s audio segment AudioUrls. The current results do not directly expose streamID information, but you can obtain it by extracting information from resultTaskId.

            Example (assuming streamID is 0001, you can see that AudioUrl contains streamID 0001):
            <Frame width="auto" height="auto" >
            <img src="https://media-resource.spreading.io/docuo/workspace741/896bc39e2e65b82d5670b01b7c131c30/5852a1ffcc.png" />
            </Frame>
      operationId: stop-censor-video
      parameters:
        - name: Action
          in: query
          required: true
          description: |
            > API prototype parameters
            >
            > https://rtc-api.zego.im?Action=StopCensorVideoV2
          schema: { type: string, enum: [StopCensorVideoV2] }
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StopCensorVideoRequest'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopCensorVideoResponse'

components:
  schemas:
    StopCensorVideoRequest:
      type: object
      required: [TaskId]
      properties:
        TaskId:
          type: string
          description: Moderation task ID, can be obtained from the response parameters of the [start video stream moderation](/real-time-video-server/api-reference/moderation/start-censor-video) task.
          example: "9f58178ba8034902c6028c728bc6f6e4"
    StopCensorVideoResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: |
            Return code.
            The following only lists some return codes related to the API business logic. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).
            <table>
              <thead>
                <tr><th>Return Code</th><th>Description</th><th>Suggested Action</th></tr>
              </thead>
              <tbody>
                <tr><td>50006、50007</td><td>HTTP request failed.</td><td>Please retry later (recommended 300s), or contact ZEGOCLOUD Technical Support.</td></tr>
                <tr><td>50009</td><td>Moderation failed.</td><td>Please retry later (recommended 300s), or contact ZEGOCLOUD Technical Support.</td></tr>
                <tr><td>50117</td><td>Configuration error, ShuMei permissions not enabled.</td><td>Please contact ZEGOCLOUD Technical Support to enable ShuMei permissions.</td></tr>
              </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Operation result description
          example: "success"
        RequestId:
          type: string
          description: Request ID
          example: "TestRequestId1635941439344723000"

