openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - name: agent-instance-control

paths:
  /:
    post:
      tags:
        - agent-instance-control
      summary: StopListening
      description: 对讲机模式下，智能体结束聆听。对讲机模式开启请参考[创建智能体实例](/aiagent-server/api-reference/agent-instance-management/create-agent-instance)的 AdvancedConfig.CommunicationMode 参数说明。
      operationId: stop-listening
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=StopListening
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [StopListening]
          style: form
          explode: true
        # 引用共享的参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StopListeningRequest"
            example:
              AgentInstanceId: "1907755175297171456"
              Sequence: 2
      responses:
        "200":
          description: 结束聆听成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StopListeningResponse"

components:
  schemas:
    StopListeningRequest:
      type: object
      required:
        - AgentInstanceId
      properties:
        AgentInstanceId:
          type: string
          description: Agent 实例的唯一标识，全局唯一。
          example: "1907755175297171456"
        Sequence:
          type: integer
          format: int64
          description: 必须保证与 [StartListening](/aiagent-server/api-reference/agent-instance-control/start-listening) 接口的 Sequence 相同，实现开始与聆听配对操作。
          example: 2

    StopListeningResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 返回码，0 表示成功，其他值表示失败。详情请参考 [返回码](/aiagent-server/api-reference/return-codes) 说明。
          example: 0
        Message:
          type: string
          description: 请求结果说明
          example: "success"
        RequestId:
          type: string
          description: 请求 ID
          example: "8916619579948490296"

