openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - community

paths:
  /:
    get:
      tags: [community]
      summary: QueryAppCommunityList
      description: |
        Get the IDs of all communities in the App.

        <Warning title="Note">The retrieved data may have a delay of up to **1 minute**.</Warning>

        <Note title="QPS Limit"> 1 time/s</Note>
      operationId: query-community-list
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=QueryAppCommunityList
          required: true
          schema:
            type: string
            enum: [QueryAppCommunityList]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryAppCommunityListRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryAppCommunityListResponse'
              example:
                Code: 0
                Message: success
                RequestId: "343649807833778782"
                TotalCount: 1680
                Next: 2
                CommunityIdList:
                  - CommunityId: "CommunityA"
                    CommunityName: "CommunityNameA"
                  - CommunityId: "CommunityB"
                    CommunityName: "CommunityNameB"

components:
  schemas:
    QueryAppCommunityListRequest:
      type: object
      properties:
        Limit:
          type: number
          description: |
            The upper limit on the number of community IDs to retrieve this time, which must not exceed 10000. That is, calling this API returns a maximum of 10000 community IDs at a time.

            When the number of communities in the App exceeds the Limit, you need to call this API multiple times <b>and the Limit must remain consistent</b>.

            If it is empty or greater than 10000, the default value is 10000.
          minimum: 0
          maximum: 10000
          example: 1000
        Next:
          type: number
          description: |
            Pagination flag. Fill in 0 for the first time, and then fill in the value returned last time. When the returned Next is 0, it means the community list has been fully retrieved.

            For example, if there are 25,000 communities in the App, when calling this API to query the community list:

            - First call: Set Limit to 10000 and Next to 0 to query communities 1 to 10000; the Next value in the returned result is 1.
            - Second call: Set Limit to 10000 and Next to 1 to query communities 10001 to 20000; the Next value in the returned result is 2.
            - Third call: Set Limit to 10000 and Next to 2 to query communities 20001 to 25000; the query is complete, and the Next value in the returned result is 0.
          example: 0
    QueryAppCommunityListResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            The following only lists the return codes related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            <table>
            <thead><tr><th>Return code</th><th>Description</th><th>Suggested Solution</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>Parameter error.</td><td>Please refer to Request Parameters and enter the correct parameters.</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Description of the request result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        TotalCount:
          type: number
          description: Current total number of communities in the App.
          example: 1680
        Next:
          type: number
          description: |
            Pagination flag. When non-zero, it indicates that the list query is not complete.
            >**Note**
            >
            > Apart from the above description, this field has no association with the list information. Please do not base any other logic on this field.
          example: 2
        CommunityIdList:
          type: array
          description: Collection of retrieved community IDs.
          items:
            type: object
            properties:
              CommunityId:
                type: string
                description: Community ID.
                example: "CommunityA"
              CommunityName:
                type: string
                description: Community name.
                example: "CommunityNameA"
