openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: DelForbidStreamRule
      description: |
        Deletes the Stream publishing prohibition rule.
        <Note title="Rate Limit">All Rooms under the same AppID: 10 times/second.</Note>
        <Note title="Note">
          - You can use [Describe Stream publishing prohibition rules](./describe-forbid-stream-rules.mdx) to check whether the corresponding Stream publishing prohibition rule was successfully deleted.
          - If the prohibition rule for the specified Stream ID does not exist, calling this interface will not return an error.
        </Note>
      operationId: del-forbid-stream-rule
      parameters:
        - name: Action
          in: query
          description: |
            > Interface prototype parameter
            >
            > https://rtc-api.zego.im?Action=DelForbidStreamRule
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DelForbidStreamRule]
          style: form
          explode: true
        # Common parameters
        - $ref: '../../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../../shared-components.yaml#/components/parameters/SignatureVersion'
        # Business parameters
        - name: RoomId
          in: query
          description: Room ID.
          required: true
          schema:
            type: string
        - name: StreamId
          in: query
          description: Stream ID, with a maximum length of 256 bytes.
          required: true
          schema:
            type: string
            maxLength: 256
      responses:
        "200":
          description: Operation succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DelForbidStreamRuleResponse'

components:
  schemas:
    DelForbidStreamRuleResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          example: 0
          description: |
            Return code. The following only lists some return codes related to the interface business logic. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).

            <table>
              <thead>
                <tr>
                  <th>Return Code</th>
                  <th>Description</th>
                  <th>Suggested Action</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>0</td>
                  <td>Request succeeded.</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>Request failed.</td>
                  <td>Please contact ZEGOCLOUD technical support for assistance.</td>
                </tr>
                <tr>
                  <td>2</td>
                  <td>Input parameter error.</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>9</td>
                  <td>Permission to use this interface has not been granted.</td>
                  <td>Please contact ZEGOCLOUD technical support for assistance.</td>
                </tr>
                <tr>
                  <td>123</td>
                  <td>Failed to set Stream information.</td>
                  <td>Please retry, or contact ZEGOCLOUD technical support for assistance.</td>
                </tr>
                <tr>
                  <td>206</td>
                  <td>App request QPS is too high and is being rate-limited.</td>
                  <td>Reduce request frequency, or contact ZEGOCLOUD technical support to increase the QPS limit threshold.</td>
                </tr>
              </tbody>
            </table>
        Message:
          type: string
          example: success
          description: Description of the operation result.
        RequestId:
          type: string
          example: TestRequestId167562222222915000
          description: Request ID.
