openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: DescribeForbidStreamRules
      description: |
        Queries stream publishing prohibition rules.
        <Note title="Rate Limiting">All rooms under the same AppID: 10 times/second.</Note>
        <Note title="Note">If the queried Stream ID does not exist or no stream publishing prohibition rules have been set, all field values in the response will be 0, as shown in streamId2 in the response example.</Note>
        <Warning title="Attention">
          Calling the `DescribeForbidStreamRules` interface allows you to query both currently valid rules and expired rules. **Please note that ZEGOCLOUD periodically purges expired prohibition rules from the database, so the list of expired rules obtained by calling this interface may be incomplete.**
        </Warning>
      operationId: describe-forbid-stream-rules
      parameters:
        - name: Action
          in: query
          description: |
            > Prototype parameters
            >
            > https://rtc-api.zego.im?Action=DescribeForbidStreamRules
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DescribeForbidStreamRules]
          style: form
          explode: true
        # 公共参数
        - $ref: '../../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../../shared-components.yaml#/components/parameters/SignatureVersion'
        # 业务参数
        - name: RoomId
          in: query
          description: The Room ID to query.
          required: true
          schema:
            type: string
        - name: StreamId
          in: query
          description: The Stream ID to query. When calling this interface, you cannot query more than 10 Stream IDs.
          required: true
          schema:
            type: array
            items:
              type: string
            maxItems: 10
            minItems: 1
          style: form
          explode: true
      responses:
        "200":
          description: Operation succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeForbidStreamRulesResponse'
              example:
                Code: 0
                Data:
                  RoomId: room1
                  ForbidStreamRuleList:
                    - StreamId: streamId1
                      DisableAudio: 1
                      DisableVideo: 1
                      CreateTime: 1343313411
                      EffectiveTime: 3600
                    - StreamId: streamId2
                      DisableAudio: 0
                      DisableVideo: 0
                      CreateTime: 0
                      EffectiveTime: 0
                Message: success
                RequestId: TestRequestId1710224543000

components:
  schemas:
    DescribeForbidStreamRulesResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: |
            Return code. The following only lists some return codes related to the interface business logic. For the complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).

            <table>
              <thead>
                <tr>
                  <th>Return Code</th>
                  <th>Description</th>
                  <th>Suggested Action</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>0</td>
                  <td>Request succeeded.</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>Request failed.</td>
                  <td>Please contact ZEGOCLOUD technical support for assistance.</td>
                </tr>
                <tr>
                  <td>2</td>
                  <td>Input parameter error.</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>9</td>
                  <td>Permission to use this interface has not been granted.</td>
                  <td>Please contact ZEGOCLOUD technical support for assistance.</td>
                </tr>
                <tr>
                  <td>123</td>
                  <td>Failed to set stream information.</td>
                  <td>Please retry, or contact ZEGOCLOUD technical support for assistance.</td>
                </tr>
                <tr>
                  <td>206</td>
                  <td>App request QPS is too high and has been rate-limited.</td>
                  <td>Reduce request frequency, or contact ZEGOCLOUD technical support to increase the QPS limit threshold.</td>
                </tr>
              </tbody>
            </table>
        Message:
          type: string
          description: Description of the operation result.
        RequestId:
          type: string
          description: Request ID.
        Data:
          type: object
          properties:
            RoomId:
              type: string
              description: Room ID.
            ForbidStreamRuleList:
              type: array
              description: List of queried stream publishing prohibition rule information.
              items:
                $ref: '#/components/schemas/ForbidStreamRule'

    ForbidStreamRule:
      type: object
      properties:
        StreamId:
          type: string
          description: The queried Stream ID.
        DisableAudio:
          type: integer
          format: int32
          description: |
            Whether the audio corresponding to the Stream ID is prohibited. 0: Not prohibited; 1: Prohibited.
          enum: [0, 1]
        DisableVideo:
          type: integer
          format: int32
          description: |
            Whether the video corresponding to the Stream ID is prohibited. 0: Not prohibited; 1: Prohibited.
          enum: [0, 1]
        CreateTime:
          type: integer
          format: int64
          description: The creation time of the stream publishing prohibition rule, Unix timestamp, in seconds.
        EffectiveTime:
          type: integer
          format: int64
          description: The effective time of the stream publishing prohibition rule, Unix timestamp, in seconds.
