openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: SetForbidStreamRule
      description: |
        Set the Stream publishing prohibition rule.

        After setting successfully, you can [query Stream publishing prohibition rules](./describe-forbid-stream-rules.mdx) or [delete Stream publishing prohibition rules](./del-forbid-stream-rule.mdx).

        <Note title="Rate Limit">For all Rooms under the same AppID: 10 times/second.</Note>
        <Warning title="Notice">
        Usage of DisableAudio and DisableVideo parameters:
        - At least one parameter must be set to 1, otherwise calling this interface will result in an error.
        - For the same Stream ID, if this interface is called multiple times to set different prohibition rules (with different DisableAudio and DisableVideo parameter values each time), the settings from the last call will prevail.
        </Warning>

      operationId: set-forbid-stream-rule
      parameters:
        - name: Action
          in: query
          description: |
            > API Prototype Parameter
            >
            > https://rtc-api.zego.im?Action=SetForbidStreamRule
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [SetForbidStreamRule]
          style: form
          explode: true
        # Common parameters
        - $ref: '../../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../../shared-components.yaml#/components/parameters/SignatureVersion'
        # Business parameters
        - name: RoomId
          in: query
          description: Room ID.
          required: true
          schema:
            type: string
        - name: StreamId
          in: query
          description: Stream ID, maximum length not exceeding 256 bytes.
          required: true
          schema:
            type: string
            maxLength: 256
        - name: DisableAudio
          in: query
          description: |
            Whether to prohibit audio. 0: Do not prohibit (default); 1: Prohibit.
          required: false
          schema:
            type: integer
            format: int32
            enum: [0, 1]
            default: 0
        - name: DisableVideo
          in: query
          description: |
            Whether to prohibit video. 0: Do not prohibit (default); 1: Prohibit.
          required: false
          schema:
            type: integer
            format: int32
            enum: [0, 1]
            default: 0
        - name: EffectiveTime
          in: query
          description: Effective duration of the prohibition rule, in seconds. Default 21600. Range 1 ~ 86400 (values exceeding 24 hours will be automatically adjusted to 24 hours).
          required: false
          schema:
            type: integer
            format: int64
            minimum: 1
            maximum: 86400
            default: 21600
      responses:
        "200":
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetForbidStreamRuleResponse'

components:
  schemas:
    SetForbidStreamRuleResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: |
            Return code. The following only lists some return codes related to the interface business logic. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).

            <table>
              <thead>
                <tr>
                  <th>Return Code</th>
                  <th>Description</th>
                  <th>Suggested Action</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>0</td>
                  <td>Request successful.</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>Request failed.</td>
                  <td>Please contact ZEGOCLOUD technical support for assistance.</td>
                </tr>
                <tr>
                  <td>2</td>
                  <td>Input parameter error.</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>9</td>
                  <td>Permission to use this interface not granted.</td>
                  <td>Please contact ZEGOCLOUD technical support for assistance.</td>
                </tr>
                <tr>
                  <td>123</td>
                  <td>Failed to set Stream information.</td>
                  <td>Please retry, or contact ZEGOCLOUD technical support for assistance.</td>
                </tr>
                <tr>
                  <td>206</td>
                  <td>App request QPS too high and rate limited.</td>
                  <td>Reduce request frequency, or contact ZEGOCLOUD technical support to increase the QPS limit threshold.</td>
                </tr>
              </tbody>
            </table>
        Message:
          type: string
          description: Operation result description.
          example: success
        RequestId:
          type: string
          description: Request ID.
          example: TestRequestId167562222222915000
