openapi: 3.0.0
info:
  title: ZEGO 共享组件
  version: 1.0.0

components:
  # 共享的参数定义
  parameters:
    AppId:
      name: AppId
      in: query
      description: AppId，ZEGO 分配的用户唯一凭证。
      required: true
      schema:
        type: integer
        format: uint32

    SignatureNonce:
      name: SignatureNonce
      in: query
      description: 随机字符串。
      required: true
      schema:
        type: string

    Timestamp:
      name: Timestamp
      in: query
      description: Unix 时间戳，单位为秒。最多允许 10 分钟的误差。
      required: true
      schema:
        type: integer
        format: int64

    SignatureVersion:
      name: SignatureVersion
      in: query
      description: 签名版本号。
      required: true
      schema:
        type: string
        default: "2.0"
        enum: ["2.0"]

    Signature:
      name: Signature
      in: query
      description: 签名，用于验证请求的合法性。
      required: true
      schema:
        type: string

  # 共享的Schema定义
  schemas:
    ErrorResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 错误码
          example: 400
        Message:
          type: string
          description: 错误信息
          example: "Invalid request parameters"
        RequestId:
          type: string
          description: 请求 ID
          example: "3151527792559699733"