openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: CloseRoom
      description: |
        This API removes all users from the Room and closes the Room.

        If the developer has configured [Logged Out Callback](/real-time-video-server/callback/room/logged-out) and [Stream Destroyed Callback](/real-time-video-server/callback/stream/destroyed) according to [Callback Configuration Guide](/real-time-video-server/callback/receiving-callback), when the server calls this API:

        - The server will receive [Logged Out Callback](/real-time-video-server/callback/room/logged-out) notifications, allowing the developer to track user logout events from the Room.
        - The status of Streams in the original Room will be closed, and the server will receive [Stream Destroyed Callback](/real-time-video-server/callback/stream/destroyed), allowing the developer to be informed about Stream closure in the Room.

        After the Room is closed, client users will be kicked out of the Room and will receive ZEGOCLOUD SDK callback interfaces:

        | |ZegoExpress SDK|LiveRoom SDK|
        |-|-|-|
        |iOS/macOS| onRoomStateChanged | onKickout |
        |Android| onRoomStateChanged | onKickout |
        |Windows| onRoomStateChanged | OnKickOut |
        |Web| roomStateChanged | onKickout |

        <Note title="Rate Limit">All Rooms under the same AppID: 1 time/second (test environment: 1 time/second)</Note>

      operationId: close
      parameters:
        - name: Action
          in: query
          description: |
            > API Prototype Parameter
            >
            > https://rtc-api.zego.im?Action=CloseRoom
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [CloseRoom]
          style: form
          explode: true
        # Public parameters
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        # Business parameters
        - name: RoomId
          in: query
          description: Room ID.
          required: true
          allowEmptyValue: false
          schema:
            type: string
        - name: CustomReason
          in: query
          description: |
            Reason for closing, with a maximum length of 256 bytes.
            When using, URL encoding (UrlEncode) must be performed on its content.
          required: false
          allowEmptyValue: false
          schema:
            type: string
        - name: RoomCloseCallback
          in: query
          default: false
          description: |
            Whether to generate [Room Close Callback]().
            Since this is usually an active closure initiated by the developer, no separate Room Close Callback notification will be sent to the developer. If you need to use Room Close Callback for unified logic processing, you can change it to true.
            > **📌 Note**
            >
            > This parameter only affects whether Room Close Callback is generated. Callback notifications for Room closure due to other reasons (such as [Logged Out Callback]()) are not affected.
          required: false
          schema:
            type: boolean
      responses:
        "200":
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloseRoomResponse'

components:
  schemas:
    CloseRoomResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: |
            Return code. The following only lists some return codes related to API business logic. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).

            <table>
              <thead>
                <tr>
                  <th>Return Code</th>
                  <th>Description</th>
                  <th>Suggested Action</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>5018</td>
                  <td>Room has been destroyed or does not exist.</td>
                  <td>Please confirm whether the requested RoomId exists.</td>
                </tr>
                <tr>
                  <td>5024</td>
                  <td>Room does not exist, with the same internal judgment logic as 104 and 50001.</td>
                  <td>Please confirm whether the requested RoomId exists.</td>
                </tr>
              </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Description of operation result.
          example: success
        RequestId:
          type: string
          description: Request ID.
          example: TestRequestId1642755866616219000

