openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: DeleteStream
      description: |
        Call this interface to delete a specified stream from a Room. Unlike [Kick out User](/real-time-video-server/api-reference/room/kick-out-user), the User corresponding to this Stream is still in the Room. This interface can be used to forcibly "remove the mic" from a User, or to delete the added CDN live Stream in a "watch together" scenario.

        This interface is only used to send notifications related to Stream deletion within the Room, and does not perform the actual stop publishing Stream operation. Developers need to call the `stopPublishingStream` interface from their client to stop publishing the Stream, which will stop transmitting audio and video data to the streaming media; accordingly, the playing Stream side needs to call the client `stopPlayingStream` interface to stop playing the Stream, which will stop receiving audio and video data from the streaming media.

        Clients use the ZEGO Express SDK callback interface to receive notifications of Stream reduction in the Room:

        | |ZegoExpress SDK|LiveRoom SDK|
        |-|-|-|
        |iOS/macOS| onRoomStreamUpdate | onStreamUpdated |
        |Android| onRoomStreamUpdate | onStreamUpdated |
        |Windows| onRoomStreamUpdate |  OnStreamUpdated |
        |Web| roomStreamUpdate | onStreamUpdated |

        <Note title="Rate Limit">For all Rooms under the same AppID: 10 times/second (test environment: 1 time/second)</Note>

        <Warning title="Attention">
        When calling this server-side interface:
        - It is not recommended to use the same UserId as the actual User in the Room, to avoid conflicts with the Stream deletion behavior of the client SDK. You can use a specific name to identify it as a server-side behavior, for example: userId = "Server-Administrator".
        - If the same UserId as the actual User in the Room is used (not recommended), the client of the corresponding operator UserId will not receive the Stream deletion callback triggered by this server-side interface, while other Users in the Room will receive the Stream deletion callback.
        </Warning>

      operationId: delete-stream
      parameters:
        - name: Action
          in: query
          description: |
            > Interface prototype parameter
            >
            > https://rtc-api.zego.im?Action=DeleteStream
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DeleteStream]
          style: form
          explode: true
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        # 业务参数
        - name: RoomId
          in: query
          description: Room ID.
          required: true
          schema:
            type: string
        - name: UserId
          in: query
          description: User ID.
          required: true
          schema:
            type: string
        - name: UserName
          in: query
          description: User Name.
          required: false
          schema:
            type: string
        - name: StreamId
          in: query
          description: Stream ID.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteStreamResponse'

components:
  schemas:
    DeleteStreamResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          example: 0
          description: |
            Return Code.

            The following only lists some return codes related to the interface business logic. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).

            <table>
              <thead>
                <tr>
                  <th>Return Code</th>
                  <th>Description</th>
                  <th>Suggested Handling</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>124</td>
                  <td>Failed to delete stream information.</td>
                  <td>Please retry, or contact ZEGOCLOUD technical support for assistance.</td>
                </tr>
                <tr>
                  <td>138</td>
                  <td>Stream information does not exist.</td>
                  <td>Please retry, or contact ZEGOCLOUD technical support for assistance.</td>
                </tr>
              </tbody>
            </table>
        Message:
          type: string
          example: success
          description: Description of the operation result.
        RequestId:
          type: string
          example: TestRequestId167562222222915000
          description: Request ID.

