openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: DescribeSimpleStreamList
      description: |
        Call this interface to get the stream list information in the Room. After obtaining the stream list, compare it with the business backend stream list to prevent "speaker blasting". You can also use this interface to obtain the unique Stream ID in the Room for mixing stream volume callback when using a third-party stream player.

        <Note title="Call Frequency Limit">All rooms under the same AppID are limited to 50 times/second; Single Room: 1 time/10 seconds</Note>

      operationId: describe-simple-streamlist
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameters
            >
            > https://rtc-api.zego.im?Action=DescribeSimpleStreamList
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DescribeSimpleStreamList]
          style: form
          explode: true
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        # 业务参数
        - name: RoomId
          in: query
          description: Room ID.
          required: true
          allowEmptyValue: false
          schema:
            type: string
      responses:
        "200":
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeSimpleStreamListResponse'

components:
  schemas:
    DescribeSimpleStreamListResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          example: 0
          description: |
            Return code. The following only lists some return codes related to the interface business logic. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).

            <table>
              <thead>
                <tr>
                  <th>Return Code</th>
                  <th>Description</th>
                  <th>Suggested Action</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>154</td>
                  <td>Failed to get list information.</td>
                  <td>Please retry, or contact ZEGOCLOUD technical support for assistance.</td>
                </tr>
              </tbody>
            </table>
        Message:
          type: string
          example: success
          description: Operation result description.
        RequestId:
          type: string
          example: 5885338326725063742
          description: Request ID.
        Data:
          type: object
          properties:
            StreamList:
              type: array
              description: Stream list.
              items:
                type: object
                properties:
                  StreamId:
                    type: string
                    example: stream_demo
                    description: Stream ID.
                  UserId:
                    type: string
                    example: user_demo
                    description: Username.
                  UserName:
                    type: string
                    example: user_name_demo
                    description: User nickname.
                  CreateTime:
                    type: integer
                    format: int64
                    example: 1642045110123
                    description: Creation time.
                  StreamNumberId:
                    type: integer
                    format: uint32
                    example: 10
                    description: Stream sequence number in the Room.


