openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: DescribeUserNum
      description: |
        Call this interface to get the User count of the Room.

        <Note title="Rate Limit">For all Rooms under the same AppID: 10 times/second (test environment: 1 time/second)</Note>
      operationId: describe-user-num
      parameters:
        - name: Action
          in: query
          description: |
            > Prototype parameter of the interface
            >
            > https://rtc-api.zego.im?Action=DescribeUserNum
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DescribeUserNum]
          style: form
          explode: true
        # Common parameters
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        # Business parameters
        - name: RoomId
          in: query
          description: |
            Room ID list, supports a maximum of 10 Rooms per call. When the Room does not exist, the User count is 0. Example: RoomId[]=room1&RoomId[]=room2
          required: true
          allowEmptyValue: false
          schema:
            type: array
            items:
              type: string
            minItems: 1
            maxItems: 10
            example: ["room1", "room2"]
          style: form
          explode: true
      responses:
        "200":
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeUserNumResponse'
              example:
                Code: 0
                Message: success
                RequestId: 7840039829955402142
                Data:
                  UserCountList:
                    - RoomId: room1
                      UserCount: 2
                      AdminUserCount: 0
                    - RoomId: room2
                      UserCount: 3
                      AdminUserCount: 1

components:
  schemas:
    DescribeUserNumResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: Return code. Please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).
          example: 0
        Message:
          type: string
          description: Description of the operation result.
          example: success
        RequestId:
          type: string
          description: Request ID.
          example: "7840039829955402142"
        Data:
          type: object
          properties:
            UserCountList:
              type: array
              description: List of Rooms and User counts.
              items:
                type: object
                properties:
                  RoomId:
                    type: string
                    description: Room ID.
                  UserCount:
                    type: integer
                    format: int32
                    description: Room User count.
                  AdminUserCount:
                    type: integer
                    format: int32
                    description: Room admin User count. This parameter is mainly used in scenarios such as cloud recording and audio/video stream review; if the Room does not have such Users, please ignore this parameter. **Note that UserCount includes AdminUserCount**.


