openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: KickoutUser
      description: |
        Use this interface to kick out a specified User from the Room. All the User's current publishing and playing Streams will be stopped. This is commonly used in content moderation scenarios where the developer's backend detects that a User's live streaming content violates the rules, and the User needs to be kicked out from the Room through this interface.

        The kicked User on the client will receive the ZEGOCLOUD SDK callback interface:

        | |ZegoExpress SDK|LiveRoom SDK|
        |-|-|-|
        |iOS/macOS| onRoomStateChanged | onKickOut |
        |Android| onRoomStateChanged | onKickOut |
        |Windows| onRoomStateChanged |  OnKickOut |
        |Web/小程序| roomStateChanged | onKickOut |


        The client receives notifications of User changes in the Room using the ZEGO Express SDK callback interface:

        | |ZegoExpress SDK|LiveRoom SDK|
        |-|-|-|
        |iOS/macOS| onRoomUserUpdate | onUserUpdate |
        |Android| onRoomUserUpdate | onUserUpdate |
        |Windows| onRoomUserUpdate |  OnUserUpdate |
        |Web/小程序| roomUserUpdate | onUserStateUpdate |

        <Note title="Rate Limit">All Rooms under the same AppID: 50 requests/second</Note>

      operationId: kick-out-user
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameters
            >
            > https://rtc-api.zego.im?Action=KickoutUser
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [KickoutUser]
          style: form
          explode: true
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        # 业务参数
        - name: RoomId
          in: query
          description: Room ID.
          required: true
          schema:
            type: string
        - name: UserId
          in: query
          description: List of User IDs to kick out from the Room. Maximum of 5 User IDs supported.
          required: true
          schema:
            type: array
            items:
              type: string
            minItems: 1
            maxItems: 5
          style: form
          explode: true
        - name: CustomReason
          in: query
          description: Reason for kicking out. Maximum length is 256 bytes. When used, URL encoding (UrlEncode) must be performed on the content.
          required: false
          schema:
            type: string
            maxLength: 256
      responses:
        "200":
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KickoutUserResponse'

components:
  schemas:
    KickoutUserResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          example: 0
          description: |
            The following only lists some return codes related to the interface business logic. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).

            <table>
              <thead>
                <tr>
                  <th>Return Code</th>
                  <th>Description</th>
                  <th>Suggested Action</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>50011</td>
                  <td>The User list length is too long.</td>
                  <td>Please check if the number of Users in the request packet exceeds the limit.</td>
                </tr>
              </tbody>
            </table>

        Message:
          type: string
          example: success
          description: Description of the operation result.
        RequestId:
          type: string
          example: 343649807833778782
          description: Request ID.

