openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: SendBarrageMessage
      description: |
        Use this interface to push barrage messages in a Room, generally used for scenarios with large volumes of message sending and receiving where message reliability is not required.

        Clients receive messages using ZEGOCLOUD Express SDK callback interfaces:

        | |ZegoExpress SDK|LiveRoom SDK|
        |-|-|-|
        |iOS/macOS| onIMRecvBarrageMessage | onRecvBigRoomMessage |
        |Android| onIMRecvBarrageMessage | onRecvBigRoomMessage |
        |Windows| onIMRecvBarrageMessage |  OnRecvBigRoomMessage |
        |Web| IMRecvBarrageMessage | onRecvBigRoomMessage |

        <Note title="Rate Limit">All Rooms under the same AppID: 100 times/second (test environment: 10 times/second)</Note>
        <Warning title="Notice">
        - When sending messages through a certain UserId on the server, clients using the same UserId will not receive that message, meaning the sender cannot receive their own sent messages.
        - If developers need all users in the Room to receive messages, when calling this interface, a UserId other than that of the Room user should be passed in.
        - The UserId used does not need to log in to the Room to send messages directly.
        </Warning>

      operationId: send-barrage-message
      parameters:
        - name: Action
          in: query
          description: |
            > API Prototype Parameters
            >
            > https://rtc-api.zego.im?Action=SendBarrageMessage
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [SendBarrageMessage]
          style: form
          explode: true
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        # 业务参数
        - name: RoomId
          in: query
          description: Room ID.
          required: true
          schema:
            type: string
        - name: UserId
          in: query
          description: Sender User ID.
          required: true
          schema:
            type: string
        - name: UserName
          in: query
          description: Sender username (corresponds one-to-one with UserId).
          required: false
          schema:
            type: string
        - name: MessageCategory
          in: query
          description: |
            Message category. 1: System message. 2: Chat message.
          required: true
          schema:
            type: integer
            format: uint32
            enum: [1, 2]
        - name: MessageContent
          in: query
          description: Message content, length cannot exceed 1024 bytes. When using, URL encoding (UrlEncode) must be performed on the content.
          required: true
          schema:
            type: string
            maxLength: 1024
      responses:
        "200":
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendBarrageMessageResponse'

components:
  schemas:
    SendBarrageMessageResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          example: 0
          description: |
            Return code.
            The following only lists some return codes related to the API business logic. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).
            <table>
              <thead>
                <tr>
                  <th>Return Code</th>
                  <th>Description</th>
                  <th>Suggested Handling</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1008</td>
                  <td>Message content MessageContent is empty.</td>
                  <td>Please retry, or contact ZEGOCLOUD technical support for assistance.</td>
                </tr>
                <tr>
                  <td>50012</td>
                  <td>Message length exceeds limit.</td>
                  <td>Please check if the parameter length exceeds the limit.</td>
                </tr>
              </tbody>
            </table>
        Message:
          type: string
          example: success
          description: Description of the operation result.
        RequestId:
          type: string
          example: 2237080460466033406
          description: Request ID.
        Data:
          type: object
          properties:
            MessageId:
              type: string
              example: "1_1611647493487_29"
              description: Message ID.

