openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: SendCustomCommand
      description: |
        Call this interface to send custom messages in a Room, i.e., sending signaling messages to specified single or multiple users in the same Room.

        Client-side message reception uses ZEGOCLOUD Express SDK callback interfaces:

        | Platform |ZegoExpress SDK|LiveRoom SDK|
        |-|-|-|
        |iOS/macOS| onIMRecvCustomCommand | onReceiveCustomCommand |
        |Android| onIMRecvCustomCommand | onRecvCustomCommand |
        |Windows| onIMRecvCustomCommand |   OnRecvCustomCommand |
        |Web| IMRecvCustomCommand | onRecvCustomCommand |

        <Note title="Call Rate Limit">All Rooms under the same AppID: 100 times/second (test environment: 10 times/second)</Note>
        <Warning title="Notice">
        - When sending messages through a certain FromUserId on the server, clients using the same FromUserId will not receive this message, i.e., the sender cannot receive messages sent by themselves.
        - If developers need all users in the Room to receive the message, when calling this interface, a FromUserId other than the Room users should be passed in.
        - The FromUserId used does not need to log in to the Room to send messages directly.
        </Warning>

      operationId: send-custom-command
      parameters:
        - name: Action
          in: query
          description: |
            > API Prototype Parameters
            >
            > https://rtc-api.zego.im?Action=SendCustomCommand
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [SendCustomCommand]
          style: form
          explode: true
        # Public parameters
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        # Business parameters
        - name: RoomId
          in: query
          description: Room ID.
          required: true
          schema:
            type: string
        - name: FromUserId
          in: query
          description: Sender User ID.
          required: true
          schema:
            type: string
        - name: ToUserId
          in: query
          description: |
            Custom message destination User ID, supporting up to 10 destination User IDs.
            If this parameter is not filled in, the custom message is broadcast to all users in the Room; if this parameter is filled in, the custom message is only pushed to the destination users.
            Example: ToUserId[]=user1&ToUserId[]=user2
          required: false
          schema:
            type: array
            items:
              type: string
            minItems: 1
            maxItems: 10
          style: form
          explode: true
        - name: MessageContent
          in: query
          description: Custom message content, length cannot exceed 1024 bytes. When using, URL encoding (UrlEncode) must be performed on its content.
          required: true
          schema:
            type: string
            maxLength: 1024
      responses:
        "200":
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendCustomCommandResponse'

components:
  schemas:
    SendCustomCommandResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          example: 0
          description: |
            Return code. The following only lists some return codes related to interface business logic. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).

            <table>
              <thead>
                <tr>
                  <th>Return Code</th>
                  <th>Description</th>
                  <th>Suggested Action</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>50003</td>
                  <td>Failed to find user online information.</td>
                  <td>Please confirm whether the requested UserId is online.</td>
                </tr>
                <tr>
                  <td>50011</td>
                  <td>User list length is too long.</td>
                  <td>Please check whether the number of users in the request packet exceeds the limit.</td>
                </tr>
                <tr>
                  <td>50012</td>
                  <td>Message length exceeds limit.</td>
                  <td>Please check whether the parameter length exceeds the limit.</td>
                </tr>
                <tr>
                  <td>50013</td>
                  <td>Failed to send custom message.</td>
                  <td>Please retry, or contact ZEGOCLOUD technical support for assistance.</td>
                </tr>
              </tbody>
            </table>
        Message:
          type: string
          example: success
          description: Operation result description.
        RequestId:
          type: string
          example: 3005402395393320157
          description: Request ID.
        Data:
          type: object
          properties:
            FailUsers:
              type: array
              description: List of target User IDs that failed to process.
              items:
                type: object
                properties:
                  Uid:
                    type: string
                    example: "1111"
                    description: User ID.
                  Code:
                    type: integer
                    format: int32
                    example: 50003
                    description: |
                      Failure error code (offline: 50003).

