openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: SendBroadcastMessage
      description: |
        Call this interface to send broadcast messages in a room, i.e., send text messages to all users in the same room.

        Clients receive messages using ZEGO Express SDK callback interfaces:

        | |ZegoExpress SDK|LiveRoom SDK|
        |-|-|-|
        |iOS/macOS| onIMRecvBroadcastMessage | onRecvRoomMessage |
        |Android| onIMRecvBroadcastMessage | onRecvRoomMessage |
        |Windows| onIMRecvBroadcastMessage | OnRecvRoomMessage |
        |Web| IMRecvBroadcastMessage | onRecvRoomMsg |

        <Note title="Rate Limit">All rooms under the same AppID: 100 requests/second (test environment: 10 requests/second)</Note>
        <Warning title="Warning">
        1. When sending a message from the server using a specific User ID, the client using the same User ID will not receive that message, meaning the sender cannot receive the message they sent.
        2. If developers need all users in the room to receive the message, when calling this interface, a User ID other than those in the room should be used.
        3. The User ID used does not need to log in to the room to send messages directly.
        </Warning>

      operationId: send-broadcast-message
      parameters:
        - name: Action
          in: query
          description: |
            > Interface prototype parameter
            >
            > https://rtc-api.zego.im?Action=SendBroadcastMessage
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [SendBroadcastMessage]
          style: form
          explode: true
        # Common parameters
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        # Business parameters
        - name: RoomId
          in: query
          description: Room ID.
          required: true
          schema:
            type: string
        - name: UserId
          in: query
          description: Sender User ID.
          required: true
          schema:
            type: string
        - name: UserName
          in: query
          description: Sender username (corresponds one-to-one with UserId).
          required: false
          schema:
            type: string
        - name: MessageCategory
          in: query
          description: |
            Message category. 1: System message. 2: Chat message.
          required: true
          schema:
            type: integer
            format: uint32
            enum: [1, 2]
        - name: MessageContent
          in: query
          description: Message content, length cannot exceed 1024 bytes. When using, URL encoding (UrlEncode) must be performed on the content.
          required: true
          schema:
            type: string
            maxLength: 1024
      responses:
        "200":
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendBroadcastMessageResponse'

components:
  schemas:
    SendBroadcastMessageResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          example: 0
          description: |
            Return code.
            Only part of the return codes related to the interface business logic are listed below. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).

            <table>
              <thead>
                <tr>
                  <th>Return Code</th>
                  <th>Description</th>
                  <th>Suggested Action</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>121</td>
                  <td>Failed to save broadcast message.</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>122</td>
                  <td>Failed to generate message ID.</td>
                  <td>Please retry, or contact ZEGOCLOUD technical support for assistance.</td>
                </tr>
                <tr>
                  <td>151</td>
                  <td>Failed to push broadcast message.</td>
                  <td>Please retry, or contact ZEGOCLOUD technical support for assistance.</td>
                </tr>
                <tr>
                  <td>5201</td>
                  <td>Failed to encode broadcast message.</td>
                  <td>Please retry, or contact ZEGOCLOUD technical support for assistance.</td>
                </tr>
                <tr>
                  <td>5202</td>
                  <td>Failed to generate message ID.</td>
                  <td>Please retry, or contact ZEGOCLOUD technical support for assistance.</td>
                </tr>
                <tr>
                  <td>50012</td>
                  <td>Message length exceeds limit.</td>
                  <td>Please check if the parameter length exceeds the limit.</td>
                </tr>
              </tbody>
            </table>

        Message:
          type: string
          example: success
          description: Operation result description.
        RequestId:
          type: string
          example: 619831198646468496
          description: Request ID.
        Data:
          type: object
          properties:
            MessageId:
              type: integer
              example: 3
              description: Message ID.

