openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: cdn

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [cdn]
      summary: DeleteMedia
      description:
        When users perform CDN recording, they will store the recorded media files on CDN servers, and users can call this interface to delete the file.

        <Warning title="Note">
        Before using this interface for the first time, please confirm whether CDN recording service has been activated. If not, please go to the [ZEGOCLOUD Console](https://console.zego.im) to activate it yourself, for details, please refer to [Console - Service Configuration - CDN](/console/service-configuration/activate-cdn-service), or contact ZEGOCLOUD Technical Support to activate it.
        </Warning>
        <Note title="Call frequency limit">All rooms under the same AppID are limited to 20 times/second</Note>
      operationId: delete-media
      parameters:
        - name: Action
          in: query
          description: |
            > Interface prototype parameters
            >
            > https://rtc-api.zego.im?Action=DeleteMedia
          required: true
          schema: { type: string, enum: [DeleteMedia] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - name: Vendor
          in: query
          required: true
          schema: { type: string, enum: [Tencent, Ws, Huawei] }
          description: |
            <p>Possible values and corresponding CDN vendors:</p>
            Tencent: Tencent Cloud.
            Ws: Wangsu.
            Huawei: Huawei Cloud.
        - name: FileId
          in: query
          required: true
          description: |
            <p>
              Unique file identifier returned in the
              <a href="/real-time-video-server/callback/cdn/cdn-record-completed" target="blank">
                recording file generation callback
              </a>, supporting up to 100 media file FileIds.
            </p>
            <p>
              Please note that the unique identifiers for recording files are different for each CDN vendor:
            </p>
            <ul>
              <li>Tencent Cloud: FileID.</li>
              <li>Wangsu: PersistentId.</li>
              <li>Huawei Cloud: ObsObject.</li>
            </ul>
            <p>
              You can also obtain the unique identifier of the media file through the
              <a href="/real-time-video-server/api-reference/cdn/search-media" target="blank">
                search media
              </a>
              interface, and the parameter names corresponding to the identifiers are different, please pay attention to distinguish them.
            </p>
            <p>
              Example: &FileId[]=5285890813221514958&FileId[]=5285890813221513290
            </p>
          schema:
            type: array
            items: { type: string }
            minItems: 1
            maxItems: 100
          style: form
          explode: true
        - name: ClearCache
          in: query
          required: false
          description: |
            Whether to delete the cache on CDN nodes when deleting files.

            >**Note:**
            >
            >Only supports Wangsu, cache deletion only applies to successfully deleted files, cache will only be deleted after the file deletion is successful.
          schema:
            type: boolean
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteMediaResponse'
              examples:
                Delete file cache success:
                  summary: Return example for successful file cache deletion.
                  value:
                    Code: 0
                    Message: success
                    Data:
                      Deleted:
                        - pickrecord-clarechen_test_ws--20251226115411.mp4
                      Errors: []
                      WsItemIdReceiverResp:
                        Code: 1
                        Message: handle success
                    RequestId: 123456

                Delete file cache failure:
                  summary: Return example when ClearCache is not filled or ClearCache is not true.
                  value:
                    Code: 0
                    Message: success
                    Data:
                      Deleted:
                        - pickrecord-clarechen_test_ws--20251226115803.mp4
                      Errors: []
                      WsItemIdReceiverResp:
                        Code: 0
                        Message: ""
                    RequestId: 123456

components:
  schemas:
    DeleteMediaResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: |
              Return codes.
              <br/>
              Only the return codes related to interface business logic are listed here. For the complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).
              <table>
                <thead>
                  <tr><th>Return Code</th><th>Description</th><th>Solution</th></tr>
                </thead>
                <tbody>
                  <tr><td>0</td><td>Request successful.</td><td>-</td></tr>
                  <tr><td>2</td><td>Input parameter error.</td><td>-</td></tr>
                  <tr><td>3</td><td>Related permissions not activated.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
                  <tr><td>4</td><td>CDN type mismatch.</td><td>Please check the parameters.</td></tr>
                  <tr><td>5</td><td>Configuration error.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
                  <tr><td>6</td><td>Request too frequent.</td><td>Please try again later.</td></tr>
                  <tr><td>7</td><td>Authentication failed.</td><td>Please check if the authentication parameters are correct.</td></tr>
                  <tr><td>1000</td><td>Request failed.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
                </tbody>
              </table>
          example: 0
        Message:
          type: string
          description: Operation result description.
          example: "success"
        RequestId:
          type: string
          description: Request ID returned by ZEGOCLOUD server.
          example: "3574501647605445341"
        Data:
          type: object
          description: Response data, generated by JSON serialization of the following parameters.
          properties:
            Deleted:
              type: array
              description: List of successfully deleted files.
              items:
                type: string
              example: ["3270835010809755971","3270835010811335406"]
            Errors:
              type: array
              description: List of files that failed to be deleted.
              items:
                type: object
                properties:
                  Code: { type: string, description: Error code for failed file deletion. }
                  Message: { type: string, description: Error message for failed file deletion. }
                  Key: { type: string, description: Unique identifier of the file that failed to be deleted. }
                  RequestId: { type: string, description: Unique request ID returned by the CDN vendor corresponding to the Vendor parameter value in the request, which needs to be provided when locating problems. }
              example: []
            WsItemIdReceiverResp:
              type: object
              description: Result of file cache deletion.
              properties:
                Code:
                  type: integer
                  format: int32
                  description: |
                    Response code.
                    - 1: Delete file cache.
                    - Not 1: Delete file cache failed.
                Message:
                  type: string
                  description: Response message. Description of the result of file cache deletion.
              example: { "Code": "1", "Message": "handle success" }
