openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: cdn

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [cdn]
      summary: StartCDNRecord
      description: |
        CDN can be configured to record all live streams, if you need to select and record a specific live stream, you can call this interface to implement it. For related callbacks, please refer to [Recording File Generation Callback](/real-time-video-server/callback/cdn/cdn-record-completed).

        When using the CDN service provided by Tencent Cloud, the following recording parameters need to be clarified:
        - Recording file format: Supports M3U8, FLV, MP4, AAC (audio only) and MP3 (audio only).
        - Recording interval: Duration of the recording file, in seconds (s), the value range is 300 s ~ 7200 s, the default value is 7200 s. This parameter is invalid for M3U8 recording file format. If you want the duration of the recording file to exceed 7200 s (2 hours), you need to use the recording file merging interface to merge multiple recording files.
        - Storage duration: Clarify the retention period of the recording file.

        <Warning title="Note">
        Before using this interface, you need to clarify the recording parameters, then synchronize the recording parameters to ZEGOCLOUD Technical Support for configuration, or go to [ZEGO Console](https://console.zego.im) for self-service configuration, for details, please refer to [Console - Service Configuration - CDN](/console/service-configuration/activate-cdn-service).
        </Warning>
        <Note title="Call frequency limit">All rooms under the same AppID are limited to 20 times/second</Note>
      operationId: start-cdn-recrod
      parameters:
        - name: Action
          in: query
          description: |
            > Interface prototype parameters
            >
            > https://rtc-api.zego.im?Action=StartCDNRecord
          required: true
          schema: { type: string, enum: [StartCDNRecord] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - name: StreamId
          in: query
          required: true
          description:
            Stream ID list。<br />To record "cdn01" and "cdn02" streams at the same time, the requested parameters are: StreamId[]=cdn01 and StreamId[]=cdn02。
          schema:
            type: array
            items: { type: string }
            minItems: 1
          style: form
          explode: true
        - name: Vendor
          in: query
          required: true
          schema: { type: string, enum: [Tencent, Ws, Huawei] }
          description: |
            <p>CDN vendor name。</p>
            Tencent：Tencent Cloud。
            Ws：Wangsu。
            Huawei：Huawei Cloud。
        - name: EndTime
          in: query
          required: false
          description: |
            Recording task end time, Unix timestamp. The set time must be greater than the current time, and cannot exceed 24 hours from the current time.

            <b>This parameter only takes effect when Vendor is "Tencent".</b>
          schema: { type: string }
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartCDNRecordResponse'

components:
  schemas:
    StartCDNRecordResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            The following only lists the return codes related to interface business logic. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).

            <table>
              <thead>
                <tr>
                  <th>Return Code</th>
                  <th>Description</th>
                  <th>Handling Suggestion</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>0</td>
                  <td>Request successful.</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>2</td>
                  <td>Input parameter error.</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>3</td>
                  <td>Related permissions not activated.</td>
                  <td>Please contact ZEGOCLOUD Technical Support.</td>
                </tr>
                <tr>
                  <td>4</td>
                  <td>CDN type mismatch.</td>
                  <td>Please check the parameters.</td>
                </tr>
                <tr>
                  <td>5</td>
                  <td>Configuration error.</td>
                  <td>Please contact ZEGOCLOUD Technical Support.</td>
                </tr>
                <tr>
                  <td>6</td>
                  <td>Request too frequent.</td>
                  <td>Please try again later.</td>
                </tr>
                <tr>
                  <td>7</td>
                  <td>Authentication failed.</td>
                  <td>Please check if the authentication parameters are correct.</td>
                </tr>
                <tr>
                  <td>1000</td>
                  <td>Request failed.</td>
                  <td>Please contact ZEGOCLOUD Technical Support.</td>
                </tr>
              </tbody>
            </table>
          example: 0
        Message: { type: string , description: Operation result description。, example: "success"}
        RequestId: { type: string , description: Request ID, returned by ZEGO server。, example: "4191282558729715911"}
        Data:
          type: object
          description: Response data。
          properties:
            Tencent:
              type: array
              description: <code>Tencent Cloud</code> return content (returned when Vendor is Tencent)。
              items:
                type: object
                properties:
                  StreamName: { type: string , description: Stream name, that is, StreamId in the request parameters。, example: "cdn01"}
                  TaskId: { type: string , description: Task ID, globally unique identifier for the recording task。, example: "UUpTbkZUQV5WQVxrRFtDUQIUB29FWwMeAxwALBxMAggNHxw7WRUWGBVeEzoTDl0CDEoFNgIESVpXQV9rRVRCXlVKWGlFV0daVENeaFdURVNY"}
                  RequestId: { type: string , description: Unique request ID, returned by the CDN vendor corresponding to the request parameter Vendor value (i.e., Tencent Cloud), which needs to be provided when locating problems。, example: "70628bcd-5652-4d5c-aa04-97956a4e771a"}
                  Code: { type: string , description: Error code of the current stream, please refer to Message information for processing, or contact ZEGOCLOUD Technical Support。, example: ""}
                  Message: { type: string , description: Current stream error message。, example: ""}
            Ws:
              type: object
              description: <code>Wangsu</code> return content (returned when Vendor is Ws)。
              properties:
                msg: { type: object, description: Operation result prompt message。, example: null }
                http_code: { type: integer, format: int32, description: Business operation status。, example: 200 }
                trace_id: { type: string, description: Serial number。, example: "15ccf21b-f3c2-4ee3-aaad-d995393f80cd" }
                call_time: { type: string, description: Request initiation time。, example: "2022-04-27 14:27:48" }
                list:
                  type: array
                  items:
                    type: object
                    properties:
                      task: { type: string, description: Format of the recording file。, example: "mp4" }
                      id: { type: string, description: Stream name, that is, StreamId in the request parameters。, example: "vega_test" }
                      http_code: { type: integer, format: int32, description: The operation status of this task, please refer to msg information for processing, or contact ZEGOCLOUD Technical Support。, example: 200 }
                      msg: { type: string, description: The operation result prompt message of this task。, example: "success" }
                      persistentId: { type: string, description: The file identifier of this task。, example: "2020bc8b648883c64e7e81f03cf72b70b86f" }
            Huawei:
              type: array
              description: <code>Huawei Cloud</code> return content (returned when Vendor is Huawei)。
              items:
                type: object
                properties:
                  StreamName: { type: string, description: Stream name, that is, StreamId in the request parameters。, example: "hwtest" }
                  RequestId: { type: string, description: Unique request ID, returned by the CDN vendor corresponding to the request parameter Vendor value (i.e., Huawei), which needs to be provided when locating problems。, example: "c373b2cc8a51159d4d60e0ec543csd88" }
                  Code: { type: integer, format: int32, description: Error code of the current stream recording, please refer to Message information for processing, or contact ZEGOCLOUD Technical Support。, example: 0 }
                  Message: { type: string, description: Current stream recording error message。, example: "success" }

