openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: cdn

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [cdn]
      summary: StopCDNRecord
      description: |
        Call this API to stop CDN recording。For related callbacks, please refer to [Recording File Generation Callback](/real-time-video-server/callback/cdn/cdn-record-completed)。

        <Note title="Call Frequency Limit">All rooms under the same AppID are limited to 20 times/second</Note>
      operationId: stop-cdn-record
      parameters:
        - name: Action
          in: query
          description: |
            > Interface prototype parameters
            >
            > https://rtc-api.zego.im?Action=StopCDNRecord
          required: true
          schema: { type: string, enum: [StopCDNRecord] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - name: StreamId
          in: query
          required: true
          description: |
            Stream ID list。<br />To stop recording "cdn01" and "cdn02" streams at the same time, the requested parameters are: StreamId[]=cdn01 and StreamId[]=cdn02。
          schema:
            type: array
            items: { type: string }
            minItems: 1
          style: form
          explode: true
        - name: Vendor
          in: query
          required: true
          description: |
            <p>CDN vendor name。</p>
            <ul>
            <li>Tencent：Tencent Cloud。</li><li>Ws：Wangsu。</li><li>Huawei：Huawei Cloud。</li>
            </ul>
          schema: { type: string, enum: [Tencent, Ws, Huawei] }
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopCDNRecordResponse'

components:
  schemas:
    StopCDNRecordResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: |
            The following only lists the return codes related to interface business logic. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes)。

            <table>
              <thead>
                <tr>
                  <th>Return Code</th>
                  <th>Description</th>
                  <th>Handling Suggestion</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>0</td>
                  <td>Request successful。</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>2</td>
                  <td>Input parameter error。</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>3</td>
                  <td>Related permissions not activated。</td>
                  <td>Please contact ZEGOCLOUD Technical Support。</td>
                </tr>
                <tr>
                  <td>4</td>
                  <td>CDN type mismatch。</td>
                  <td>Please check the parameters。</td>
                </tr>
                <tr>
                  <td>5</td>
                  <td>Configuration error。</td>
                  <td>Please contact ZEGOCLOUD Technical Support。</td>
                </tr>
                <tr>
                  <td>6</td>
                  <td>Request too frequent。</td>
                  <td>Please try again later。</td>
                </tr>
                <tr>
                  <td>7</td>
                  <td>Authentication failed。</td>
                  <td>Please check if the authentication parameters are correct。</td>
                </tr>
                <tr>
                  <td>1000</td>
                  <td>Request failed。</td>
                  <td>Please contact ZEGOCLOUD Technical Support。</td>
                </tr>
              </tbody>
            </table>
          example: 0
        Message: { type: string, description: Operation result description。, example: "success" }
        RequestId: { type: string, description: Request ID, returned by ZEGO server。, example: "4315169065145771656" }
        Data:
          type: object
          description: Response data。
          properties:
            Tencent:
              type: array
              description: <code>Tencent Cloud</code> return content (returned when Vendor is Tencent)。
              items:
                type: object
                properties:
                  StreamName: { type: string, description: Stream name, that is, StreamId in the request parameters。, example: "cdn01" }
                  RequestId: { type: string, description: Unique request ID, returned by the CDN vendor corresponding to the request parameter Vendor value (i.e., Tencent Cloud), which needs to be provided when locating problems。, example: "d39548da-fbd4-4dce-8023-cfccd28a9963" }
                  Code: { type: string, description: Error code of the current stream, please refer to Message information for processing, or contact ZEGOCLOUD Technical Support。, example: "" }
                  Message: { type: string, description: Current stream error message。, example: "" }
            Ws:
              type: object
              description: <code>Wangsu</code> return content (returned when Vendor is Ws)。
              properties:
                msg: { type: object, description: Operation result prompt message。, example: null }
                http_code: { type: integer, format: int32, description: Business operation status。, example: 200 }
                trace_id: { type: string, description: Serial number。, example: "10021988-6472-4b6d-9f9a-6b5a6d4b6551" }
                call_time: { type: string, description: Request initiation time。, example: "2022-05-26 11:46:06" }
                list:
                  type: array
                  description: Request task processing result list。
                  items:
                    type: object
                    properties:
                      task: { type: string, description: Format of the recording file。, example: "mp4" }
                      id: { type: string, description: Stream name, that is, StreamId in the request parameters。, example: "test" }
                      http_code: { type: integer, format: int32, description: The operation status of this task, please refer to msg information for processing, or contact ZEGOCLOUD Technical Support。, example: 200 }
                      msg: { type: string, description: The operation result prompt message of this task。, example: "success" }
                      persistentId: { type: string, description: The file identifier of this task。, example: "202009a378bae528409f87dbe20717415676" }
            Huawei:
              type: array
              description: <code>Huawei Cloud</code> return content (returned when Vendor is Huawei)。
              items:
                type: object
                properties:
                  StreamName: { type: string, description: Stream name, that is, StreamId in the request parameters。, example: "hwtest" }
                  RequestId: { type: string, description: Unique request ID, returned by the CDN vendor corresponding to the request parameter Vendor value (i.e., Huawei), which needs to be provided when locating problems。, example: "f7b1e2f0ca92e7e90f8f0c8b96cds757" }
                  Code: { type: integer, format: int32, description: Error code of the current stream recording, please refer to Message information for processing, or contact ZEGOCLOUD Technical Support。, example: 0 }
                  Message: { type: string, description: Current stream recording error message。, example: "success" }

