openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - group

paths:
  /:
    post:
      tags: [group]
      summary: 查询 App 下的禁言群组列表
      description: |
        本接口用于查询 App 中的所有禁言群组的 ID，包含处于全员禁言、按群组角色禁言或按用户 ID 禁言状态的群组。

        本接口每次默认返回 10000 个群组，如需调整，请联系 ZEGO 技术支持。

        <Note title="说明">调用频率限制：20 次/秒。</Note>
      operationId: fetch-forbid-group-list
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=FetchForbidGroupList
          required: true
          schema:
            type: string
            enum: [FetchForbidGroupList]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FetchForbidGroupListRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FetchForbidGroupListResponse'
              example:
                Code: 0
                Message: success
                RequestId: "343649807833778782"
                FetchEnd: 1
                NextFlag: 100000
                GroupList:
                  - GroupId: "group_1"
                    ForbidType: 1
                  - GroupId: "group_2"
                    ForbidType: 5

components:
  schemas:
    FetchForbidGroupListRequest:
      type: object
      required: [FromUserId, StartFlag]
      properties:
        FromUserId:
          type: string
          description: 查询操作者的用户 ID（已在客户端调用 login 方法登录 ZIM 服务，或已调用 [服务端 API](/zim-server/user/batch-register-users) 完成注册）。
          maxLength: 32
          example: "userId"
        StartFlag:
          type: number
          description: 分页拉取标志。第一次填 0，之后填上一次返回的 NextFlag 值。当返回的 NextFlag 为 0 时，表示群组列表获取完毕。
          example: 0
    FetchForbidGroupListResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            返回码。

            以下仅列出了接口业务逻辑相关的返回码，完整返回码请参考 [全局返回码](/zim-server/return-codes)。
            <table>
            <thead><tr><th>返回码</th><th>描述</th><th>处理建议</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>输入参数错误。</td><td>请检查输入的参数。</td></tr>
            <tr><td>660000003</td><td>逻辑处理错误。</td><td>请重试，或联系 ZEGO 技术支持。</td></tr>
            <tr><td>660000011</td><td>用户个数超过限制。</td><td>请检查输入的用户列表。</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: 操作结果描述。
          example: "success"
        RequestId:
          type: string
          description: 请求 ID。
          example: "343649807833778782"
        FetchEnd:
          type: number
          description: 
            是否拉取完毕：
            - 0：否。
            - 1：是。
          example: 1
        NextFlag:
          type: number
          description: |
            - 当 FetchEnd 为 0 时，表示仍有更多群组可拉取，可将其作为下次接口调用的 StartFlag。
            - 当 FetchEnd 为 1 时，表示列表已拉取完毕，此时请忽略此字段。
          example: 100000
        GroupList:
          type: array
          description: 禁言群组列表。
          items:
            type: object
            properties:
              GroupId:
                type: string
                description: 群组 ID。
                example: "group_1"
              ForbidType:
                type: number
                description: |
                  禁言类型：
                  - 1：全员禁言
                  - 2：按群组角色禁言
                  - 4：按用户 ID 禁言
                  
                  如果同时存在多种禁言情况，ForbidType 会把这些数值相加，例如同时全员禁言（1）和按群组角色禁言（2）时，ForbidType 为 3。
                example: 1