openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - group

paths:
  /:
    get:
      tags: [group]
      summary: 修改群规格限制
      description: |
        通过此接口修改群组的以下规格限制：
        - 进群模式；
        - 邀请模式；
        - 受邀请模式；
        - 群组成员人数上限（最高不超过套餐包的限制，详情请参考 [计费说明 - 版本差异](/zim-android/introduction/pricing#版本差异)）。

        修改成功后，群成员可通过以下 ZIM SDK 的回调接口接收群组规格限制修改的通知：

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|--------|---------|
        | [groupVerifyInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-group-verify-info-updated-operated-info-group-id) | [onGroupVerifyInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-group-verify-info-updated) | [groupVerifyInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-group-verify-info-updated-operated-info-group-id) | [onGroupVerifyInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-group-verify-info-updated) |

        | Web-25% | 小程序-25% | Flutter-25% | React Native-25% |
        |-----|---------|---------|---------|
        | [groupVerifyInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#group-verify-info-updated) | [groupVerifyInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#group-verify-info-updated) | [onGroupVerifyInfoUpdated](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onGroupVerifyInfoUpdated.html) |[groupVerifyInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#group-verify-info-updated) |

        | Unity3D-25% | uni-app \| uni-app x-25% | HarmonyOS-25% |
        |---------|--------------|-----------|
        | [OnGroupVerifyInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-group-verify-info-updated) |[groupVerifyInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#group-verify-info-updated) |[groupVerifyInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#group-verify-info-updated) |

        <Note title="说明">调用频率限制：20 次/秒。</Note>

        <Note title="说明">如果无需修改 JoinMode、InviteMode 或 BeInvitedMode，请不要在 URL 中携带该参数；若携带但未赋值，其值可能被修改为 0。</Note>
      operationId: modify-group-specification-limits
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=ModifyGroupLimit
          required: true
          schema:
            type: string
            enum: [ModifyGroupLimit]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - name: FromUserId
          in: query
          required: true
          description: 修改操作者的用户 ID（已注册/已登录）。
          schema:
            type: string
            maxLength: 32
            example: "operator_user"
        - name: GroupId
          in: query
          required: true
          description: 目标群组的 ID。
          schema:
            type: string
            maxLength: 32
            example: "group123"
        - name: JoinMode
          in: query
          required: false
          schema:
            type: integer
            enum: [0, 1, 2]
          description: 加入群组的模式：0 无需验证；1 需申请并经群主/管理员同意；2 仅可被邀请入群。
        - name: InviteMode
          in: query
          required: false
          schema:
            type: integer
            enum: [0, 1]
          description: 邀请模式：0 所有成员可邀请；1 仅群主或管理员可邀请。
        - name: BeInvitedMode
          in: query
          required: false
          schema:
            type: integer
            enum: [0, 1]
          description: 受邀请模式：0 可直接邀请入群；1 邀请后需对方同意。
        - name: MemberCountLimit
          in: query
          required: false
          schema:
            type: integer
          description: 群组成员人数上限，默认值为 0。
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'

components:
  schemas:
    CommonResponse:
      type: object
      properties:
        Code:
          type: integer
          description: |
            返回码。
            <table>
            <thead><tr><th>返回码</th><th>说明</th><th>处理建议</th></tr></thead>
            <tbody>
            <tr><td>660000001</td><td>服务端出错。</td><td>请重试，或联系 ZEGO 技术支持。</td></tr>
            <tr><td>660000002</td><td>输入的参数缺失或不合法。</td><td>请检查输入的参数。</td></tr>
            <tr><td>660300005</td><td>调用接口的频率超出了 AppID 级别限制。</td><td>请稍后再试。</td></tr>
            <tr><td>660500002</td><td>操作者用户未注册。</td><td>请先注册操作者用户。</td></tr>
            <tr><td>660600001</td><td>群不存在。</td><td>请确认输入的 GroupId 是否正确。</td></tr>
            <tr><td>660600009</td><td>获取群相关信息失败。</td><td>请先确认 GroupID 是否正确。如果正确，请联系 ZEGO 技术支持。</td></tr>
            </tbody>
            </table>
        Message:
          type: string
        RequestId:
          type: string
