openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - group

paths:
  /:
    get:
      tags: [group]
      summary: 查询 App 下的群组列表
      description: |
        获取 App 中所有群组的 ID。

        <Warning title="注意">获取的数据可能会存在最多 1 分钟 的延迟。</Warning>

        <Note title="说明">调用频率限制：1 次/秒。</Note>
      operationId: query-group-list-in-the-app
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=QueryAppGroupList
          required: true
          schema:
            type: string
            enum: [QueryAppGroupList]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryAppGroupListRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryAppGroupListResponse'
              example:
                Code: 0
                Message: success
                RequestId: "343649807833778782"
                TotalCount: 1680
                Next: 168
                GroupIdList:
                  - GroupId: "groupA"
                    GroupName: "groupNameA"
                  - GroupId: "groupB"
                    GroupName: "groupNameB"

components:
  schemas:
    QueryAppGroupListRequest:
      type: object
      properties:
        Limit:
          type: number
          description: |
            单次获取群组 ID 的数量，取值范围为 [0, 10000]，即调用本接口一次最多返回 10000 个群组 ID。

            当 App 内的群组数量存在超过 Limit 时，需调用多次本接口<b>且 Limit 需保持一致</b>。

            如果传空或大于 10000，则默认取值为 10000。
          minimum: 0
          maximum: 10000
          example: 100
        Next:
          type: number
          description: |
            分页拉取标志，第一次填 0，以后填上一次返回的值，返回的 Next 为 0 代表群列表获取完毕。

            例如，App 内有 25000 个群组，调用本接口查询群列表时：

            - 第一次调用本接口，Limit 填 10000，Next 填 0，查询第 1 ～ 10000 个群组；返回结果中的 Next 值为 1
            - 第二次调用本接口，Limit 填 10000，Next 填 1，查询第 10001 ～ 20000 名群组；返回结果中 Next 值为 2。
            - 第三次调用本接口，Limit 填 10000，Next 填 2，查询第 20001 ～ 25000 名群组；查询完毕，返回结果中的 Next 为 0。
          example: 0
    QueryAppGroupListResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            返回码。

            以下仅列出了接口业务逻辑相关的返回码，完整返回码请参考 [全局返回码](/zim-server/return-codes)。
            <table>
            <thead><tr><th>返回码</th><th>说明</th><th>处理建议</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>参数错误。</td><td>请参考 请求参数 输入正确参数。</td></tr>
            <tr><td>660600006</td><td>查询群列表数据出错。</td><td>请联系 ZEGO 技术支持。</td></tr>
            <tr><td>660600007</td><td>调用 QueryAppGroupList 接口的频率超出限制。</td><td>调用频率为 1 次/秒，请勿超出限制。</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: 请求结果的说明信息。
          example: "success"
        RequestId:
          type: string
          description: 请求 ID。
          example: "343649807833778782"
        TotalCount:
          type: number
          description: App 当前的群组总数。
          example: 1680
        Next:
          type: number
          description: |
            分页拉取的标志。非 0 时表示列表查询未完。
            >**说明**
            >
            > 除上述说明之外，此字段与列表信息无任何关联，请勿基于此做任何其他逻辑。
          example: 168
        GroupIdList:
          type: array
          description: 获取到的群组 ID 的集合。
          items:
            type: object
            properties:
              GroupId:
                type: string
                description: 群组的 ID。
                example: "groupA"
              GroupName:
                type: string
                description: 群组名称。
                example: "groupNameA"