openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - group

paths:
  /:
    post:
      tags: [group]
      summary: 查询群成员列表
      description: |
        根据群组 ID 获取群组中的用户列表。

        <Note title="说明">群组 ID 可通过 查询 App 下的群组列表 获取。</Note>

        <Note title="说明">调用频率限制：20 次/秒。</Note>
      operationId: query-group-member-list
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=QueryGroupMemberList
          required: true
          schema:
            type: string
            enum: [QueryGroupMemberList]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryGroupMemberListRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryGroupMemberListResponse'

components:
  schemas:
    QueryGroupMemberListRequest:
      type: object
      required: [GroupId]
      properties:
        GroupId:
          type: string
          description: 群组 ID。
          maxLength: 32
          example: "group123"
        Limit:
          type: integer
          format: int32
          description: 单次获取成员的数量，范围 [0, 1000]，为空或>1000时取 1000。
          minimum: 0
          maximum: 1000
          example: 100
        Next:
          type: integer
          format: int32
          description: 分页拉取标志，第一次 0，之后填上一次返回的 Next。
          example: 0
    QueryGroupMemberListResponse:
      type: object
      properties:
        Code:
          type: integer
          description: |
            返回码。
            <table>
            <thead><tr><th>返回码</th><th>说明</th><th>处理建议</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>参数错误。</td><td>请检查请求参数。</td></tr>
            <tr><td>660600001</td><td>群不存在。</td><td>请确认 GroupId 是否正确。</td></tr>
            <tr><td>660600003</td><td>查询群成员列表出错。</td><td>请联系 ZEGO 技术支持。</td></tr>
            <tr><td>660600004</td><td>调用频率超出限制。</td><td>调用频率为 20 次/秒，请勿超出限制。</td></tr>
            </tbody>
            </table>
        Message:
          type: string
          description: 请求结果说明。
        RequestId:
          type: string
          description: 请求 ID。
        Data:
          type: object
          properties:
            TotalCount:
              type: integer
              description: 服务端开始查询时的群成员总数。
            Next:
              type: integer
              description: 分页拉取标志，非 0 表示未完。
            MemberList:
              type: array
              description: 群成员信息集合。
              items:
                type: object
                properties:
                  UserId:
                    type: string
                  UserName:
                    type: string
                  UserNickName:
                    type: string
