openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - group

paths:
  /:
    post:
      tags: [group]
      summary: 查询群成员列表
      description: |
        根据群组 ID 获取群组中的用户列表。

        <Note title="说明">群组 ID 可通过 [查询 App 下的群组列表](/zim-server/group/query-group-list-in-the-app) 获取。</Note>

        <Note title="说明">调用频率限制：20 次/秒。</Note>
      operationId: query-group-member-list
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=QueryGroupMemberList
          required: true
          schema:
            type: string
            enum: [QueryGroupMemberList]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryGroupMemberListRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryGroupMemberListResponse'
              example:
                Code: 0
                Message: success
                RequestId: "343649807833778782"
                TotalCount: 1680
                Next: 168
                MemberList:
                  - UserId: "u1"
                    UserName: "userName1"
                    UserNickName: "userNickName1"
                  - UserId: "u2"
                    UserName: "userName2"
                    UserNickName: "userNickName2"

components:
  schemas:
    QueryGroupMemberListRequest:
      type: object
      required: [GroupId]
      properties:
        GroupId:
          type: string
          description: 群组 ID。仅支持数字，英文字符和 '!'，'#'，'$'，'%'，'&'，'('，')'，'+'，'-'，':'，';'，'<'，'='，'.'，'>'，'?'，'@'，'['，']'，'^'，'_'，'{'，'}'，'|'，'~'。
          maxLength: 32
          example: "groupA"
        Limit:
          type: number
          description: |
            单次获取成员的数量，取值范围为 [0, 1000]，即调用本接口一次最多返回 1000 个成员。

            当群组内成员超过 Limit 时，需调用多次本接口<b>且 Limit 需保持一致</b>。
            
            如果传空或大于 1000，则默认取值为 1000。
          minimum: 0
          maximum: 1000
          example: 1000
        Next:
          type: number
          description: |
            分页拉取标志，第一次 0，之后填上一次返回的 Next。

            例如，群组内有 2500 个成员，调用本接口查询群成员列表时：
            
            - 第一次调用本接口，Limit 填 1000，Next 填 0，查询第 1 ～ 1000 名成员；返回结果中的 Next 值为 1。
            - 第二次调用本接口，Limit 填 1000，Next 填 1，查询第 1001 ～ 2000 名成员；返回结果中 Next 值为 2。
            - 第三次调用本接口，Limit 填 1000，Next 填 2，查询第 2001 ～ 2500 名成员；查询完毕，返回结果中的 Next 为 0。
          example: 0
    QueryGroupMemberListResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            返回码。

            以下仅列出了接口业务逻辑相关的返回码，完整返回码请参考 [全局返回码](/zim-server/return-codes)。
            <table>
            <thead><tr><th>返回码</th><th>说明</th><th>处理建议</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>参数错误。</td><td>请参考 Request 输入正确参数。</td></tr>
            <tr><td>660600001</td><td>群不存在。</td><td>请确认 GroupId 是否正确。</td></tr>
            <tr><td>660600003</td><td>查询群成员列表出错。</td><td>请联系 ZEGO 技术支持。</td></tr>
            <tr><td>660600004</td><td>调用频率超出限制。</td><td>调用频率为 20 次/秒，请勿超出限制。</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: 请求结果的说明信息。
          example: "success"
        RequestId:
          type: string
          description: 请求 ID。
          example: "343649807833778782"
        TotalCount:
          type: number
          description: 服务端开始查询时的群成员总数。
          example: 1680
        Next:
          type: number
          description: |
            分页拉取的标志。非 0 时表示列表获取未完。
            >说明
            >
            > 除上述说明之外，此字段与列表信息无任何关联，请勿基于此做任何其他逻辑。
          example: 168
        MemberList:
          type: array
          description: 群成员信息集合。
          items:
            type: object
            properties:
              UserId:
                type: string
                description: 群成员 ID。
                example: "u1"
              UserName:
                type: string
                description: 群成员名称。
                example: "userName1"
              UserNickName:
                type: string
                description: 用户在群组内的昵称。
                example: "userNickName1"