openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - group

paths:
  /:
    post:
      tags: [group]
      summary: 设置群成员昵称
      description: |
        通过该接口批量修改群内成员在该群中的昵称。默认单次最多可修改 20 名用户的昵称，如需调整，请联系 ZEGO 技术支持。

        <Note title="说明">以下 FromUserId 和 UserId 对应的用户需已登录或已注册。</Note>

        <Note title="说明">调用频率限制：1 次/秒（群级别）。</Note>
      operationId: set-nicknames-of-group-members
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=SetGroupMembersNickname
          required: true
          schema:
            type: string
            enum: [SetGroupMembersNickname]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetGroupMembersNicknameRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetGroupMembersNicknameResponse'

components:
  schemas:
    SetGroupMembersNicknameRequest:
      type: object
      required: [FromUserId, GroupId, UserIds]
      properties:
        FromUserId:
          type: string
          description: 操作者用户 ID。用户需已注册 ZIM 服务。
          maxLength: 32
          example: "operator_user"
        GroupId:
          type: string
          description: 群组 ID。
          maxLength: 32
          example: "group123"
        UserIds:
          type: array
          description: 需要被设置昵称的用户列表。
          items:
            type: object
            required: [UserId, Nickname]
            properties:
              UserId:
                type: string
                description: 用户 ID。
                maxLength: 32
                example: "user1"
              Nickname:
                type: string
                description: 群昵称。
                maxLength: 256
                example: "User Nickname"
    SetGroupMembersNicknameResponse:
      type: object
      properties:
        Code:
          type: integer
          description: |
            返回码。
            <table>
            <thead><tr><th>返回码</th><th>说明</th><th>处理建议</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>输入参数错误。</td><td>请检查输入参数。</td></tr>
            <tr><td>660000011</td><td>用户个数超过限制。</td><td>请检查输入的用户列表。</td></tr>
            <tr><td>660300006</td><td>频率限制。</td><td>请稍后再试，或了解相关频率限制。</td></tr>
            <tr><td>660500002</td><td>操作者用户未注册。</td><td>请让操作者先注册 ZIM 服务。</td></tr>
            <tr><td>660600001</td><td>群组不存在。</td><td>请确认输入的 GroupID 是否正确。</td></tr>
            </tbody>
            </table>
        Message:
          type: string
        RequestId:
          type: string
        ErrorUsers:
          type: array
          description: 昵称设置失败用户信息。部分失败时返回。
          items:
            type: object
            properties:
              UserId:
                type: string
              SubCode:
                type: integer
