openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - group

paths:
  /:
    post:
      tags: [group]
      summary: 设置群成员昵称
      description: |
        通过该接口批量修改群内成员在该群中的昵称。默认单次最多可修改 20 名用户的昵称，如需调整，请联系 ZEGO 技术支持。

        昵称设置成功后，群内成员通过以下 ZIM SDK 的回调接口，收到相关通知：
        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|--------|---------|
        | [groupMemberInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-group-member-info-updated-operated-info-group-id) | [onGroupMemberInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-group-member-info-updated) | [groupMemberInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-group-member-info-updated-operated-info-group-id) | [onGroupMemberInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-group-member-info-updated) |
        
        | Web-25% | 小程序-25% | Flutter-25% | React Native-25% |
        |---------|-----|---------|---------|
        | [groupMemberInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#group-member-info-updated) | [groupMemberInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#group-member-info-updated) | [onGroupMemberInfoUpdated](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onGroupMemberInfoUpdated.html) | [groupMemberInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#group-member-info-updated) |
        
        | Unity3D-25% | uni-app \| uni-app x-25% | HarmonyOS-25% |
        |---------|---------|---------|
        | [OnGroupMemberInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-group-member-info-updated) | [groupMemberInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#group-member-info-updated) | [groupMemberInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#group-member-info-updated) |


        <Note title="说明">以下 `FromUserId` 和 `UserId` 对应的用户已在客户端调用 `login` 方法登录 ZIM 服务，或已调用 [服务端 API](/zh/zim-server/user/batch-register-users) 完成注册。</Note>

        <Note title="说明">1 次/秒，群级别限制。如需调整，请联系 ZEGO 技术支持。</Note>
        <Note title="说明">
        FromUserId、GroupId、UserIds 和 Nickname 仅支持数字，英文字符和 `'!'，'#'，'$'，'%'，'&'，'('，')'，'+'，''，':'，';'，'<'，'='，'.'，'>'，'?'
        ，'@'，'['，']'，'^'，'_'，'{'，'}'，'|'，'~'`。
        </Note>
      operationId: set-nicknames-of-group-members
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=SetGroupMembersNickname
          required: true
          schema:
            type: string
            enum: [SetGroupMembersNickname]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetGroupMembersNicknameRequest'
            example:
              FromUserId: "zego_user"
              GroupId: "groupA"
              UserIds:
                - UserId: "usera"
                  Nickname: "nicknamea"
                - UserId: "userb"
                  Nickname: "nicknameb"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetGroupMembersNicknameResponse'

components:
  schemas:
    SetGroupMembersNicknameRequest:
      type: object
      required: [FromUserId, GroupId, UserIds]
      properties:
        FromUserId:
          type: string
          description: 操作者用户 ID。用户需已注册 ZIM 服务。
          maxLength: 32
          example: "zego_user"
        GroupId:
          type: string
          description: 群组 ID。
          maxLength: 32
          example: "groupA"
        UserIds:
          type: array
          description: 需要被设置昵称的用户列表。
          items:
            type: object
            required: [UserId, Nickname]
            properties:
              UserId:
                type: string
                description: 用户 ID。
                maxLength: 32
                example: "usera"
              Nickname:
                type: string
                description: 用户在群组的昵称。
                maxLength: 256
                example: "nicknamea"
    SetGroupMembersNicknameResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            返回码。

            以下仅列出了接口业务逻辑相关的返回码，完整返回码请参考 [全局返回码](/zim-server/return-codes)。
            <table>
            <thead><tr><th>返回码</th><th>说明</th><th>处理建议</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>输入参数错误。</td><td>请检查输入参数。</td></tr>
            <tr><td>660000011</td><td>用户个数超过限制。</td><td>请检查输入的用户列表。</td></tr>
            <tr><td>660300006</td><td>频率限制。</td><td>请稍后再试，或了解相关频率限制。</td></tr>
            <tr><td>660500002</td><td>操作者用户未注册。</td><td>请让操作者先注册 ZIM 服务。</td></tr>
            <tr><td>660600001</td><td>群组不存在。</td><td>请确认输入的 GroupID 是否正确。</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: 操作结果描述。
          example: "success"
        RequestId:
          type: string
          description: 请求 ID。
          example: "343649807833778782"
        ErrorUsers:
          type: array
          description: |
            昵称设置失败用户信息。
            <ul>
            <li>Code 为 0：</li>
            <li>ErrorUsers 为空，全部指定用户昵称设置成功。</li>
            <li>ErrorUsers 不为空，表示部分指定用户昵称设置失败，请参考 SubCode 处理。</li>
            <li>Code 不为 0：</li>
            <li>ErrorUsers 为空，表示参数错误、接口频率限制、系统错误。</li>
            <li>ErrorUsers 不为空，表示全部指定用户昵称设置失败。</li>
            </ul>
          items:
            type: object
            properties:
              UserId:
                type: string
                description: 失败用户 ID。
              SubCode:
                type: number
                description: |
                  昵称设置失败的具体返回码。

                  以下仅列出了接口业务逻辑相关的返回码，完整返回码请参考 [全局返回码](/zim-server/return-codes)。
                  <table>
                  <thead><tr><th>返回码</th><th>说明</th><th>处理建议</th></tr></thead>
                  <tbody>
                  <tr><td>660000002</td><td>输入参数错误。</td><td>请检查输入参数。</td></tr>
                  <tr><td>660000011</td><td>用户个数超过限制。</td><td>请检查输入的用户列表。</td></tr>
                  <tr><td>660300006</td><td>频率限制。</td><td>请稍后再试，或了解相关频率限制。</td></tr>
                  <tr><td>660500002</td><td>操作者用户未注册。</td><td>请让操作者先注册 ZIM 服务。</td></tr>
                  <tr><td>660600001</td><td>群组不存在。</td><td>请确认输入的 GroupID 是否正确。</td></tr>
                  </tbody>
                  </table>
