openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - conversation

paths:
  /:
    post:
      tags: [conversation]
      summary: Mute notifications for conversations
      description: |
        By calling this API, you can batch set the mute notification status for one-on-one or group conversations. After setting to mute, the ZIM SDK will not push message notifications for related conversations to users, and the user's "total unread message count" will not increase.

        By default, users can set up to 500 one-on-one conversations to mute. If you need to increase this limit, please contact ZEGOCLOUD Technical Support. The maximum can be 1000.

        The mute limit for group conversations is the upper limit of the number of groups each user can join.

        The client will receive changes in the mute notification status of conversations through the following ZIM SDK callback:

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|-------|---------|
        | [conversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-group-member-info-updated-operated-info-group-id) | [onConversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~java_android~class~ZIMEventHandler#on-conversation-changed) | [conversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-group-member-info-updated-operated-info-group-id) | [onConversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-conversation-changed) |

        | Web-25% | Mini Program-25% | Flutter-25% | React Native-25% |
        |-----|--------|---------|--------------|
        | [conversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#conversation-changed) | [conversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#conversation-changed) | [onConversationChanged](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onConversationChanged.html) | [conversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#conversation-changed) |

        | Unity3D-25% | uni-app \| uni-app x-25% | HarmonyOS-25%  |
        |---------|---------|---------|
        | [OnConversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-conversation-changed) | [conversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#conversation-changed) | [conversationChanged](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#conversation-changed) |

        <Note title="Note">The parameter FromUserId only supports numbers, English characters, and \{'!', '#', '$', '%', '&', '(', ')', '+', '-', ':', ';', '\<', '=', '.', '\>', '?', '@', '[', ']', '^', '_', ' ', '\{', '\}', '|', '~'\}.</Note>

        <Note title="QPS Limit"> 20 times/s</Note>
      operationId: mute-notifications-for-conversations
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=SilenceConvNotification
          required: true
          schema:
            type: string
            enum: [SilenceConvNotification]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SilenceConvNotificationRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SilenceConvNotificationResponse'

components:
  schemas:
    SilenceConvNotificationRequest:
      type: object
      required: [FromUserId, ConvType, ConvIds, Enable]
      properties:
        FromUserId:
          type: string
          description: |
            Request to set the mute notification status for conversations of this UserID (who has logged in to the ZIM service by calling the login method on the client, or has completed registration by calling the [server-side API](/zim-server/user/batch-register-users)).
          maxLength: 32
          example: "userA"
        ConvType:
          type: number
          description: |
            Conversation type:
            - 0: One-on-one conversation.
            - 2: Group conversation.
          enum: [0, 2]
          example: 0
        ConvIds:
          type: array
          description: |
            List of conversation IDs to set mute status, with a maximum length of 10.
            - One-on-one conversation: Conversation ID is the user ID.
            - Group conversation: Conversation ID is the group ID.

            > Note
            >
            > The conversation types in this list must be consistent, otherwise the API call will fail.
          maxItems: 10
          items:
            type: string
            maxLength: 32
            example: "ConvId1"
          example: ["ConvId1", "ConvId2"]
        Enable:
          type: boolean
          description: |
            Whether to mute:
            - true: Enable mute.
            - false: Disable mute.
          example: true
    SilenceConvNotificationResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            The following only lists the Code and SubCode related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            > **Note**
            >
            > When you request to modify the mute status of multiple conversations:
            > <ul><li>As long as the status of 1 or more conversations is successfully modified, Code will return 0, indicating success. In this case, please refer to the specific information in ErrorList to understand the details of failed conversation status modifications.</li>
            > <li>If the status of all conversations fails to be modified, Code will return the relevant return code. For details, please refer to <a href="/zim-server/return-codes" target="_blank">Return codes</a>.</li></ul>
            <table>
            <thead><tr><th>Code / SubCode</th><th>Description</th><th>Suggested Solution</th></tr></thead>
            <tbody>
            <tr><td>660000001</td><td>General business error.</td><td>Please retry or contact ZEGOCLOUD Technical Support.</td></tr>
            <tr><td>660000002</td><td>Input parameter error.</td><td>Please check the input parameters.</td></tr>
            <tr><td>660300005</td><td>The API call frequency exceeds the AppID-level limit.</td><td>Please try again later.</td></tr>
            <tr><td>660500002</td><td>FromUserId is not registered.</td><td>Please register FromUserId first.</td></tr>
            <tr><td>660600001</td><td>Group does not exist.</td><td>Please confirm if the entered GroupId is correct.</td></tr>
            <tr><td>660600009</td><td>Failed to get group-related information.</td><td>Please confirm if the GroupID is correct first. If correct, please contact ZEGOCLOUD Technical Support.</td></tr>
            <tr><td>660600024</td><td>FromUserId is not in the target group.</td><td>Please join the group first.</td></tr>
            <tr><td>660700015</td><td><ul><li>If this error code is code, it means all peer users of one-on-one conversations are not registered.</li><li>If this error code is subCode, it means the peer user of the one-on-one conversation corresponding to ConvID is not registered.</li></ul></td><td>Please register the peer user first.</td></tr>
            <tr><td>660800030</td><td>The user's mute list exceeds the length limit, default is 500, can be configured by contacting technical support, maximum can be 1000.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
            <tr><td>660800051</td><td>Conversation is already muted, cannot be set to mute again.</td><td>No action needed.</td></tr>
            <tr><td>660800052</td><td>Conversation mute has already been canceled, cannot be canceled again.</td><td>No action needed.</td></tr>
            </tbody>
            </table>
        Message:
          type: string
          description: Description of the request result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        ErrorList:
          type: array
          description: |
            Failure list.
            - When Code is 0:
              - If ErrorList is empty, the mute status of all conversations has been successfully modified.
              - If ErrorList is not empty, it means the mute status modification of some conversations failed. Please refer to SubCode and SubMessage for handling.
            - When Code is not 0:
              - If ErrorList is empty, it indicates parameter error, API frequency limit, or system error.
              - If ErrorList is not empty, it means the mute status modification of all conversations failed.
          items:
            type: object
            properties:
              ConvId:
                type: string
                description: |
                  Conversation ID for which the mute status modification failed.
                  - One-on-one conversation: Conversation ID is the user ID.
                  - Group conversation: Conversation ID is the group ID.
                example: "ConvId1"
              SubCode:
                type: number
                description: |
                  Specific error code for the failed mute status modification. For the complete return codes, please refer to the Code description or [Return codes](/zim-server/return-codes).
                example: 660800030
              SubMessage:
                type: string
                description: Specific error description for the failed mute status modification.
                example: "input params error"
          example:
            - ConvId: "ConvId1"
              SubCode: 660800030
              SubMessage: "input params error"
