openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - conversation

paths:
  /:
    post:
      tags: [conversation]
      summary: Query conversation list
      description: |
        By calling this API, you can retrieve the complete conversation list of a specified user in pages, returning up to 1000 latest conversations (one-on-one and group chats).

        <Note title="Note">Even if a user is kicked out of a conversation, the API will still return that conversation; however, if the conversation is disbanded, the conversation information cannot be obtained through this API.</Note>

        <Note title="QPS Limit"> 20 times/s</Note>
      operationId: query-conversation-list
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=QueryConversationList
          required: true
          schema:
            type: string
            enum: [QueryConversationList]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryConversationListRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryConversationListResponse'

components:
  schemas:
    QueryConversationListRequest:
      type: object
      required: [FromUserId]
      properties:
        FromUserId:
          type: string
          description: |
            Query the conversation list of this UserID (who has logged in to the ZIM service by calling the login method on the client, or has completed registration by calling the [server-side API](/zim-server/user/batch-register-users)).

            > **Note**
            >
            > FromUserId only supports numbers, English characters, and {"'!', '#', '$', '%', '&', '(', ')', '+', '', ':', ';', '<', '=', '.', '>', '?', '@', '[', ']', '^', '_', ' ', '{', '}', '|', '~'}.
          maxLength: 32
          example: "u1"
        Limit:
          type: number
          description: |
            Number of conversations to retrieve at once, default is 100, value range is (0, 500].
            - When the value is ≤ 0, it will be corrected to 100.
            - When the value is > 500, it will be corrected to 500.
          minimum: 1
          maximum: 500
          default: 100
          example: 10
        Next:
          type: number
          description: |
            Pagination flag. Fill in 0 for the first time, and then fill in the Next value returned from the previous call. When the returned Next is 0, it means the friend list has been fully retrieved.

            For example, if FromUserId has 250 conversations, when calling this API:
            - First call: Set Limit to 100, Next to 0, to query conversations 1-100; the Next value in the returned result is num1.
            - Second call: Set Limit to 100, Next to num1, to query conversations 101-200; the Next value in the returned result is num2.
            - Third call: Set Limit to 100, Next to num2, to query conversations 201-250; query is complete, the Next value in the returned result is 0.
          example: 0
    QueryConversationListResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.
            <table>
            <thead><tr><th>Return code</th><th>Description</th><th>Suggested Solution</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>Input parameter error.</td><td>Please check the input parameters.</td></tr>
            <tr><td>660300005</td><td>The API call frequency exceeds the AppID-level limit.</td><td>Please try again later.</td></tr>
            <tr><td>660500002</td><td>FromUserId is not registered.</td><td>Please check if FromUserId is correct.</td></tr>
            <tr><td>660800053</td><td>Failed to query conversation list.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
            </tbody>
            </table>
        Message:
          type: string
          description: Description of the request result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        TotalCount:
          type: number
          description: Total number of current conversations.
          example: 500
        Next:
          type: number
          description: |
            Pagination flag.
            - Non-zero: Indicates that there is still conversation information not returned. You need to set this field to the request parameter Next to retrieve more conversation information.
            - Zero: Indicates that the complete conversation list has been returned.

            > **Note**
            >
            > Apart from the above description, this field has no association with the list information. Please do not base any other logic on it.
          example: 1000
        List:
          type: array
          description: Conversation list. Results are returned in ascending order by UpdateTime.
          items:
            type: object
            properties:
              ConvId:
                type: string
                description: |
                  Conversation ID.
                  - One-on-one conversation: Conversation ID is the peer user's ID.
                  - Group conversation: Conversation ID is the group ID.
                example: "conv1"
              ConvType:
                type: number
                description: |
                  Conversation type.
                  - 0 or this field is not returned: One-on-one conversation.
                  - 2: Group conversation.
                example: 2
              UpdateTime:
                type: number
                description: Last modification time of the conversation, in milliseconds timestamp.
                example: 1708254395000
          example:
            - ConvId: "conv1"
              ConvType: 2
              UpdateTime: 1708254395000
            - ConvId: "conv2"
              ConvType: 0
              UpdateTime: 1708254395000
            - ConvId: "conv3"
              UpdateTime: 1708254395000
