openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com
servers:
  $ref: '../shared-components.yaml#/servers'
tags:
  - user
paths:
  /:
    get:
      tags: [user]
      summary: 删除所有好友
      description: |
        调用此接口，可为用户单向或双向删除全部好友数据。

        以用户 A、B 举例说明单向删除和双向删除：
        - 单向删除：当用户 A 单向删除了用户 B，用户 B 不再是用户 A 的好友、用户 A 仍为用户 B 的好友。
        - 双向删除：当用户 A 双向删除了用户 B，彼此都不再是对方的好友。


        为用户删除好友成功后，相关用户的客户端将通过以下 ZIM SDK 的回调接口接收好友列表更新的通知：

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|--------|---------|
        | [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-friend-list-changed-friend-info-list) | [onFriendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-friend-list-changed) | [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-friend-list-changed-friend-info-list) | [onFriendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-friend-list-changed) |

        | Web-25% | 小程序-25% | Flutter-25% | React Native-25% |
        |-----|---------|---------|---------|
        | [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#friend-list-changed) | [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#friend-list-changed) | [onFriendListChanged](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onFriendListChanged.html) | [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#friend-list-changed) |

        | uni-app \| uni-app x-25% | HarmonyOS-25% |
        |---------|---------|
        | [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#friend-list-changed) | [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#friend-list-changed) |
        
        <Note title="说明">FromUserId 仅支持数字，英文字符和 `'!', '#', '$', '%', '&', '(', ')', '+', '-', ':', ';', '<', '=', '.', '>', '?', '@', '[', ']', '^', '_', '{', '}', '|', '~'`。</Note>
        
        <Note title="说明">调用频率限制：20 次/秒。</Note>
      operationId: delete-all-friends
      parameters:
        - name: Action
          in: query
          required: true
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=DeleteAllFriends
          schema:
            type: string
            enum: [DeleteAllFriends]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - name: FromUserId
          in: query
          required: true
          description: 为此 UserId（已在客户端调用 login 方法登录 ZIM 服务，或已调用 [服务端 API](/zim-server/user/batch-register-users) 完成注册）删除全部好友。
          schema:
            type: string
            maxLength: 32
            example: "zego_user"
        - name: DeleteType
          in: query
          required: true
          description: |
            删除类型：
            - 0：双向删除。
            - 1：单向删除。
          schema:
            type: number
            enum: [0, 1]
            example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Code:
                    type: integer
                    description: |
                      返回码。

                      以下仅列出了接口业务逻辑相关的返回码，完整返回码请参考 [全局返回码](/zim-server/return-codes)。
                      <table>
                      <tbody><tr>
                      <th>返回码</th>
                      <th>描述</th>
                      <th>处理建议</th>
                      </tr>
                      <tr>
                      <td>660000001</td>
                      <td>业务类通用错误。</td>
                      <td>请重试，或联系 ZEGO 技术支持。</td>
                      </tr>
                      <tr>
                      <td>660000002</td>
                      <td>输入参数错误。</td>
                      <td>请检查输入的参数。</td>
                      </tr>
                      <tr>
                      <td>660300005</td>
                      <td>调用接口的频率超出了 AppID 级别限制。</td>
                      <td>请稍后再试。</td>
                      </tr>
                      </tbody></table>
                    example: 0
                  Message:
                    type: string
                    description: 请求结果的说明信息。
                    example: "success"
                  RequestId:
                    type: string
                    description: 请求 ID。
                    example: "343649807833778782"
