openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - user

paths:
  /:
    post:
      tags: [user]
      summary: 查询用户已加入的群信息
      description: |
        查询某用户已加入的群列表，支持分页。

        <Note title="说明">调用频率限制：20 次/秒。</Note>
      operationId: query-group-information-of-user-joined
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=QueryGroupsInfoOfUser
          required: true
          schema:
            type: string
            enum: [QueryGroupsInfoOfUser]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [FromUserId]
              properties:
                FromUserId:
                  type: string
                  description: 查询的用户 Id。
                  maxLength: 32
                  example: "UserId123"
                Limit:
                  type: integer
                  format: int32
                  description: 每页返回的群组数量。取值范围为 [1, 100]。
                  minimum: 1
                  maximum: 100
                  example: 2
                Next:
                  type: string
                  description: 分页标识符。首次请求填写空字符串获取第一页，后续请求填写响应结果中 NextRsp 值获取下一页。
                  example: ""
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryGroupsInfoOfUserResponse'

components:
  schemas:
    GroupInfoItem:
      type: object
      properties:
        GroupId:
          type: string
          description: 群组 Id。
          example: "groupId1"
        GroupName:
          type: string
          description: 群组名。
          example: "groupName1"
        GroupAvatar:
          type: string
          description: 群头像。
          example: "GroupAvatar1"
    QueryGroupsInfoOfUserResponse:
      type: object
      properties:
        Code:
          type: integer
          description: |
            返回码。

            <table>
            <tbody><tr>
            <th>返回码</th>
            <th>说明</th>
            <th>解决方案</th>
            </tr>
            <tr>
            <td>660000002</td>
            <td>参数错误。</td>
            <td>请检查参数。</td>
            </tr>
            <tr>
            <td>660300005</td>
            <td>频率限制。</td>
            <td>请稍后再尝试。</td>
            </tr>
            <tr>
            <td>660500002</td>
            <td>操作者用户未注册。</td>
            <td>请先注册请求的用户。</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: 返回状态信息信息。
          example: "success"
        RequestId:
          type: string
          description: 请求唯一标识。
          example: "req-123456789"
        NextRsp:
          type: string
          description: 下一页的分页拉取标识。如果为 0 表示没有更多数据。
          example: "3"
        HasJoinGroupNum:
          type: integer
          format: int64
          description: 用户已加入的群组数量。
          example: 21
        GroupInfoList:
          type: array
          description: 用户已加入的群组信息列表。
          items:
            $ref: '#/components/schemas/GroupInfoItem'
