openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - user

paths:
  /:
    get:
      tags: [user]
      summary: 查询好友列表
      description: |
        根据用户 ID 分页拉取其好友列表，获取备注、好友关系建立时间等信息。

        <Note title="说明">调用频率限制：20 次/秒。</Note>
      operationId: query-the-friend-list
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=QueryFriendList
          required: true
          schema:
            type: string
            enum: [QueryFriendList]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - name: FromUserId
          in: query
          required: true
          description: 查询此 UserID 的好友列表。
          schema:
            type: string
            maxLength: 32
            example: "zego"
        - name: Limit
          in: query
          required: false
          description: 单次拉取多少名好友的信息。取值范围为 [0, 100]。如果不填或数值为 0、大于 100，取值为 100。
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 100
            example: 100
        - name: Next
          in: query
          required: false
          description: 分页拉取标志，第一次填 0，之后填上一次返回的 Next 值。当返回的 Next 为 0 时，代表好友列表获取完毕。
          schema:
            type: string
            example: "2"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryFriendListResponse'

components:
  schemas:
    FriendAttribute:
      type: object
      properties:
        Key:
          type: string
          description: 好友属性的键。
          enum: [k0, k1, k2, k3, k4]
          example: "k0"
        Value:
          type: string
          description: 好友属性的值。
          example: "Value"
    FriendInfoItem:
      type: object
      properties:
        UserId:
          type: string
          description: 好友用户 ID。
          example: "user1"
        UserName:
          type: string
          description: 好友用户名。
          example: "UserName1"
        Avatar:
          type: string
          description: 好友头像。
          example: "Avatar1"
        UpdateTime:
          type: integer
          format: int64
          description: 好友关系建立时间戳（毫秒）。
          example: 1698310534000
        Attributes:
          type: array
          description: 好友属性列表。
          items:
            $ref: '#/components/schemas/FriendAttribute'
    QueryFriendListResponse:
      type: object
      properties:
        Code:
          type: integer
          description: |
            返回码。

            <table>
            <tbody><tr>
            <th>返回码</th>
            <th>说明</th>
            <th>处理建议</th>
            </tr>
            <tr>
            <td>660000001</td>
            <td>业务类通用错误。</td>
            <td>请重试，或联系 ZEGO 技术支持。</td>
            </tr>
            <tr>
            <td>660000002</td>
            <td>参数错误。</td>
            <td>请检查请求参数。</td>
            </tr>
            <tr>
            <td>660300005</td>
            <td>调用接口的频率超出了 AppID 级别限制。</td>
            <td>请稍后再试。</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: 请求结果的说明信息。
          example: "success"
        RequestId:
          type: string
          description: 请求 ID。
          example: "343649807833778782"
        TotalCount:
          type: integer
          format: int32
          description: 当前好友总数。
          example: 250
        Next:
          type: string
          description: 分页拉取标志，非 0 表示还有好友信息未返回；为 0 表示已经返回所有好友信息。
          example: "3"
        FriendInfos:
          type: array
          description: 好友信息列表。
          items:
            $ref: '#/components/schemas/FriendInfoItem'
