openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - user

paths:
  /:
    post:
      tags: [user]
      summary: 查询用户信息
      description: |
        支持通过用户 ID 查询用户的信息，包含用户名称、用户头像和扩展字段。

        <Note title="说明">调用频率限制：20 次/秒。</Note>
      operationId: query-user-information
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=QueryUserInfos
          required: true
          schema:
            type: string
            enum: [QueryUserInfos]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [UserIds]
              properties:
                UserIds:
                  type: array
                  description: |
                    需要查询的用户 ID 列表（已在客户端调用 login 方法登录 ZIM 服务，或已调用 [服务端 API](https://doc-zh.zego.im/zim-server/user/batch-register-users)，最大支持查询 100 个用户 ID。单个用户 ID 不超过 64 字节。
                    
                    >**说明**
                    >
                    > UserIds 仅支持数字，英文字符和 '!'，'#'，'$'，'%'，'&'，'('，')'，'+'，'-'，':'，';'，'<'，'='，'.'，'>'，'?'，'@'，'['，']'，'^'，'_'，' '，'{'，'}'，'|'，'~'。
                  maxItems: 100
                  items:
                    type: string
                    maxLength: 64
                    example: "userA"
                  example: ["userA", "userB", "userC"]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryUserInfosResponse'

components:
  schemas:
    QueryUserInfosResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            返回码。
            以下仅列出了接口业务逻辑相关的返回码，完整返回码请参考 [全局返回码](/zim-server/return-codes)。
            <table>
            <tbody><tr>
            <th>返回码</th>
            <th>描述</th>
            <th>处理建议</th>
            </tr>
            <tr>
            <td>660000001</td>
            <td>业务类通用错误。</td>
            <td>请重试，或联系 ZEGO 技术支持。</td>
            </tr>
            <tr>
            <td>660000002</td>
            <td>不存在的用户 ID，或者用户已经登出。</td>
            <td>请检查输入的参数。</td>
            </tr>
            <tr>
            <td>660300005</td>
            <td>调用接口的频率超出了 AppID 级别限制。</td>
            <td>请稍后再试。</td>
            </tr>
            <tr>
            <td>660700008</td>
            <td>获取用户信息出错。</td>
            <td>请检查用户 ID 是否正确，或联系 ZEGO 技术支持。</td>
            </tr>
            <tr>
            <td>660700015</td>
            <td>用户未注册。</td>
            <td>请先注册用户。</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: 请求结果的说明信息。
          example: "success"
        RequestId:
          type: string
          description: 请求 ID。
          example: "343649807833778782"
        Result:
          type: array
          description: 查询成功结果。
          items:
            type: object
            properties:
              UserId:
                type: string
                description: 查询成功的用户 ID。
                example: "UserA"
              UserName:
                type: string
                description: 用户名称。
                example: "userName"
              UserAvatar:
                type: string
                description: 用户头像地址。
                example: "avatar"
              Extra:
                type: string
                description: 扩展字段。
                example: "extra"
        ErrorList:
          type: array
          description: |
            查询失败列表。用户 ID 不存在或者用户已登出时，通过该字段返回。
            <ul>
            <li>Code 为 0：</li>
            <li>  ErrorList 为空，全部用户在线状态查询成功。</li>
            <li>  ErrorList 不为空，表示部分用户在线状态查询失败，请参考 SubCode 处理。</li>
            </ul>
            <ul>
            <li>Code 不为 0：</li>
            <li>  ErrorList 为空，表示参数错误、接口频率限制、系统错误。</li>
            <li>  ErrorList 不为空，表示所有用户在线状态查询失败。</li>
            </ul>
          items:
            type: object
            properties:
              UserId:
                type: string
                description: 查询失败的用户 ID。
                example: "UserB"
              SubCode:
                type: number
                description: |
                  查询失败时的返回码。
                example: 660000002
