openapi: 3.0.0
info:
  title: open-api-desc

  version: 1.0.0

servers:
  - url: https://cloud-realtime-asr-api.zegotech.cn

paths:
  /:
    post:
      tags:
        - cloud-realtime-asr
      summary: StopRealtimeASRTask
      description: Stop ASR task. When this interface is not called proactively and in a timely manner, the service will detect whether the room is empty. If it is empty for more than 150s, the task will be automatically terminated and the caller will be notified.
      operationId: stop
      parameters:
        - name: Action
          in: query
          description: |
            > Interface prototype parameters
            >
            > https://cloud-realtime-asr-api.zegotech.cn?Action=StopRealtimeASRTask
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [StopRealtimeASRTask]
          style: form
          explode: true
        # Reference shared parameters
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StopASRTaskRequest"
      responses:
        "200":
          description: Task stopped successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StopASRTaskResponse"

components:
  schemas:
    StopASRTaskRequest:
      type: object
      required:
        - TaskId
      properties:
        TaskId:
          type: string
          description: Unique identifier of the task.
          example: "1920370518175780864"

    StopASRTaskResponse:
      type: object
      properties:
        Code:
          type: integer
          description: Return code, 0 means success, other values mean failure. For details, refer to [Return Codes](/cloud-realtime-asr/api-reference/return-codes).
          example: 0
        Message:
          type: string
          description: Request result description
          example: "Success"
        RequestId:
          type: string
          description: Request ID
          example: "3151527792559699732"
