openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: './shared-components.yaml#/servers'

paths:
  /:
    post:
      tags:
        - upload
      summary: 取消上传任务
      description: |
        可通过本接口取消一个上传任务。

        <Note title="说明">
        - 本接口只能取消正在等待中的任务，不适用于已开始或已结束的任务。
        - 取消结果请通过[回调](/cloud-player-server/callback/callback)或[查询上传任务](/cloud-player-server/describe-upload-tasks)接口判断。
        </Note>

        <Note title="说明">调用频率限制：20 次/秒</Note>
      operationId: cancel-upload-task
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://cloud-player-api.zego.im?Action=CancelUploadTask
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [CancelUploadTask]
          style: form
          explode: true
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - UploadTaskId
              properties:
                UploadTaskId:
                  type: string
                  description: 上传任务 ID，上传任务的唯一标识。在调用 [CreateUploadTask](/cloud-player-server/create-upload-task) 接口创建上传任务后，您可通过响应参数获取此 ID。
                  example: "XXXXXXXXXXXX"
              example:
                UploadTaskId: "XXXXXXXXXXXX"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Code:
                    type: number
                    description: |
                      错误码。
                      
                      以下仅列出了接口业务逻辑相关的返回码，完整返回码请参考 [全局返回码](/cloud-player-server/return-codes)。
                      <table>
                      <thead>
                      <tr><th>返回码</th><th>说明</th><th>处理建议</th></tr>
                      </thead>
                      <tbody>
                      <tr><td>0</td><td>成功。</td><td>-</td></tr>
                      <tr><td>100000004</td><td>签名过期。</td><td>请重新生成签名。</td></tr>
                      <tr><td>100000005</td><td>签名错误。</td><td>请确认生成签名的参数是否正确。</td></tr>
                      <tr><td>350006001</td><td>接口请求频率超过上限。</td><td>请确认对应接口的 QPS 限制，降低请求频率。</td></tr>
                      <tr><td>350006002</td><td>网关校验失败。</td><td>请联系 ZEGO 技术支持处理。</td></tr>
                      <tr><td>350006003</td><td>无效的输入参数。</td><td>请根据 Message 提示，调整对应参数的取值。</td></tr>
                      <tr><td>350006006</td><td>服务未开通。</td><td>请联系 ZEGO 技术支持，开通服务权限。</td></tr>
                      <tr><td>350010000</td><td>系统错误。</td><td>请联系 ZEGO 技术支持处理。</td></tr>
                      </tbody>
                      </table>
                    example: 0
                  Message:
                    type: string
                    description: 错误描述。
                    example: "succeed"
                  RequestId:
                    type: string
                    description: 请求 ID。
                    example: "3433376152562619"
                  Data:
                    type: "null"
                    description: 返回的具体信息。
                    example: null
                example:
                  Code: 0
                  Message: "succeed"
                  RequestId: "3433376152562619"
                  Data: null

