openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: './shared-components.yaml#/servers'

paths:
  /:
    post:
      tags:
        - player
      summary: 销毁云端播放器
      description: |
        调用本接口销毁指定的云端播放器。

        <Note title="说明">调用频率限制：20 次/秒</Note>
      operationId: delete-player
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://cloud-player-api.zego.im?Action=DeletePlayer
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DeletePlayer]
          style: form
          explode: true
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeletePlayerRequest'
      responses:
        '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/DeletePlayerResponse'

components:
  schemas:
    DeletePlayerRequest:
      type: object
      required: [PlayerId]
      properties:
        PlayerId:
          type: string
          description: 云端播放器唯一标识 ID，通过 [CreatePlayer](/cloud-player-server/create-player) 返回。<b>调用本接口时，请确保 PlayerId 是已存在的，否则可能会出错。</b>
          example: "player_1"

    DeletePlayerResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            错误码。

            以下仅列出了接口业务逻辑相关的返回码，完整返回码请参考 [全局返回码](/cloud-player-server/return-codes)。
            <table>
            <thead>
            <tr><th>返回码</th><th>说明</th><th>处理建议</th></tr>
            </thead>
            <tbody>
            <tr><td>0</td><td>成功。</td><td>-</td></tr>
            <tr><td>100000004</td><td>签名过期。</td><td>请重新生成签名。</td></tr>
            <tr><td>100000005</td><td>签名错误。</td><td>请确认生成签名的参数是否正确。</td></tr>
            <tr><td>350006001</td><td>接口请求频率超过上限。</td><td>请确认对应接口的 QPS 限制，降低请求频率。</td></tr>
            <tr><td>350006002</td><td>网关校验失败。</td><td>请联系 ZEGO 技术支持处理。</td></tr>
            <tr><td>350006003</td><td>无效的输入参数。</td><td>请根据 Message 提示，调整对应参数的取值。</td></tr>
            <tr><td>350006006</td><td>服务未开通。</td><td>请联系 ZEGO 技术支持，开通服务权限。</td></tr>
            <tr><td>350006009</td><td>云端播放器正在创建中。</td><td>请稍后重试本次操作。</td></tr>
            <tr><td>350010000</td><td>系统错误。</td><td>请联系 ZEGO 技术支持处理。</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: 错误描述。
          example: "succeed"
        RequestId:
          type: string
          description: 请求 ID。
          example: "abcd123"
      example:
        Code: 0
        Message: "succeed"
        RequestId: "abcd123"

