openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - messaging

paths:
  /:
    post:
      tags: [messaging]
      summary: 删除指定单聊用户全部消息
      description: |
        调用此接口，您可以在服务端删除单聊会话中某一用户的全部消息。

        <Note title="说明">示例：用户 A 与 B 对话，若需要删除用户 A 的全部单聊消息，则 FromUserId 为 A，ToUserId 为 B；若需要删除用户 B 的全部单聊消息，则 FromUserId 为 B，ToUserId 为 A。</Note>

        <Note title="说明">调用频率限制：20 次/秒。</Note>
        
      operationId: delete-all-messages-from-a-one-to-one-conversaiton-user
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=ClearPeerMessage
          required: true
          schema:
            type: string
            enum: [ClearPeerMessage]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClearPeerMessageRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'

components:
  schemas:
    ClearPeerMessageRequest:
      type: object
      required: [FromUserId, ToUserId]
      properties:
        FromUserId:
          type: string
          description: |
            删除此用户向 ToUserId 发送过的所有单聊消息。
          maxLength: 32
          example: "user_a"
        ToUserId:
          type: string
          description: 消息接收用户。
          maxLength: 32
          example: "user_b"
    CommonResponse:
      type: object
      properties:
        Code:
          type: number
          description: 返回码。<br/>返回码请参考 [全局返回码](/zim-server/return-codes)。
          example: 0
        Message:
          type: string
          description: 操作结果描述。
          example: "success"
        RequestId:
          type: string
          description: 请求 ID。
          example: "343649807833778782"
      example:
        Code: 0
        Message: "success"
        RequestId: "343649807833778782"
