openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - messaging

paths:
  /:
    post:
      tags: [messaging]
      summary: 导入群聊消息
      description: |
        如果您正使用其他即时通讯服务并希望接入 ZIM，可调用此接口，向 ZIM 导入群组的历史消息（按时间顺序）。

        <Note title="说明">
        参数 FromUserId、GroupId 仅支持数字、英文字符和 \'!'，'#'，'$'，'%'，'&'，'('，')'，'+'，'-'，':'，';'，'\<'，'='，'.'，'\>'，'?'，'@'，'['，']'，'^'，'_'，' '，'\{'，'\}'，'|'，'~'。
        
        为了给开发者带来更好的体验，ZEGO 推荐开发者使用最新版本的 SDK。
        
        如果发送方请求发送 MessageType 为 1 的文本消息，则发送方对应的客户端（SDK 版本需为 2.7.0 或以上）也会收到该消息。
        
        对于发送和接收 MessageType 为 200 的自定义消息，发送方和接收放对应的客户端的 SDK 版本需为 2.8.0 或以上。
        
        如果接收端的 SDK 版本介乎 [2.0.0, 2.8.0) 区间，可以收到自定义消息时，但会显示此消息类型为未知，且无法获取信息内容。如需获取此条消息，请将 SDK 升级为 2.8.0 或以上版本。
        
        如果接收端的 SDK 版本为 1.x.x 版本，则无法收到自定义消息，也不会收到未知消息。
        </Note>
        <Note title="说明">调用频率限制：20 次/秒。</Note>

        ## 验证效果
        成功导入消息后，可调用 ZIM 服务端接口 [查询群聊会话消息列表](/zim-server/conversation/query-the-message-list-of-group-chats)，确认群聊会话消息是否导入完整。
      operationId: import-group-messages
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=ImportGroupMsg
          required: true
          schema:
            type: string
            enum: [ImportGroupMsg]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImportGroupMessageRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportGroupMessageResponse'

components:
  schemas:
    ImportGroupMessageRequest:
      type: object
      required: [FromUserId, GroupId, MessageType, Priority, MessageBody]
      properties:
        FromUserId:
          type: string
          description: 消息发送者的用户 ID（已在客户端调用 login 方法登录 ZIM 服务，或已调用 [服务端 API](/zim-server/user/batch-register-users) 完成注册）。
          maxLength: 32
          example: "u1"
        GroupId:
          type: string
          description: 群组 ID。
          maxLength: 32
          example: "r1"
        MessageType:
          type: number
          description: |
            消息类型，群聊会话的适用类型请参考 [MessageBody 说明](/zim-server/messaging/messagebody-introduction)。
            > 注意
            >
            > 不支持信令消息。
          example: 1
        Priority:
          type: number
          description: |
            消息优先级（详情请参考 [基本概念介绍 - 消息优先级](https://doc-zh.zego.im/zim-android/introduction/basic-concepts#消息优先级)），取值如下：
            - 1：低。
            - 2：中。
            - 3：高。
          enum: [1, 2, 3]
          example: 1
        MessageBody:
          type: object
          description: |
            消息内容，具体参数格式请参考 [MessageBody 说明](/zim-server/messaging/messagebody-introduction)。
            > 注意
            >
            > 不支持 `OfflinePush` 和 `HasReceipt` 字段。
          example:
            Message: "hello world"
            ExtendedData: "d"
        SubMsgType:
          type: number
          description: 具体的自定义类型。值由您定义，取值范围为 [0,200]。当 MessageType 为自定义消息时，必填。
          example: 200
        SearchedContent:
          type: string
          description: 自定义消息的检索字段。当 MessageType 为自定义消息时，才可填写此字段，长度上限默认为 64 字节。此字段作用于客户端，除非填写了此字段，否则无法通过客户端搜索到关联的自定义消息。
          example: "ex"
        SendMessageTime:
          type: number
          description: |
            消息发送时间戳（Unix，毫秒级别）。请按照发送时间从前到后的顺序进行导入。
            - 传 0 或不传：取"当前时间"。
            - 其他值：最早可取"当前时间 - 套餐包规定的历史消息保存天数（详情请参考 [计费说明 - 版本差异](/zim-android/introduction/pricing#版本差异)）* 86400000"，最晚不得晚于"当前时间"。

            不能早于套餐包规定的历史消息保存天数（详情请参考 [计费说明 - 版本差异](/zim-android/introduction/pricing#版本差异)），也不能晚于当前时间。
          example: 123
    ImportGroupMessageResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            返回码。

            以下仅列出了接口业务逻辑相关的返回码，完整返回码请参考 [全局返回码](/zim-server/return-codes)。
            <table>
            <tbody><tr>
            <th>返回码</th>
            <th>说明</th>
            <th>处理建议</th>
            </tr>
            <tr>
            <td>660400001</td>
            <td>输入的消息大小超出限制。</td>
            <td>请检查输入的消息大小。</td>
            </tr>
            <tr>
            <td>660500002</td>
            <td>消息发送者未登录过 SDK。</td>
            <td>请用户先登录后再发送消息。</td>
            </tr>
            <tr>
            <td>660600001</td>
            <td>输入的 GroupId 不存在。</td>
            <td>请确认输入的 GroupId 是否正确。</td>
            </tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: 请求结果的说明信息。
          example: "success"
        RequestId:
          type: string
          description: 请求 ID。
          example: "343649807833778782"
        MsgSeq:
          type: number
          description: 消息 seq。
          example: 123
      example:
        Code: 0
        Message: "success"
        RequestId: "343649807833778782"
        MsgSeq: 123
