openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - messaging

paths:
  /:
    post:
      tags: [messaging]
      summary: 撤回群聊消息
      description: |
        调用此接口，您可以撤回 2 分钟内的群聊会话消息。如需撤回更早之前的消息，请联系 ZEGO 技术支持，最多可撤回 24 小时内发出的消息。

        消息撤回后，消息接收用户将通过以下 ZIM SDK 的回调接口，接收消息已被撤回的通知。

        | iOS | Android | macOS-25% | Windows-25% |
        |-----|---------|-------|---------|
        | [messageRevokeReceived](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-message-revoke-received) | [onMessageRevokeReceived](https://doc-zh.zego.im/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-message-revoke-received) | [messageRevokeReceived](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-message-revoke-received) | [onMessageRevokeReceived](https://doc-zh.zego.im/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-message-revoke-received) |

        | Web | 小程序 | Flutter-25% | React Native-25% |
        |---------|-----|--------|--------------|
        | [messageRevokeReceived](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#message-revoke-received) | [messageRevokeReceived](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#message-revoke-received) | [onMessageRevokeReceived](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onMessageRevokeReceived.html) | [messageRevokeReceived](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#message-revoke-received) |

        | Unity3D-25% | uni-app \| uni-app x-25% | HarmonyOS-25% |
        |---------|---------|---------|
        | [OnMessageRevokeReceived](https://doc-zh.zego.im/article/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-message-revoke-received) | [messageRevokeReceived](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#message-revoke-received) | [messageRevokeReceived](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#message-revoke-received) |

        <Note title="说明">调用频率限制：20 次/秒。</Note>
        
      operationId: recall-a-group-message
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=RevokeGroupMessage
          required: true
          schema:
            type: string
            enum: [RevokeGroupMessage]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RevokeGroupMessageRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'

components:
  schemas:
    RevokeGroupMessageRequest:
      type: object
      required: [FromUserId, GroupId, MsgSeq]
      properties:
        FromUserId:
          type: string
          description: 消息发送者用户 ID（已在客户端调用 login 方法登录 ZIM 服务，或已调用 [服务端 API](/zim-server/user/batch-register-users) 完成注册）。
          maxLength: 32
          example: "u1"
        GroupId:
          type: string
          description: 群组 ID。
          maxLength: 32
          example: "group1"
        MsgSeq:
          type: number
          description: |
            消息 seq。获取方式：
            - 若需要撤回由**客户端**发出的群聊消息，通过 [消息发送后回调](/zim-server/callbacks/message-sent) 获取 MsgSeq。
            - 若需要撤回由 服务端 API [SendGroupMessage](/zim-server/messaging/send-group-messages) 发出的群聊消息，通过接口响应数据获取 MsgSeq。
          example: 10
        Payload:
          type: string
          description: 撤回附加信息，最大 200 字节。
          maxLength: 200
          example: "payload"
        OfflinePush:
          type: object
          description: 离线推送配置。如配置开启则在设备切换至后台时以离线推送形式通知消息被撤回，详情请参考 [OfflinePush 说明](/zim-server/messaging/messagebody-introduction)。
          example:
            Enable: 1
            Title: "title"
            Content: "content"
            Payload: "payload"
    CommonResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            返回码。

            以下仅列出了接口业务逻辑相关的返回码，完整返回码请参考 [全局返回码](/zim-server/return-codes)。
            <table>
            <tbody><tr>
            <th>返回码</th>
            <th>说明</th>
            <th>处理建议</th>
            </tr>
            <tr>
            <td>660000002</td>
            <td>参数错误。</td>
            <td>请参考 Request 输入正确参数。</td>
            </tr>
            <tr>
            <td>660000022</td>
            <td>未找到消息，可能是消息已经被删除或者消息不存在。</td>
            <td>请检查消息是否被删除，以及 MsgSeq 是否正确。</td>
            </tr>
            <tr>
            <td>660000023</td>
            <td>消息已被撤回。</td>
            <td>请确认消息是否已被撤回。<ul><li>如经确认，消息已被撤回，则无需处理。</li><li>如经确认，消息未被撤回，请联系 ZEGO 技术支持排查问题。</li></ul></td>
            </tr>
            <tr>
            <td>660000024</td>
            <td>已超过撤回时间。</td>
            <td>如需撤回更长时间内的消息，请联系 ZEGO 技术支持进行配置。</td>
            </tr>
            <tr>
            <td>660000026</td>
            <td>待撤回消息与 FromUserId 不匹配。</td>
            <td>请检查 FromUserId 字段是否正确。</td>
            </tr>
            <tr>
            <td>660300005</td>
            <td>频率超出 AppID 级别限制。</td>
            <td>请稍后再试，或参考相关文档了解调用频率。</td>
            </tr>
            <tr>
            <td>660600001</td>
            <td>群组不存在。</td>
            <td>请确认输入的 GroupId 是否正确。</td>
            </tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: 请求结果的说明信息。
          example: "success"
        RequestId:
          type: string
          description: 请求 ID。
          example: "343649807833778782"
      example:
        Code: 0
        Message: "success"
        RequestId: "343649807833778782"
