openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - messaging

paths:
  /:
    post:
      tags: [messaging]
      summary: 发送房间消息
      description: |
        发送房间消息，推送给房间内的所有在线用户。

        客户端将通过 ZIM SDK 的回调接口，接收房间内的消息通知。

        import MessageModerationNote from '/core_products/zim/zh/snippets/MessageModerationNote.mdx'

        <MessageModerationNote />

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|-------|---------|
        | [roomMessageReceived](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-room-message-received-info-from-room-id) | [onRoomMessageReceived](https://doc-zh.zego.im/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-room-message-received) | [roomMessageReceived](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-room-message-received-info-from-room-id) | [onRoomMessageReceived](https://doc-zh.zego.im/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-room-message-received) |

        | Web-25% | 小程序-25% | Flutter-25% | React Native-25% |
        |---------|---------|---------|---------|
        | [roomMessageReceived](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#room-message-received) | [roomMessageReceived](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#room-message-received) | [onRoomMessageReceived](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onRoomMessageReceived.html) | [roomMessageReceived](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#room-message-received) |

        | Unity3D-25% | uni-app \| uni-app x-25% | HarmonyOS-25% |
        |---------|---------|---------|
        | [onReceiveRoomMessage](https://doc-zh.zego.im/article/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-receive-room-message) | [roomMessageReceived](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#room-message-received) | [roomMessageReceived](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#room-message-received) |

        <Note title="说明">调用频率限制：10 次/秒，如需调整，请联系 ZEGO 商务人员了解具体计费规则。</Note>
      operationId: send-room-messages
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=SendRoomMessage
          required: true
          schema:
            type: string
            enum: [SendRoomMessage]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendRoomMessageRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendRoomMessageResponse'

components:
  schemas:
    SendRoomMessageRequest:
      type: object
      required: [FromUserId, RoomId, MessageType, Priority, MessageBody]
      properties:
        FromUserId:
          type: string
          description: 发送方用户 ID。
          maxLength: 32
          example: "sender_user"
        RoomId:
          type: string
          description: 房间 ID。
          maxLength: 32
          example: "room123"
        MessageType:
          type: integer
          format: int32
          description: 消息类型。
          example: 1
        Priority:
          type: integer
          format: int32
          description: 消息优先级：1 低；2 中；3 高。
          enum: [1, 2, 3]
          example: 2
        MessageBody:
          type: object
          additionalProperties: true
        SubMsgType:
          type: integer
          description: 当 MessageType 为自定义消息时填写，范围 [0,200]。
        SearchedContent:
          type: string
          description: 自定义消息检索字段，最大 64 字节。
        SenderUnaware:
          type: integer
          description: 0 可以感知；1 无感知（默认）。
    SendRoomMessageResponse:
      type: object
      properties:
        Code:
          type: integer
        Message:
          type: string
        RequestId:
          type: string
        AuditInfos:
          type: array
          items:
            type: object
            properties:
              Index:
                type: integer
                description: 组合消息为 item 下标；其他类型恒为 0；若发送前回调拒绝则恒为 0。
              Reason:
                type: string
