openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: scene

servers:
  - url: https://metaworld-api.zego.im

paths:
  /:
    get:
      tags: [scene]
      summary: SetSceneTemplate
      description: |
        > This feature has been discontinued

        Express supports custom scene template configuration for logging into scenes with corresponding configurations.
        When the system's pre-configured templates cannot meet your business needs, you can create custom templates and set related parameters through this server API.

        <Warning title="Note">
        The limit for custom templates is 50, if you need more templates, please contact ZEGOCLOUD Technical Support.
        </Warning>
        <Note title="Call frequency limit">All rooms under the same AppID are limited to 50 times/second</Note>

        <Note title="Description">
        In the test environment (see the IsTest common parameter description), the stream ID needs to be prefixed with "zegotest-AppId-". For example, if the stream ID is "test" and the AppId is "123456789" in the test environment, the stream ID should be "zegotest-123456789-test".
        </Note>
        ```
        -------------------------------------------(RightUpX, RightUpZ)
        |	                                                            |
        |	                                                            |
        |	                                                            |
        |	                                                            |
        (LeftBottomX, LeftBottomZ)-------------------------------------

        ```
        <Warning title="Note">
        After the template configuration is changed, scenes using this template will not take effect immediately. You need to wait for the scene to be destroyed (the scene will be automatically destroyed after all users exit for 10 minutes) and recreate it to take effect.
        </Warning>
      operationId: set-scene-template
      parameters:
        - name: Action
          in: query
          description: |
            > Interface prototype parameters
            >
            > https://metaworld-api.zego.im/?Action=SetSceneTemplate
          required: true
          schema: { type: string, enum: [SetSceneTemplate] }
        # 公共参数
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        # 业务参数（按 mdx）
        - name: AppId
          in: query
          required: true
          schema: { type: number }
          description: App AppID.
        - name: TemplateId
          in: query
          required: true
          schema: { type: number }
          description: Template ID.
        - name: LeftBottomX
          in: query
          required: false
          schema: { type: number, format: float }
          description: Lower-left corner X coordinate of the map (see the figure above).
        - name: LeftBottomZ
          in: query
          required: false
          schema: { type: number, format: float }
          description: Lower-left corner Z coordinate of the map (see the figure above).
        - name: RightUpX
          in: query
          required: false
          schema: { type: number, format: float }
          description: Upper-right corner X coordinate of the map (see the figure above).
        - name: RightUpZ
          in: query
          required: false
          schema: { type: number, format: float }
          description: Upper-right corner Z coordinate of the map (see the figure above).
        - name: MaxUserNum
          in: query
          required: true
          schema: { type: integer, format: int32 }
          description: Maximum number of users in the scene.
        - name: ViewRadius
          in: query
          required: true
          schema: { type: integer, format: int32 }
          description: AOI radius (user view radius).
        - name: MaxVisibleNum
          in: query
          required: true
          schema: { type: integer, format: int32 }
          description: |
            AOI user limit

            The upper limit of the number of remote users visible in the local user's AOI range, with a maximum limit of 100 users.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetSceneTemplateResponse'

components:
  schemas:
    SetSceneTemplateResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: |
            Error codes.
            Only the return codes related to interface business logic are listed here. For the complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).
            <table>
              <thead>
                <tr><th>Return Code</th><th>Description</th><th>Solution</th></tr>
              </thead>
              <tbody>
                <tr><td>340004003</td><td>Template already exists.</td><td>Set another template ID.</td></tr>
                <tr><td>340006003</td><td>Parameter error.</td><td>Set the correct request parameters according to the error prompt.</td></tr>
              </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Error message description
          example: "succeed"
        RequestId:
          type: string
          description: Request ID
          example: "9f674801-69e9-463f-a966-1ba2c6b5dbbe"
        Data:
          type: object
          nullable: true
          description: Return data content
          example: null

