openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - call-invitation
      summary: Reject a call invitation
      description: |
        This API allows a user to reject a call invitation.

        After the user rejects the invitation, other users in the call will receive a notification of the call user status change through the following ZIM SDK callback:

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|--------|---------|
        | [callUserStateChanged](https://www.zegocloud.com/docs/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-call-user-state-changed-call-id) | [onCallUserStateChanged](https://www.zegocloud.com/docs/api?doc=zim_API~java_android~class~ZIMEventHandler#on-call-user-state-changed) | [callUserStateChanged](https://www.zegocloud.com/docs/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-call-user-state-changed-call-id) | [onCallUserStateChanged](https://www.zegocloud.com/docs/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-call-user-state-changed) |

        | Web-25% | Mini Program-25% | Flutter-25% | React Native-25% |
        |-----|---------|---------|--------------|
        | [callUserStateChanged](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#call-user-state-changed) | [callUserStateChanged](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#call-user-state-changed) | [onCallUserStateChanged](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onCallUserStateChanged.html) | [callUserStateChanged](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#call-user-state-changed) |

        | Unity3D-25% | uniapp \| uniapp x-25% | HarmonyOS-25% |
        |---------|---------|------------|
        | [OnCallUserStateChanged](https://www.zegocloud.com/docs/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-call-user-state-changed) | [callUserStateChanged](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#call-user-state-changed) | [callUserStateChanged](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#call-user-state-changed) |

        <Note title="Note">The parameter FromUserId only supports numbers, English characters, and \{'!', '#', '$', '%', '&', '(', ')', '+', '-', ':', ';', '\<', '=', '.', '\>', '?', '@', '[', ']', '^', '_', ' ', '\{', '\}', '|', '~'\}.</Note>

        <Note title="QPS Limit"> 20 times/s</Note>
      operationId: reject-a-call-invitation
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=CallReject
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [CallReject]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - name: FromUserId
          in: query
          required: true
          description: |
            Reject the invitation for the user with this ID (who has logged in to the ZIM service by calling the `login` method on the client, or has completed registration by calling the [Server API](/zim-server/user/batch-register-users)).
          schema:
            type: string
            maxLength: 32
            example: "callee_user"
        - name: CallId
          in: query
          required: true
          description: Call ID.
          schema:
            type: string
            maxLength: 32
            example: "call123"
        - name: ExtendedData
          in: query
          required: false
          description: Extended field, with a maximum length of 2 KB.
          schema:
            type: string
            maxLength: 2048
            example: "Extended data"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallRejectResponse'

components:
  schemas:
    CallRejectResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            The following only lists the return codes related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            <table>
            <tbody><tr>
            <th>Return code</th>
            <th>Description</th>
            <th>Suggested Solution</th>
            </tr>
            <tr>
            <td>660000002</td>
            <td>Parameter error.</td>
            <td>Please check the request parameters.</td>
            </tr>
            <tr>
            <td>660300005</td>
            <td>The call frequency exceeds the AppID-level limit.</td>
            <td>Please try again later.</td>
            </tr>
            <tr>
            <td>660500002</td>
            <td>Operator user is not registered.</td>
            <td>Please register the operator user with the ZIM service first.</td>
            </tr>
            <tr>
            <td>660900004</td>
            <td>Failed to get call information.</td>
            <td>Please check if the call exists, or try again later.</td>
            </tr>
            <tr>
            <td>660900005</td>
            <td>The call has ended and cannot be operated on.</td>
            <td>No action required.</td>
            </tr>
            <tr>
            <td>660900006</td>
            <td>The call invitation has timed out and cannot be operated on.</td>
            <td>No action required.</td>
            </tr>
            <tr>
            <td>660900008</td>
            <td>The call did not invite the operator user and cannot be operated on.</td>
            <td>No action required.</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: Operation result description.
          example: success
        RequestId:
          type: string
          description: Request ID.
          example: '343649807833778782'
