openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    post:
      tags:
        - call-invitation
      summary: Send a call invitation
      description: |
        This API allows you to create a call invitation in **normal mode**.

        After the call invitation is successfully created, the user who initiated the invitation (caller) will receive a notification that the invitation has been created through the following ZIM SDK callback:

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|--------|---------|
        | [callInvitationCreated](https://www.zegocloud.com/docs/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-call-invitation-created-call-id) | [onCallInvitationCreated](https://www.zegocloud.com/docs/api?doc=zim_API~java_android~class~ZIMEventHandler#on-call-invitation-created) | [callInvitationCreated](https://www.zegocloud.com/docs/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-call-invitation-created-call-id) | [onCallInvitationCreated](https://www.zegocloud.com/docs/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-call-invitation-created) |

        | Web-25% | Mini Program-25% | Flutter-25% | React Native-25% |
        |-----|--------|---------|--------------|
        | [callInvitationCreated](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#call-invitation-created) | [callInvitationCreated](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#call-invitation-created) | [onCallInvitationCreated](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onCallInvitationCreated.html) | [callInvitationCreated](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#call-invitation-created) |

        | Unity3D-25% | uniapp \| uniapp x-25% | HarmonyOS-25% |
        |--------|--|--|
        | [onCallInvitationCreated](https://www.zegocloud.com/docs/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-call-invitation-created) |[callInvitationCreated](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#call-invitation-created) | [callInvitationCreated](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#call-invitation-created) |

        The invited users (callees) will receive a notification that they have been invited:

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|--------|---------|
        | [callInvitationReceived](https://www.zegocloud.com/docs/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-call-invitation-received-call-id) | [onCallInvitationReceived](https://www.zegocloud.com/docs/api?doc=zim_API~java_android~class~ZIMEventHandler#on-call-invitation-received) | [callInvitationReceived](https://www.zegocloud.com/docs/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-call-invitation-received-call-id) | [onCallInvitationReceived](https://www.zegocloud.com/docs/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-call-invitation-received) |

        | Web-25% | Mini Program-25% | Flutter-25% | React Native-25% |
        |-----|--------|---------|--------------|
        | [callInvitationReceived](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#call-invitation-received) | [callInvitationReceived](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#call-invitation-received) | [onCallInvitationReceived](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onCallInvitationReceived.html) | [callInvitationReceived](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#call-invitation-received) |

        | Unity3D-25% | uniapp \| uniapp x-25% | HarmonyOS-25% |
        |---------|---------|------------|
        | [OnCallInvitationReceived](https://www.zegocloud.com/docs/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-call-invitation-received) | [callInvitationReceived](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#call-invitation-received) | [callInvitationReceived](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#call-invitation-received) |  |

        <Note title="Note">The users corresponding to the parameters `FromUserId` and `UserIds` have logged in to the ZIM service by calling the `login` method on the client, or the developer has registered the relevant userID by calling the [Server API](/zim-server/user/batch-register-users).</Note>

        <Note title="Note">The parameters FromUserId and UserIds only support numbers, English characters, and '!', '#', '$', '%', '&', '(', ')', '+', '-', ':', ';', '\<', '=', '.', '\>', '?', '@', '[', ']', '^', '_', ' ', '\{', '\}', '|', '~'.</Note>

        <Note title="QPS Limit"> 20 times/s</Note>
      operationId: send-a-call-invitation
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=CallInvite
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [CallInvite]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CallInviteRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallInviteResponse'

components:
  schemas:
    CallInviteRequest:
      type: object
      required: [FromUserId, UserIds, OfflinePush]
      properties:
        FromUserId:
          type: string
          description: |
            Caller user ID (who has logged in to the ZIM service by calling the `login` method on the client, or has completed registration by calling the [Server API](/zim-server/user/batch-register-users)).
          maxLength: 32
          example: "caller_user"
        UserIds:
          type: array
          description: |
            List of callee users, with a maximum of 9 users. If you need to increase the limit, please contact ZEGOCLOUD Technical Support.
          maxItems: 9
          items:
            type: string
            maxLength: 32
            example: "callee1"
          style: form
          explode: true
          example: ["callee1", "callee2"]
        Timeout:
          type: number
          description: Call timeout period in seconds, with a value range of (0, 600]. If 0 or empty, the default value is 90.
          minimum: 0
          maximum: 600
          default: 90
          example: 90
        ExtendedData:
          type: string
          description: Extended field, with a maximum length of 2 KB.
          maxLength: 2048
          example: "Extended data"
        OfflinePush:
          type: object
          description: |
            Offline push configuration. For details, please refer to [MessageBody description - OfflinePush description](https://www.zegocloud.com/docs/article/17609#offlinePush).
          properties:
            Enable:
              type: integer
              description: |
                Whether to enable offline push.
                <ul><li>1: Enabled;</li><li>0: Disabled.</li></ul>
              example: 1
            Title:
              type: string
              description: Title displayed in offline push.
              example: "title"
            Content:
              type: string
              description: Content displayed in offline push.
              example: "content"
            Payload:
              type: string
              description: Extended field, developers can customize the behavior after receiving offline push messages.
              example: "payload"

    CallInviteResponse:
      type: object
      properties:
        Code:
          type: integer
          description: |
            Return code.

            The following only lists the return codes related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            <table>
            <tbody><tr>
            <th>Return code</th>
            <th>Description</th>
            <th>Suggested Solution</th>
            </tr>
            <tr>
            <td>660000002</td>
            <td>Parameter error.</td>
            <td>Please check the request parameters.</td>
            </tr>
            <tr>
            <td>660300005</td>
            <td>The call frequency exceeds the AppID-level limit.</td>
            <td>Please try again later.</td>
            </tr>
            <tr>
            <td>660500002</td>
            <td>Operator user is not registered.</td>
            <td>Please register the operator user with the ZIM service first.</td>
            </tr>
            <tr>
            <td>660900003</td>
            <td>All callee users must be registered.</td>
            <td>Please check the registration status of the callee users or try again later.</td>
            </tr>
            <tr>
            <td>660900007</td>
            <td>The callee user list length exceeds the limit.</td>
            <td>Please shorten the callee user list length, or contact ZEGOCLOUD Technical Support to increase the limit.</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: Operation result description.
          example: success
        RequestId:
          type: string
          description: Request ID.
          example: '343649807833778782'
        CallId:
           type: string
           description: Call ID.
           example: "12261423186766631832"
        CreateTime:
          type: number
          description: Call invitation creation timestamp.
          example: 1713249504000
        ErrorUsers:
          type: array
          description: |
            Information of users who failed to receive the invitation.

            When Code is 0:
            <ul>
              <li>If ErrorUsers is empty, the invitation was successfully sent to all specified users.</li>
              <li>If ErrorUsers is not empty, it means the invitation failed to be sent to some specified users. Please refer to SubCode for handling.</li>
            </ul>
            When Code is not 0:
            <ul>
              <li>If ErrorUsers is empty, it indicates parameter error, API frequency limit, or system error.</li>
              <li>If ErrorUsers is not empty, it means the invitation failed to be sent to all specified users.</li>
            </ul>
          items:
            type: object
            properties:
              UserId:
                type: string
                description: Failed user ID.
                example: "uid2"
              SubCode:
                type: number
                description: |
                  Specific return code for the failure.
                  The following only lists the return codes related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
                  <table>
                  <tbody><tr>
                  <th>Return code</th>
                  <th>Description</th>
                  <th>Suggested Solution</th>
                  </tr>
                  <tr>
                  <td>660000002</td>
                  <td>Parameter error.</td>
                  <td>Please check the request parameters.</td>
                  </tr>
                  <tr>
                  <td>660300005</td>
                  <td>The call frequency exceeds the AppID-level limit.</td>
                  <td>Please try again later.</td>
                  </tr>
                  <tr>
                  <td>660500002</td>
                  <td>Operator user is not registered.</td>
                  <td>Please register the operator user with the ZIM service first.</td>
                  </tr>
                  <tr>
                  <td>660900003</td>
                  <td>All callee users must be registered.</td>
                  <td>Please check the registration status of the callee users or try again later.</td>
                  </tr>
                  <tr>
                  <td>660900007</td>
                  <td>The callee user list length exceeds the limit.</td>
                  <td>Please shorten the callee user list length, or contact ZEGOCLOUD Technical Support to increase the limit.</td>
                  </tr>
                  </tbody></table>
                example: 660500002
