openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: cdn

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [cdn]
      summary: DeleteMedia
      description:
        用户进行 CDN 录制时，会把录制好的媒体文件存放在 CDN 服务器上，用户可以调用本接口删除该文件。

        <Warning title="注意">
        首次使用本接口之前，请确认是否已经开通 CDN 录制服务。若未开通，请前往 [ZEGO 控制台](https://console.zego.im) 自助开通，详情请参考 [控制台 - 服务配置 - CDN](/console/service-configuration/activate-cdn-service)，或联系 ZEGO 技术支持开通。
        </Warning>
        <Note title="调用频率限制">同一个 AppID 下所有房间：20 次/秒</Note>
      operationId: delete-media
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=DeleteMedia
          required: true
          schema: { type: string, enum: [DeleteMedia] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - name: Vendor
          in: query
          required: true
          schema: { type: string, enum: [Tencent, Ws, Huawei] }
          description: |
            <p>可能的取值及对应的 CDN 厂商：</p>
            Tencent：腾讯云。
            Ws：网宿。
            Huawei：华为云。
        - name: FileId
          in: query
          required: true
          description:
            <p>文件唯一标识，在 <a href="/real-time-video-server/callback/cdn/cdn-record-completed" target="blank">录制文件生成回调</a> 中返回，最大支持 100 个媒体文件 FileId。</p><p>请注意，各 CDN 厂商的录制文件唯一标识不同：</p><ul><li>腾讯云：FileID。</li><li>网宿：PersistentId。</li><li>华为云：ObsObject。</li></ul><p>您也可以通过 <a href="/real-time-video-server/api-reference/cdn/search-media" target="blank">检索媒体信息</a> 接口，获取媒体文件的唯一标识，标识对应的参数名称有所差异，请注意区分使用。</p><p>示例：&FileId[]=5285890813221514958&FileId[]=5285890813221513290</p>
          schema:
            type: array
            items: { type: string }
            minItems: 1
            maxItems: 100
          style: form
          explode: true
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteMediaResponse'

components:
  schemas:
    DeleteMediaResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: |
              返回码。
              <br/>
              以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。
              <table>
                <thead>
                  <tr><th>返回码</th><th>说明</th><th>处理建议</th></tr>
                </thead>
                <tbody>
                  <tr><td>0</td><td>请求成功。</td><td>-</td></tr>
                  <tr><td>2</td><td>输入参数错误。</td><td>-</td></tr>
                  <tr><td>3</td><td>未开通相关权限。</td><td>请联系 ZEGO 技术支持。</td></tr>
                  <tr><td>4</td><td>CDN 类型不匹配。</td><td>请检查参数。</td></tr>
                  <tr><td>5</td><td>配置错误。</td><td>请联系 ZEGO 技术支持。</td></tr>
                  <tr><td>6</td><td>请求过于频繁。</td><td>请稍后重试。</td></tr>
                  <tr><td>7</td><td>鉴权失败。</td><td>请检查鉴权参数是否正确。</td></tr>
                  <tr><td>1000</td><td>请求失败。</td><td>请联系 ZEGO 技术支持。</td></tr>
                </tbody>
              </table>
          example: 0
        Message:
          type: string
          description: 操作结果描述。
          example: "success"
        RequestId:
          type: string
          description: 请求 ID，由 ZEGO 服务端返回。
          example: "3574501647605445341"
        Data:
          type: object
          description: 响应数据，由以下参数 JSON 序列化后生成。
          properties:
            Deleted:
              type: array
              description: 成功删除的文件列表。
              items:
                type: string
              example: ["3270835010809755971","3270835010811335406"]
            Errors:
              type: array
              description: 未成功删除的文件列表。
              items:
                type: object
                properties:
                  Code: { type: string, description: 删除文件失败的错误码。 }
                  Message: { type: string, description: 删除文件失败的错误消息。 }
                  Key: { type: string, description: 删除失败的文件的唯一标识。 }
                  RequestId: { type: string, description: 唯一请求 ID，由请求参数 Vendor 取值对应的 CDN 厂商返回，定位问题时需要提供该次请求的 RequestId。 }
              example: []

