openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0

servers:
  - url: https://cloud-realtime-asr-api.zegotech.cn

paths:
  /:
    post:
      tags:
        - cloud-realtime-asr
      summary: AddASRStream
      description: 将指定的流添加到语音识别任务中。仅在 RecognitionRange 参数为 1 时有效。
      operationId: add-stream
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://cloud-realtime-asr-api.zegotech.cn?Action=AddASRStream
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [AddASRStream]
          style: form
          explode: true
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddASRStreamRequest"
            example:
              TaskId: "1920370518175780864"
              StreamInfo:
                StreamId: "stremId1"
                ASR:
                  Vendor: "AliyunParaformer"
                EnableTranslation: true
                Translation:
                  Vendor: "DoubaoSeedTranslation"
                  SourceLanguage: "zh"
                  TargetLanguage: "en"
                  LLM:
                    Url: "https://api.minimax.chat/v2/text/chatcompletion_v2"
                    ApiKey: "your_api_key"
                    Model: "abab6.5s-chat"
                    Params: {}
      responses:
        "200":
          description: 添加识别流成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddASRStreamResponse"
              example:
                Code: 0
                Message: "success"
                RequestId: "6710396424239903698"

components:
  schemas:
    AddASRStreamRequest:
      type: object
      required:
        - TaskId
        - StreamInfo
      properties:
        TaskId:
          type: string
          description: 任务的唯一标识。
          example: "1920370518175780864"
        StreamInfo:
          $ref: "./shared-components.yaml#/components/schemas/StreamListItem"
          description: 需要识别的流。
        Sequence:
          type: integer
          format: int64
          description: |
            请求序列号，用于保证对同一条流的添加、删除时序。后台只处理 Sequence 最新的请求，如果不设置，以后台接收到请求的顺序处理。
            > 📌 **重要说明**
            > AddASRStream 和 DeleteASRStream 接口的 Sequence 必须有序。比如：
            > 1. AddASRStream(Sequence:1)
            > 2. DeleteASRStream(Sequence:2)
            > 3. AddASRStream(Sequence:3)
            > 4. DeleteASRStream(Sequence:4)
            > 5. ...

    AddASRStreamResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 返回码，0 表示成功，其他值表示失败。详情请参考 [返回码](/cloud-realtime-asr/api-reference/return-codes) 说明。
          example: 0
        Message:
          type: string
          description: 请求结果说明
          example: "success"
        RequestId:
          type: string
          description: 请求 ID
          example: "6710396424239903698"
