openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0

servers:
  - url: https://cloud-realtime-asr-api.zegotech.cn

paths:
  /:
    post:
      tags:
        - cloud-realtime-asr
      summary: 开启云端实时语音识别
      description: 开启云端实时语音识别任务，并把语音识别实例加入 RTC 对话中。
      operationId: start
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://cloud-realtime-asr-api.zegotech.cn?Action=StartRealtimeASRTask
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [StartRealtimeASRTask]
          style: form
          explode: true
        # 引用共享的参数
        - $ref: '../../../../../snippets/common/zh/openapi/zego-shared-components.yaml#/components/parameters/AppId'
        - name: SignatureNonce
          in: query
          description: 💡公共参数。16 位 16 进制随机字符串（8 字节随机数的 hex 编码）。生成算法可参考 <a href="/cloud-realtime-asr/api-reference/accessing-server-apis#signature-example">签名示例</a>。
          required: true
          schema:
            type: string
        - name: Timestamp
          in: query
          description: 💡公共参数。当前 Unix 时间戳，单位为秒。生成算法可参考 <a href="/cloud-realtime-asr/api-reference/accessing-server-apis#signature-example">签名示例</a>，最多允许 10 分钟的误差。
          required: true
          schema:
            type: integer
            format: int64
        - name: SignatureVersion
          $ref: "../../../../../snippets/common/zh/openapi/zego-shared-components.yaml#/components/parameters/SignatureVersion"
        - name: Signature
          in: query
          description: 💡公共参数。签名，用于验证请求的合法性。请参考[签名机制](/cloud-realtime-asr/api-reference/accessing-server-apis#signature-mechanism)生成。
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StartASRTaskRequest"
      responses:
        "200":
          description: 开始任务成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StartASRTaskResponse"

components:
  schemas:
    StartASRTaskRequest:
      type: object
      required:
        - RoomId
      properties:
        RoomId:
          type: string
          description: RTC 房间 Id
        ASR:
          type: object
          description: ASR 参数
          properties:
            HotWord:
              type: string
              description: |
                热词表，用于提升识别准确率。
                单个热词限制："热词|权重"，单个热词不超过30个字符（最多10个汉字）。
                多个热词用英文逗号分割，最多支持128个热词。
            Params:
              type: object
              description: 额外参数
              properties:
                engine_model_type:
                  type: string
                  default: 16k_zh
                  enum:
                    - 16k_zh
                    - 16k_en
                    - 16k_ar
                  description: |
                    引擎模型类型。
                    16k_zh：中文通用；
                    16k_en：英文通用；
                    16k_ar：阿拉伯语；
            VADSilenceSegmentation:
              type: integer
              format: Int
              minimum: 200
              maximum: 2000
              default: 500
              description: 用于设置用户说话停顿多少秒后，不再将两句话视为一句。单位为 ms。

    StartASRTaskResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 返回码，0 表示成功，其他值表示失败。详情请参考 [返回码](/cloud-realtime-asr/api-reference/return-codes) 说明。
          example: 0
        Message:
          type: string
          description: 请求结果说明
          example: "Success"
        RequestId:
          type: string
          description: 请求 ID
          example: "3151527792559699732"
        Data:
          type: object
          properties:
            TaskId:
              type: string
              description: 任务的唯一标识。
              example: "1920370518175780864"
