openapi: 3.0.0
info:
  title: open-api-desc

  version: 1.0.0

servers:
  - url: https://cloud-realtime-asr-api.zegotech.cn

paths:
  /:
    post:
      tags:
        - cloud-realtime-asr
      summary: 停止云端实时语音识别
      description: 停止ASR任务。当该接口未被主动及时调用，服务会检测房间里是否处于无人状态，如处于无人状态超过 150s 则自动结束任务，并通知调用方。
      operationId: stop
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://cloud-realtime-asr-api.zegotech.cn?Action=StopRealtimeASRTask
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [StopRealtimeASRTask]
          style: form
          explode: true
        # 引用共享的参数
        - $ref: '../../../../../snippets/common/zh/openapi/zego-shared-components.yaml#/components/parameters/AppId'
        - $ref: '../../../../../snippets/common/zh/openapi/zego-shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../../../../../snippets/common/zh/openapi/zego-shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../../../../../snippets/common/zh/openapi/zego-shared-components.yaml#/components/parameters/Signature'
        - $ref: '../../../../../snippets/common/zh/openapi/zego-shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StopASRTaskRequest"
      responses:
        "200":
          description: 停止任务成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StopASRTaskResponse"

components:
  schemas:
    StopASRTaskRequest:
      type: object
      required:
        - TaskId
      properties:
        TaskId:
          type: string
          description: 任务的唯一标识。
          example: "1920370518175780864"

    StopASRTaskResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 返回码，0 表示成功，其他值表示失败。详情请参考 [返回码](/cloud-realtime-asr/api-reference/return-codes) 说明。
          example: 0
        Message:
          type: string
          description: 请求结果说明
          example: "Success"
        RequestId:
          type: string
          description: 请求 ID
          example: "3151527792559699732"
