openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0

servers:
  - url: https://cloud-realtime-asr-api.zegotech.cn

paths:
  /:
    post:
      tags:
        - cloud-realtime-asr
      summary: UpdateRealtimeASRTask
      description: 更新 ASR 任务。
      operationId: update
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://cloud-realtime-asr-api.zegotech.cn?Action=UpdateRealtimeASRTask
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [UpdateRealtimeASRTask]
          style: form
          explode: true
        # 引用共享的参数
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateASRTaskRequest"
            example:
              TaskId: "1920370518175780864"
              StreamList:
                - StreamId: "stremId4"
                - StreamId: "stremId5"
                - StreamId: "stremId6"
      responses:
        "200":
          description: 更新任务成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateASRTaskResponse"
              example:
                Code: 0
                Message: "success"
                RequestId: "6710396424239903698"

components:
  schemas:
    UpdateASRTaskRequest:
      type: object
      required:
        - TaskId
      properties:
        TaskId:
          type: string
          description: 任务的唯一标识。
          example: "1920370518175780864"
        StreamList:
          type: array
          description: 需要识别的流列表，不填默认识别所有流。会覆盖掉之前的识别流列表。
          items:
            $ref: "./shared-components.yaml#/components/schemas/StreamListItem"
          example:
            - StreamId: "stremId1"
              ASR:
                Vendor: "AliyunParaformer"
            - StreamId: "stremId2"
              ASR:
                VADSilenceSegmentation: 500
            - StreamId: "stremId3"

    UpdateASRTaskResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 返回码，0 表示成功，其他值表示失败。详情请参考 [返回码](/cloud-realtime-asr/api-reference/return-codes) 说明。
          example: 0
        Message:
          type: string
          description: 请求结果说明
          example: "success"
        RequestId:
          type: string
          description: 请求 ID
          example: "6710396424239903698"

