openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: './shared-components.yaml#/servers'

paths:
  /:
    post:
      tags:
        - cloud-recording
        - POST
      summary: UpdateLayout
      description: |
        During the recording process, you can call this API at any time to change the stream mixing layout settings.

        <Note title="Note">Call frequency limit: 10 times/second</Note>
      operationId: update-layout
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://cloudrecord-api.zego.im?Action=UpdateLayout
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [UpdateLayout]
          style: form
          explode: true
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateLayoutRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateLayoutResponse'

components:
  schemas:
    UpdateLayoutRequest:
      type: object
      required: [TaskId]
      properties:
        TaskId:
          type: string
          description: Recording task ID, a fixed-length string of 16 bytes.
          example: "xxxx"
        MixMode:
          type: integer
          description: |
            Layout mode.

            - 1: Custom layout, MixInputList must be specified
            - 2: Equal division layout (default)
            - 3: Horizontal layout
            - 4: Vertical layout
            - 5: Floating layout
          enum: [1, 2, 3, 4, 5]
          default: 2
        MixInputList:
          type: array
          description: |
            Custom layout parameters.
          items:
            $ref: '#/components/schemas/MixInputListItem'
        MixMaxResolutionStreamId:
          type: string
          description: |
            When `MixMode` is set to 3, 4, or 5, used to specify the stream ID to display in the large view.
          example: "stream_1"
      example:
        TaskId: "xxxx"
        MixMode: 1
        MixInputList:
          - StreamId: "xxxx"
            ViewType: 1
            Top: 0
            Left: 0
            Bottom: 720
            Right: 540
            Layer: 1
          - StreamId: ""
            ViewType: 1
            Top: 0
            Left: 540
            Bottom: 360
            Right: 1080
            Layer: 1
          - StreamId: ""
            ViewType: 1
            Top: 360
            Left: 540
            Bottom: 720
            Right: 1080
            Layer: 1

    MixInputListItem:
      type: object
      required: [Top, Left, Bottom, Right, Layer]
      properties:
        StreamId:
          type: string
          description: |
            Specifies the streamID to be displayed in this view. If not specified, streams will be matched in the order they join the room.
          example: "xxxx"
        ViewType:
          type: integer
          description: |
            The type of content displayed in this view.

            - 1: Audio and video (default)
            - 2: Whiteboard

            Type 2 is only valid when whiteboard recording is enabled. Only one view can be set as whiteboard; setting two or more will return an error.
          enum: [1, 2]
          default: 1
        Top:
          type: integer
          description: |
            The y-axis coordinate of the top-left corner of this view on the canvas. Value range is [0, 1920], cannot exceed the Bottom value and the canvas height.
          minimum: 0
          maximum: 1920
          example: 0
        Left:
          type: integer
          description: |
            The x-axis coordinate of the top-left corner of this view on the canvas. Value range is [0, 1920], cannot exceed the Right value and the canvas width.
          minimum: 0
          maximum: 1920
          example: 0
        Bottom:
          type: integer
          description: |
            The y-axis coordinate of the bottom-right corner of this view on the canvas. Value range is [0, 1920], cannot exceed the canvas height.
          minimum: 0
          maximum: 1920
          example: 720
        Right:
          type: integer
          description: |
            The x-axis coordinate of the bottom-right corner of this view on the canvas. Value range is [0, 1920], cannot exceed the canvas width.
          minimum: 0
          maximum: 1920
          example: 540
        Layer:
          type: integer
          description: The layer priority of this view. When two views overlap, the one with a larger value is displayed on top.
          example: 1
        FillMode:
          type: integer
          description: |
            How to handle when the actual video stream aspect ratio is inconsistent with the view.

            - 1: Crop mode. In this mode, priority is given to ensuring the view is filled. After the original video is scaled proportionally to fill the view, content exceeding the view on all sides will be cropped. (Default)
            - 2: Scale mode. In this mode, priority is given to ensuring the integrity of the original video. After the original video is scaled proportionally to fill the view, black borders will be added on all sides.
          enum: [1, 2]
          default: 1
        BackgroundImage:
          type: string
          description: |
            The URL address of the stream view background image, only takes effect when the [StreamId] parameter is specified. This background image will be displayed when the stream specified in the custom layout does not exist or the stream is interrupted.

            - It is recommended that the background image resolution matches the stream view resolution. If the two resolutions are inconsistent, the background image will be stretched or compressed to fill the entire view.
            - Background image format supports JPG and PNG, size cannot exceed 5MB. If the background image download fails, the setting will not take effect.
            - URL supports HTTP and HTTPS protocols.

    UpdateLayoutResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int64
          description: |
            Error code.
          example: 0
        Message:
          type: string
          description: Error description.
          example: "succeed"
        RequestId:
          type: string
          description: Request ID.
          example: "abcd123"
      example:
        Code: 0
        Message: "succeed"
        RequestId: "abcd123"

