openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - messaging

paths:
  /:
    post:
      tags: [messaging]
      summary: Push message to all users
      description: |
        Push message to all users refers to sending messages with specific content, such as text, images, etc., to all online users (including the message sender themselves) and offline users. This feature is suitable for scenarios such as announcements for all users, cross-room gift floating screens, etc.

        - Online users: Users who have logged in to ZIM and whose heartbeat has not timed out.
        - Offline users: Users whose heartbeat has timed out after logging in to ZIM and reporting ZPNsPushId.
        <Note title="Note">
        - To use this feature, please activate ZIM Professional or Flagship service.
        - Messages sent through this API will not create conversations and will not be saved.
        </Note>
        Message receiving users can only receive broadcast messages through the following ZIM SDK callback interfaces and know which user sent the message.

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|-------|---------|
        | [broadcastMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-broadcast-message-received) | [onBroadcastMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-broadcast-message-received) | [broadcastMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-broadcast-message-received) | [onBroadcastMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-broadcast-message-received) |

        | Web-25% | Mini Program-25% | Flutter-25% | React Native-25% |
        |---------|-----|--------|--------------|
        | [broadcastMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#broadcast-message-received) | [broadcastMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#broadcast-message-received) | [onBroadcastMessageReceived](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onBroadcastMessageReceived.html) | [broadcastMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#broadcast-message-received) |

        | uni-app \| uni-app x-25% | HarmonyOS-25% |
        |---------|-----------|
        | [broadcastMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#broadcast-message-received) | [broadcastMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#broadcast-message-received) | |

        <Note title="Note">
          The parameter FromUserId only supports numbers, English characters, and `'!'，'#'，'$'，'%'，'&'，'('，')'，'+'，'-'，':'，';'，'<'，'='，'.'，'>'，'?'，'@'，'['，']'，'^'，'_'，' '，'{'，'}'，'|'，'~'`.

          If the sender's SDK version (for version information, please refer to [Release notes](/zim-android/client-sdks/zim-release-notes)) is lower than `2.0.0`, the ZIM server only supports Command type messages with `MessageType` of `2`, and does not support other types.<br/>To provide developers with a better experience, ZEGOCLOUD recommends that developers use the latest version of the SDK.

          The message receiver's SDK version must be 2.10.0 or above to receive broadcast messages.
        </Note>
        <Note title="QPS Limit"> 1 time/s, limited to 100 times within 24 hours. If you need to adjust, please contact ZEGOCLOUD Technical Support.</Note>
      operationId: push-message-to-all-users
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=SendMessageToAllUsers
          required: true
          schema:
            type: string
            enum: [SendMessageToAllUsers]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageToAllUsersRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendMessageToAllUsersResponse'

components:
  schemas:
    SendMessageToAllUsersRequest:
      type: object
      required: [FromUserId, MessageType, MessageBody]
      properties:
        FromUserId:
          type: string
          description: Sender's user ID (who has logged in to the ZIM service by calling the login method on the client, or has completed registration by calling the [server-side API](/zim-server/user/batch-register-users)).
          maxLength: 32
          example: "u1"
        MessageType:
          type: number
          description: Message type. For applicable types for broadcast messages, please refer to [MessageBody description](/zim-server/messaging/messagebody-introduction).
          example: 1
        MessageBody:
          type: object
          description: Message content. For specific parameter format, please refer to [MessageBody description](/zim-server/messaging/messagebody-introduction).
          example:
            Message: "hello world"
            ExtendedData: "s"
        SubMsgType:
          type: number
          description: Specific custom type. The value is defined by the developer, with a value range of [0,200]. This parameter only needs to be assigned when MessageType is a custom message.
          example: 0
        PushType:
          type: number
          description: |
            Push type:
            - 0: Online push to online users.
            - 1: Online push to online users, offline push to offline users.
            - 2: Offline push to all users who have reported ZPNsPushId.
          example: 0
    SendMessageToAllUsersResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            > **Note**
            >
            > When you initiate a request to send messages to multiple users simultaneously:
            > - If you only need to successfully send messages to 1 or more users, Code will return 0, indicating success. In this case, please refer to the specific information in ErrorList to confirm the operation result and understand whether sending messages to some users failed.
            > - If sending messages to all users fails, Code will return the relevant return code. For details, please refer to [Return codes](/zim-server/return-codes).

            The following only lists the return codes related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).

            <table>
            <tbody><tr>
            <th>Return code</th>
            <th>Description</th>
            <th>Suggested Solution</th>
            </tr>
            <tr>
            <td>660000002</td>
            <td>Input parameter error。</td>
            <td>Please check the input parameters。</td>
            </tr>
            <tr>
            <td>660400001</td>
            <td>The input message size exceeds the limit。</td>
            <td>Please check the input message size。</td>
            </tr>
            <tr>
            <td>660500002</td>
            <td>Message sender has not logged in to the SDK。</td>
            <td>Please log in to ZIM SDK before sending messages。</td>
            </tr>
            <tr>
            <td>660500003</td>
            <td>The frequency of calling the SendMessageToAllUsers API exceeds the limit。</td>
            <td>Please try again later。</td>
            </tr>
            </tbody></table>

          example: 0
        Message:
          type: string
          description: Description of the request result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
      description: Only returns the common three fields, no Data.
      example:
        Code: 0
        Message: "success"
        RequestId: "343649807833778782"
