openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - messaging

paths:
  /:
    post:
      tags: [messaging]
      summary: Query messages
      description: |
        This API supports querying multiple messages in a specific conversation (group chat, one-to-one chat).

        <Warning title="Warning">The frequency limit of this API is 20 messages/second, not 20 times/second.</Warning>

      operationId: query-messages
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=QueryMessagesByMsgSeq
          required: true
          schema:
            type: string
            enum: [QueryMessagesByMsgSeq]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryMessagesRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryMessagesResponse'

components:
  schemas:
    MsgBodyContent:
      anyOf:
        - $ref: '#/components/schemas/Multimedia message'
        - $ref: '#/components/schemas/multi-item messages'
        - $ref: '#/components/schemas/revoked message'
        - $ref: '#/components/schemas/Tips message'

    Multimedia message:
      type: object
      description: Multimedia message
      properties:
        md5:
          type: string
          description: MD5 value of the file.
        file_name:
          type: string
          description: File name.
        file_size:
          type: string
          description: File size in bytes (B).
        download_url:
          type: string
          description: Download URL.
        media_duration:
          type: string
          description: Audio/video duration in seconds (s).
        origin_image_width:
          type: integer
          description: ðŸžï¸If it is an image message, this attribute is included. Width of the original image in pixels (px).
        origin_image_height:
          type: integer
          description: ðŸžï¸If it is an image message, this attribute is included. Height of the original image in pixels (px).
        large_image_download_url:
          type: string
          description: ðŸžï¸If it is an image message, this attribute is included. Large image Download URL.
        large_image_width:
          type: integer
          description: ðŸžï¸If it is an image message, this attribute is included. Width of the large image in pixels (px).
        large_image_height:
          type: integer
          description: ðŸžï¸If it is an image message, this attribute is included. Height of the large image in pixels (px).
        thumbnail_download_url:
          type: string
          description: ðŸžï¸If it is an image message, this attribute is included. Thumbnail Download URL.
        thumbnail_width:
          type: integer
          description: ðŸžï¸If it is an image message, this attribute is included. Width of the thumbnail in pixels (px).
        thumbnail_height:
          type: integer
          description: ðŸžï¸If it is an image message, this attribute is included. Height of the thumbnail in pixels (px).
        video_first_frame_download_url:
          type: string
          description: ðŸŽ¬If it is a video message, this attribute is included. Download URL of the video first frame image.
        video_first_frame_width:
          type: integer
          description: ðŸŽ¬If it is a video message, this attribute is included. Width of the video first frame image in pixels (px).
        video_first_frame_height:
          type: integer
          description: ðŸŽ¬If it is a video message, this attribute is included. Height of the video first frame image in pixels (px).


    multi-item messages:
      type: object
      description: multi-item messages
      properties:
        multi_msg:
          type: array
          description: multi-item messages Item array.
          items:
            $ref: '#/components/schemas/MultiMsgItem'

    MultiMsgItem:
      type: object
      description: multi-item messages Item
      properties:
        msg_type:
          type: integer
          description: |
            Item type:
            - 1: Text.
            - 11: Image.
            - 12: Document.
            - 13: Audio.
            - 14: Video.
            - 200: Custom message type.
          enum: [1, 11, 12, 13, 14, 200]
        sub_msg_type:
          type: integer
          description: Only when msg_type is 200, this parameter is returned.
        callback_content:
          type: object
          description: |
            Item content.
            - Only when msg_type is 1 or 200, the message content can be read directly from this parameter.
            - When Item is 11, 12, 13, or 14, please refer to the Multimedia message structure to understand the data of each field in the message.

    revoked message:
      type: object
      description: revoked message
      properties:
        user_id:
          type: string
          description: userID of the user who initiated the revoked operation.
        revoke_time:
          type: number
          description: timestamp of the revoked operation, in milliseconds.
        msg_type:
          type: number
          description: original Message type.
        payload:
          type: string
          description: Extended field carried during the revoked operation.
        msg_status:
          type: number
          description: |
            Corresponding status of the revoked operation:
            - 4: Revoked by the user.
            - 8: Revoked by the system.
            - 12: Revoked through the server-side API.
            - 16: Revoked by the group manager.
            - 20: Revoked by the group owner.
            - 24: Revoked due to failure to pass the audit.

    Tips message:
      type: object
      description: Tips message
      properties:
        type:
          type: number
          description: |
            Tips message type:
            - Group member change:
              - 1: Group created.
              - 2: Group created.
              - 3: User joins the group.
              - 4: Members of the group invite users outside the group to join the group.
              - 5: Members of the group leave.
              - 6: Members of the group are kicked out.
            - Group member information change:
              - 11: Group owner transfer.
              - 12: Group member role change.
              - 13: Group member mute status change.
            - Group information change:
              - 30: Group name, group avatar, group notice change.
              - 34: Group mute status change.
        op_user_info:
          type: object
          description: Tips message trigger user (e.g. group creation user, group name modification user) user information.
          properties:
            user_id:
              type: string
              description: User ID.
            role:
              type: number
              description: |
                User's group member role.
                - 1: Group owner.
                - 2: Group manager.
                - 3: Group member.
            group_member_name:
              type: string
              description: User name.
            group_member_nickname:
              type: string
              description: User's group member nickname.
        target_users:
          type: array
          description: Tips message trigger operation target users (e.g. users invited to join the group together when the group is created, users kicked out of the group, etc.).
          items:
            type: object
            properties:
              user_id:
                type: string
                description: User ID.
              role:
                type: number
                description: |
                  User's group member role.
                  - 1: Group owner.
                  - 2: Group manager.
                  - 3: Group member.
              group_member_name:
                type: string
                description: User name.
              group_member_nickname:
                type: string
                description: User's group member nickname.
        group_data_flag:
          type: number
          description: |
            When type is 30, this parameter is meaningful, indicating the group information project that has been modified.
            - 1: Group name.
            - 2: Group notice.
            - 4: Group avatar.
        group_notice:
          type: string
          description: Group notice.
        group_name:
          type: string
          description: Group name.
        group_avatar:
          type: string
          description: Group avatar.
        forbid:
          type: object
          description: When type is 34, this parameter represents the group members who are muted.
          properties:
            is_all_forbid:
              type: boolean
              description: |
                Whether all members are muted:
                - false: No.
                - true: Yes.
            forbid_role_list:
              type: array
              description: Group members who are muted.
              items:
                type: number
            forbid_expire_time:
              type: number
              description: Mute expiration timestamp, in milliseconds.
        forbid_expire_time:
          type: number
          description: When type is 13, this parameter represents the group member mute expiration timestamp, in milliseconds.
        role:
          type: number
          description: |
            When type is 12, this parameter represents the group member role after the change.
            - 1: Group owner.
            - 2: Group manager.
            - 3: Group member.

    QueryMessagesRequest:
      type: object
      required: [FromUserId, ConvId, ConvType, MsgSeqList]
      properties:
        FromUserId:
          type: string
          description: |
            User's UserID (logged in ZIM service through the login method in the client, or registered through the [server API](/zim-server/user/batch-register-users)).
            - When querying one-to-one chat session messages, enter the userID of any participating user here.
            - When querying group chat session messages, enter the userID of any registered user here.
          maxLength: 32
          example: "user0"
        ConvId:
          type: string
          description: |
            Conversation ID.
            - When querying one-to-one chat session messages, enter the userID of the other participating user here (logged in ZIM service through the login method in the client, or registered through the [server API](/zim-server/user/batch-register-users)).
            - When querying group chat session messages, enter the groupID of the target group here.
          maxLength: 32
          example: "user1"
        ConvType:
          type: number
          description: |
            Conversation type:
            - 0: One-on-one conversation.
            - 2: Group conversation.
          enum: [0, 2]
          example: 0
        MsgSeqList:
          type: array
          description: |
            List of seqs to query messages. The list length limit is 20.
            > **Note**
            >
            > If you need to increase the limit, please contact ZEGO Technical Support.

            seq get method:
            - If you need to query messages sent by the **client**, get MsgSeq through the [message sent callback](/zim-server/callbacks/message-sent).
            - If you need to query messages sent by the server-side API [SendPeerMessage](/zim-server/messaging/send-a-one-to-one-message) sent by the **one-to-one chat**, get MsgSeq through the interface response data.
            - If you need to query messages sent by the server-side API [SendGroupMessage](/zim-server/messaging/send-group-messages) sent by the **group chat**, get MsgSeq through the interface response data.
          maxItems: 20
          items:
            type: number
            example: 1
          example: [1, 2, 3]
    QueryMessagesResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            The following only lists the return codes related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            <table>
            <tbody><tr>
            <th>Code / SubCode</th>
            <th>Description</th>
            <th>Suggested Solution</th>
            </tr>
            <tr>
            <td>660000001</td>
            <td>Server error.</td>
            <td>Please retry or contact ZEGO Technical Support.</td>
            </tr>
            <tr>
            <td>660000002</td>
            <td>Input parameters are missing or invalid.</td>
            <td>Please check the input parametersã€‚</td>
            </tr>
            <tr>
            <td>660300005</td>
            <td>The API call frequency exceeds the AppID-level limit.</td>
            <td>Please try again later, or refer to the relevant documentation to understand the call frequency.</td>
            </tr>
            <tr>
            <td>660700008</td>
            <td>Error getting user information.</td>
            <td>Please check if the user ID is correct.</td>
            </tr>
            <tr>
            <td>660700015</td>
            <td>User is not registered.</td>
            <td>Please register the user first.</td>
            </tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Description of the request result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        MessageList:
          type: array
          description: Returned message content list.
          items:
            type: object
            properties:
              Sender:
                type: string
                description: Message sender.
                example: "userA"
              MsgType:
                type: number
                description: |
                  Message type:
                  - 1: Text.
                  - 10: Combination.
                  - 11: Image.
                  - 12: File.
                  - 13: Audio.
                  - 14: Video.
                  - 31: Revoked message.
                  - 32: Tips message.
                  - 200: Custom.
                example: 1
              SubMsgType:
                type: number
                description: Specific custom type. The value is filled by the user when sending a custom message, with a value range of [0,200]. This parameter is meaningful only when MsgType is 200 (custom type).
              MsgBody:
                $ref: '#/components/schemas/MsgBodyContent'
                description: |
                  Message content.
                  - When MsgType is 1 (text type) or 200 (custom type), MsgBody is the message content passed in when sending the message, and the developer can read it directly.
                  - When MsgType is one of the following types, MsgBody is a JSON string. Please use URLDecode to decode this JSON string and obtain the data of each field in the message according to the corresponding structure:
                    - When MsgType is 11, 12, 13, or 14 (Multimedia message): refer to the Multimedia message structure.
                    - When MsgType is 10 (combination message): refer to the combination message structure.
                    - When MsgType is 31 (message has been revoked): refer to the revoked message structure.
                    - When MsgType is 32 (Tips message): refer to the Tips message structure.
              MsgId:
                type: number
                description: Message ID, which can be used to determine the uniqueness of the message.
                example: 971503777289036700
              MsgSeq:
                type: number
                description: Message seq.
                example: 1
              Payload:
                type: string
                description: Message extended field.
                example: "this is a payload"
              MsgTime:
                type: number
                description: The time the server received the message, in Unix timestamp format, in milliseconds (ms).
                example: 1705895412000
              IsEmpty:
                type: number
                description: |
                  Whether it is an empty message:
                  - 0: Not an empty message.
                  - 1: The message has been deleted (cannot be queried or deleted by the customer through the interface), and all other parameters are empty at this time.
                  - 2: The message has been revoked.
                example: 0
          example:
            - Sender: "userA"
              MsgType: 1
              MsgBody: "this is a message"
              MsgId: 971503777289036700
              MsgSeq: 1
              Payload: "this is a payload"
              MsgTime: 1705895412000
              IsEmpty: 0
