openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - messaging

paths:
  /:
    post:
      tags: [messaging]
      summary: Recall a room message
      description: |
        <Note title="Note">

        To use this feature, please activate the ZIM flagship service to ensure that your App ID is set to enable saving room messages.
        </Note>

        By calling this API, you can recall room conversation messages.

        After a message is recalled, users in the room will receive a notification that the message has been recalled through the following ZIM SDK callback interfaces.

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|-------|---------|
        | [messageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-message-revoke-received) | [onMessageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-message-revoke-received) | [messageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-message-revoke-received) | [onMessageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-message-revoke-received) |

        | Web-25% | Mini Program-25% | Flutter-25% | React Native-25% |
        |---------|-----|--------|--------------|
        | [messageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#message-revoke-received) | [messageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#message-revoke-received) | [onMessageRevokeReceived](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onMessageRevokeReceived.html) | [messageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#message-revoke-received) |

        | Unity3D-25% | uni-app \| uni-app x-25% | HarmonyOS-25% |
        |---------|---------|---------|
        | [OnMessageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-message-revoke-received) | [messageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#message-revoke-received) | [messageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#message-revoke-received) |

        <Note title="QPS Limit"> 20 times/s</Note>
        
      operationId: recall-a-room-message
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=RevokeRoomMessage
          required: true
          schema:
            type: string
            enum: [RevokeRoomMessage]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RevokeRoomMessageRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'

components:
  schemas:
    RevokeRoomMessageRequest:
      type: object
      required: [FromUserId, RoomId, MsgSeq]
      properties:
        FromUserId:
          type: string
          description: Message sender user ID (who has logged in to the ZIM service by calling the login method on the client, or has completed registration by calling the [server-side API](/zim-server/user/batch-register-users)).
          maxLength: 32
          example: "u1"
        RoomId:
          type: string
          description: Room ID.
          maxLength: 32
          example: "room1"
        MsgSeq:
          type: number
          description: |
            Message seq. How to obtain:
            - To recall a room message sent by the **client**, obtain MsgSeq through the [message sent callback](/zim-server/callbacks/message-sent).
            - To recall a room message sent by the server-side API [SendRoomMessage](/zim-server/messaging/send-room-messages), obtain MsgSeq through the API response data.
          example: 10
        Payload:
          type: string
          description: Recall additional information, maximum 200 bytes.
          maxLength: 200
          example: "hello world"
    CommonResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            The following only lists the return codes related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            <table>
            <tbody><tr>
            <th>Return code</th>
            <th>Description</th>
            <th>Suggested Solution</th>
            </tr>
            <tr>
            <td>660000001</td>
            <td>Business general error.</td>
            <td>Please retry or contact ZEGOCLOUD Technical Support.</td>
            </tr>
            <tr>
            <td>660000002</td>
            <td>Parameter error.</td>
            <td>Please refer to Request and enter the correct parameters.</td>
            </tr>
            <tr>
            <td>660000022</td>
            <td>Message not found, possibly because the message has been deleted or does not exist.</td>
            <td>Please check if the message has been deleted and if MsgSeq is correct.</td>
            </tr>
            <tr>
            <td>660000023</td>
            <td>Message has been recalled.</td>
            <td>Please confirm if the message has been recalled. <ul><li>If confirmed that the message has been recalled, no action is needed.</li><li>If confirmed that the message has not been recalled, please contact ZEGOCLOUD Technical Support to troubleshoot the issue.</li></ul></td>
            </tr>
            <tr>
            <td>660000027</td>
            <td>Save room messages configuration is not enabled.</td>
            <td>Please activate the ZIM flagship service.</td>
            </tr>
            <tr>
            <td>660300001</td>
            <td>Room does not exist.</td>
            <td>Confirm if RoomId is correct or if the room has been destroyed.</td>
            </tr>
            <tr>
            <td>660300002</td>
            <td>User is not in this room.</td>
            <td>Please confirm if UserId is correct.</td>
            </tr>
            <tr>
            <td>660300005</td>
            <td>The API call frequency exceeds the AppID-level limit.</td>
            <td>Please try again later, or refer to the relevant documentation to understand the call frequency.</td>
            </tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Description of the request result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
      example:
        Code: 0
        Message: "success"
        RequestId: "343649807833778782"
