openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - messaging

paths:
  /:
    post:
      tags: [messaging]
      summary: Recall a group message
      description: |
        By calling this API, you can recall group conversation messages within 2 minutes. If you need to recall messages sent earlier, please contact ZEGOCLOUD Technical Support. Messages sent within 24 hours can be recalled at most.

        After a message is recalled, the message receiving user will receive a notification that the message has been recalled through the following ZIM SDK callback interfaces.

        | iOS | Android | macOS-25% | Windows-25% |
        |-----|---------|-------|---------|
        | [messageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-message-revoke-received) | [onMessageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-message-revoke-received) | [messageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-message-revoke-received) | [onMessageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-message-revoke-received) |

        | Web | Mini Program | Flutter-25% | React Native-25% |
        |---------|-----|--------|--------------|
        | [messageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#message-revoke-received) | [messageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#message-revoke-received) | [onMessageRevokeReceived](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onMessageRevokeReceived.html) | [messageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#message-revoke-received) |

        | Unity3D-25% | uni-app \| uni-app x-25% | HarmonyOS-25% |
        |---------|---------|---------|
        | [OnMessageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-message-revoke-received) | [messageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#message-revoke-received) | [messageRevokeReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#message-revoke-received) |

        <Note title="QPS Limit"> 20 times/s</Note>
        
      operationId: recall-a-group-message
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=RevokeGroupMessage
          required: true
          schema:
            type: string
            enum: [RevokeGroupMessage]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RevokeGroupMessageRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'

components:
  schemas:
    RevokeGroupMessageRequest:
      type: object
      required: [FromUserId, GroupId, MsgSeq]
      properties:
        FromUserId:
          type: string
          description: Message sender user ID (who has logged in to the ZIM service by calling the login method on the client, or has completed registration by calling the [server-side API](/zim-server/user/batch-register-users)).
          maxLength: 32
          example: "u1"
        GroupId:
          type: string
          description: Group ID.
          maxLength: 32
          example: "group1"
        MsgSeq:
          type: number
          description: |
            Message seq. How to obtain:
            - To recall a group message sent by the **client**, obtain MsgSeq through the [message sent callback](/zim-server/callbacks/message-sent).
            - To recall a group message sent by the server-side API [SendGroupMessage](/zim-server/messaging/send-group-messages), obtain MsgSeq through the API response data.
          example: 10
        Payload:
          type: string
          description: Recall additional information, maximum 200 bytes.
          maxLength: 200
          example: "payload"
        OfflinePush:
          type: object
          description: Offline push configuration. If configured and enabled, the message recall will be notified in the form of offline push when the device switches to the background. For details, please refer to [OfflinePush description](/zim-server/messaging/messagebody-introduction).
          example:
            Enable: 1
            Title: "title"
            Content: "content"
            Payload: "payload"
    CommonResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            The following only lists the return codes related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            <table>
            <tbody><tr>
            <th>Return code</th>
            <th>Description</th>
            <th>Suggested Solution</th>
            </tr>
            <tr>
            <td>660000002</td>
            <td>Parameter error.</td>
            <td>Please refer to Request and enter the correct parameters.</td>
            </tr>
            <tr>
            <td>660000022</td>
            <td>Message not found, possibly because the message has been deleted or does not exist.</td>
            <td>Please check if the message has been deleted and if MsgSeq is correct.</td>
            </tr>
            <tr>
            <td>660000023</td>
            <td>Message has been recalled.</td>
            <td>Please confirm if the message has been recalled. <ul><li>If confirmed that the message has been recalled, no action is needed.</li><li>If confirmed that the message has not been recalled, please contact ZEGOCLOUD Technical Support to troubleshoot the issue.</li></ul></td>
            </tr>
            <tr>
            <td>660000024</td>
            <td>Recall time has been exceeded.</td>
            <td>If you need to recall messages sent over a longer period, please contact ZEGOCLOUD Technical Support for configuration.</td>
            </tr>
            <tr>
            <td>660000026</td>
            <td>The message to be recalled does not match FromUserId.</td>
            <td>Please check if the FromUserId field is correct.</td>
            </tr>
            <tr>
            <td>660300005</td>
            <td>Frequency exceeds the AppID-level limit.</td>
            <td>Please try again later, or refer to the relevant documentation to understand the call frequency.</td>
            </tr>
            <tr>
            <td>660600001</td>
            <td>Group does not exist.</td>
            <td>Please confirm if the entered GroupId is correct.</td>
            </tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Description of the request result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
      example:
        Code: 0
        Message: "success"
        RequestId: "343649807833778782"
