openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - messaging

paths:
  /:
    post:
      tags: [messaging]
      summary: Send a one-to-one message
      description: |
        Send 1v1 one-to-one messages, supporting sending messages to a single user or batch sending to multiple users.

        The target client will receive one-to-one message notifications through the ZIM SDK callback interface.
        <Note title="Note">After enabling the content moderation feature, messages sent by the server will be moderated by default. If messages sent by the server do not need to be moderated, please contact ZEGOCLOUD Technical Support for configuration.</Note>

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|-------|---------|
        | [peerMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-peer-message-received-info-from-user-id) | [onPeerMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-peer-message-received) | [peerMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-peer-message-received-info-from-user-id) | [onPeerMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-peer-message-received) |

        | Web-25% | Mini Program-25% | Flutter-25% | React Native-25% |
        |-----|---------|-------|---------|
        | [peerMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#peer-message-received) | [peerMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#peer-message-received) | [onPeerMessageReceived](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onPeerMessageReceived.html) | [peerMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#peer-message-received) |

        | Unity3D-25% | uni-app \| uni-app x-25% | HarmonyOS-25% |
        |-----|---------|-------|
        | [OnReceivePeerMessage](https://www.zegocloud.com/docs/article/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-receive-peer-message) | [peerMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#peer-message-received) | [peerMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#peer-message-received) |  |

        <Note title="Note">The users corresponding to the parameters `FromUserId` and `ToUserId` have logged in to the ZIM service by calling the `login` method on the client, or the developer has registered the relevant userID by calling the server-side API.</Note>

        <Note title="Note">
        The parameters FromUserId and ToUserId only support numbers, English characters, and `'!'，'#'，'$'，'%'，'&'，'('，')'，'+'，'-'，':'，';'，'<'，'='，'.'，'>'，'?'，'@'，'['，']'，'^'，'_'，' '，'{'，'}'，'|'，'~'`.

        If the sender's SDK version (for version information, please refer to Release notes) is lower than 2.0.0, the ZIM server only supports Command type messages with MessageType 2, and does not support other types.
        To provide developers with a better experience, ZEGOCLOUD recommends that developers use the latest version of the SDK.

        If the sender requests to send a text message with MessageType 1, the sender's corresponding client (SDK version needs to be 2.7.0 or above) will also receive the message.

        For sending and receiving custom messages with MessageType 200, the SDK version of the sender's and receiver's corresponding clients needs to be 2.8.0 or above.

        If the receiver's SDK version is in the [2.0.0, 2.8.0) range, they can receive custom messages, but the message type will be displayed as unknown and the message content cannot be obtained. To obtain this message, please upgrade the SDK to version 2.8.0 or above.

        If the receiver's SDK version is 1.x.x, they will not be able to receive custom messages, nor will they receive unknown messages.
        </Note>

        <Note title="QPS Limit"> 20 times/s</Note>
      operationId: send-a-one-to-one-message
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=SendPeerMessage
          required: true
          schema:
            type: string
            enum: [SendPeerMessage]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendPeerMessageRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendPeerMessageResponse'

components:
  schemas:
    SendPeerMessageRequest:
      type: object
      required: [FromUserId, ToUserId, MessageType, Priority, MessageBody]
      properties:
        FromUserId:
          type: string
          description: Sender user ID.
          maxLength: 32
          example: "u1"
        ToUserId:
          type: array
          description: |
            Receiver's user ID list, supporting up to 100 user IDs.
            > **Note**
            >
            > The list cannot contain userIDs identical to FromUserId, meaning the sender cannot send messages to themselves.
          maxItems: 100
          items:
            type: string
            maxLength: 32
          example: ["u2", "u3"]
        MessageType:
          type: number
          description: Message type. For applicable types for one-to-one conversations, please refer to [MessageBody](/zim-server/messaging/messagebody-introduction) description.
          example: 1
        Priority:
          type: number
          format: int32
          description: |
            Message priority (for details, please refer to [Basic Concepts Introduction - Message Priority](/zim-android/introduction/basic-concepts#message-priority)), with the following values:
            - 1: Low.
            - 2: Medium.
            - 3: High.
          enum: [1, 2, 3]
          example: 1
        MessageBody:
          type: object
          description: Message content. For specific parameter format, please refer to [MessageBody](/zim-server/messaging/messagebody-introduction) description.
          example: {
            "Message": "hello world",
            "ExtendedData": "extendedData",
            "OfflinePush": {
              "Enable": 0,
              "Title": "Title",
              "Content": "Content",
              "Payload": "data"
            }
          }
        SubMsgType:
          type: number
          description: Specific custom type. The value is defined by you, with a value range of [0,200]. This parameter only needs to be assigned when MessageType is a custom message
        SearchedContent:
          type: string
          description: Search field for custom messages. This field can only be filled in when MessageType is a custom message, with a default maximum length of 64 bytes. This field applies to the client. Unless this field is filled in, the associated custom message cannot be searched through the client.
        SenderUnaware:
          type: number
          description: |
            When sending messages through this server-side API, whether the client corresponding to FromUserId in the request parameters can perceive this sending:
            - 0: (default) Can perceive.
            - 1: Unperceived.
        SendMsgOptions:
          type: object
          description: Optional configuration items.
          properties:
            NoUnread:
              type: boolean
              description: |
                Whether this message will increase the receiver's unread message count.
                - false: (default value) will.
                - true: will not.
              example: true
    SendPeerMessageResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            The following only lists the Code and SubCode related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            > **Note**
            >
            > When you initiate a request to send messages to multiple users simultaneously:
            > <ul><li>If you only need to successfully send messages to 1 or more users, Code will return 0, indicating success. In this case, please refer to the specific information in ErrorList to confirm the operation result and understand whether sending messages to some users failed.</li>
            > <li>If sending messages to all users fails, Code will return the relevant return code. For details, please refer to <a href="/zim-server/return-codes" target="_blank">Return codes</a>.</li></ul>

            <table>
            <tbody><tr>
            <th>Code / SubCode</th>
            <th>Note</th>
            <th>Suggested Solution</th>
            </tr>
            <tr>
            <td>660000011</td>
            <td>The number of users exceeds the limit, and the input user list is too large.</td>
            <td>Please check the input user list.</td>
            </tr>
            <tr>
            <td>660000025</td>
            <td>Sending a signaling message encoded in base64 fails after IsBase64 is passed in MessageBody.</td>
            <td>
            Please confirm:
            <ul>
            <li>Please confirm whether IsBase64 needs to be 1, i.e., whether to send a binary type signaling message.</li>
            <li>Please confirm whether the message content is encoded in base64.</li>
            </ul>
            </td>
            </tr>
            <tr>
            <td>660400001</td>
            <td>The input message size exceeds the limit.</td>
            <td>Please check the input message size.</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: Return information.
          example: success
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        ErrorList:
          type: array
          description: |
            Failed list.
            <ul>
            <li>Code is 0:</li>
            <li>ErrorList is empty, indicating that all one-to-one messages are successfully sent.</li>
            <li>ErrorList is not empty, indicating that some one-to-one messages failed to send. Please refer to SubCode for handling.</li>
            <li>Code is not 0:</li>
            <li>ErrorList is empty, indicating that parameter error, interface frequency limit, or system error occurred.</li>
            <li>ErrorList is not empty, indicating that all one-to-one messages failed to be sent.</li>
            </ul>
          items:
            type: object
            properties:
              UserId:
                type: string
                description: The target UserID of the message that failed to be sent.
                example: "u3"
              SubCode:
                type: number
                description: |
                  Specific return code for failed message sending. For the complete return codes, please refer to the Code description or [Return codes](/zim-server/return-codes).
                example: 1
        SuccList:
          type: array
          description: The list of users to whom messages were successfully accepted.
          items:
            type: object
            properties:
              UserId:
                type: string
                description: User ID.
                example: "id4"
              MsgId:
                type: string
                description: Message ID. Globally unique.
                example: "6654861479614"
              MsgSeq:
                type: number
                description: Message Seq. When the message type is a signaling message, this field is empty. Can be used for [Recall a one-to-one message](/zim-server/messaging/recall-a-one-to-one-message).
                example: 1
        AuditInfos:
          type: array
          description: Audit structure array. When the array is not empty, it indicates that there are messages that failed the audit, and you can view the reason for the audit failure through this structure.
          items:
            type: object
            properties:
              Index:
                type: number
                description: |
                  This parameter may have the following situations:

                  When you have enabled the ZIM content moderation service and have not rejected the message through the [message not sent yet callback](/zim-server/callbacks/message-not-sent-yet):
                  - For combined messages, this parameter indicates the index of the Item that failed the audit in the combined message, starting from 0.
                  - For other types of messages, this parameter is always 0.
                  
                  When you reject this message after receiving the message not sent yet callback, this parameter is always 0 regardless of the message type.
                example: 0
              Reason:
                type: string
                description: Rejection reason.
                example: "reason"