openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - messaging

paths:
  /:
    post:
      tags: [messaging]
      summary: Send room messages
      description: |
        Send room messages and push them to all online users in the room.

        The client will receive message notifications in the room through the ZIM SDK callback interface.
        <Note title="Note">After enabling the content moderation feature, messages sent by the server will be moderated by default. If messages sent by the server do not need to be moderated, please contact ZEGOCLOUD Technical Support for configuration.</Note>

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|-------|---------|
        | [roomMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-room-message-received-info-from-room-id) | [onRoomMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-room-message-received) | [roomMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-room-message-received-info-from-room-id) | [onRoomMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-room-message-received) |

        | Web-25% | Mini Program-25% | Flutter-25% | React Native-25% |
        |---------|---------|---------|---------|
        | [roomMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#room-message-received) | [roomMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#room-message-received) | [onRoomMessageReceived](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onRoomMessageReceived.html) | [roomMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#room-message-received) |

        | Unity3D-25% | uni-app \| uni-app x-25% | HarmonyOS-25% |
        |---------|---------|---------|
        | [onReceiveRoomMessage](https://www.zegocloud.com/docs/article/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-receive-room-message) | [roomMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#room-message-received) | [roomMessageReceived](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#room-message-received) |

        <Note title="Note">
        The parameters FromUserId and RoomId only support numbers, English characters, and `'!'，'#'，'$'，'%'，'&'，'('，')'，'+'，'-'，':'，';'，'<'，'='，'.'，'>'，'?'，'@'，'['，']'，'^'，'_'，' '，'{'，'}'，'|'，'~'`.

        For sending and receiving custom messages with MessageType 200, the SDK version of the sender's and receiver's corresponding clients needs to be 2.8.0 or above.

        If the receiver's SDK version is in the [2.0.0, 2.8.0) range, they can receive custom messages, but the message type will be displayed as unknown and the message content cannot be obtained. To obtain this message, please upgrade the SDK to version 2.8.0 or above.

        If the receiver's SDK version is 1.x.x, they will not be able to receive custom messages, nor will they receive unknown messages.
        </Note>

        <Note title="QPS Limit"> 10 times/s. If you need to adjust, please contact ZEGOCLOUD sales to understand the specific billing rules.</Note>
      operationId: send-room-messages
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=SendRoomMessage
          required: true
          schema:
            type: string
            enum: [SendRoomMessage]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendRoomMessageRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendRoomMessageResponse'

components:
  schemas:
    SendRoomMessageRequest:
      type: object
      required: [FromUserId, RoomId, MessageType, Priority, MessageBody]
      properties:
        FromUserId:
          type: string
          description: Sender's user ID (who has logged in to the ZIM service by calling the login method on the client, or has completed registration by calling the [server-side API](/zim-server/user/batch-register-users)).
          maxLength: 32
          example: "u1"
        RoomId:
          type: string
          description: Room ID.
          maxLength: 32
          example: "r1"
        MessageType:
          type: number
          description: Message type. For applicable types for room conversations, please refer to [MessageBody description](/zim-server/messaging/messagebody-introduction).
          example: 1
        Priority:
          type: number
          description: |
            Message priority (for details, please refer to [Basic concepts - Message priority](https://www.zegocloud.com/docs/zim-android/introduction/basic-concepts#message-priority)). Values are as follows:
            - 1: Low.
            - 2: Medium.
            - 3: High.
          enum: [1, 2, 3]
          example: 1
        MessageBody:
          type: object
          description: Message content. For specific parameter format, please refer to [MessageBody description](/zim-server/messaging/messagebody-introduction).
          example:
            Message: "hello world"
            ExtendedData: "d"
        SubMsgType:
          type: number
          description: Specific custom type. The value is defined by the developer, with a value range of [0,200]. This parameter only needs to be assigned when MessageType is a custom message.
        SearchedContent:
          type: string
          description: Search field for custom messages. This field can only be filled in when MessageType is a custom message, with a default maximum length of 64 bytes. This field applies to the client. Unless this field is filled in, the associated custom message cannot be searched through the client.
        SenderUnaware:
          type: number
          description: |
            When sending messages through this server-side API, whether the client corresponding to FromUserId in the request parameters can perceive this sending:
            - 0: Can perceive.
            - 1: (Default) Cannot perceive.
          example: 0
    SendRoomMessageResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            The following only lists the return codes related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            <table>
            <tbody><tr>
            <th>Return code</th>
            <th>Description</th>
            <th>Suggested Solution</th>
            </tr>
            <tr>
            <td>660000025</td>
            <td>After passing 1 for IsBase64 in MessageBody, sending base64-encoded signaling messages failed.</td>
            <td>
            Please confirm:
            <ul>
            <li>Please confirm whether IsBase64 needs to be 1, i.e., whether binary type signaling messages need to be sent.</li>
            <li>Please confirm whether the message content is base64 encoded.</li>
            </ul>
            </td>
            </tr>
            <tr>
            <td>660300001</td>
            <td>The input RoomId does not exist.</td>
            <td>Please confirm if the input RoomId is correct.</td>
            </tr>
            <tr>
            <td>660300013</td>
            <td>Room messages do not support receipts.</td>
            <td>Please delete the "HasReceipt" field in the request message body.</td>
            </tr>
            <tr>
            <td>660400001</td>
            <td>The input message size exceeds the limit.</td>
            <td>Please check the input message size.</td>
            </tr>
            <tr>
            <td>660500002</td>
            <td>Message sender has not logged in to the SDK.</td>
            <td>Please have the user log in first before sending messages.</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: Description of the request result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        AuditInfos:
          type: array
          description: Audit structure array. When the array is not empty, it indicates that there are messages that failed the audit, and you can view the reason for the audit failure through this structure.
          items:
            type: object
            properties:
              Index:
                type: number
                description: |
                  This parameter may have the following situations:
                  - When you have enabled the ZIM content moderation service and have not rejected the message through the [message not sent yet callback](/zim-server/callbacks/message-not-sent-yet):
                    - For combined messages, this parameter indicates the index of the Item that failed the audit in the combined message, starting from 0.
                    - For other types of messages, this parameter is always 0.
                  - When you reject this message after receiving the message not sent yet callback, this parameter is always 0 regardless of the message type.
                example: 0
              Reason:
                type: string
                description: Rejection reason.
                example: "reason"
          example:
            - Index: 0
              Reason: "reason"    # Return the reason for audit failure
