export default function AudioTable() {
  return (
    <table>
      <tbody>
        <tr>
          <th>原始声音</th>
          <th colSpan={2}>目标音色</th>
          <th>AI 变声后</th>
        </tr>
        <tr>
          <td rowSpan={4}>
            <audio
              src="https://doc-media.zego.im/sdk-doc/doc/video/Express_Video_SDK/Audio/VoiceChanger/original_voice.wav"
              controls
            />
          </td>
          <td>青年男性</td>
          <td>
            <audio
              src="https://doc-media.zego.im/sdk-doc/doc/video/Express_Video_SDK/Audio/VoiceChanger/young_male_target_voice.wav"
              controls
            />
          </td>
          <td>
            <audio
              src="https://doc-media.zego.im/sdk-doc/doc/video/Express_Video_SDK/Audio/VoiceChanger/young_male_changer_voice.wav"
              controls
            />
          </td>
        </tr>
        <tr>
          <td>成年男性</td>
          <td>
            <audio
              src="https://doc-media.zego.im/sdk-doc/doc/video/Express_Video_SDK/Audio/VoiceChanger/adult_male_target_voice.wav"
              controls
            />
          </td>
          <td>
            <audio
              src="https://doc-media.zego.im/sdk-doc/doc/video/Express_Video_SDK/Audio/VoiceChanger/adult_male_changer_voice.wav"
              controls
            />
          </td>
        </tr>
        <tr>
          <td>青年女性</td>
          <td>
            <audio
              src="https://doc-media.zego.im/sdk-doc/doc/video/Express_Video_SDK/Audio/VoiceChanger/young_female_target_voice.wav"
              controls
            />
          </td>
          <td>
            <audio
              src="https://doc-media.zego.im/sdk-doc/doc/video/Express_Video_SDK/Audio/VoiceChanger/young_female_changer_voice.wav"
              controls
            />
          </td>
        </tr>
        <tr>
          <td>成年女性</td>
          <td>
            <audio
              src="https://doc-media.zego.im/sdk-doc/doc/video/Express_Video_SDK/Audio/VoiceChanger/adult_female_target_voice.wav"
              controls
            />
          </td>
          <td>
            <audio
              src="https://doc-media.zego.im/sdk-doc/doc/video/Express_Video_SDK/Audio/VoiceChanger/adult_female_changer_voice.wav"
              controls
            />
          </td>
        </tr>
      </tbody>
    </table>
  );
}