openapi: 3.0.0
info:
  title: ZIM Server API - Shared Components
  version: 1.0.0

# Shared server configuration (ZIM and authentication service)
servers:
  - url: https://zim-api.zego.im
    description: Unified access address (regardless of region)	
  - url: https://zim-api-sha.zego.im
    description: Chinese Mainland (Shanghai)
  - url: https://zim-api-hkg.zego.im
    description: Hong Kong, Macau and Taiwan (Hong Kong)
  - url: https://zim-api-fra.zego.im
    description: Europe (Frankfurt)
  - url: https://zim-api-lax.zego.im
    description: Western United States (California)
  - url: https://zim-api-bom.zego.im
    description: Asia-Pacific (Mumbai)
  - url: https://zim-api-sgp.zego.im
    description: Southeast Asia (Singapore)
  - url: https://auth-api.zego.im
    description: Authentication (for ZIMAudio)

components:
  parameters:
    # Re-export ZEGO global shared parameters for convenient local reference
    AppId:
      $ref: "../../../../snippets/common/en/openapi/zego-shared-components.yaml#/components/parameters/AppId"
    SignatureNonce:
      name: SignatureNonce
      in: query
      description: 💡Public parameter. A 16-character hexadecimal random string (hex encoding of 8-byte random number). Refer to [Signature example](/zim-server/accessing-server-apis#signature-example) for how to generate.
      required: true
      schema:
        type: string

    Timestamp:
      name: Timestamp
      in: query
      description: 💡Public parameter. Current Unix timestamp, in seconds. Refer to [Signature example](/zim-server/accessing-server-apis#signature-example) for how to generate, with a maximum error of 10 minutes.
      required: true
      schema:
        type: integer
        format: int64
    SignatureVersion:
      $ref: "../../../../snippets/common/en/openapi/zego-shared-components.yaml#/components/parameters/SignatureVersion"
    Signature:
      name: Signature
      in: query
      description: 💡Public parameter. Signature, used to verify the legitimacy of the request. Refer to [Signing the requests](/zim-server/accessing-server-apis#signing-the-requests) for how to generate an API request signature.
      required: true
      schema:
        type: string

