openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - room

paths:
  /:
    get:
      tags: [room]
      summary: 获取房间成员信息
      description: |
        根据房间 ID 获取房间成员的信息，包括房间用户数量、用户 ID 及名称。

        说明：关于 NextFlag 的额外说明：除上述说明之外，此字段与列表信息无任何关联，请勿基于此做任何其他逻辑。

        <Note title="说明">调用频率限制：20 次/秒</Note>
      operationId: obtain-information-about-users-in-a-room
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=QueryRoomUserList
          required: true
          schema:
            type: string
            enum: [QueryRoomUserList]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - name: RoomId
          in: query
          required: true
          description: 房间ID，长度上限为 32 字节。
          schema:
            type: string
            maxLength: 32
            example: "room123"
        - name: Mode
          in: query
          required: false
          schema:
            type: integer
            enum: [0, 1]
            default: 0
          description: 按用户登录房间时间排序：0：按时间顺序（默认值）；1：按时间倒序。
        - name: NextFlag
          in: query
          required: false
          schema:
            type: string
          description: 分页拉取标志，第一次填空，之后填上一次返回的 NextFlag 值。
        - name: Limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 500
          description: 单次查询用户的数量，取值范围为 [0, 500]，默认 500。
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryRoomUserListResponse'

components:
  schemas:
    QueryRoomUserListResponse:
      type: object
      properties:
        Code:
          type: integer
          description: |
            返回码。
            <table>
            <thead><tr><th>返回码</th><th>说明</th><th>处理建议</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>参数错误。</td><td>请检查请求参数。</td></tr>
            <tr><td>660300001</td><td>房间不存在。</td><td>请检查 RoomId 是否正确或房间是否已被销毁。</td></tr>
            <tr><td>660300006</td><td>超出调用频率限制。</td><td>调用频率为 20 次/秒，请稍后重试。</td></tr>
            <tr><td>660300007</td><td>获取房间失败。</td><td>请联系 ZEGO 技术支持。</td></tr>
            <tr><td>660300008</td><td>获取房间用户列表失败；房间人数为空，一般是处于房间延迟销毁期间。</td><td>无需操作。</td></tr>
            </tbody>
            </table>
        Message:
          type: string
          description: 请求结果的说明信息。
        RequestId:
          type: string
          description: 请求 ID。
        Data:
          type: object
          properties:
            Count:
              type: integer
              description: 当前房间用户数。
            NextFlag:
              type: string
              description: 分页拉取标志。
            UserList:
              type: array
              description: 成员列表。
              items:
                type: object
                properties:
                  UserId:
                    type: string
                  UserName:
                    type: string
