openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - room

paths:
  /:
    post:
      tags: [room]
      summary: 查询房间属性
      description: |
        查询指定房间 ID 的所有房间属性。

        <Note title="说明">调用频率限制：20 次/秒。</Note>
      operationId: query-room-attributes
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=QueryRoomAttribute
          required: true
          schema:
            type: string
            enum: [QueryRoomAttribute]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRoomAttributeRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryRoomAttributeResponse'
              example:
                Code: 0
                Message: success
                RequestId: "req-123456789"
                AttributeSeq: 10
                Attributes:
                  - Key: "1"
                    Value: "attr1"
                    Seq: 9
                    AutoDelete: 0
                  - Key: "2"
                    Value: "attr1"
                    Seq: 10
                    AutoDelete: 0

components:
  schemas:
    QueryRoomAttributeRequest:
      type: object
      required: [FromUserId, RoomId]
      properties:
        FromUserId:
          type: string
          description: 操作者，需要是已注册状态，该用户不会自动加入房间。仅支持数字，英文字符和 '!'，'#'，'$'，'%'，'&'，'('，')'，'+'，'-'，':'，';'，'<'，'='，'.'，'>'，'?'，'@'，'['，']'，'^'，'_'，' '，'，'，'
          maxLength: 32
          example: "fromUserId"   
        RoomId:
          type: string
          description: 房间 ID 。仅支持数字，英文字符和 '!'，'#'，'$'，'%'，'&'，'('，')'，'+'，'-'，':'，';'，'<'，'='，'.'，'>'，'?'，'@'，'['，']'，'^'，'_'，' '，'，'，'
          maxLength: 32
          example: "room123"
    QueryRoomAttributeResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            返回状态码（0 表示成功）。

            以下仅列出了接口业务逻辑相关的返回码，完整返回码请参考 [全局返回码](/zim-server/return-codes)。
            <table>
            <thead><tr><th>返回码</th><th>说明</th><th>解决方案</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>参数错误。</td><td>请检查参数。</td></tr>
            <tr><td>660300005</td><td>频率限制。</td><td>请稍后再尝试。</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: 返回状态信息。
          example: "success"
        RequestId:
          type: string
          description: 请求唯一标识。
          example: "req-123456789"
        AttributeSeq:
          type: number
          description: |
            记录房间内所有属性（创建、修改、删除）的总变更次数，用于校准属性和计算属性变更顺序，每有一个属性发生变化时 AttributeSeq 值 + 1。
            > 注意： 当一次有多个属性变更时，AttributeSeq 值会增加多次。例如，一次修改了 3 个属性，则 AttributeSeq 值会增加 3。
          example: 10
        Attributes:
          type: array
          description: 房间属性列表。
          items:
            $ref: '#/components/schemas/RoomAttribute'
    RoomAttribute:
      type: object
      properties:
        Key:
          type: string
          description: 房间属性 key 值。
          example: "1"
        Value:
          type: string
          description: 房间属性 value 值。
          example: "attr1"
        Seq:
          type: int32
          description: 房间属性 Key 的序列号，用于校准属性和计算属性变更顺序。每个属性在创建、修改成功时，Seq 值与当前的 AttributeSeq 相等。
          example: 1
        AutoDelete:
          type: number
          description: 是否自动删除。
          example: 0