openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - room

paths:
  /:
    post:
      tags: [room]
      summary: 更新房间属性
      description: |
        根据房间 ID 更新自定义的房间属性。一个房间最多可设置 20 个房间属性，如果需要增加房间属性数量上限，请联系 ZEGO 技术支持。

        <Note title="说明">如果传递的 Key 已经存在，则会修改已有的属性信息。</Note>

        <Note title="说明">调用频率限制：20 次/秒。</Note>
      operationId: update-room-attributes
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=ModifyRoomAttribute
          required: true
          schema:
            type: string
            enum: [ModifyRoomAttribute]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModifyRoomAttributeRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModifyRoomAttributeResponse'

components:
  schemas:
    ModifyRoomAttributeRequest:
      type: object
      required: [FromUserId, RoomId, Attributes]
      properties:
        FromUserId:
          type: string
          description: 操作者，需要是已注册状态，该用户不会自动加入房间。
          maxLength: 32
          example: "operator_user"
        RoomId:
          type: string
          description: 房间 ID。
          maxLength: 32
          example: "room123"
        Attributes:
          type: array
          items:
            $ref: '#/components/schemas/ModifyRoomAttribute'
    ModifyRoomAttribute:
      type: object
      required: [Action, Key]
      properties:
        Action:
          type: integer
          description: 删除还是设置，0 设置，1 删除。
          enum: [0, 1]
        Key:
          type: string
          description: 房间属性 key。
        Value:
          type: string
          description: 房间属性 value。
        AutoDelete:
          type: integer
          description: 用户退出时，是否自动删除，0：不自动删除，1：自动删除。
          enum: [0, 1]
        StopOnError:
          type: integer
          description: |
            是否开启快速失败，默认为关闭。
            - 0: 关闭快速失败。执行遇到错误时，记录当前属性并继续执行后续的更新操作，执行结束后返回所有记录到的属性。
            - 1: 开启快速失败。执行遇到错误时，停止更新操作并返回本次更新的属性，已执行成功的更新操作会保留。
          enum: [0, 1]
    ModifyRoomAttributeResponse:
      type: object
      properties:
        Code:
          type: integer
          description: |
            返回状态码（0 表示成功）。
            <table>
            <thead><tr><th>返回码</th><th>说明</th><th>解决方案</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>参数错误。</td><td>请检查参数。</td></tr>
            <tr><td>660300005</td><td>频率限制。</td><td>请稍后再尝试。</td></tr>
            </tbody>
            </table>
        Message:
          type: string
          description: 返回状态信息。
        RequestId:
          type: string
          description: 请求唯一标识。
        Data:
          type: object
          properties:
            ErrKeyList:
              type: array
              description: 错误的 key 列表（仅失败时返回）。
              items:
                type: object
                properties:
                  SubCode:
                    type: integer
                  Key:
                    type: string
