openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: './shared-components.yaml#/servers'

paths:
  /:
    post:
      tags:
        - cloud-recording
        - POST
      summary: PauseRecord
      description: |
        调用本接口可以暂停录制中的任务，暂停期间将不会录制房间内的音视频流、白板等。

        <Warning title="注意">仅混流录制任务可通过本接口暂停。</Warning>

        <Note title="说明">调用频率限制：10 次/秒</Note>
      operationId: pause-recording
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://cloudrecord-api.zego.im?Action=PauseRecord
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [PauseRecord]
          style: form
          explode: true
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PauseRecordingRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PauseRecordingResponse'

components:
  schemas:
    PauseRecordingRequest:
      type: object
      required: [TaskId]
      properties:
        TaskId:
          type: string
          description: 录制任务 ID，长度固定为 16 个字节的字符串。
          example: "XXXXXXXXXXX"
      example:
        TaskId: "XXXXXXXXXXX"

    PauseRecordingResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int64
          description: |
            错误码。
          example: 0
        Message:
          type: string
          description: 错误描述。
          example: "succeed"
        RequestId:
          type: string
          description: 请求 ID。
          example: "abcd123"
      example:
        Code: 0
        Message: "succeed"
        RequestId: "abcd123"

