openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: './shared-components.yaml#/servers'

paths:
  /:
    post:
      tags:
        - cloud-recording
        - POST
      summary: StopRecord
      description: |
        调用本接口结束云端录制。

        当开发者成功调用 StopRecord 接口后，云端录制服务会退出录制的房间并上传录制文件至设定的第三方云存储。

        <Note title="说明">调用频率限制：50 次/秒</Note>
      operationId: stop-record
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://cloudrecord-api.zego.im?Action=StopRecord
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [StopRecord]
          style: form
          explode: true
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StopRecordRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopRecordResponse'

components:
  schemas:
    StopRecordRequest:
      type: object
      required: [TaskId]
      properties:
        TaskId:
          type: string
          description: 录制任务 ID，长度固定为 16 个字节的字符串。
          example: "XXXXXXXXXXX"
      example:
        TaskId: "XXXXXXXXXXX"

    StopRecordResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int64
          description: |
            错误码。
          example: 0
        Message:
          type: string
          description: 错误描述。
          example: "succeed"
        RequestId:
          type: string
          description: 请求 ID。
          example: "abcd123"
      example:
        Code: 0
        Message: "succeed"
        RequestId: "abcd123"

