openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - group

paths:
  /:
    post:
      tags: [group]
      summary: Add group members
      description: |
        By calling this API, you can batch add new members to a specified group. A maximum of 100 members can be added at a time. If you need to adjust this limit, please contact ZEGOCLOUD Technical Support.

        After successful addition, all group members (including the added users) will receive relevant notifications through the following ZIM SDK callback interfaces:

        | iOS-25% | Android-25% | macOS-25% |Windows-25% |
        |-----|---------|--------|---------|
        | [groupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-group-member-state-changed-event-user-list-operated-info-group-id) | [onGroupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-group-member-state-changed) | [groupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-group-member-state-changed-event-user-list-operated-info-group-id)| [onGroupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-group-member-state-changed)  |

        |  Web-25% | Mini Program-25% |Flutter-25% |React Native-25% |
        |---------|-----|---------|---------|
        | [groupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#group-member-state-changed) | [groupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#group-member-state-changed) | [onGroupMemberStateChanged](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onGroupMemberStateChanged.html)| [groupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#group-member-state-changed) |

        |  Unity3D-25% | uni-app \| uni-app x-25% | HarmonyOS-25% |
        |---------|---------|---------|
        | [OnGroupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-group-member-state-changed) | [groupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#group-member-state-changed) | [groupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#group-member-state-changed) |

        <Note title="Note">The users corresponding to the parameters `FromUserId` and `UserId` have logged in to the ZIM service by calling the `login` method on the client, or have completed registration by calling the [server-side API](/zim-server/user/batch-register-users).</Note>
        <Note title="Note">
        The parameters FromUserId, GroupId, and NewOwner only support numbers, English characters, and `'!', '#', '$', '%', '&', '(', ')', '+', '', ':', ';', '<', '=', '.', '>', '?'
        , '@', '[', ']', '^', '_', '{', '}', '|', '~'`.
        </Note>
        <Note title="QPS Limit"> 1 time/s, group-level limit. If you need to adjust this limit, please contact ZEGOCLOUD Technical Support.</Note>
      operationId: add-group-members
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=InviteUsersIntoGroup
          required: true
          schema:
            type: string
            enum: [InviteUsersIntoGroup]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InviteUsersIntoGroupRequest'
            example:
              FromUserId: "zego_user"
              GroupId: "groupA"
              GroupMemberInfos:
                - UserId: "user_a"
                  EnterGroupTime: 123
                - UserId: "user_b"
                  EnterGroupTime: 0
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InviteUsersIntoGroupResponse'

components:
  schemas:
    InviteUsersIntoGroupRequest:
      type: object
      required: [FromUserId, GroupId, UserIds, GroupMemberInfos]
      properties:
        FromUserId:
          type: string
          description: Operator user ID. The user must be registered with the ZIM service.
          example: "zego_user"
        GroupId:
          type: string
          description: Group ID.
          example: "groupA"
        UserIds:
          type: array
          description: |
            List of user IDs to join the group. By default, a maximum of 100 user IDs are supported.
            > **Note**
            >
            > - If the array contains the same value as `FromUserId`, that value will be removed.
            > - This parameter has the same function as `GroupMemberInfos`. You can choose either one.
            > - This parameter is only valid when the length of `GroupMemberInfos` is 0.
          items:
            type: string
        GroupMemberInfos:
          type: array
          description: |
            List of user information to join the group. By default, a maximum of 100 user information entries are supported.

            This parameter has the same function as UserIds. You can choose either one.
          items:
            type: object
            required: [UserId]
            properties:
              UserId:
                type: string
                description: |
                  User ID joining the group.
                  > **Note**
                  >
                  > If this parameter is the same as FromUserId, it will be removed.
                  example: "userA"
              EnterGroupTime:
                type: number
                description: |
                  Timestamp for joining the group (in milliseconds).

                  - 0 or not passed: Use the current timestamp.
                  - Other: Cannot be greater than the current time.
                example: 123
              IsInvite:
                type: number
                description: |
                  User's group joining mode.

                  - 0: (Default) Inviting a user can directly pull them into the group without their consent.
                  - 1: After receiving an invitation, the user needs to agree before joining the group.
                enum: [0, 1]
    InviteUsersIntoGroupResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            The following only lists the Code and SubCode related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            <table>
            <thead><tr><th>Code / SubCode</th><th>Description</th><th>Suggested Solution</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>Input parameter error.</td><td>Please check the input parameters.</td></tr>
            <tr><td>660300006</td><td>Frequency limit.</td><td>Please try again later or learn about the relevant frequency limits.</td></tr>
            <tr><td>660500002</td><td>Operator user is not registered.</td><td>Please have the operator register with the ZIM service first.</td></tr>
            <tr><td>660600001</td><td>Group does not exist.</td><td>Please confirm if the GroupId is correct.</td></tr>
            <tr><td>660000011</td><td>Number of users exceeds the limit.</td><td>Please check the input user list.</td></tr>
            </tbody>
            </table>
        Message:
          type: string
          description: Description of the operation result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        ErrorUsers:
          type: array
          description: |
            Failure list.
            <ul>
            <li>When Code is 0:</li>
            <li>If ErrorUsers is empty, all specified users were successfully invited.</li>
            <li>If ErrorUsers is not empty, it means some specified users failed to be invited. Please refer to SubCode for handling.</li>
            <li>When Code is not 0:</li>
            <li>If ErrorUsers is empty, it indicates parameter error, API frequency limit, or system error.</li>
            <li>If ErrorUsers is not empty, it means all specified users failed to be invited.</li></ul>
          items:
            type: object
            properties:
              UserId:
                type: string
                description: User ID that failed to be invited.
                example: "usera"
              SubCode:
                type: number
                description: |
                  Return code for invitation failure. For the complete return codes, please refer to the Code description or [Return codes](/zim-server/return-codes).
                example: 660000002
