openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - group

paths:
  /:
    post:
      tags: [group]
      summary: Query the list of muted groups in the App
      description: |
        This API is used to query the IDs of all muted groups in the App, including groups in all-member mute, group role mute, or user ID mute status.

        This API returns 10,000 groups by default each time. If you need to adjust this limit, please contact ZEGOCLOUD Technical Support.

        <Note title="QPS Limit"> 20 times/s</Note>
      operationId: fetch-forbid-group-list
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=FetchForbidGroupList
          required: true
          schema:
            type: string
            enum: [FetchForbidGroupList]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FetchForbidGroupListRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FetchForbidGroupListResponse'
              example:
                Code: 0
                Message: success
                RequestId: "343649807833778782"
                FetchEnd: 1
                NextFlag: 100000
                GroupList:
                  - GroupId: "group_1"
                    ForbidType: 1
                  - GroupId: "group_2"
                    ForbidType: 5

components:
  schemas:
    FetchForbidGroupListRequest:
      type: object
      required: [FromUserId, StartFlag]
      properties:
        FromUserId:
          type: string
          description: User ID of the query operator (who has logged in to the ZIM service by calling the login method on the client, or has completed registration by calling the [server-side API](/zim-server/user/batch-register-users)).
          maxLength: 32
          example: "userId"
        StartFlag:
          type: number
          description: |
            Pagination flag.
            <ul><li>Fill in 0 for the first time;</li><li>Then fill in the NextFlag value returned last time.</li></ul>
            When the returned NextFlag is 0, it means the group list has been fully retrieved.
          example: 0
    FetchForbidGroupListResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            The following only lists the return codes related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            <table>
            <thead><tr><th>Return code</th><th>Description</th><th>Suggested Solution</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>Input parameter error.</td><td>Please check the input parameters.</td></tr>
            <tr><td>660000003</td><td>Logic processing error.</td><td>Please retry or contact ZEGOCLOUD Technical Support.</td></tr>
            <tr><td>660000011</td><td>Number of users exceeds the limit.</td><td>Please check the input user list.</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Description of the operation result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        FetchEnd:
          type: number
          description:
            Whether the retrieval is complete:
            - 0: No.
            - 1: Yes.
          example: 1
        NextFlag:
          type: number
          description: |
            - When FetchEnd is 0, it means there are still more groups to retrieve. You can use this as the StartFlag for the next API call.
            - When FetchEnd is 1, it means the list has been fully retrieved. Please ignore this field at this time.
          example: 100000
        GroupList:
          type: array
          description: List of muted groups.
          items:
            type: object
            properties:
              GroupId:
                type: string
                description: Group ID.
                example: "group_1"
              ForbidType:
                type: number
                description: |
                  Mute type:
                  - 1: All-member mute
                  - 2: Group role mute
                  - 4: User ID mute

                  If multiple mute situations exist simultaneously, ForbidType will add these values together. For example, when both all-member mute (1) and group role mute (2) exist, ForbidType is 3.
                example: 1