openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - group

paths:
  /:
    post:
      tags: [group]
      summary: Modify group attributes
      description: |
        By calling this API, you can set the group attributes of a group.

        <Note title="QPS Limit"> 20 times/s</Note>
      operationId: modify-group-attributes
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=ModifyGroupAttribute
          required: true
          schema:
            type: string
            enum: [ModifyGroupAttribute]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModifyGroupAttributeRequest'
            example:
              GroupId: "room123"
              FromUserId: "fromUserId"
              Action: 0
              Attributes:
                - Key: "attribute1"
                  Value: "value1"
                - Key: "attribute2"
                  Value: ""
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModifyGroupAttributeResponse'
              example:
                Code: 0
                Message: success
                RequestId: "req-123456789"
                FailKeys:
                  - Reason: "key db-non-existent"
                    Key: "attr1"
                  - Reason: "key db-non-existent"
                    Key: "attr2"
                Attributes:
                  Attributes:
                    - Key: "attribute1"
                      Value: "value1"
                    - Key: "attribute2"
                      Value: "value2"

components:
  schemas:
    ModifyGroupAttributeRequest:
      type: object
      required: [Action, FromUserId, GroupId, Attributes]
      properties:
        Action:
          type: number
          description: |
            Modification behavior for this request.
            - 0 (default): Update group attributes.
            - 1: Delete group attributes.
          example: 0
        FromUserId:
          type: string
          description: Operator ID, must be in registered status.
          example: "fromUserId"
        GroupId:
          type: string
          description: Group ID.
          example: "room123"
        Attributes:
          type: array
          description: Updated group attribute information.
          items:
            type: object
            required: [Key]
            properties:
              Key:
                type: string
                description: |
                  Group attribute key. When modifying group attributes, if the group attribute key already exists, the group attribute will be updated; if the group attribute key does not exist, the group attribute will be created.
                example: "attribute1"
              Value:
                type: string
                description: |
                  Group attribute value. This parameter is required when Action is 0; it is not required when Action is 1.
                example: "value1"
    ModifyGroupAttributeResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return status code (0 indicates success).

            The following only lists the return codes related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            <table>
            <thead><tr><th>Return code</th><th>Description</th><th>Suggested Solution</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>Parameter error.</td><td>Please check and enter the correct parameters.</td></tr>
            <tr><td>660300006</td><td>The API call frequency exceeds the group/room limit.</td><td>Please try again later.</td></tr>
            <tr><td>660500002</td><td>FromUserId is not registered.</td><td>Please register FromUserId first.</td></tr>
            <tr><td>660600001</td><td>Group does not exist.</td><td>Please confirm if the input GroupId is correct, or create a group.</td></tr>
            <tr><td>660600009</td><td>Failed to obtain group-related information.</td><td>Please confirm if the GroupID is correct first. If the GroupID is correct, please contact ZEGOCLOUD Technical Support.</td></tr>
            <tr><td>660600028</td><td>Failed to modify group data.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
            <tr><td>660300019</td><td>The total length of the value of the set group attributes exceeds the limit.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Return status information.
          example: "success"
        RequestId:
          type: string
          description: Unique request identifier.
          example: "req-123456789"
        FailKeys:
          type: array
          description: List of keys that failed to update or delete.
          items:
            type: object
            properties:
              Reason:
                type: string
                description: Reason for failure.
                example: "key db-non-existent"
              Key:
                type: string
                description: Key value that failed to update or delete.
                example: "attr1"
        Attributes:
          type: object
          description: List of group attributes that were successfully updated or deleted.
          properties:
            Attributes:
              type: array
              items:
                type: object
                properties:
                  Key:
                    type: string
                    description: Group attribute key.
                    example: "attribute1"
                  Value:
                    type: string
                    description: Group attribute value.
                    example: "value1"

