openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - group

paths:
  /:
    post:
      tags: [group]
      summary: Query group member list
      description: |
        Get the user list in a group based on the group ID.

        <Note title="Note">The group ID can be obtained through [Query the group list in the App](/zim-server/group/query-group-list-in-the-app).</Note>

        <Note title="QPS Limit"> 20 times/s</Note>
      operationId: query-group-member-list
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=QueryGroupMemberList
          required: true
          schema:
            type: string
            enum: [QueryGroupMemberList]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryGroupMemberListRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryGroupMemberListResponse'
              example:
                Code: 0
                Message: success
                RequestId: "343649807833778782"
                TotalCount: 1680
                Next: 168
                MemberList:
                  - UserId: "u1"
                    UserName: "userName1"
                    UserNickName: "userNickName1"
                  - UserId: "u2"
                    UserName: "userName2"
                    UserNickName: "userNickName2"

components:
  schemas:
    QueryGroupMemberListRequest:
      type: object
      required: [GroupId]
      properties:
        GroupId:
          type: string
          description: Group ID. Only supports numbers, English characters, and '!','#','$','%','&','(',')','+',' -',':',';','<','=','.','>','?','@','[',']','^','_','{','}','|','~'.
          maxLength: 32
          example: "groupA"
        Limit:
          type: number
          description: |
            Number of members to retrieve at once, with a value range of [0, 1000], meaning this API can return a maximum of 1,000 members per call.

            When the number of members in the group exceeds the Limit, you need to call this API multiple times <b>and the Limit must remain consistent</b>.

            If empty or greater than 1,000, the default value is 1,000.
          minimum: 0
          maximum: 1000
          example: 1000
        Next:
          type: number
          description: |
            Pagination flag. Fill in 0 for the first time, and then fill in the Next value returned last time.

            For example, if there are 2,500 members in the group, when calling this API to query the group member list:

            - First call: Set Limit to 1,000 and Next to 0 to query members 1 to 1,000; the Next value in the returned result is 1.
            - Second call: Set Limit to 1,000 and Next to 1 to query members 1,001 to 2,000; the Next value in the returned result is 2.
            - Third call: Set Limit to 1,000 and Next to 2 to query members 2,001 to 2,500; the query is complete, and the Next value in the returned result is 0.
          example: 0
    QueryGroupMemberListResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            The following only lists the return codes related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            <table>
            <thead><tr><th>Return code</th><th>Description</th><th>Suggested Solution</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>Parameter error.</td><td>Please refer to Request and input the correct parameters.</td></tr>
            <tr><td>660600001</td><td>Group does not exist.</td><td>Please confirm if the GroupId is correct.</td></tr>
            <tr><td>660600003</td><td>Error querying group member list.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
            <tr><td>660600004</td><td>Call frequency exceeds the limit.</td><td>The call frequency is 20 times/s, please do not exceed the limit.</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Description of the request result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        TotalCount:
          type: number
          description: Total number of group members when the server starts the query.
          example: 1680
        Next:
          type: number
          description: |
            Pagination flag. A non-zero value indicates that the list retrieval is not complete.
            >**Note**
            >
            > Apart from the above description, this field has no association with the list information. Please do not base any other logic on this field.
          example: 168
        MemberList:
          type: array
          description: Collection of group member information.
          items:
            type: object
            properties:
              UserId:
                type: string
                description: Group member ID.
                example: "u1"
              UserName:
                type: string
                description: Group member name.
                example: "userName1"
              UserNickName:
                type: string
                description: User's nickname in the group.
                example: "userNickName1"