openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - group

paths:
  /:
    post:
      tags: [group]
      summary: Remove group member
      description: |
        Remove users from a group by specifying user IDs.

        <Note title="Note">
        - User IDs in the group can be obtained through [Query group member list](/zim-server/group/query-group-member-list).
        - If the removed user is the group owner, the first user in the group list will automatically become the new group owner.
        </Note>

        After successfully removing users, all group members (including the group owner and the removed members) will receive group member status change notifications through the ZIM SDK callback interface:

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|--------|---------|
        | [groupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-group-member-state-changed-event-user-list-operated-info-group-id) | [onGroupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-group-member-state-changed) | [groupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-group-member-state-changed-event-user-list-operated-info-group-id) | [onGroupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-group-member-state-changed) |

        | Web-25% | Mini Program-25% | Flutter-25% | React Native-25% |
        |---------|-----|---------|---------|
        | [groupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#group-member-state-changed) | [groupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#group-member-state-changed) | [onGroupMemberStateChanged](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onGroupMemberStateChanged.html) | [groupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#group-member-state-changed) |

        | Unity3D-25% | uni-app \| uni-app x-25% | HarmonyOS-25% |
        |---------|---------|---------|
        | [OnGroupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-group-member-state-changed) | [groupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#group-member-state-changed) | [groupMemberStateChanged](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#group-member-state-changed) |

        <Note title="Note">The users corresponding to the parameters `FromUserId` and `UserId` have logged in to the ZIM service by calling the `login` method on the client, or have completed registration by calling the [server-side API](/zim-server/user/batch-register-users).</Note>

        <Note title="Note">The parameters FromUserId, GroupId, UserId[], and CustomReason only support numbers, English characters, and `'!','#','$','%','&','(',')','+','\'',':',';','<','=','.','>','?',
        '@','[',']','^','_','{','}','|','~'`.</Note>

        <Note title="QPS Limit"> 20 times/s</Note>
      operationId: remove-group-member
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=KickoutGroupUser
          required: true
          schema:
            type: string
            enum: [KickoutGroupUser]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KickoutGroupUserRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KickoutGroupUserResponse'

components:
  schemas:
    KickoutGroupUserRequest:
      type: object
      required: [FromUserId, GroupId, UserId]
      properties:
        FromUserId:
          type: string
          description: Operator user ID.
          maxLength: 32
          example: "zego_user"
        GroupId:
          type: string
          description: Group ID.
          maxLength: 32
          example: "groupA"
        UserId:
          type: array
          description: |
            List of user IDs to be removed. Maximum support for 50 user IDs.

            Example: "UserId": ["usera","userb"].
          maxItems: 50
          items:
            type: string
            maxLength: 32
            example: "user1"
          example: ["userA"]
        CustomReason:
          type: string
          description: Reason for removal, maximum 32 bytes.
          example: "reason"
    KickoutGroupUserResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            The following only lists the Code and SubCode related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            > **Note**
            >
            > When you initiate a request to remove multiple users at the same time:
            > <ul><li>If 1 or more users are successfully removed, Code will return 0. In this case, please refer to the specific information in ErrorList to confirm the operation result.</li>
            > <li>If all users are not successfully removed, Code will return the relevant return code. For details, please refer to <a href="/zim-server/return-codes" target="_blank">Return codes</a>.</li></ul>
            <table>
            <thead><tr><th>Code / SubCode</th><th>Description</th><th>Suggested Solution</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>Parameter error.</td><td>Please refer to Request and input the correct parameters.</td></tr>
            <tr><td>660000011</td><td>Number of users to be removed exceeds the limit.</td><td>The number should not exceed 50.</td></tr>
            <tr><td>660600001</td><td>Group does not exist.</td><td>Please confirm if the GroupId is correct.</td></tr>
            <tr><td>660600005</td><td>Call frequency exceeds the limit.</td><td>The call frequency is 20 times/s, please do not exceed the limit.</td></tr>
            <tr><td>660600008</td><td>User to be removed is not in the group.</td><td>The user has left the group, no action needed.</td></tr>
            <tr><td>660600009</td><td>Failed to obtain group-related information.</td><td>Please confirm if the GroupID is correct; if correct, please contact technical support.</td></tr>
            </tbody>
            </table>
        Message:
          type: string
          description: Description of the request result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        ErrorList:
          type: array
          description: |
            Failure list.
            <ul>
            <li>When Code is 0:</li>
            <li>If ErrorList is empty, all specified users were removed successfully.</li>
            <li>If ErrorList is not empty, it means some specified users failed to be removed. Please refer to SubCode for handling.</li>
            <li>When Code is not 0:</li>
            <li>If ErrorList is empty, it indicates parameter error, API frequency limit, or system error.</li>
            <li>If ErrorList is not empty, it means all specified users failed to be removed.</li>
            </ul>
          items:
            type: object
            properties:
              UserId:
                type: string
                description: User ID that failed to be removed.
                example: "u2"
              SubCode:
                type: number
                description: |
                  Error code for removal failure. For the complete return codes, please refer to the Code description or [Return codes](/zim-server/return-codes).
                example: 660000012