openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - group

paths:
  /:
    get:
      tags: [group]
      summary: Transfer the group ownership
      description: |
        By calling this API, you can transfer the group owner identity to other members in the group.

        After successful transfer, group members will receive relevant notifications through the following ZIM SDK callback interfaces:
        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|--------|---------|
        | [groupMemberInfoUpdated](https://www.zegocloud.com/docs/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-group-member-info-updated-operated-info-group-id) | [onGroupMemberInfoUpdated](https://www.zegocloud.com/docs/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-group-member-info-updated) | [groupMemberInfoUpdated](https://www.zegocloud.com/docs/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-group-member-info-updated-operated-info-group-id) | [onGroupMemberInfoUpdated](https://www.zegocloud.com/docs/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-group-member-info-updated) |

        | Web-25% | Mini Program-25% | Flutter-25% | React Native-25% |
        |---------|-----|---------|---------|
        | [groupMemberInfoUpdated](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#group-member-info-updated) | [groupMemberInfoUpdated](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#group-member-info-updated) | [onGroupMemberInfoUpdated](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onGroupMemberInfoUpdated.html) | [groupMemberInfoUpdated](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#group-member-info-updated) |


        | Unity3D-25% | uni-app \| uni-app x-25% | HarmonyOS-25% |
        |---------|---------|---------|
        | [OnGroupMemberInfoUpdated](https://www.zegocloud.com/docs/article/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-group-member-info-updated) | [groupMemberInfoUpdated](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#group-member-info-updated) | [groupMemberInfoUpdated](https://www.zegocloud.com/docs/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#group-member-info-updated) |

        <Note title="Note">
        The parameters FromUserId, GroupId, and NewOwner only support numbers, English characters, and `'!','#','$','%','&','(',')','+','\'',':',';','<','=','.','>','?'
        ,'@','[',']','^','_','{','}','|','~'`.
        </Note>
        <Note title="QPS Limit"> 1 time/s, group-level limit. If you need to adjust this limit, please contact ZEGOCLOUD Technical Support.</Note>
      operationId: transfer-the-group-ownership
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=TransferGroupOwner
          required: true
          schema:
            type: string
            enum: [TransferGroupOwner]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - name: FromUserId
          in: query
          required: true
          description: Operator user ID (who has logged in to the ZIM service by calling the login method on the client, or has completed registration by calling the [server-side API](/zim-server/user/batch-register-users)).
          schema:
            type: string
            maxLength: 32
            example: "current_owner"
        - name: GroupId
          in: query
          required: true
          description: Group ID.
          schema:
            type: string
            maxLength: 32
            example: "group123"
        - name: NewOwner
          in: query
          required: true
          description: New group owner (user receiving the transfer) ID, must be a user in the group.
          schema:
            type: string
            maxLength: 32
            example: "new_owner"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'

components:
  schemas:
    CommonResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            The following only lists the return codes related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            <table>
            <thead><tr><th>Return code</th><th>Description</th><th>Suggested Solution</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>Parameter error.</td><td>Please check the request parameters.</td></tr>
            <tr><td>660300006</td><td>Call frequency limit exceeded.</td><td>Please try again later.</td></tr>
            <tr><td>660500002</td><td>Operator user is not registered.</td><td>Please register the user first.</td></tr>
            <tr><td>660600001</td><td>Group does not exist.</td><td>Please check if the GroupID is correct.</td></tr>
            <tr><td>660600024</td><td>User receiving the transfer is not in the group.</td><td>Please add the user to the group.</td></tr>
            </tbody>
            </table>
        Message:
          type: string
          description: Description of the operation result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
