openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - conversation

paths:
  /:
    post:
      tags: [conversation]
      summary: 设置会话消息免打扰
      description: |
        调用过此接口，可批量设置单聊或群聊会话的消息免打扰状态。设置为免打扰后，ZIM SDK 将不会向用户推送相关会话的消息通知，同时用户的“消息未读总数”也不会增加。

        用户默认最多可对 500 个单聊会话设置为免打扰。如需上调，请联系 ZEGO 技术支持，最多可为 1000。

        群聊会话的免打扰上限是各用户加入群组的数量上限。

        客户端将通过 ZIM SDK 的回调接口，接收会话的消息免打扰状态变化。

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|-------|---------|
        | [conversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-group-member-info-updated-operated-info-group-id) | [onConversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-conversation-changed) | [conversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-group-member-info-updated-operated-info-group-id) | [onConversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-conversation-changed) |

        | Web-25% | 小程序-25% | Flutter-25% | React Native-25% |
        |-----|--------|---------|--------------|
        | [conversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#conversation-changed) | [conversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#conversation-changed) | [onConversationChanged](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onConversationChanged.html) | [conversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#conversation-changed) |

        | Unity3D-25% | uni-app \| uni-app x-25% | HarmonyOS-25%  |
        |---------|---------|---------|
        | [OnConversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-conversation-changed) | [conversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#conversation-changed) | [conversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#conversation-changed) |

        <Note title="说明">参数 FromUserId 仅支持数字，英文字符和 \{'!'，'#'，'$'，'%'，'&'，'('，')'，'+'，'-'，':'，';'，'\<'，'='，'.'，'\>'，'?'，'@'，'['，']'，'^'，'_'，' '，'\{'，'\}'，'|'，'~'\}。</Note>

        <Note title="说明">调用频率限制：20 次/秒。</Note>
      operationId: mute-notifications-for-conversations
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=SilenceConvNotification
          required: true
          schema:
            type: string
            enum: [SilenceConvNotification]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SilenceConvNotificationRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SilenceConvNotificationResponse'

components:
  schemas:
    SilenceConvNotificationRequest:
      type: object
      required: [FromUserId, ConvType, ConvIds, Enable]
      properties:
        FromUserId:
          type: string
          description: |
            请求设置该 UserID（已在客户端调用 login 方法登录 ZIM 服务，或已调用 [服务端 API](/zim-server/user/batch-register-users) 完成注册）的会话消息免打扰状态。
          maxLength: 32
          example: "userA"
        ConvType:
          type: number
          description: |
            会话类型：
            - 0：单聊会话。
            - 2：群聊会话。
          enum: [0, 2]
          example: 0
        ConvIds:
          type: array
          description: |
            待设置免打扰状态的会话 ID 列表，长度不超过 10。
            - 单聊会话：会话 ID 为用户 ID。
            - 群聊会话：会话 ID 为群组 ID。

            > 注意
            >
            > 此列表中的会话类型需保持一致，否则会导致接口调用失败。
          maxItems: 10
          items:
            type: string
            maxLength: 32
            example: "ConvId1"
          example: ["ConvId1", "ConvId2"]
        Enable:
          type: boolean
          description: |
            是否免打扰：
            - true：开启免打扰。
            - false：取消免打扰。
          example: true
    SilenceConvNotificationResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            返回码。

            以下仅列出了接口业务逻辑相关的 Code 和 SubCode ，完整返回码请参考 [全局返回码](/zim-server/return-codes)。
            > **说明**
            >
            > 当您发起请求修改多个会话的免打扰状态时：
            > <ul><li>只需成功修改 1 个或以上会话的状态，Code 都会返回 0，表示成功。此时请参考 ErrorList 中的具体信息，了解会话修改状态失败详情。</li>
            > <li>如果所有会话的状态都修改失败，Code 会返回相关返回码，具体请参考 <a href="/zim-server/return-codes" target="_blank">全局返回码</a>。</li></ul>
            <table>
            <thead><tr><th>Code / SubCode</th><th>说明</th><th>处理建议</th></tr></thead>
            <tbody>
            <tr><td>660000001</td><td>业务类通用错误。</td><td>请重试，或联系 ZEGO 技术支持。</td></tr>
            <tr><td>660000002</td><td>输入参数错误。</td><td>请检查输入的参数。</td></tr>
            <tr><td>660300005</td><td>调用接口的频率超出了 AppID 级别限制。</td><td>请稍后再试。</td></tr>
            <tr><td>660500002</td><td>FromUserId 未注册。</td><td>请先注册 FromUserId。</td></tr>
            <tr><td>660600001</td><td>群组不存在。</td><td>请确认输入的 GroupId 是否正确。</td></tr>
            <tr><td>660600009</td><td>获取群相关信息失败。</td><td>请先确认 GroupID 是否正确。如果正确，请联系 ZEGO 技术支持。</td></tr>
            <tr><td>660600024</td><td>FromUserId 不在目标群组中。</td><td>请先加入该群组。</td></tr>
            <tr><td>660700015</td><td><ul><li>如果此错误码是 code，表示所有单聊会话的对端用户都未注册。</li><li>如果此错误码是 subCode，表示 ConvID 对应的单聊会话对端用户未注册。</li></ul></td><td>请先注册对端用户。</td></tr>
            <tr><td>660800030</td><td>用户的免打扰列表超过长度限制，默认 500，可联系技术支持配置，最大可为 1000。</td><td>请联系 ZEGO 技术支持。</td></tr>
            <tr><td>660800051</td><td>会话已为免打扰，无法再次设置为免打扰。</td><td>无需处理。</td></tr>
            <tr><td>660800052</td><td>会话已被取消免打扰，无法再次取消。</td><td>无需处理。</td></tr>
            </tbody>
            </table>
        Message:
          type: string
          description: 请求结果的说明信息。
          example: "success"
        RequestId:
          type: string
          description: 请求 ID。
          example: "343649807833778782"
        ErrorList:
          type: array
          description: |
            失败列表。
            - Code 为 0：
              - ErrorList 为空，全部会话的免打扰状态修改成功。
              - ErrorList 不为空，表示部分会话的免打扰状态修改失败。请参考 SubCode、SubMessage 处理。
            - Code 不为 0：
              - ErrorList 为空，表示参数错误、接口频率限制、系统错误。
              - ErrorList 不为空，表示全部会话免打扰状态都修改失败。
          items:
            type: object
            properties:
              ConvId:
                type: string
                description: |
                  免打扰状态修改失败的会话 ID。
                  - 单聊会话：会话 ID 为用户 ID。
                  - 群聊会话：会话 ID 为群组 ID。
                example: "ConvId1"
              SubCode:
                type: number
                description: |
                  免打扰状态修改失败的具体错误码，完整返回码请参考 Code 说明或者 [全局返回码](/zim-server/return-codes)。
                example: 660800030
              SubMessage:
                type: string
                description: 免打扰状态修改失败的具体错误描述。
                example: "input params error"
          example:
            - ConvId: "ConvId1"
              SubCode: 660800030
              SubMessage: "input params error"
