openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - conversation

paths:
  /:
    post:
      tags: [conversation]
      summary: 置顶会话
      description: |
        调用此接口，可为用户批量置顶或取消置顶至多 20 个会话。如需上调，请联系 ZEGO 技术支持。

        客户端将通过 ZIM SDK 的回调接口，接收会话的置顶状态变化。

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|-------|---------|
        | [conversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-group-member-info-updated-operated-info-group-id) | [onConversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-conversation-changed) | [conversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-group-member-info-updated-operated-info-group-id) | [onConversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-conversation-changed) |

        | Web-25% | 小程序-25% | Flutter-25% | React Native-25% |
        |-----|---------|-------|---------|
        |[conversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#conversation-changed) |[conversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#conversation-changed) | [onConversationChanged](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onConversationChanged.html) | [conversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#conversation-changed) |

        | Unity3D-25% |  uni-app \| uni-app x-25% |HarmonyOS-25% |
        |-----|---------|-------|
        | [OnConversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-conversation-changed) |[conversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#conversation-changed) | [conversationChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#conversation-changed) |

        <Note title="说明">调用频率限制：20 次/秒。</Note>
      operationId: pin-conversations-to-the-top
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=ConvPinned
          required: true
          schema:
            type: string
            enum: [ConvPinned]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConvPinnedRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConvPinnedResponse'

components:
  schemas:
    ConvPinnedRequest:
      type: object
      required: [FromUserId, ConvList, PinnedType]
      properties:
        FromUserId:
          type: string
          description: |
            为此 UserID（已在客户端调用 login 方法登录 ZIM 服务，或已调用 [服务端 API](/zim-server/user/batch-register-users) 完成注册）设置会话的置顶状态。

            > **说明**
            >
            > FromUserId 仅支持数字，英文字符和 "'!'，'#'，'$'，'%'，'&'，'('，')'，'+'，'-'，':'，';'，'<'，'='，'.'，'>'，'?'，'@'，'['，']'，'^'，'_'，' '，'{'，'}'，'|'，'~'"。
          maxLength: 32
          example: "user0"
        ConvList:
          type: array
          description: 会话列表，默认长度限制20。
          maxItems: 20
          items:
            type: object
            required: [ConvId, ConvType]
            properties:
              ConvId:
                type: string
                description: |
                  会话 ID。
                  - 单聊时，conversationID 即是对端用户的 userID（已在客户端调用 login 方法登录 ZIM 服务，或已调用 [服务端 API](/zim-server/user/batch-register-users) 完成注册）。
                  - 群聊时，conversationID 即是群组的 groupID。
                maxLength: 32
                example: "user1"
              ConvType:
                type: number
                description: |
                  会话类型：
                  - 0：单聊会话。
                  - 2：群聊会话。
                enum: [0, 2]
                example: 0
          example:
            - ConvId: "user1"
              ConvType: 0
            - ConvId: "user2"
              ConvType: 0
        PinnedType:
          type: number
          description: |
            置顶操作：
            - 0：取消置顶。
            - 1：设置置顶。
          enum: [0, 1]
          example: 1
    ConvPinnedResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            返回码。

            以下仅列出了接口业务逻辑相关的 Code 和 SubCode ，完整返回码请参考 [全局返回码](/zim-server/return-codes)。
            > **说明**
            >
            > 当您发起请求修改多个会话的置顶状态时：
            > <ul><li>只需成功修改 1 个或以上会话的状态，Code 都会返回 0，表示成功。此时请参考 ErrorList 中的具体信息，了解会话修改状态失败详情。</li>
            > <li>如果所有会话的状态都修改失败，Code 会返回相关返回码，具体请参考 <a href="/zim-server/return-codes" target="_blank">全局返回码</a>。</li></ul>
            <table>
            <thead><tr><th>Code / SubCode</th><th>说明</th><th>处理建议</th></tr></thead>
            <tbody>
            <tr><td>660000001</td><td>业务类通用错误。</td><td>请重试，或联系 ZEGO 技术支持。</td></tr>
            <tr><td>660000002</td><td>输入参数错误。</td><td>请检查输入的参数。</td></tr>
            <tr><td>660300005</td><td>调用接口的频率超出了 AppID 级别限制。</td><td>请稍后再试。</td></tr>
            <tr><td>660500002</td><td>FromUserId 未注册。</td><td>请先注册 FromUserId。</td></tr>
            <tr><td>660800001</td><td>置顶单聊会话时，操作目标会话 ConvID 对应的用户未注册。</td><td>请确认该 ConvId 对应的用户是否已注册：<ul><li>确认已注册，请联系 ZEGO 技术支持排查。</li><li>确认未注册，请注册此用户。</li></ul></td></tr>
            <tr><td>660800048</td><td>置顶列表长度超过限制（100，不可配置）。</td><td>无需处理。</td></tr>
            </tbody>
            </table>
        Message:
          type: string
          description: 请求结果的说明信息。
          example: "success"
        RequestId:
          type: string
          description: 请求 ID。
          example: "343649807833778782"
        ErrorList:
          type: array
          description: |
            失败列表。
            - Code 为 0：
              - ErrorList 为空，全部会话的置顶状态修改成功。
              - ErrorList 不为空，表示部分会话的置顶状态修改失败。请参考 SubCode、SubMessage 处理。
            - Code 不为 0：
              - ErrorList 为空，表示参数错误、接口频率限制、系统错误。
              - ErrorList 不为空，表示全部会话置顶状态都修改失败。
          items:
            type: object
            properties:
              ConvId:
                type: string
                description: 置顶状态修改失败的会话 ID。
                example: "user1"
              ConvType:
                type: number
                description: 会话类型。
                example: 0
              SubCode:
                type: number
                description: |
                  置顶状态修改失败的具体错误码，完整返回码请参考 Code 说明或者 [全局返回码](/zim-server/return-codes)。
                example: 660000002
              SubMessage:
                type: string
                description: 具体错误描述。
                example: "input params error"
          example:
            - ConvId: "user1"
              ConvType: 0
              SubCode: 660000002
              SubMessage: "input params error"
