openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - conversation

paths:
  /:
    post:
      tags: [conversation]
      summary: 查询会话列表
      description: |
        调用此接口，分页拉取指定用户的全量会话列表，最多返回 1000 个最新会话（单聊与群聊）。

        <Note title="说明">即便用户被踢出会话，本接口返回结果仍包含该会话；但是如果会话解散，则无法通过本接口获取该会话相关信息。</Note>

        <Note title="说明">调用频率限制：20 次/秒。</Note>
      operationId: query-conversation-list
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=QueryConversationList
          required: true
          schema:
            type: string
            enum: [QueryConversationList]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryConversationListRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryConversationListResponse'

components:
  schemas:
    QueryConversationListRequest:
      type: object
      required: [FromUserId]
      properties:
        FromUserId:
          type: string
          description: |
            查询此 UserID（已在客户端调用 login 方法登录 ZIM 服务，或已调用 [服务端 API](/zim-server/user/batch-register-users) 完成注册）的会话列表。

            > **说明**
            >
            > FromUserId 仅支持数字，英文字符和 {"'!'，'#'，'$'，'%'，'&'，'('，')'，'+'，''，':'，';'，'<'，'='，'.'，'>'，'?'，'@'，'['，']'，'^'，'_'，' '，'{'，'}'，'|'，'~'"}。
          maxLength: 32
          example: "u1"
        Limit:
          type: number
          description: |
            单次获取会话的数量，默认为 100，取值范围为 (0, 500]。
            - 当值 ≤ 0 时，修正为 100。
            - 当值 > 500，修正为 500。
          minimum: 1
          maximum: 500
          default: 100
          example: 10
        Next:
          type: number
          description: |
            分页拉取标志，第一次填 0 ，之后填上一次返回的 Next 值。当返回的 Next 为 0 时，代表好友列表获取完毕。

            例如，FromUserId 有 250 个会话，调用本接口查询时：
            - 第一次调用本接口，Limit 填 100，Next 传 0，查询第 1 ～100 个会话；返回结果中的 Next 值为 num1。
            - 第二次调用本接口，Limit 填 100，Next 填 num1，查询第 101 ～ 200 个会话；返回结果中 Next 值为 num2。
            - 第三次调用本接口，Limit 填 100，Next 填 num2，查询第 201 ～ 250 个会话；查询完毕，返回结果中的 Next 为 0。
          example: 0
    QueryConversationListResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            返回码。
            <table>
            <thead><tr><th>返回码</th><th>说明</th><th>处理建议</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>输入参数错误。</td><td>请检查输入的参数。</td></tr>
            <tr><td>660300005</td><td>调用接口的频率超出了 AppID 级别限制。</td><td>请稍后再试。</td></tr>
            <tr><td>660500002</td><td>FromUserId 未注册。</td><td>请检查 FromUserId 是否正确。</td></tr>
            <tr><td>660800053</td><td>查询会话列表失败。</td><td>请联系 ZEGO 技术支持。</td></tr>
            </tbody>
            </table>
        Message:
          type: string
          description: 请求结果的说明信息。
          example: "success"
        RequestId:
          type: string
          description: 请求 ID。
          example: "343649807833778782"
        TotalCount:
          type: number
          description: 当前的会话总数。
          example: 500
        Next:
          type: number
          description: |
            分页拉取标志。
            - 非 0：表示还有会话信息未返回，需要将该字段设置到请求参数 Next 中拉取更多会话信息。
            - 为 0：表示已经返回完整会话列表。

            > **说明**
            >
            > 除上述说明之外，此字段与列表信息无任何关联，请勿基于此做任何其他逻辑。
          example: 1000
        List:
          type: array
          description: 会话列表。按 UpdateTime 升序返回结果。
          items:
            type: object
            properties:
              ConvId:
                type: string
                description: |
                  会话 ID。
                  - 单聊会话：会话 ID 为对端用户的 ID。
                  - 群聊会话：会话 ID 为群组 ID。
                example: "conv1"
              ConvType:
                type: number
                description: |
                  会话类型。
                  - 0 或没有返回此字段：单聊会话。
                  - 2：群聊会话。
                example: 2
              UpdateTime:
                type: number
                description: 会话最后修改时间，毫秒时间戳。
                example: 1708254395000
          example:
            - ConvId: "conv1"
              ConvType: 2
              UpdateTime: 1708254395000
            - ConvId: "conv2"
              ConvType: 0
              UpdateTime: 1708254395000
            - ConvId: "conv3"
              UpdateTime: 1708254395000
