openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: stream-mixing

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - stream-mixing
      summary: GetMixTaskInfo
      description: |
        Query related information based on the specified stream mixing task's taskid.

        <Note title="Call frequency limit">100 times/second</Note>
      operationId: get-mix-task-info
      parameters:
        - name: Action
          in: query
          description: |
            > Interface prototype parameters
            >
            > https://rtc-api.zego.im?Action=GetMixTaskInfo
          required: true
          schema:
            type: string
            enum: [GetMixTaskInfo]
          style: form
          explode: true
        # 公共参数（Query）
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        # 业务参数
        - name: TaskId
          in: query
          description: Task ID, unique identifier of the stream mixing task。
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMixTaskInfoResponse'

components:
  schemas:
    GetMixTaskInfoResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: |
            The following only lists the return codes related to interface business logic. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).

            <table>
            <thead>
              <tr><th>Return Code</th><th>Description</th><th>Handling Suggestion</th></tr>
            </thead>
            <tbody>
              <tr><td>0</td><td>Request successful.</td><td>-</td></tr>
              <tr><td>110200001</td><td>Failed.</td><td>It is recommended to try again. Generally caused by network errors.</td></tr>
              <tr><td>110200004</td><td>Failed to parse input parameters.</td><td>Please check if the stream mixing parameters are correct.</td></tr>
              <tr><td>110200194</td><td>Stream mixing request overload.</td><td>The request is too frequent, please try again later.</td></tr>
              <tr><td>110209001</td><td>Stream mixing task does not exist.</td><td>Please check if the stream mixing task is actually in progress. If the stream mixing task is actually in progress, please contact ZEGOCLOUD Technical Support.</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Operation result description。
          example: "success"
        RequestId:
          type: string
          description: Request ID。
          example: "1864314306034131629"
        Data:
          type: object
          description: Response data。
          properties:
            TaskInfo:
              type: object
              description: Stream mixing task information。
              properties:
                TaskId:
                  type: string
                  description: Stream mixing task ID。
                  example: "task_test_123"
                MixDuration:
                  type: integer
                  format: int32
                  description: Stream mixing task duration, unit seconds。
                  example: 13

