openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: stream-mixing

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    post:
      tags:
        - stream-mixing
      summary: StartCloudTranscode
      description: |
        ## Overview

        This document describes how to use the server-side API to transcode a specified single input Stream into video Streams with different resolutions, bitrates, and frame rates.

        For single-stream transcoding triggered by the "client" based on transcoding templates, please refer to [Single-Stream Transcoding](/real-time-video-android-java/live-streaming/single-stream-transcoding); for related "server" callbacks, please refer to [Single-Stream Transcoding Started Callback](/real-time-video-server/callback/transcoding/on-demand-transcoding-started) and [Single-Stream Transcoding Stopped Callback](/real-time-video-server/callback/transcoding/on-demand-transcoding-stopped).


        ## Prerequisites

        Before implementing single-stream transcoding, ensure that:

        - You have created a project in the [ZEGOCLOUD Console](https://console.zego.im) and applied for a valid AppId and ServerSecret. For details, please refer to [Console - Project Information](/console/project-info).
        - You have enabled the "Stream Mixing" service permission in the [ZEGOCLOUD Console](https://console.zego.im). For details, please refer to [Console - Service Configuration - Stream Mixing](/console/service-configuration/enable-stream-mixing-service), or contact ZEGOCLOUD technical support to enable it.

        <Note title="Rate Limit">100 requests/second</Note>

        <h4 id="template">Preset output templates for single-stream transcoding</h4>

        The parameter configurations for preset templates (TemplateId values 0, 1, 2, 3) are as follows:

        <table>

        <tbody><tr>
        <th>Template ID</th>
        <th>Resolution (Short Edge)</th>
        <th>Bitrate (kbps)</th>
        <th>Other Configuration</th>
        </tr>
        <tr>
        <td>0 (360P)</td>
        <td>360</td>
        <td>600</td>
        <td rowspan="4"><ul><li>Frame rate: Maintained at the original input Stream frame rate.</li><li>GOP: Default is 2.</li><li>Video encoding format: Default is H.264.</li><li>Audio encoding format: Default is AAC-LC.</li><li>Preset templates output resolution adaptively based on the short edge, with the long edge scaled proportionally according to the short edge of the transcoding template.</li></ul></td>
        </tr>
        <tr>
        <td>1 (540P)</td>
        <td>540</td>
        <td>1000</td>
        </tr>
        <tr>
        <td>2 (720P)</td>
        <td>720</td>
        <td>1500</td>
        </tr>
        <tr>
        <td>3 (1080P)</td>
        <td>1080</td>
        <td>2000</td>
        </tr>
        </tbody></table>

        ***Only some parameters in this interface support dynamic updates after starting Stream Mixing. Parameters not marked do not support dynamic updates. For details, please refer to the parameter descriptions in the table below.***
      operationId: start-cloud-transcode
      parameters:
        - name: Action
          in: query
          description: |
            > Interface prototype parameters
            >
            > https://rtc-api.zego.im?Action=StartCloudTranscode
          required: true
          schema:
            type: string
            enum: [StartCloudTranscode]
          style: form
          explode: true
        # Common parameters (Query)
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartCloudTranscodeRequest'
            example:
              {
                  "TaskId": "2213699902971205739",
                  "UserId": "456",
                  "TranscodeInput": {
                      "StreamId": "stream1"
                  },
                  "TranscodeOutput": [
                      {
                          "StreamId": "stream3",
                          "TemplateId": 3
                      }
                  ]
              }
      responses:
        "200":
          description: Operation succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartCloudTranscodeResponse'

components:
  schemas:
    StartCloudTranscodeRequest:
      type: object
      required: [TaskId, UserId, TranscodeInput, TranscodeOutput]
      properties:
        TaskId:
          type: string
          required: true
          description: |
            Task ID, the unique identifier for the single-stream transcoding task, customized by the developer.

            **Calling the "Start Cloud Transcoding" interface repeatedly with the same TaskId can directly update the transcoding task information.**
          example: "2213699902971205739"
        UserId:
          type: string
          required: true
          description: |
            User ID of the User initiating the transcoding task, customized by the developer. **The User ID for the same TaskId must be consistent, and the User IDs for different TaskId tasks must be different.**

            Through UserId, you can achieve User attribution for transcoding tasks, meaning only this User can update or stop the transcoding task corresponding to the TaskId. This feature requires contacting ZEGOCLOUD technical support to enable.
          example: "456"
        Sequence:
          type: integer
          format: int
          description: Sequence number of the transcoding task, used to ensure ordering. Parameter modifications for the same task need to ensure the sequence number is incremented.
        TranscodeInput:
          type: object
          required: [StreamId, StreamUrl]
          description: Input Stream settings for the transcoding task.
          properties:
            StreamId:
              type: string
              description: |
                Transcoding input Stream ID, which comes from the RTC service. Only supports numbers, English characters, "-", and "_".

                > **Note**
                >
                > Only one of StreamId or StreamUrl is required. If both StreamId and StreamUrl are specified, StreamUrl takes effect.
              example: "stream1"
            StreamUrl:
              type: string
              example: ""
              description: |
                Transcoding input Stream URL, supports RTMP protocol.

                > **Note**
                >
                > Only one of StreamId or StreamUrl is required. If both StreamId and StreamUrl are specified, StreamUrl takes effect.
        TranscodeOutput:
          type: array
          description: Output Stream information for the transcoding task.
          items:
            type: object
            required: [StreamId, StreamUrl, TemplateId]
            properties:
              StreamId:
                type: string
                description: |
                  Output Stream ID.
                  - By default, the transcoding task outputs to RTC or low-latency live streaming products.
                  - You can also contact ZEGOCLOUD technical support to configure the transcoding Stream output to the ZEGOCLOUD-proxied CDN live streaming product, with the scope taking effect for the entire AppId. If a Stream is specified to output to the CDN live streaming product, StreamUrl must be set, and the default transcoding output to ZEGOCLOUD-proxied CDN cannot be configured.

                  > **Note**
                  >
                  > Only one of StreamId or StreamUrl is required. If both StreamId and StreamUrl are specified, StreamUrl takes effect.
                example: "stream3"
              StreamUrl:
                type: string
                example: ""
                description: |
                  Only supports RTMP protocol, indicating transcoding output to the CDN live streaming service. Audiences can pull the transcoded Stream from the CDN live streaming.

                  > **Note**
                  >
                  > Only one of StreamId or StreamUrl is required. If both StreamId and StreamUrl are specified, StreamUrl takes effect.
              TemplateId:
                type: integer
                format: int32
                enum: [0,1,2,3,4]
                description: |
                  Single-stream transcoding output template ID. ZEGOCLOUD provides the following templates:
                  - 0: Output 360P transcoded Stream
                  - 1: Output 540P transcoded Stream
                  - 2: Output 720P transcoded Stream
                  - 3: Output 1080P transcoded Stream
                  - 4: Custom template. When the general template does not meet your requirements, please use the custom template to set output parameters

                  Please click [Preset output templates for single-stream transcoding](#template) to view specific preset template configuration parameters.
                example: 4
              TemplateConfig:
                type: object
                description: Custom template configuration.
                properties:
                  VideoEncId:
                    type: integer
                    format: int
                    enum: [0,1,2]
                    default: 0
                    description: |
                      Video encoding format of the output Stream.

                      - 0: Default value, indicating the output Stream encoding format is consistent with the input Stream encoding format.
                      - 1: H264
                      - 2: H265
                    example: 0
                  Fps:
                    type: integer
                    format: int
                    description: |
                      Video frame rate, must be greater than or equal to 0.

                      - 0: Default value, indicating the output Stream frame rate is consistent with the input Stream frame rate.
                      - Other values: Output frame rate of the transcoded Stream. The maximum frame rate is limited to 20 fps by default. If you need to output a Stream with a higher frame rate, please contact ZEGOCLOUD technical support for configuration.

                      Currently, outputting transcoded Streams with different frame rates is not supported. The frame rate settings for all output Streams must be consistent.
                    example: 15
                  GOP:
                    type: integer
                    format: int
                    default: 2
                    description: |
                      Keyframe interval of the transcoded output Stream, must be greater than 0, default value is 2, unit: seconds.

                      If you need to customize it, please contact ZEGOCLOUD technical support to enable custom support.
                    example: 2
                  ShortEdgeAdaption:
                    type: integer
                    format: int
                    default: 0
                    description: |
                      Whether the output Stream resolution uses the set Width as the short edge and adapts to landscape or portrait orientation.

                      - 0: Default value, output directly according to the set Width and Height.
                      - 1: Use the set Width as the short edge, and adapt to landscape or portrait orientation by scaling proportionally according to the input Stream resolution.
                  Height:
                    type: integer
                    format: int
                    description: |
                      Height, range is [0, 3000], the value must be a multiple of 2.

                      - 0: Default value. When both this parameter and Width are 0, it indicates the output Stream resolution is consistent with the input Stream resolution.
                      - Other values: The height of the transcoded Stream's custom resolution.

                      **🔁Supports real-time updates during transcoding. Call this interface again to dynamically update this parameter.**
                    example: 720
                  Width:
                    type: integer
                    format: int
                    description: |
                      Width, range is [0, 3000], the value must be a multiple of 2.

                      - 0: Default value. When both this parameter and Height are 0, it indicates the output Stream resolution is consistent with the input Stream resolution.
                      - Other values: The width of the transcoded Stream's custom resolution.

                      **🔁Supports real-time updates during transcoding. Call this interface again to dynamically update this parameter.**
                    example: 1280
                  VideoBitrate:
                    type: integer
                    format: int
                    default: 0
                    description: |
                      Video bitrate, must be greater than or equal to 0, unit is bps.

                      - 0: Default value, indicating the output bitrate is consistent with the input Stream bitrate.
                      - Other values: Output bitrate of the transcoded Stream.

                      **🔁Supports real-time updates during transcoding. Call this interface again to dynamically update this parameter.**
                    example: 0
                  LowBitrateHD:
                    type: integer
                    format: int
                    default: 0
                    description: |
                      Whether to enable the "HD Low Bitrate" feature.

                      - 0: Default value, not enabled.
                      - 1: Enabled.

                      Currently, the "HD Low Bitrate" feature requires contacting ZEGOCLOUD technical support to enable permission, and it only takes effect when VideoEncId is set to 2 (H265).
                    example: 0
    StartCloudTranscodeResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: |
            The following only lists some return codes related to the interface's business logic. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).

            <table>
            <thead>
              <tr><th>Return Code</th><th>Description</th><th>Suggested Action</th></tr>
            </thead>
            <tbody>
              <tr><td>110200002</td><td>Input parameter error.</td><td>Please handle according to the Message information.</td></tr>
              <tr><td>110200150</td><td>The input Stream for single-stream transcoding does not exist.</td><td>Please confirm whether the input StreamId or StreamUrl exists.</td></tr>
              <tr><td>110200151</td><td>Single-stream transcoding task failed.</td><td>Please retry, or contact ZEGOCLOUD technical support for assistance.</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Description of the operation result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "8472822294336370476"

