openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: stream-mixing

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    post:
      tags:
        - stream-mixing
      summary: StartAutoMix
      description: |
        This document describes how to call the server-side API to specify a Room and automatically mix all `audio` Streams in the Room. It can be applied to scenarios such as voice chat rooms, chorus, etc.

        In cross-room PK connection scenarios, it supports adding a Stream from another Room to participate in automatic Stream Mixing; or removing a Stream from the current Room to not participate in automatic Stream Mixing. For details, please refer to the `ExtraMixInput` parameter description in the request parameters.

        <Note title="Note">
        * Currently only supports automatic mixing of `audio` Streams.
        * When Streams are added or removed in the Room later, you don't need to do any processing. ZEGOCLOUD server automatically updates Stream Mixing internally.
        </Note>

        For the Stream Mixing function of the "client", please refer to [Stream Mixing - Auto Stream Mixing](/real-time-video-android-java/live-streaming/stream-mixing); for related "server" callbacks, please refer to [Stream Mixing Started Callback](/real-time-video-server/callback/stream-mixing/started) and [Stream Mixing Stopped Callback](/real-time-video-server/callback/stream-mixing/stopped).
        ## Prerequisites

        Before implementing Stream Mixing, please ensure:

        - You have created a project in the [ZEGOCLOUD Console](https://console.zego.im) and applied for a valid AppId and ServerSecret. For details, please refer to [Console - Project Information](/console/project-info).
        - You have self-serviced enabled the "Stream Mixing" service permission in the [ZEGOCLOUD Console](https://console.zego.im). For details, please refer to [Console - Service Configuration - Stream Mixing](/console/service-configuration/enable-stream-mixing-service), or contact ZEGOCLOUD Technical Support to enable it.
        - You have initiated publishing and subscribing Streams in the Room through your own client. For details, please refer to [Implementing Video Call](/real-time-video-android-java/quick-start/implementing-video-call).
        - If you want to automatically create the corresponding Room when it doesn't exist during auto Stream Mixing creation, please contact ZEGOCLOUD Technical Support to enable this feature.
        <Note title="Note">
        In the test environment (see IsTest common parameter description for details), the Stream IDs of `input Streams` and `output Streams`:

        - If it is the original Stream ID entered by the developer, you need to add the "zegotest-AppId-" prefix, otherwise the Stream Mixing will fail (the Stream Mixing server cannot pull the input Stream or pull the mixed output Stream). For example, if the developer enters the Stream ID as "test", in the test environment with AppId "123456789", the Stream ID should be "zegotest-123456789-test".
        - If it is obtained through SDK interfaces or server-side API interfaces, you don't need to add the "zegotest-AppId-" prefix at this time.
        </Note>

        <Note title="Rate Limit">100 requests/second</Note>

        **Only some parameters in this interface support dynamic updates after Stream Mixing starts. Parameters not marked do not support dynamic updates. For details, please refer to the parameter descriptions in the table below.**
      operationId: start-auto-mix
      parameters:
        - name: Action
          in: query
          description: |
            > API Prototype Parameter
            >
            > https://rtc-api.zego.im?Action=StartAutoMix
          required: true
          schema:
            type: string
            enum: [StartAutoMix]
          style: form
          explode: true
        # Common parameters (Query)
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartAutoMixRequest'
            example:
              {
                "TaskId": "2213699902971205739",
                "UserId": "123",
                "RoomId": "room123",
                "MixOutput": [{"StreamId": "stream3"}]
              }
      responses:
        "200":
          description: Operation succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartAutoMixResponse'

components:
  schemas:
    StartAutoMixRequest:
      type: object
      required: [TaskId, UserId, RoomId, MixOutput]
      properties:
        TaskId:
          type: string
          description: |
            Task ID, the unique identifier of the Stream Mixing task.
            - Repeatedly calling the "Start Stream Mixing" interface with the same TaskId can directly update the Stream Mixing task information.
            - When initiating "audio and video" Stream Mixing, if a "pure audio" Stream Mixing task with the corresponding TaskId has been initiated before, you need to stop this task first and then re-initiate the "audio and video" Stream Mixing task.
          example: "2213699902971205739"
        UserId:
          type: string
          description: |
            User ID of the user initiating the Stream Mixing task, customized by the developer.

            **User IDs for the same task need to be consistent, and User IDs for different tasks need to be different.**

            Through UserId, you can implement user attribution of Stream Mixing tasks. That is, only this user can update or stop the Stream Mixing task corresponding to the TaskId. This function needs to be enabled by contacting ZEGOCLOUD Technical Support.
          example: "123"
        RoomId:
          type: string
          description: Room ID.
          example: "room123"
        ExtraMixInput:
          type: array
          description: |

            Additional input Stream list (Streams from other Rooms), supports up to 9 additional input Streams by default.

            <br/>
            **📌Note**
            <br/>
            When enabling automatic Stream Mixing, up to 9 input Streams are supported. That is, after adding or removing (determined by ModifyType value whether to add or delete a Stream) additional input Streams to the Streams in the Room, the total number of Streams cannot exceed 9.
          items:
            type: object
            properties:
              StreamId:
                type: string
                example: "room_other_stream1"
                description: |
                  Stream Mixing input Stream ID, this Stream ID comes from RTC service.

                  Only supports numbers, English characters, and "-", "_".

                  > **Note**
                  >
                  > StreamId and StreamUrl, choose one of the two. If both StreamId and StreamUrl are filled in:
                  > - When ModifyType is 0 (add), StreamUrl takes effect.
                  > - When ModifyType is 1 (remove), StreamId takes effect.
              StreamUrl:
                type: string
                example: ""
                description: |
                  Stream Mixing input Stream URL, supports both RTMP and HTTP-FLV protocols.

                  > **Note**
                  >
                  > StreamId and StreamUrl, choose one of the two. If both StreamId and StreamUrl are filled in:
                  > - When ModifyType is 0 (add), StreamUrl takes effect.
                  > - When ModifyType is 1 (remove), StreamId takes effect.
              ModifyType:
                type: integer
                format: int
                enum: [0,1]
                description: |
                  Type of input Stream list, indicating "add" or "remove" this input Stream in the current Stream Mixing task:
                  - 0: When enabling automatic Stream Mixing, **add** the current Stream to the input Stream list, default value
                  - 1: When enabling automatic Stream Mixing, **remove** the current Stream from the input Stream list. At this time, you only need to fill in StreamId and the value of this parameter
              SoundLevelId:
                type: integer
                format: int
                description: |
                  Sound Level ID. When the parameter SoundLevel (Stream Mixing Sound Level) is set to "1", this parameter is required.
              Volume:
                type: integer
                format: int
                default: 100
                description: Volume, value range [0, 200], default is 100.
        MixOutput:
          type: array
          description: |
            Output Stream information, currently supports up to 3. When the output target is in URL format, currently only RTMP URL format is supported: rtmp://xxxxxxxx, and two identical Stream Mixing output addresses cannot be passed in.
          items:
            type: object
            properties:
              StreamId:
                type: string
                example: "stream3"
                description: |
                  Output Stream ID. By default, it means the Stream Mixing output goes to RTC or low-latency live products. You can also contact ZEGOCLOUD Technical Support to configure Stream Mixing output to ZEGOCLOUD proxy CDN live products. The effective scope is the entire AppId. If you want to control the specified Stream output to CDN live products, you cannot configure Stream Mixing default output to ZEGOCLOUD proxy CDN, and should set StreamUrl as needed.

                  **StreamId and StreamUrl, choose one of the two. If StreamId is filled in, StreamUrl will not take effect.**
              StreamUrl:
                type: string
                example: ""
                description: |
                  Only supports RTMP protocol, indicating Stream Mixing output to CDN live service. Audiences can pull Stream Mixing from CDN live.

                  **StreamId and StreamUrl, choose one of the two. If StreamUrl is filled in, StreamId will not take effect.**
              AudioCodec:
                type: integer
                format: int
                enum: [0,1,2,3]
                example: 0
                description: |
                  Audio codec and sample rate. To modify the sample rate, please contact ZEGOCLOUD Technical Support to configure:
                  - 0: HE-AAC, sample rate: 44100 kHz, default value
                  - 1: AAC-LC, sample rate: 44100 kHz
                  - 2: MP3, sample rate: 44100 kHz
                  - 3: OPUS, sample rate: 48000 kHz
              AudioBitrate:
                type: integer
                format: int
                description: Stream Mixing output audio bitrate. If not filled, the default value is 48000, unit is bps.
              SoundChannel:
                type: integer
                format: int
                enum: [1,2]
                description: |
                  Output audio channel count, higher priority than global parameters:
                  - 1: Mono, default value
                  - 2: Stereo
          example:
            - StreamId: "stream3"
        Sequence:
          type: integer
          format: int
          description: |
            Sequence number of the Stream Mixing request, used to ensure timing. Parameter modifications for the same task need to ensure the sequence number increases. For example: "Sequence": 1.

            **If the timing control of the Stream Mixing task is enabled (if needed, please contact ZEGOCLOUD Technical Support to enable), this parameter is required.**
        UserData:
          type: string
          example: "base64_encoded_data"
          description: |
            Custom user data. When using, you need to base64 encode the content of this parameter. Length limit is 4000 bytes, recommended not to exceed 850 bytes.

            Custom user data will be transmitted to the subscribing side as SEI information. The subscribing side can obtain the data by listening to the client's <a href="https://doc-zh.zego.im/article/api?doc=Express_Video_SDK_API~objective-c_ios~protocol~ZegoEventHandler#on-player-sync-recv-sei-stream-id" target="_blank">onPlayerSyncRecvSEI</a> callback.

            **🔁Call this interface again to dynamically update this parameter.**
        SoundLevel:
          type: integer
          format: int
          enum: [0,1]
          example: 0
          description: |
            Stream Mixing Sound Level, refers to the volume size of Stream Mixing. Supports real-time updates during Stream Mixing:
            - 0: Disabled, default value
            - 1: Enabled. After enabling, the client can receive notifications of automatic Stream Mixing sound level updates through the <a href="https://doc-zh.zego.im/article/api?doc=Express_Video_SDK_API~objective-c_ios~protocol~ZegoEventHandler#on-auto-mixer-sound-level-update" target="_blank">onAutoMixerSoundLevelUpdate</a> callback

            **🔁Call this interface again to dynamically update this parameter.**
        ByPass:
          type: integer
          format: int
          default: 0
          enum: [0,1]
          description: |
            Single Stream passthrough switch, that is, whether to re-encode according to output parameters when there is only one input Stream. This function needs to be enabled by contacting ZEGOCLOUD Technical Support:
            - 0: Disabled, default value
            - 1: Enabled
        SoundChannel:
          type: integer
          format: int
          default: 1
          enum: [1,2]
          description: |
            Output audio channel count, this configuration is used when no output Stream is specified:
            - 1: Mono, default value
            - 2: Stereo
        AlignmentType:
          type: integer
          format: int
          enum: [0,1,2]
          description: |
            Control whether the real-time audio and video Streams being played need to be mixed after precise alignment according to NTP (Network Time). **This parameter is mainly applied in KTV scenarios and will increase certain Stream Mixing latency; for non-KTV similar scenarios, it is not recommended to set this parameter.**
            - 0: No alignment, default value
            - 1: Specified Stream alignment
            - 2: Force all Streams to align
        RecvBufferLevel:
          type: integer
          format: int
          minimum: 0
          maximum: 4000
          description: |
            Control the minimum buffer time for subscribing Streams, value range [0, 4000], unit: milliseconds; default minimum buffer time is 0.
        ExPara:
          type: array
          description: Extended parameters, fill in according to actual situation, regular tasks can be left blank.
          items:
            type: object
            properties:
              Key:
                type: string
                example: "k1"
                description: Key value.
              Value:
                type: string
                example: "v1"
                description: Value value.
    StartAutoMixResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int
          description: |
            The following only lists some return codes related to the interface business logic. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).

            <table>
            <thead>
              <tr><th>Return Code</th><th>Description</th><th>Suggested Handling</th></tr>
            </thead>
            <tbody>
              <tr><td>110200001</td><td>Failed.</td><td>Please retry.</td></tr>
              <tr><td>110200002</td><td>Input parameter error.</td><td>Please handle according to Message information.</td></tr>
              <tr><td>110200003</td><td>Authentication failed.</td><td>Please confirm whether the authentication information is correct or expired. For details, please refer to "Signature Mechanism" in <a href="/real-time-video-server/api-reference/accessing-server-apis#signature-mechanism-" target="_blank">Calling Method</a>.</td></tr>
              <tr><td>110200004</td><td>Failed to parse input parameters.</td><td>Please check whether the Stream Mixing parameters are correct.</td></tr>
              <tr><td>110200005</td><td>Failed to acquire distributed lock for Stream Mixing start.</td><td>The same UserId starts Stream Mixing requests too frequently, please try again later.</td></tr>
              <tr><td>110200006</td><td>Failed to acquire distributed lock for Stream Mixing stop.</td><td>The same UserId stops Stream Mixing requests too frequently, please try again later.</td></tr>
              <tr><td>110200151</td><td>Stream Mixing task failed.</td><td>Please retry, or contact ZEGOCLOUD Technical Support for handling.</td></tr>
              <tr><td>110200194</td><td>Stream Mixing request overload.</td><td>Requests are too frequent, please try again later.</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Operation result description.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "8472822294336370476"
        Data:
          type: object
          description: Response data.
          properties:
            UserId:
              type: string
              description: User ID.
              example: "123"
            Sequence:
              type: integer
              format: int
              description: Sequence number.
              example: 1
            RoomId:
              type: string
              description: Room ID.
              example: "room123"
            PlayInfo:
              type: array
              description: Playback information.
              items:
                type: object
                properties:
                  StreamId:
                    type: string
                    description: Output Stream ID.
                    example: "test"
                  RTMP:
                    type: string
                    description: CDN playback address corresponding to RTMP protocol (if the specified Stream Mixing output address is CDN and this protocol's pull domain name is configured).
                    example: "rtmp://domain/appname/test"
                  HLS:
                    type: string
                    description: CDN playback address corresponding to HLS protocol (if the specified Stream Mixing output address is CDN and this protocol's pull domain name is configured).
                    example: "http://domain/appname/test/playlist.m3u8"
                  FLV:
                    type: string
                    description: CDN playback address corresponding to HTTP-FLV protocol (if the specified Stream Mixing output address is CDN and this protocol's pull domain name is configured).
                    example: "http://domain/appname/test.flv"
                  Status:
                    type: integer
                    description: Stream status.
                    example: 0
                  UserName:
                    type: string
                    description: User name.
                    example: ""

