openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: stream-mixing

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    post:
      tags:
        - stream-mixing
      summary: StopAutoMix
      description: |
        Call this API to stop the `audio` automatic stream mixing task. For related callbacks, please refer to [Stream Mixing End Callback](/real-time-video-server/callback/stream-mixing/stopped).

        <Note title="Call frequency limit">100 times/second</Note>
      operationId: stop-auto-mix
      parameters:
        - name: Action
          in: query
          description: |
            > Interface prototype parameters
            >
            > https://rtc-api.zego.im?Action=StopAutoMix
          required: true
          schema:
            type: string
            enum: [StopAutoMix]
          style: form
          explode: true
        # 公共参数（Query）
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StopAutoMixRequest'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopAutoMixResponse'

components:
  schemas:
    StopAutoMixRequest:
      type: object
      required: [TaskId, RoomId]
      properties:
        TaskId:
          type: string
          description: Stream mixing task ID, which needs to be consistent with the TaskId passed in when starting stream mixing。
          example: "2213699902971205739"
        RoomId:
          type: string
          description: Room ID。
          example: "room123"
        Sequence:
          type: integer
          format: int
          description: Sequence number of the stream mixing task, used to ensure sequence, parameter modification of the same task needs to ensure the sequence number increments。
          example: 1
        UserId:
          type: string
          description: User ID。When enabling stream mixing task ownership, stopping the stream mixing task of a certain TaskId must input the UserId specified when starting the stream mixing task。
          example: "user1"
    StopAutoMixResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int
          description: |
            The following only lists the return codes related to interface business logic. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).

            <table>
            <thead>
              <tr><th>Return Code</th><th>Description</th><th>Handling Suggestion</th></tr>
            </thead>
            <tbody>
              <tr><td>110200001</td><td>Failed.</td><td>Please try again.</td></tr>
              <tr><td>110200002</td><td>Input parameter error.</td><td>Please refer to Message information for processing.</td></tr>
              <tr><td>110200003</td><td>Authentication failed.</td><td>Please confirm whether the authentication information is correct or expired, for details, please refer to "Signature Mechanism" in <a href="/real-time-video-server/api-reference/accessing-server-apis#签名机制-" target="_blank">Calling Method</a>.</td></tr>
              <tr><td>110200004</td><td>Failed to parse input parameters.</td><td>Please check if the stream mixing parameters are correct.</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Operation result description。
          example: "success"
        RequestId:
          type: string
          description: Request ID。
          example: "6351841974556802202"

