openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: stream-mixing

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    post:
      tags:
        - stream-mixing
      summary: StopMix
      description: |
        Call this API to stop stream mixing. For related callbacks, please refer to [Stream Mixing End Callback](/real-time-video-server/callback/stream-mixing/stopped).

        <Warning title="Note">
        - When the current stream mixing task (hereinafter referred to as "Stream Mixing Task A") is still in progress, if the developer starts a new stream mixing task (hereinafter referred to as "Stream Mixing Task B"), Stream Mixing Task A will not stop automatically. Only after 90 seconds from when all input streams of Stream Mixing Task A no longer exist, will it automatically end.
        - When using the stream mixing function of ZEGO Audio/Video Cloud Service, developers should pay attention: when starting Stream Mixing Task B, Stream Mixing Task A should be stopped, to avoid the situation where the host has already started Stream Mixing Task B to mix with other hosts, but the audience is still pulling the output stream of Stream Mixing Task A.
        </Warning>

        <Note title="Call frequency limit">All rooms under the same AppID are limited to 100 times/second</Note>
      operationId: stop-mix
      parameters:
        - name: Action
          in: query
          description: |
            > Interface prototype parameters
            >
            > https://rtc-api.zego.im?Action=StopMix
          required: true
          schema:
            type: string
            enum: [StopMix]
          style: form
          explode: true
        # 公共参数（Query）
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StopMixRequest'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopMixResponse'

components:
  schemas:
    StopMixRequest:
      type: object
      required: [TaskId]
      properties:
        TaskId:
          type: string
          description: Stream mixing task ID, which needs to be consistent with the TaskId passed in when starting stream mixing。
          example: "2213699902971205739"
        Sequence:
          type: integer
          format: int32
          description: Sequence number of the stream mixing task, used to ensure sequence, parameter modification of the same task needs to ensure the sequence number increments。
          example: 1
        UserId:
          type: string
          description: User ID。When enabling stream mixing task ownership, stopping the stream mixing task of a certain TaskId must input the UserId specified when starting the stream mixing task 。
          example: "456"
    StopMixResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          description: |
            The following only lists the return codes related to interface business logic. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).

            <table>
            <thead>
              <tr><th>Return Code</th><th>Description</th><th>Handling Suggestion</th></tr>
            </thead>
            <tbody>
              <tr><td>110200001</td><td>Failed.</td><td>Please try again.</td></tr>
              <tr><td>110200002</td><td>Input parameter error.</td><td>Please refer to Message information for processing.</td></tr>
              <tr><td>110200003</td><td>Authentication failed.</td><td>Please confirm whether the authentication information is correct or expired, for details, please refer to "Signature Mechanism" in <a href="/real-time-video-server/api-reference/accessing-server-apis#签名机制-" target="_blank">Calling Method</a>.</td></tr>
              <tr><td>110200004</td><td>Failed to parse input parameters.</td><td>Please check if the stream mixing parameters are correct.</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Operation result description。
          example: "success"
        RequestId:
          type: string
          description: Request ID。
          example: "8472822294336370476"

