openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: stream-mixing

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    post:
      tags:
        - stream-mixing
      summary: StopCloudTranscode
      description: |
        Call this API to stop single stream transcoding tasks.

        "Client" single stream transcoding introduction triggered by transcoding template, please refer to [Single Stream Transcoding](/real-time-video-android-java/live-streaming/single-stream-transcoding)；
        "Server" related callbacks, please refer to [Single Stream Transcoding Start Callback](/real-time-video-server/callback/transcoding/on-demand-transcoding-started) and [Single Stream Transcoding Stop Callback](/real-time-video-server/callback/transcoding/on-demand-transcoding-stopped).

         <Note title="Call frequency limit">100 times/second</Note>
      operationId: stop-cloud-transcode
      parameters:
        - name: Action
          in: query
          description: |
            > Interface prototype parameters
            >
            > https://rtc-api.zego.im?Action=StopCloudTranscode
          required: true
          schema:
            type: string
            enum: [StopCloudTranscode]
          style: form
          explode: true
        # 公共参数（Query）
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StopCloudTranscodeRequest'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopCloudTranscodeResponse'

components:
  schemas:
    StopCloudTranscodeRequest:
      type: object
      required: [TaskId, UserId]
      properties:
        TaskId:
          type: string
          description: Task ID, unique identifier of the single stream transcoding task, customized by the developer。
          example: "2213699902971205739"
        UserId:
          type: string
          description: User ID。When enabling single stream transcoding task ownership, stopping the transcoding task of a certain TaskId must input the UserId specified when starting the single stream transcoding task <a href="/real-time-video-server/api-reference/stream-mixing/start-cloud-transcode" target="_blank">start single stream transcoding</a> task.
          example: "456"
        Sequence:
          type: integer
          format: int
          description: Sequence number of the transcoding task, used to ensure sequence, parameter modification of the same task needs to ensure the sequence number increments。
    StopCloudTranscodeResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int
          description: |
            The following only lists the return codes related to interface business logic. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).

            <table>
            <thead>
              <tr><th>Return Code</th><th>Description</th><th>Handling Suggestion</th></tr>
            </thead>
            <tbody>
              <tr><td>110200002</td><td>Input parameter error.</td><td>Please refer to Message information for processing.</td></tr>
              <tr><td>110200151</td><td>Single stream transcoding task failed.</td><td>Please try again, or contact ZEGOCLOUD Technical Support for processing.</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Operation result description。
          example: "success"
        RequestId:
          type: string
          description: Request ID。
          example: "8472822294336370476"

