openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com
servers:
  $ref: '../shared-components.yaml#/servers'
tags:
  - user
paths:
  /:
    post:
      tags: [user]
      summary: Batch remove from blocklist
      description: |
        By calling this API, you can batch remove 20 users from the blocklist for a user. If you need to increase the limit, please contact ZEGOCLOUD Technical Support.

        After the API is successfully called, this user's client will receive blocklist update notifications through the following ZIM SDK callback interface:

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|--------|---------|
        | [blacklistChanged](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-blacklist-changed-user-list) | [onBlacklistChanged](https://doc-zh.zego.im/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-blacklist-changed) | [blacklistChanged](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-blacklist-changed-user-list) | [onBlacklistChanged](https://doc-zh.zego.im/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-blacklist-changed) |

        | Web-25% | Mini Program-25% | Flutter-25% | React Native-25% |
        |-----|---------|---------|---------|
        | [blacklistChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#blacklist-changed) | [blacklistChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#blacklist-changed) | [onBlacklistChanged](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onBlacklistChanged.html) | [blacklistChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#blacklist-changed) |

        | uni-app \| uni-app x-25% | HarmonyOS-25% |
        |---------|---------|
        | [blacklistChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#blacklist-changed) | [blacklistChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#blacklist-changed) |
        
        <Note title="Note">

        The users corresponding to the parameters `FromUserId` and `UserIds` have logged in to the ZIM service by calling the `login` method on the client, or have completed registration by calling the [server-side API](/zim-server/user/batch-register-users).
        </Note>
        
        <Note title="Note">The parameters FromUserId and UserId only support numbers, English characters, and `'!', '#', '$', '%', '&', '(', ')', '+', '-', ':', ';', '<', '=', '.', '>', '?', '@', '[', ']', '^', '_', '{', '}', '|', '~'`</Note>
        <Note title="QPS Limit">20 times/s</Note>
      operationId: batch-unblock-users
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=RemoveUsersFromBlacklist
          required: true
          schema:
            type: string
            enum: [RemoveUsersFromBlacklist]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoveUsersFromBlacklistRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RemoveUsersFromBlacklistResponse'
components:
  schemas:
    RemoveUsersFromBlacklistRequest:
      type: object
      required: [FromUserId, UserIds]
      properties:
        FromUserId:
          type: string
          description: Remove target users from the blocklist for this user.
          maxLength: 32
          example: "zego_user"
        UserIds:
          type: array
          description: List of target users to be removed from the blocklist. The default maximum is 20 strings. Each string has a maximum length of 32 bytes.
          maxItems: 20
          items:
            type: string
            maxLength: 32
            example: "user1"
          example: ["user1", "user2", "user3", "user4"]
    RemoveUsersFromBlacklistResponse:
      type: object
      properties:
        Code:
          type: integer
          description: |
            Return code.

            The following only lists the Code and SubCode related to the API business logic. For complete return codes, please refer to [Global Return Codes](/zim-server/return-codes).
            > **Note**
            >
            > When you initiate a request to remove multiple users from the blocklist at the same time:
            > <ul><li>If 1 or more users are successfully removed, Code will return 0. In this case, please refer to the specific information in ErrList to confirm the operation result.</li>
            > <li>If all specified users fail to be removed, Code will return the relevant return code. For details, please refer to <a href="/zim-server/return-codes" target="_blank">Global Return Codes</a>.</li></ul>
            
            <table>
            <tbody><tr>
            <th>Code / SubCode</th>
            <th>Description</th>
            <th>Suggested Solution</th>
            </tr>
            <tr>
            <td>660000002</td>
            <td>Input parameter error。</td>
            <td>Please check the input parameters。</td>
            </tr>
            <tr>
            <td>660300005</td>
            <td>The API call frequency exceeds the AppID-level limit.</td>
            <td>Please try again later.</td>
            </tr>
            <tr>
            <td>660500002</td>
            <td>FromUserId is not registered.</td>
            <td>Please confirm whether the user is registered:<br/>If confirmed registered, please contact ZEGOCLOUD Technical Support for troubleshooting.<br/>If confirmed not registered, please register this user.</td>
            </tr>
            <tr>
            <td>660800001</td>
            <td>FromUserId is not registered.</td>
            <td>Please confirm whether the user is registered:<br/>If confirmed registered, please contact ZEGOCLOUD Technical Support for troubleshooting.<br/>If confirmed not registered, please register this user.</td>
            </tr>
            <tr>
            <td>660800038</td>
            <td>Cannot block FromUserId or remove FromUserId from the blocklist.</td>
            <td>Please modify UserIds.</td>
            </tr>
            <tr>
            <td>660800039</td>
            <td>The incoming user list exceeds the limit.</td>
            <td>Please shorten the incoming user list.</td>
            </tr>
            <tr>
            <td>660800042</td>
            <td>Failed to remove all specified users from the blocklist.</td>
            <td>Please refer to the SubCode of the response parameter ErrList for processing.</td>
            </tr>
            <tr>
            <td>660800043</td>
            <td>This user has been removed from the blocklist.</td>
            <td>No action required.</td>
            </tr>
            <tr>
            <td>660800044</td>
            <td>This user is not in the blocklist.</td>
            <td>No action required.</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: Description of the request result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        ErrList:
          type: array
          description: |
            Failure information list.
            <ul>
            <li>Code is 0:</li>
            <li>ErrList is empty, indicating that all specified users are successfully removed.</li>
            <li>ErrList is not empty, indicating that some specified users failed to be removed from the blocklist. Please refer to SubCode for processing.</li>
            </ul>
            <ul>
            <li>Code is not 0:</li>
            <li>ErrList is empty, indicating parameter error, API frequency limit, or system error.</li>
            <li>ErrList is not empty, indicating that all specified users failed to be removed from the blocklist.</li>
            </ul>
          items:
            type: object
            properties:
              UserId:
                type: string
                description: Failed to remove this UserID from the blocklist.
                example: "user1"
              SubCode:
                type: integer
                description: |
                  Specific failure return code. For complete return codes, please refer to the Code description or [Global Return Codes](/zim-server/return-codes).
                example: 660000002
