openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com
servers:
  $ref: '../shared-components.yaml#/servers'
tags:
  - user
paths:
  /:
    post:
      tags: [user]
      summary: Batch add friends
      description: |
        By calling this API, you can directly batch add up to 20 friends for users without requiring the other party's consent. If you need to increase the limit (up to 50), please contact ZEGOCLOUD Technical Support.

        Each user can have a maximum of 3000 friends.

        After successfully adding friends for users, the clients of the relevant users will receive friend list update notifications through the following ZIM SDK callback interface:

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        | --- | --- | --- | --- |
        | [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-friend-list-changed-friend-info-list) | [onFriendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-friend-list-changed) | [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-friend-list-changed-friend-info-list) | [onFriendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-friend-list-changed) |

        | Web-25% | Mini Program-25% | Flutter-25% | React Native-25% |
        | --- | --- | --- | --- |
        | [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#friend-list-changed) |  [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#friend-list-changed) | [onFriendListChanged](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onFriendListChanged.html) | [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#friend-list-changed)   |

        |uni-app \| uni-app x-25% | HarmonyOS-25% |
        |  --- | --- |
        | [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#friend-list-changed) | [friendListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#friend-list-changed) |

        <Note title="Note">

        The users corresponding to the parameters `FromUserId` and `UserId` have logged in to the ZIM service by calling the `login` method on the client, or have completed registration by calling the [server-side API](/zim-server/user/batch-register-users).
        </Note>
        <Note title="Note">The parameter FromUserId 和 UserId Only supports numbers, English characters, and `'!', '#', '$', '%', '&', '(', ')', '+', '-', ':', ';', '<', '=', '.', '>', '?', '@', '[', ']', '^', '_', '{', '}', '|', '~'`</Note>
        <Note title="Note">QPS Limit: 20 times/s</Note>
      operationId: batch-add-friends
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=AddFriends
          required: true
          schema:
            type: string
            enum: [AddFriends]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddFriendsRequest'
              example:
                FromUserId: "zego_user"
                FriendInfos:
                  - UserId: "usera1"
                    Wording: "Wording1"
                    FriendAlias: "alias1"
                    Attributes:
                      - Key: "k1"
                        Value: "Value"
                      - key: "k2"
                        Value: "Value1"
                  - UserId: "usera2"
                    Wording: "Wording2"
                    FriendAlias: "alias2"
                    Attributes:
                      - key: "k3"
                        Value: "Value"
                      - key: "k0"
                        Value: "Value1"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddFriendsResponse'
components:
  schemas:
    AddFriendsRequest:
      type: object
      required: [FromUserId, FriendInfos]
      properties:
        FromUserId:
          type: string
          description: 为此 UserId 添加好友。
          maxLength: 32
          example: "zego_user"
        FriendInfos:
          type: array
          description: 好友结构体对象。默认上限为 20。
          maxItems: 20
          items:
            type: object
            required: [UserId]
            properties:
              UserId:
                type: string
                description: 目标User ID.长度上限为 32 bytes。
                maxLength: 32
                example: "usera1"
              Wording:
                type: string
                description: FromUserId 对目标用户成为好友时的附言，长度上限为 256 字符。
                maxLength: 256
                example: "Wording1"
              FriendAlias:
                type: string
                description: Remark from FromUserId to the target user, with a maximum length of 256 characters.
                maxLength: 256
                example: "alias1"
              FriendTime:
                type: number
                description: |
                  成为好友的时间。此参数可在数据迁移时用于导入好友列表。
                  - 为 0 时，ZIM 服务端以当前时间为准。
                  - 不为 0 时，此参数需为 MS 时间戳，且不晚于当前时间。
                default: 0
                example: 1640995200000
              Attributes:
                type: array
                description: |
                  好友属性，上限 5 个。
                  <Note title="Note">

                  Key 的总长度与 Value 的总长度上限为 1024 bytes。如需上调，请联系 ZEGOCLOUD Technical Support。建议不要将上限设置过大。
                  </Note>
                maxItems: 5
                items:
                  type: object
                  required: [Key, Value]
                  properties:
                    Key:
                      type: string
                      description: 好友属性的键。取值仅能为 k0、k1、k2、k3、k4。
                      enum: [k0, k1, k2, k3, k4]
                      example: "k1"
                    Value:
                      type: string
                      description: 好友属性的值。
                      example: "Value"
    AddFriendsResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.
            
            以下仅列出了接口业务逻辑相关的 Code 和 SubCode ，完整返回码请参考 [全局返回码](/zim-server/return-codes)。
            > **Note**
            >
            > 当您发起请求同时将多名指定用户添加为好友时：
            > <ul><li>如果成功添加 1 名或更多好友，Code 都会返回 0。此时请参考 ErrorList 中的具体信息，确认操作结果。</li>
            > <li>如果添加全部指定用户为好友失败，Code 会返回相关返回码，具体请参考 <a href="/zim-server/return-codes" target="_blank">全局返回码</a>。</li></ul>

            <table>
            <tbody><tr>
            <th>Code / SubCode</th>
            <th>描述</th>
            <th>Suggested Solution</th>
            </tr>
            <tr>
            <td>660000002</td>
            <td>Input parameter error。</td>
            <td>Please check the input parameters。</td>
            </tr>
            <tr>
            <td>660300005</td>
            <td>调用接口的频率超出了 AppID 级别限制。</td>
            <td>请稍后再试。</td>
            </tr>
            <tr>
            <td>660500002</td>
            <td>FromUserId 未注册。</td>
            <td>请先注册 “FromUserId”。</td>
            </tr>
            <tr>
            <td>660700015</td>
            <td><ul><li>如果为 code：FromUserId 未注册。</li><li>如果为 subCode：目标用户未注册。</li></ul></td>
            <td><ul><li>如果为 code：请先注册 FromUserId。</li><li>如果为 subCode：请先注册目标用户。</li></ul></td>
            </tr>
            <tr>
            <td>660800019</td>
            <td>单次批量操作超过上限。</td>
            <td>减少单次批量操作数量。</td>
            </tr>
            <tr>
            <td>660800020</td>
            <td>不能将 FromUserId 添加为好友，即 FriendInfos 中的 UserId 不能与 FromUserId 相同。</td>
            <td>请修改 FriendInfos 中与 FromUserId 相同的 UserId。</td>
            </tr>
            <tr>
            <td>660800021</td>
            <td>FriendAlias 或 Wording 超过长度上限。</td>
            <td>请缩减相关字段的内容长度。</td>
            </tr>
            <tr>
            <td>660800022</td>
            <td>参数中的用户 ID 相关参数重复。</td>
            <td>请删除或修改重复参数。</td>
            </tr>
            <tr>
            <td>660800023</td>
            <td>Attributes 的 Key 取值不属于 k0 ~ k4。</td>
            <td>请修改 Key 的值。</td>
            </tr>
            <tr>
            <td>660800024</td>
            <td>Attributes 的所有 Key、Value 总长度超过长度上限。</td>
            <td>请缩减相关字段的内容长度。</td>
            </tr>
            <tr>
            <td>660800025</td>
            <td>所有好友均未注册过，接口调用失败。</td>
            <td>请先注册目标用户。</td>
            </tr>
            <tr>
            <td>660800026</td>
            <td>好友属性参数错误。</td>
            <td>Please check the input parameters。</td>
            </tr>
            <tr>
            <td>660800027</td>
            <td>目标用户已经是好友，无需重复添加。</td>
            <td>无需操作。</td>
            </tr>
            <tr>
            <td>660800028</td>
            <td>FromUserId 的好友数量到达上限。</td>
            <td>无法添加更多好友。</td>
            </tr>
            <tr>
            <td>660800032</td>
            <td>Attributes 有重复的 Key。</td>
            <td>请修改 Key。</td>
            </tr>
            <tr>
            <td>660800046</td>
            <td>传递的时间戳大于当前时间。</td>
            <td>可以不填，默认是当前时间。</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: Description of the request result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        ErrorList:
          type: array
          description: |
            失败信息列表。
            <ul>
            <li>Code 为 0：</li>
            <li>ErrorList 为空，成功添加全部指定用户为好友。</li>
            <li>ErrorList 不为空，表示添加部分指定用户失败，请参考 SubCode 处理。</li>
            <li>Code 不为 0：</li>
            <li>ErrorList 为空，表示参数错误、接口频率限制、系统错误。</li>
            <li>ErrorList 不为空，表示添加全部指定用户为好友失败。</li>
            </ul>
          items:
            type: object
            properties:
              UserId:
                type: string
                description: 添加该 UserID 为好友失败。
                example: "usera2"
              SubCode:
                type: number
                description: |
                  具体失败返回码，完整返回码请参考 Code 说明或者 [全局返回码](/zim-server/return-codes)。
                example: 660800022
