openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com
servers:
  $ref: '../shared-components.yaml#/servers'
tags:
  - user
paths:
  /:
    post:
      tags: [user]
      summary: Batch send friend requests
      description: |
        By calling this API, you can batch send friend requests to up to 20 other users for a user. If you need to increase the limit (up to 50), please contact ZEGOCLOUD Technical Support.

        <Note title="Note">

        When a user is already a one-way friend of the target user, if you call this API to send a friend request to the target user, the target user will directly become a friend of the user.

        For example, users A and B were originally two-way friends. A deleted B in one-way mode, so A is a one-way friend of B, and B is not a friend of A. After calling this API to send a friend request to B, B directly becomes a friend of A without B's consent.
        </Note>

        Each user can have a maximum of 3000 friends.

        After sending a friend request, the client of the target user will receive the request notification through the following ZIM SDK callback interface:

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|--------|---------|
        | [friendApplicationListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-friend-application-list-changed-friend-application-info-list) | [onFriendApplicationListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-friend-application-list-changed) | [friendApplicationListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-friend-application-list-changed-friend-application-info-list) | [onFriendApplicationListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-friend-application-list-changed) |

        | Web-25% | Mini Program-25% | Flutter-25% | React Native-25% |
        |-----|---------|---------|---------|
        | [friendApplicationListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#friend-application-list-changed) | [friendApplicationListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#friend-application-list-changed) | [onFriendApplicationListChanged](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onFriendApplicationListChanged.html) | [friendApplicationListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#friend-application-list-changed) |

        | uni-app \| uni-app x-25% | HarmonyOS-25% |
        |---------|---------|
        | [friendApplicationListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#friend-application-list-changed) | [friendApplicationListChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#friend-application-list-changed) |

        <Note title="Note">

        The users corresponding to the parameters `FromUserId` and `UserId` have logged in to the ZIM service by calling the `login` method on the client, or have completed registration by calling the [server-side API](/zim-server/user/batch-register-users).
        </Note>
        <Note title="Note">The parameters FromUserId and UserId only support numbers, English characters, and `'!', '#', '$', '%', '&', '(', ')', '+', '-', ':', ';', '<', '=', '.', '>', '?', '@', '[', ']', '^', '_', '{', '}', '|', '~'`</Note>
        <Note title="QPS Limit">20 times/s</Note>
      operationId: batch-send-friend-requests
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=SendFriendApplication
          required: true
          schema:
            type: string
            enum: [SendFriendApplication]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendFriendApplicationRequest'
            example:
              FromUserId: "zego_user"
              FriendInfos:
                - UserId: "usera1"
                  Wording: "Wording1"
                  FriendAlias: "Remark1"
                  Attributes:
                    - Key: "k2"
                      Value: "Value"
                    - Key: "k0"
                      Value: "Value1"
                - UserId: "usera2"
                  Wording: "Wording2"
                  FriendAlias: "Remark2"
                  Attributes:
                    - Key: "k0"
                      Value: "Value"
                    - Key: "k1"
                      Value: "Value1"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendFriendApplicationResponse'
components:
  schemas:
    SendFriendApplicationRequest:
      type: object
      required: [FromUserId, FriendInfos]
      properties:
        FromUserId:
          type: string
          description: Send friend requests for this UserId.
          maxLength: 32
          example: "zego_user"
        FriendInfos:
          type: array
          description: Friend structure object. Default maximum is 20.
          maxItems: 20
          items:
            type: object
            required: [UserId]
            properties:
              UserId:
                type: string
                description: Target user ID. Maximum length is 32 bytes.
                maxLength: 32
                example: "usera1"
              Wording:
                type: string
                description: Message from FromUserId when becoming friends with the target user. Maximum length is 256 characters.
                maxLength: 256
                example: "Wording1"
              FriendAlias:
                type: string
                description: Remark from FromUserId to the target user, with a maximum length of 256 characters.
                maxLength: 256
                example: "Remark1"
              CreateTime:
                type: number
                description: |
                  Application creation time. This parameter can be used to import friend lists during data migration.
                  - When it is 0, the ZIM server uses the current time.
                  - When it is not 0, this parameter must be a millisecond timestamp and not later than the current time.
              UpdateTime:
                type: number
                description: |
                  Application update time. This parameter can be used to import friend lists during data migration.
                  - When it is 0, the ZIM server uses the current time.
                  - When it is not 0, this parameter must be a millisecond timestamp and not later than the current time.
              Attributes:
                type: array
                description: |
                  Friend attributes. Maximum is 5.
                  <Note title="Note">The total length of Key and Value is limited to 1024 bytes. If you need to increase the limit, please contact ZEGOCLOUD Technical Support. It is recommended not to set the limit too high.</Note>
                maxItems: 5
                items:
                  type: object
                  required: [Key, Value]
                  properties:
                    Key:
                      type: string
                      description: Friend attribute key. Can only be k0, k1, k2, k3, or k4.
                      enum: [k0, k1, k2, k3, k4]
                      example: "k2"
                    Value:
                      type: string
                      description: Friend attribute value.
                      example: "Value"
    SendFriendApplicationResponse:
      type: object
      properties:
        Code:
          type: integer
          description: |
            Return code.
            
            The following only lists the Code and SubCode related to the API business logic. For complete return codes, please refer to [Global Return Codes](/zim-server/return-codes).
            > **Note**
            >
            > When you initiate a request to send friend requests to multiple users at the same time:
            > <ul><li>If the request is successfully sent to 1 or more users, Code will return 0. In this case, please refer to the specific information in ErrorList to confirm the operation result.</li>
            > <li>If all friend requests fail to be sent, Code will return the relevant return code. For details, please refer to <a href="/zim-server/return-codes" target="_blank">Global Return Codes</a>.</li></ul>

            <table>
            <tbody><tr>
            <th>Code / SubCode</th>
            <th>Description</th>
            <th>Suggested Solution</th>
            </tr>
            <tr>
            <td>660000002</td>
            <td>Input parameter error。</td>
            <td>Please check the input parameters。</td>
            </tr>
            <tr>
            <td>660000011</td>
            <td>The input user list is too large.</td>
            <td>Please check the input user list.</td>
            </tr>
            <tr>
            <td>660300005</td>
            <td>The API call frequency exceeds the AppID-level limit.</td>
            <td>Please try again later.</td>
            </tr>
            <tr>
            <td>660500002</td>
            <td>FromUserId is not registered.</td>
            <td>Please register FromUserId first.</td>
            </tr>
            <tr>
            <td>660700015</td>
            <td><ul><li>If it is code: FromUserId is not registered.</li><li>If it is subCode: Target user is not registered.</li></ul></td>
            <td><ul><li>If it is code: Please register FromUserId first.</li><li>If it is subCode: Please register the target user first.</li></ul></td>
            </tr>
            <tr>
            <td>660800019</td>
            <td>The number of single batch operations exceeds the limit.</td>
            <td>Reduce the number of single batch operations.</td>
            </tr>
            <tr>
            <td>660800020</td>
            <td>Cannot add FromUserId as a friend, that is, the UserId in FriendInfos cannot be the same as FromUserId.</td>
            <td>Please modify the UserId in FriendInfos that is the same as FromUserId.</td>
            </tr>
            <tr>
            <td>660800021</td>
            <td>FriendAlias or Wording exceeds the length limit.</td>
            <td>Please reduce the content length of the related fields.</td>
            </tr>
            <tr>
            <td>660800022</td>
            <td>User ID related parameters in the parameters are duplicated.</td>
            <td>Please delete or modify duplicate parameters.</td>
            </tr>
            <tr>
            <td>660800023</td>
            <td>The Key value of Attributes does not belong to k0 ~ k4.</td>
            <td>Please modify the value of Key.</td>
            </tr>
            <tr>
            <td>660800024</td>
            <td>The total length of all Keys and Values in Attributes exceeds the limit.</td>
            <td>Please reduce the content length of the related fields.</td>
            </tr>
            <tr>
            <td>660800025</td>
            <td>All target users are not registered, and the API call failed.</td>
            <td>Please register the target user first.</td>
            </tr>
            <tr>
            <td>660800026</td>
            <td>Attributes parameter error.</td>
            <td>Please check the input parameters。</td>
            </tr>
            <tr>
            <td>660800027</td>
            <td>The target user is already a friend, no need to send a friend request.</td>
            <td>No action required.</td>
            </tr>
            <tr>
            <td>660800028</td>
            <td>FromUserId's friend count has reached the limit.</td>
            <td>Cannot add more friends.</td>
            </tr>
            <tr>
            <td>660800032</td>
            <td>Attributes has duplicate Keys.</td>
            <td>Please modify the Key.</td>
            </tr>
            <tr>
            <td>660800046</td>
            <td>The passed timestamp is greater than the current time.</td>
            <td>Can be left blank, default is the current time.</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: Description of the request result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        ErrorList:
          type: array
          description: |
            Failure information list.
            <ul>
            <li>Code is 0:</li>
            <li>ErrorList is empty, all friend requests are successfully sent.</li>
            <li>ErrorList is not empty, indicating that some friend requests failed to be sent. Please refer to SubCode for processing.</li>
            <li>Code is not 0:</li>
            <li>ErrorList is empty, indicating parameter error, API frequency limit, or system error.</li>
            <li>ErrorList is not empty, indicating that all friend requests failed to be sent.</li>
            </ul>
          items:
            type: object
            properties:
              UserId:
                type: string
                description: Failed to send friend request to this UserID.
                example: "usera2"
              SubCode:
                type: integer
                description: |
                  Specific failure return code. For complete return codes, please refer to the Code description or [Global Return Codes](/zim-server/return-codes).
                example: 660800022
