openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com
servers:
  $ref: '../shared-components.yaml#/servers'
tags:
  - user
paths:
  /:
    post:
      tags: [user]
      summary: Change the alias of a friend
      description: |
        Through this API, you can batch modify the remarks of up to 20 friends for one user. If you need to increase the limit (up to 50), please contact ZEGOCLOUD Technical Support.

        After successfully modifying friend remarks, users receive relevant modification notifications through the following ZIM SDK callback interface:

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|--------|---------|
        | [friendInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-friend-info-updated-friend-info-list) | [onFriendInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-friend-info-updated) | [friendInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-friend-info-updated-friend-info-list) | [onFriendInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-friend-info-updated) |

        | Web-25% | Mini Program-25% | Flutter-25% | React Native-25% |
        |-----|---------|---------|---------|
        | [friendInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#friend-info-updated) | [friendInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#friend-info-updated) | [onFriendInfoUpdated](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onFriendInfoUpdated.html) | [friendInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#friend-info-updated) |

        | uni-app \| uni-app x-25% | HarmonyOS-25% |
        |---------|---------|
        | [friendInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#friend-info-updated) |[friendInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#friend-info-updated)  |
        
        <Note title="Note">
        The users corresponding to the parameters `FromUserId` and `UserId` have logged in to the ZIM service by calling the `login` method on the client, or have completed registration by calling the [server-side API](/zim-server/user/batch-register-users).
        </Note>
        <Note title="QPS Limit">20 times/s</Note>
      operationId: change-the-alias-of-a-friend
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=UpdateFriendsAlias
          required: true
          schema:
            type: string
            enum: [UpdateFriendsAlias]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateFriendsAliasRequest'
            example:
              FromUserId: "zego_user"
              UserIds:
                - UserId: "user1"
                  FriendAlias: "FriendAlias1"
                - UserId: "user2"
                  FriendAlias: "FriendAlias2"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateFriendsAliasResponse'
              example:
                Code: 0
                Message: success
                RequestId: "343649807833778782"
                ErrorList:
                  - UserId: "aaa"
                    SubCode: 660000012
                  - UserId: "bbb"
                    SubCode: 660000013
components:
  schemas:
    UpdateFriendsAliasRequest:
      type: object
      required: [FromUserId, UserIds]
      properties:
        FromUserId:
          type: string
          description: Update the remark for specified friends of this user.
          maxLength: 32
          example: "zego_user"
        UserIds:
          type: array
          description: List of users whose remarks are to be updated. A maximum of 20 users can be modified at a time.
          maxItems: 20
          items:
            type: object
            required: [UserId]
            properties:
              UserId:
                type: string
                description: User ID. Maximum length is 32 bytes.
                maxLength: 32
                example: "user1"
              FriendAlias:
                type: string
                description: New friend remark, with a maximum length of 256 characters.
                maxLength: 256
                example: "FriendAlias1"
    UpdateFriendsAliasResponse:
      type: object
      properties:
        Code:
          type: integer
          description: |
            Return code.
            
            The following only lists the Code and SubCode related to the API business logic. For complete return codes, please refer to [Global Return Codes](/zim-server/return-codes).
            > **Note**
            >
            > When you initiate a request to update multiple friend remarks at the same time:
            > <ul><li>If 1 or more friend remarks are successfully updated, Code will return 0. In this case, please refer to the specific information in ErrorList to confirm the operation result.</li>
            > <li>If all friend remarks fail to be updated, Code will return the relevant return code. For details, please refer to <a href="/zim-server/return-codes" target="_blank">Global Return Codes</a>.</li></ul>

            <table>
            <tbody><tr>
            <th>Code / SubCode</th>
            <th>Description</th>
            <th>Suggested Solution</th>
            </tr>
            <tr>
            <td>660000001</td>
            <td>General business error.</td>
            <td>Please retry or contact ZEGOCLOUD Technical Support.</td>
            </tr>
            <tr>
            <td>660000002</td>
            <td>Input parameter error。</td>
            <td>Please check the input parameters。</td>
            </tr>
            <tr>
            <td>660300005</td>
            <td>The API call frequency exceeds the AppID-level limit.</td>
            <td>Please try again later.</td>
            </tr>
            <tr>
            <td>660800019</td>
            <td>Single batch operation exceeds the limit.</td>
            <td>Reduce the number of single batch operations.</td>
            </tr>
            <tr>
            <td>660800021</td>
            <td>FriendAlias exceeds the length limit.</td>
            <td>Please reduce the content length of the related fields.</td>
            </tr>
            <tr>
            <td>660800034</td>
            <td>This user is not a friend of FromUserId.</td>
            <td>Please add this user as a friend first.</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: Operation result description.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        ErrorList:
          type: array
          description: |
            Check failure list.
            <ul>
            <li>Code is 0:</li>
            <li>ErrorList is empty, all friend remarks are successfully modified.</li>
            <li>ErrorList is not empty, indicating that some friend remarks failed to be modified. Please refer to SubCode for processing.</li>
            </ul>
            <ul>
            <li>Code is not 0:</li>
            <li>ErrorList is empty, indicating parameter error, API frequency limit, or system error.</li>
            <li>ErrorList is not empty, indicating that all friend remarks failed to be modified.</li>
            </ul>
          items:
            type: object
            properties:
              UserId:
                type: string
                description: User ID whose friend remark failed to be modified.
                example: "aaa"
              SubCode:
                type: number
                description: |
                  Specific failure return code. For complete return codes, please refer to the Code description or [Global Return Codes](/zim-server/return-codes).
                example: 660000012
