openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com
servers:
  $ref: '../shared-components.yaml#/servers'
tags:
  - user
paths:
  /:
    post:
      tags: [user]
      summary: Check friendships
      description: |
        By calling this API, you can batch check the friend relationship between one user and up to 20 other users. If you need to increase the limit (up to 50), please contact ZEGOCLOUD Technical Support.

        ZEGOCLOUD supports one-sided or two-sided checking of friend relationships. Taking checking the friend relationship between user A and target user B as an example:
        - One-way check: Only check whether user A's friend list has user B.
        - Two-way check: Check whether user A and user B have each other in their friend lists.

        The results of checking friend relationships may include:

        <table>
        <tbody><tr>
        <th rowspan="2">Check Type</th>
        <th rowspan="2">Relation</th>
        <th colspan="2">Description</th>
        </tr>
        <tr>
        <th>A's friend list has B</th>
        <th>B's friend list has A</th>
        </tr>
        <tr>
        <td rowspan="2">One-way</td>
        <td>1</td>
        <td>✖</td>
        <td>Cannot confirm</td>
        </tr>
        <tr>
        <td>2</td>
        <td>✔️</td>
        <td>Cannot confirm</td>
        </tr>
        <tr>
        <td rowspan="4">Two-way</td>
        <td>3</td>
        <td>✖</td>
        <td>✖</td>
        </tr>
        <tr>
        <td>4</td>
        <td>✔️</td>
        <td>✖</td>
        </tr>
        <tr>
        <td>5</td>
        <td>✖</td>
        <td>✔️</td>
        </tr>
        <tr>
        <td>6</td>
        <td>✔️</td>
        <td>✔️</td>
        </tr>
        </tbody></table>
        
        <Note title="Note">

        The users corresponding to the parameters `FromUserId` and `UserId` have logged in to the ZIM service by calling the `login` method on the client, or have completed registration by calling the [server-side API](/zim-server/user/batch-register-users).
        </Note>
        <Note title="Note">QPS Limit: 20 times/s</Note>
      operationId: check-friendships
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=CheckFriendsRelation
          required: true
          schema:
            type: string
            enum: [CheckFriendsRelation]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckFriendsRelationRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckFriendsRelationResponse'
              example:
                Code: 0
                Message: success
                RequestId: "343649807833778782"
                Successes:
                  - UserId: "user_id1"
                    Relation: 4
                  - UserId: "user_id2"
                    Relation: 4
                Fails:
                  - UserId: "user_id3"
                    SubCode: 660000001
                    Relation: 1
                  - UserId: "user_id4"
                    SubCode: 660000001
                    Relation: 2
components:
  schemas:
    CheckFriendsRelationRequest:
      type: object
      required: [FromUserId, UserIds, CheckType]
      properties:
        FromUserId:
          type: string
          description: Query friend relationships for this UserId.
          maxLength: 32
          example: "zego_user"
        UserIds:
          type: array
          description: List of target users to check friend relationships. Default maximum is 20.
          maxItems: 20
          items:
            type: string
            maxLength: 32
            example: "user_id1"
          example: ["user_id1", "user_id2", "user_id3", "user_id4"]
        CheckType:
          type: number
          description: |
            Check type:
            - 0: Two-way check.
            - 1: One-way check.
          enum: [0, 1]
          example: 0
    CheckFriendsRelationResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.
            
            The following only lists the Code and SubCode related to the API business logic. For complete return codes, please refer to [Global Return Codes](/zim-server/return-codes).
            > **Note**
            >
            > When you initiate a request to check the friend relationship between FromUserId and multiple users at the same time:
            > <ul><li>If the friend relationship between FromUserId and 1 or more users is successfully checked, Code will return 0. In this case, please refer to the specific information in Fails to confirm the operation result.</li>
            > <li>If the friend relationship check between FromUserId and all target users fails, Code will return the relevant return code. For details, please refer to <a href="/zim-server/return-codes" target="_blank">Global Return Codes</a>.</li></ul>

            <table>
            <tbody><tr>
            <th>Code / SubCode</th>
            <th>Description</th>
            <th>Suggested Solution</th>
            </tr>
            <tr>
            <td>660000001</td>
            <td>General business error.</td>
            <td>Please retry or contact ZEGOCLOUD Technical Support.</td>
            </tr>
            <tr>
            <td>660000002</td>
            <td>Input parameter error。</td>
            <td>Please check the input parameters。</td>
            </tr>
            <tr>
            <td>660300005</td>
            <td>The API call frequency exceeds the AppID-level limit.</td>
            <td>Please try again later.</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: Description of the request result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        Successes:
          type: array
          description: Check success list.
          items:
            type: object
            properties:
              UserId:
                type: string
                description: Successfully checked the friend relationship between FromUserId and this user ID.
                example: "user_id1"
              Relation:
                type: number
                description: Relationship type. For details, please refer to the function description of this API.
                example: 4
        Fails:
          type: array
          description: |
            Check failure list.
            <ul>
            <li>Code is 0:</li>
            <li>Fails is empty, indicating that the friend relationship between FromUserId and all target users is successfully checked.</li>
            <li>Fails is not empty, indicating that the friend relationship check between FromUserId and some target users failed. Please refer to SubCode for processing.</li>
            </ul>
            <ul>
            <li>Code is not 0:</li>
            <li>Fails is empty, indicating parameter error, API frequency limit, or system error.</li>
            <li>Fails is not empty, indicating that the friend relationship check between FromUserId and all target users failed.</li>
            </ul>
          items:
            type: object
            properties:
              UserId:
                type: string
                description: Failed to check the friend relationship between FromUserId and this user ID.
                example: "user_id3"
              SubCode:
                type: number
                description: |
                  Specific failure return code. For complete return codes, please refer to the Code description or [Global Return Codes](/zim-server/return-codes).
                example: 660000001
              Relation:
                type: number
                description: Relationship type. This field has a value only when the request parameter CheckType is 0, which is 1 or 2. For details of related values, please refer to the function description of this API.
                example: 1
