openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com
servers:
  $ref: '../shared-components.yaml#/servers'
tags:
  - user
paths:
  /:
    post:
      tags: [user]
      summary: Modify user information
      description: |
        Through this API, you can modify user profile information, including user nickname, avatar, etc.

        After successfully modifying user profile, related users receive user profile modification notifications through the following ZIM SDK callback interface:

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        | --- | --- | --- | --- |
        | [userInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-user-info-updated) | [onUserInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-user-info-updated) | [userInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-user-info-updated) | [onUserInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-user-info-updated) |

        | Web-25% | Mini Program-25% | Flutter-25% | Unity3D-25% |
        | --- | --- | --- | --- |
        | [userInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#user-info-updated) | [userInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#user-info-updated) | [onUserInfoUpdated](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onUserInfoUpdated.html) | [OnUserInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-user-info-updated) |

        | uni-app \| uni-app x-25% | React Native-25% | HarmonyOS-25% |
        | --- | --- | --- |
        | [userInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#user-info-updated) | [userInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#user-info-updated) | [userInfoUpdated](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#user-info-updated) |

        <Note title="Note">QPS Limit: 20 times/s</Note>
      operationId: modify-user-information
      parameters:
        - name: Action
          in: query
          required: true
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=ModifyUserInfo
          schema:
            type: string
            enum: [ModifyUserInfo]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModifyUserInfoRequest'
            example:
              UserInfo:
                - UserId: "aaa"
                  UserName: "userNamea"
                  UserAvatar: "http"
                  Extra: "extra info"
                - UserId: "bbb"
                  UserName: "userNameb"
                  UserAvatar: "http"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModifyUserInfoResponse'
                example:
                  Code: 0
                  Message: success
                  RequestId: "343649807833778782"
                  ErrorList:
                    - UserId: "aaa"
                      SubCode: 660000012
                      SubMessage: "user length limit"
                    - UserId: "bbb"
                      SubCode: 660000013
                      SubMessage: "this is a demo"
components:
  schemas:
    ModifyUserInfoRequest:
      type: object
      required: [UserInfo]
      properties:
        UserInfo:
          type: array
          description: List of users whose profiles are to be modified. A maximum of 100 users can be modified at a time.
          maxItems: 100
          items:
            type: object
            required: [UserId]
            properties:
              UserId:
                type: string
                description: Modify the profile of this user ID (who has logged in to the ZIM service by calling the login method on the client, or has completed registration by calling the [server-side API](/zim-server/user/batch-register-users)).
                maxLength: 32
                example: "aaa"
              UserName:
                type: string
                description: New user name, with a maximum length of 256 bytes.
                maxLength: 256
                example: "userNamea"
              UserAvatar:
                type: string
                description: New avatar, with a maximum length of 500 bytes.
                maxLength: 500
                example: "http"
              Extra:
                type: string
                description: User extended information. Default length is 2 KB. If you need to increase the limit, please contact ZEGOCLOUD Technical Support. Maximum is 32 KB.
                example: "extra info"
    ModifyUserInfoResponse:
      type: object
      properties:
        Code:
          type: integer
          description: |
            Return code.

            The following only lists the Code and SubCode related to the API business logic. For complete return codes, please refer to [Global Return Codes](/zim-server/return-codes).
            <table>
            <tbody><tr>
            <th>Code / SubCode</th>
            <th>Description</th>
            <th>Suggested Solution</th>
            </tr>
            <tr>
            <td>660000002</td>
            <td>Parameter error.</td>
            <td>Please refer to the request parameters and enter the correct parameters.</td>
            </tr>
            <tr>
            <td>660300005</td>
            <td>The API call frequency exceeds the AppID-level limit.</td>
            <td>Please try again later.</td>
            </tr>
            <tr>
            <td>660700012</td>
            <td>User is not registered.</td>
            <td>Please register the user first.</td>
            </tr>
            <tr>
            <td>660700013</td>
            <td>Error querying user information.</td>
            <td>Please contact ZEGOCLOUD Technical Support.</td>
            </tr>
            <tr>
            <td>660700016</td>
            <td>Error synchronizing user information.</td>
            <td>Please contact ZEGOCLOUD Technical Support.</td>
            </tr>
            <tr>
            <td>660700017</td>
            <td>Error updating user information.</td>
            <td>Please contact ZEGOCLOUD Technical Support.</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: Operation result description.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        ErrorList:
          type: array
          description: |
            Failure information list.
            <ul>
            <li>Code is 0:</li>
            <li>ErrorList is empty, all user profiles are successfully modified.</li>
            <li>ErrorList is not empty, indicating that some user profiles failed to be modified. Please refer to SubCode and SubMessage for processing.</li>
            </ul>
            <ul>
            <li>Code is not 0:</li>
            <li>ErrorList is empty, indicating parameter error, API frequency limit, or system error.</li>
            <li>ErrorList is not empty, indicating that all user profiles failed to be modified.</li>
            </ul>

          items:
            type: object
            properties:
              UserId:
                type: string
                description: User ID whose profile failed to be modified.
                example: "aaa"
              SubCode:
                type: number
                description: |
                  Specific return code for user profile modification failure. For complete return codes, please refer to the Code description or [Global Return Codes](/zim-server/return-codes).
                example: 660000012
              SubMessage:
                type: string
                description: Reason for user profile modification failure.
                example: "user length limit"
