openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - user

paths:
  /:
    post:
      tags: [user]
      summary: Query user information
      description: |
        Query user information by user ID, including user name, user avatar, and extended field.

        <Note title="Note">QPS Limit: 20 times/s</Note>
      operationId: query-user-information
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=QueryUserInfos
          required: true
          schema:
            type: string
            enum: [QueryUserInfos]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [UserIds]
              properties:
                UserIds:
                  type: array
                  description: |
                    User ID list to query (who have logged in to the ZIM service by calling the login method on the client, or have completed registration by calling the [server-side API](https://www.zegocloud.com/docs/zim-server/user/batch-register-users)). A maximum of 100 user IDs can be queried. Each user ID does not exceed 64 bytes.
                    
                    >**Note**
                    >
                    > UserIds Only supports numbers, English characters, and '!'，'#'，'$'，'%'，'&'，'('，')'，'+'，'-'，':'，';'，'<'，'='，'.'，'>'，'?'，'@'，'['，']'，'^'，'_'，' '，'{'，'}'，'|'，'~'。
                  maxItems: 100
                  items:
                    type: string
                    maxLength: 64
                    example: "userA"
                  example: ["userA", "userB", "userC"]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryUserInfosResponse'

components:
  schemas:
    QueryUserInfosResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            以下仅列出了接口业务逻辑相关的 Code 和 SubCode ，完整返回码请参考 [全局返回码](/zim-server/return-codes)。
            <table>
            <tbody><tr>
            <th>Code / SubCode</th>
            <th>描述</th>
            <th>Suggested Solution</th>
            </tr>
            <tr>
            <td>660000001</td>
            <td>业务类通用错误。</td>
            <td>请重试，或联系 ZEGOCLOUD Technical Support。</td>
            </tr>
            <tr>
            <td>660000002</td>
            <td>不存在的用户 ID，或者用户已经登出。</td>
            <td>Please check the input parameters。</td>
            </tr>
            <tr>
            <td>660300005</td>
            <td>调用接口的频率超出了 AppID 级别限制。</td>
            <td>请稍后再试。</td>
            </tr>
            <tr>
            <td>660700008</td>
            <td>获取用户信息出错。</td>
            <td>请检查用户 ID 是否正确，或联系 ZEGOCLOUD Technical Support。</td>
            </tr>
            <tr>
            <td>660700015</td>
            <td>用户未注册。</td>
            <td>请先注册用户。</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: Description of the request result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        Result:
          type: array
          description: 查询成功结果。
          items:
            type: object
            properties:
              UserId:
                type: string
                description: 查询成功的User ID.
                example: "UserA"
              UserName:
                type: string
                description: User name.
                example: "userName"
              UserAvatar:
                type: string
                description: 用户头像地址。
                example: "avatar"
              Extra:
                type: string
                description: Extended field.
                example: "extra"
        ErrorList:
          type: array
          description: |
            查询失败列表。用户 ID 不存在或者用户已登出时，通过该字段返回。
            <ul>
            <li>Code 为 0：</li>
            <li>  ErrorList 为空，全部用户在线状态查询成功。</li>
            <li>  ErrorList 不为空，表示部分用户在线状态查询失败，请参考 SubCode 处理。</li>
            </ul>
            <ul>
            <li>Code 不为 0：</li>
            <li>  ErrorList 为空，表示参数错误、接口频率限制、系统错误。</li>
            <li>  ErrorList 不为空，表示所有用户在线状态查询失败。</li>
            </ul>
          items:
            type: object
            properties:
              UserId:
                type: string
                description: 查询失败的User ID.
                example: "UserB"
              SubCode:
                type: number
                description: |
                  查询失败时的返回码，完整返回码请参考 Code 说明或者 [全局返回码](/zim-server/return-codes)。
                example: 660000002
