openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - user

paths:
  /:
    get:
      tags: [user]
      summary: Query the friend list
      description: |
        Paginate and retrieve the friend list based on user ID, obtaining information such as remarks and friend relationship establishment time.

        <Note title="QPS Limit">20 times/s</Note>
      operationId: query-the-friend-list
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=QueryFriendList
          required: true
          schema:
            type: string
            enum: [QueryFriendList]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryFriendListRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryFriendListResponse'
              example:
                Code: 0
                Message: success
                RequestId: "343649807833778782"
                TotalCount: 500
                Next: 1
                FriendInfos:
                  - UserId: "UserA"
                    UserName: "UserNameA"
                    Avatar: "Avatar1"
                    Wording: "Wording1"
                    FriendAlias: "FriendAlias1"
                    CreateTime: 1698310534000
                    Attributes:
                      - Key: "k1"
                        Value: "Value"
                      - Key: "k0"
                        Value: "Value1"
                  - UserId: "UserB"
                    UserName: "UserNameB"
                    Avatar: "Avatar2"
                    Wording: "Wording1"
                    FriendAlias: "FriendAlias2"
                    CreateTime: 1698310534000
                    Attributes:
                      - Key: "k3"
                        Value: "Value"
                      - Key: "k4"
                        Value: "Value1"

components:
  schemas:
    QueryFriendListRequest:
      type: object
      required: [FromUserId, Limit, Next]
      properties:
        FromUserId:
          type: string
          description: Query the friend list of this UserID (who has logged in to the ZIM service by calling the login method on the client, or has completed registration by calling the [server-side API](/zim-server/user/batch-register-users)).
          maxLength: 32
          example: "zego"
        Limit:
          type: number
          description: How many friends' information to retrieve at a time. Value range is [0, 100]. If not filled in or the value is 0 or greater than 100, the value is 100.
          minimum: 0
          maximum: 100
          example: 100
        Next:
          type: number
          description: |
            Pagination flag. Fill in 0 for the first time, and then fill in the Next value returned last time. When the returned Next is 0, it means the friend list retrieval is complete.

            For example, if FromUserId has 250 friends, when calling this API to query:

            - First call: Limit is 100, Next is empty, query friends 1 ~ 100; the Next value in the returned result is num1.
            - Second call: Limit is 100, Next is num1, query friends 101 ~ 200; the Next value in the returned result is num2.
            - Third call: Limit is 100, Next is num2, query friends 201 ~ 250; query is complete, the Next in the returned result is 0.
          example: 2
    FriendAttribute:
      type: object
      properties:
        Key:
          type: string
          description: Friend attribute key.
          example: "k1"
        Value:
          type: string
          description: Friend attribute value.
          example: "Value"
    FriendInfoItem:
      type: object
      properties:
        UserId:
          type: string
          description: Friend user ID.
          example: "UserA"
        UserName:
          type: string
          description: 	User name.
          example: "UserNameA"
        Avatar:
          type: string
          description: User avatar URL.
          example: "Avatar1"
        Wording:
          type: string
          description: Wording when establishing friend relationship.
          example: "Wording1"
        FriendAlias:
          type: string
          description: FromUserId's remark for this friend.
          example: "FriendAlias1"
        CreateTime:
          type: number
          description: Friend relationship establishment time in milliseconds (ms).
          example: 1698310534000
        Attributes:
          type: array
          description: Friend attributes.
          items:
            $ref: '#/components/schemas/FriendAttribute'
    QueryFriendListResponse:
      type: object
      properties:
        Code:
          type: integer
          description: |
            Return code.

            <table>
            <tbody><tr>
            <th>Return Code</th>
            <th>Description</th>
            <th>Suggested Solution</th>
            </tr>
            <tr>
            <td>660000001</td>
            <td>General business error.</td>
            <td>Please retry or contact ZEGOCLOUD Technical Support.</td>
            </tr>
            <tr>
            <td>660000002</td>
            <td>Parameter error.</td>
            <td>Please check the request parameters.</td>
            </tr>
            <tr>
            <td>660300005</td>
            <td>The API call frequency exceeds the AppID-level limit.</td>
            <td>Please try again later.</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: Description of the request result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        TotalCount:
          type: integer
          format: int32
          description: Total number of current friends.
          example: 500
        Next:
          type: number
          description: |
            Pagination flag. Non-zero means there is still friend information not returned; 0 means all friend information has been returned.
            > **Note**
            >
            > In addition to the above description, this field has no association with the list information. Do not make any other logic based on this.
          example: 1
        FriendInfos:
          type: array
          description: Friend data list.
          items:
            $ref: '#/components/schemas/FriendInfoItem'
