openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - user

paths:
  /:
    post:
      tags: [user]
      summary: Query user information
      description: |
        Query user information by user ID, including user name, user avatar, and extended field.

        <Note title="QPS Limit">20 times/s</Note>
      operationId: query-user-information
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=QueryUserInfos
          required: true
          schema:
            type: string
            enum: [QueryUserInfos]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [UserIds]
              properties:
                UserIds:
                  type: array
                  description: |
                    User ID list to query (who have logged in to the ZIM service by calling the login method on the client, or have completed registration by calling the [server-side API](https://www.zegocloud.com/docs/zim-server/user/batch-register-users)). A maximum of 100 user IDs can be queried. Each user ID does not exceed 64 bytes.
                    
                    >**Note**
                    >
                    > UserIds Only supports numbers, English characters, and '!'，'#'，'$'，'%'，'&'，'('，')'，'+'，'-'，':'，';'，'<'，'='，'.'，'>'，'?'，'@'，'['，']'，'^'，'_'，' '，'{'，'}'，'|'，'~'。
                  maxItems: 100
                  items:
                    type: string
                    maxLength: 64
                    example: "userA"
                  example: ["userA", "userB", "userC"]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryUserInfosResponse'

components:
  schemas:
    QueryUserInfosResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            The following only lists the Code and SubCode related to the API business logic. For complete return codes, please refer to [Global Return Codes](/zim-server/return-codes).
            <table>
            <tbody><tr>
            <th>Code / SubCode</th>
            <th>Description</th>
            <th>Suggested Solution</th>
            </tr>
            <tr>
            <td>660000001</td>
            <td>General business error.</td>
            <td>Please retry or contact ZEGOCLOUD Technical Support.</td>
            </tr>
            <tr>
            <td>660000002</td>
            <td>Non-existent user ID, or the user has logged out.</td>
            <td>Please check the input parameters。</td>
            </tr>
            <tr>
            <td>660300005</td>
            <td>The API call frequency exceeds the AppID-level limit.</td>
            <td>Please try again later.</td>
            </tr>
            <tr>
            <td>660700008</td>
            <td>Error getting user information.</td>
            <td>Please check if the user ID is correct, or contact ZEGOCLOUD Technical Support.</td>
            </tr>
            <tr>
            <td>660700015</td>
            <td>User is not registered.</td>
            <td>Please register the user first.</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: Description of the request result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        Result:
          type: array
          description: Query success result.
          items:
            type: object
            properties:
              UserId:
                type: string
                description: User ID that was successfully queried.
                example: "UserA"
              UserName:
                type: string
                description: User name.
                example: "userName"
              UserAvatar:
                type: string
                description: User avatar URL.
                example: "avatar"
              Extra:
                type: string
                description: Extended field.
                example: "extra"
        ErrorList:
          type: array
          description: |
            Query failure list. Returned through this field when the user ID does not exist or the user has logged out.
            <ul>
            <li>Code is 0:</li>
            <li>ErrorList is empty, all user online statuses are successfully queried.</li>
            <li>ErrorList is not empty, indicating that some user online status queries failed. Please refer to SubCode for processing.</li>
            </ul>
            <ul>
            <li>Code is not 0:</li>
            <li>ErrorList is empty, indicating parameter error, API frequency limit, or system error.</li>
            <li>ErrorList is not empty, indicating that all user online status queries failed.</li>
            </ul>
          items:
            type: object
            properties:
              UserId:
                type: string
                description: User ID that failed to be queried.
                example: "UserB"
              SubCode:
                type: number
                description: |
                  Return code when query fails. For complete return codes, please refer to the Code description or [Global Return Codes](/zim-server/return-codes).
                example: 660000002
