openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - user

paths:
  /:
    get:
      tags: [user]
      summary: Query users online status
      description: |
        Query the online status of users. Supports querying a single user or batch querying multiple users' online status.

        <Note title="Note">QPS Limit: 20 times/s</Note>
      operationId: query-users-online-status
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=QueryUserOnlineState
          required: true
          schema:
            type: string
            enum: [QueryUserOnlineState]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - name: UserId
          in: query
          required: true
          description: |
            User ID list to query (who have logged in to the ZIM service by calling the login method on the client, or have completed registration by calling the [server-side API](https://www.zegocloud.com/docs/zim-server/user/batch-register-users)). A maximum of 100 user IDs can be queried.
            
            示例：UserId[]=a&UserId[]=b

            >**Note**
            >
            > UserId Only supports numbers, English characters, and '!'，'#'，'$'，'%'，'&'，'('，')'，'+'，'-'，':'，';'，'<'，'='，'.'，'>'，'?'，'@'，'['，']'，'^'，'_'，' '，'{'，'}'，'|'，'~'。
          schema:
            type: array
            maxItems: 100
            items:
              type: string
              maxLength: 64
              example: "a"
          style: form
          explode: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryUserOnlineStateResponse'
                example:
                  Code: 0
                  Message: success
                  RequestId: "343649807833778782"
                  Result:
                    - UserId: "id1"
                      Status: "Offline"
                    - UserId: "id2"
                      Status: "Online"
                  ErrorList:
                    - UserId: "id4"
                      SubCode: 660200001

components:
  schemas:
    QueryUserOnlineStateResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            以下仅列出了接口业务逻辑相关的 Code 和 SubCode ，完整返回码请参考 [全局返回码](/zim-server/return-codes)。
            <table>
            <tbody><tr>
            <th>Code / SubCode</th>
            <th>说明</th>
            </tr>
            <tr>
            <td>660000011</td>
            <td>用户个数超过限制。</td>
            </tr>
            <tr>
            <td>660200001</td>
            <td>不存在的User ID.<br/>用户已经登出。<br/>用户仅通过服务端注册，并未登录过。</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: Description of the request result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        Result:
          type: array
          description: 查询的用户状态结果。用户处于在线状态或离线状态时，通过该字段返回。
          items:
            type: object
            properties:
              UserId:
                type: string
                description: 在线或离线用户的 ID。
                example: "id1"
              Status:
                type: string
                description: |
                  用户状态，包括：
                  - Online：Online.
                  - Offline：Offline.
                enum: [Online, Offline]
                example: "Offline"
        ErrorList:
          type: array
          description: |
            查询失败列表。用户 ID 不存在或者用户已登出时，通过该字段返回。
            <ul>
            <li>Code 为 0：</li>
            <li>  ErrorList 为空，全部用户在线状态查询成功。</li>
            <li>  ErrorList 不为空，表示部分用户在线状态查询失败，请参考 SubCode 处理。</li>
            </ul>
            <ul>
            <li>Code 不为 0：</li>
            <li>  ErrorList 为空，表示参数错误、接口频率限制、系统错误。</li>
            <li>  ErrorList 不为空，表示所有用户在线状态查询失败。</li>
            </ul>
          items:
            type: object
            properties:
              UserId:
                type: string
                description: 不存在的用户 ID 或已登出用户的 ID。
                example: "id4"
              SubCode:
                type: number
                description: |
                  查询失败时的返回码，完整返回码请参考 Code 说明或者 [全局返回码](/zim-server/return-codes)。
                example: 660200001
