openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - call-invitation
      summary: 拒绝呼叫邀请
      description: |
        通过该接口可以为用户拒绝呼叫邀请。

        用户拒绝邀请后，通过以下 ZIM SDK 的回调接口，其他处于呼叫中的用户会收到呼叫用户状态变更的通知：

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |-----|---------|--------|---------|
        | [callUserStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-call-user-state-changed-call-id) | [onCallUserStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~java_android~class~ZIMEventHandler#on-call-user-state-changed) | [callUserStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-call-user-state-changed-call-id) | [onCallUserStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-call-user-state-changed) |
        
        | Web-25% | 小程序-25% | Flutter-25% | React Native-25% |
        |-----|---------|---------|--------------|
        | [callUserStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#call-user-state-changed) | [callUserStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#call-user-state-changed) | [onCallUserStateChanged](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onCallUserStateChanged.html) | [callUserStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#call-user-state-changed) |
        
        | Unity3D-25% | uniapp \| uniapp x-25% | HarmonyOS-25% |
        |---------|---------|------------|
        | [OnCallUserStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-call-user-state-changed) | [callUserStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#call-user-state-changed) | [callUserStateChanged](https://doc-zh.zego.im/article/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#call-user-state-changed) |

        <Note title="说明">参数 FromUserId 仅支持数字，英文字符和 \{'!'，'#'，'$'，'%'，'&'，'('，')'，'+'，'-'，':'，';'，'\<'，'='，'.'，'\>'，'?'，'@'，'['，']'，'^'，'_'，' '，'\{'，'\}'，'|'，'~'\}。</Note>

        <Note title="说明">调用频率限制：20 次/秒</Note>
      operationId: reject-a-call-invitation
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=CallReject
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [CallReject]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - name: FromUserId
          in: query
          required: true
          description: |
            为此 ID（已在客户端调用 `login` 方法登录 ZIM 服务，或已调用 [服务端 API](/zim-server/user/batch-register-users) 完成注册）的用户拒绝邀请。
          schema:
            type: string
            maxLength: 32
            example: "callee_user"
        - name: CallId
          in: query
          required: true
          description: 呼叫 ID。
          schema:
            type: string
            maxLength: 32
            example: "call123"
        - name: ExtendedData
          in: query
          required: false
          description: 扩展字段，长度上限为 2 KB。
          schema:
            type: string
            maxLength: 2048
            example: "Extended data"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallRejectResponse'

components:
  schemas:
    CallRejectResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            返回码。

            以下仅列出了接口业务逻辑相关的返回码，完整返回码请参考 [全局返回码](/zim-server/return-codes)。
            <table>
            <tbody><tr>
            <th>返回码</th>
            <th>说明</th>
            <th>处理建议</th>
            </tr>
            <tr>
            <td>660000002</td>
            <td>参数错误。</td>
            <td>请检查请求参数。</td>
            </tr>
            <tr>
            <td>660300005</td>
            <td>调用接口的频率超出了 AppID 级别限制。</td>
            <td>请稍后再试。</td>
            </tr>
            <tr>
            <td>660500002</td>
            <td>操作者用户未注册。</td>
            <td>请先让操作者用户注册 ZIM 服务。</td>
            </tr>
            <tr>
            <td>660900004</td>
            <td>获取呼叫信息异常</td>
            <td>请检查呼叫是否存在，或者稍后再试。</td>
            </tr>
            <tr>
            <td>660900005</td>
            <td>呼叫已结束，无法对其进行操作。</td>
            <td>无需处理。</td>
            </tr>
            <tr>
            <td>660900006</td>
            <td>呼叫邀请已超时，无法对其进行操作。</td>
            <td>无需处理。</td>
            </tr>
            <tr>
            <td>660900008</td>
            <td>该呼叫没有邀请操作用户，无法对其进行操作。</td>
            <td>无需处理。</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: 操作结果描述。
          example: success
        RequestId:
          type: string
          description: 请求 ID。
          example: '343649807833778782'
