openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      summary: 获取鉴权文件
      description: 获取 ZIM Audio 鉴权文件。
      operationId: obtain-a-license
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://zim-api.zego.im/?Action=CgiDescribeZIMAudioLicense
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [CgiDescribeZIMAudioLicense]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/obtain-a-license'

components:
  schemas:
    obtain-a-license:
      type: object
      properties:
        Code:
          type: integer
          description: |
            返回码。

            以下仅列出了接口业务逻辑相关的返回码，完整返回码请参考 [全局返回码](/zim-server/return-codes)。
            <table>
            <thead>
            <tr><th>返回码</th><th>说明</th><th>处理建议</th></tr>
            </thead>
            <tbody>
            <tr><td>910001</td><td>参数错误。</td><td>请检查参数。</td></tr>
            <tr><td>910002</td><td>证书无效。</td><td>请联系 ZEGO 技术支持。</td></tr>
            <tr><td>910003</td><td>服务内部问题。</td><td>请联系技术支持。</td></tr>
            <tr><td>910004</td><td>授权信息有误。</td><td>请检查公共参数的认证信息。</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: 请求结果的说明信息。
          example: "Success."
        Data:
          type: object
          description: '"Code" 为 0 时，此参数为鉴权文件。'
          properties:
            License:
              type: string
              description: 鉴权文件的内容，可在 7 天内重复使用。
              example: "1234567890QWERTYUIOASDFGHJKLZXCVNM"
      example:
        Code: 0
        Message: "Success."
        Data:
          License: "1234567890QWERTYUIOASDFGHJKLZXCVNM"