openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGOCLOUD Support
    email: support@zegocloud.com

servers:
  - url: https://whiteboard-api.zego.im
    description: Whiteboard permission service unified access address (region-independent)
  - url: https://whiteboard-api-sha.zego.im
    description: Whiteboard permission service - Mainland China (Shanghai)
  - url: https://whiteboard-api-hkg.zego.im
    description: Whiteboard permission service - Hong Kong, Macao and Taiwan (Hong Kong)
  - url: https://whiteboard-api-fra.zego.im
    description: Whiteboard permission service - Europe (Frankfurt)
  - url: https://whiteboard-api-lax.zego.im
    description: Whiteboard permission service - US West (California)
  - url: https://whiteboard-api-bom.zego.im
    description: Whiteboard permission service - Asia Pacific (Mumbai)
  - url: https://whiteboard-api-sgp.zego.im
    description: Whiteboard permission service - Southeast Asia (Singapore)

tags:
  - whiteboard

paths:
  /:
    get:
      tags: [whiteboard]
      summary: GetWhiteboardRoomAuth
      description: |
        Call this API to query the default whiteboard permissions of a room.

        <Note title="Note">Rate limit\: 50 requests/second (Test environment\: 1 request/second).</Note>
      operationId: get-white-board-room-auth
      parameters:
        - name: Action
          in: query
          description: |
            > API endpoint parameter
            >
            > https://whiteboard-api.zego.im/?Action=GetWhiteboardRoomAuth
          required: true
          schema:
            type: string
            enum: [GetWhiteboardRoomAuth]
          style: form
          explode: true
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
        - name: RoomId
          in: query
          description: The room ID to query.
          required: true
          schema:
            type: string
          style: form
          explode: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetWhiteboardRoomAuthResponse'

components:
  schemas:
    GetWhiteboardRoomAuthResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            Only business-related return codes are listed below. For common return codes, please refer to [Common error codes](/super-board-server/common-error-codes).

            <table>
            <tbody><tr>
            <th>Return code</th>
            <th>Description</th>
            </tr>
            <tr>
            <td>120000001</td>
            <td>Signature authentication failed.</td>
            </tr>
            <tr>
            <td>120000002</td>
            <td>Invalid input parameters.</td>
            </tr>
            <tr>
            <td>120000104</td>
            <td>Failed to query room permissions.</td>
            </tr>
            <tr>
            <td>120000301</td>
            <td>Room does not exist.</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: Details.
          example: "SUCCESS"
        RequestId:
          type: string
          description: Unique request ID generated by ZEGOCLOUD.
          example: "223708046046603340"
        Data:
          type: object
          description: If Data is empty, it means no whiteboard permissions have been set for this room.
          properties:
            RoomId:
              type: string
              description: Room ID.
              example: "RoomName"
            ModuleAuth:
              type: array
              description: |
                Whiteboard operation permission set.
                - 0\: No permission
                - 1\: Allow zooming the whiteboard
                - 2\: Allow scrolling the whiteboard
              items:
                type: integer
                enum: [0, 1, 2]
              example: [1, 2]
            GraphicAuth:
              type: array
              description: |
                Graphic element operation permission set.
                - 0\: No operation permission
                - 2\: Allow modifying graphic elements created by others
                - 4\: Allow erasing graphic elements created by others
                - 8\: Allow moving graphic elements created by others
                - 16\: Allow clearing graphic elements
                - 32\: Allow creating graphic elements
              items:
                type: integer
                enum: [0, 2, 4, 8, 16, 32]
              example: [32, 2]

