openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGOCLOUD Support
    email: support@zegocloud.com

servers:
  - url: https://whiteboard-api.zego.im

tags:
  - whiteboard

paths:
  /:
    get:
      tags: [whiteboard]
      summary: SetWhiteboardUserAuth
      description: |
        Call this API to set a user's whiteboard permissions.
        - When a user leaves the room or disconnects, the user's permissions are cleared. If the user logs into the same room again and wants to use user permissions, they need to set the user permissions again.
        - When the room that the user is in is destroyed, the user's permissions are also cleared.

        Set the user permissions to\:

        - Whiteboard can be zoomed and scrolled.
        - Can create graphic elements and modify others' graphic elements.

        <Note title="Note">Rate limit\: 50 requests/second (Test environment\: 1 request/second).</Note>
      operationId: set-white-board-user-auth
      parameters:
        - name: Action
          in: query
          description: |
            > API endpoint parameter
            >
            > https://whiteboard-api.zego.im/?Action=SetWhiteboardUserAuth
          required: true
          schema:
            type: string
            enum: [SetWhiteboardUserAuth]
          style: form
          explode: true
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
        - name: RoomId
          in: query
          description: The room ID to set permissions for.
          required: true
          schema:
            type: string
          style: form
          explode: true
        - name: UserId
          in: query
          description: The user ID to set permissions for.
          required: true
          schema:
            type: string
          style: form
          explode: true
        - name: ModuleAuth
          in: query
          description: |
            Whiteboard operation permission set. Empty arrays are not allowed.
            - 0\: No permission
            - 1\: Allow zooming the whiteboard
            - 2\: Allow scrolling the whiteboard

            Example\: ModuleAuth[]=1&ModuleAuth[]=2
          required: true
          schema:
            type: array
            items:
              type: number
              enum: [0, 1, 2]
          style: form
          explode: true
        - name: GraphicAuth
          in: query
          description: |
            Graphic element operation permission set. Empty arrays are not allowed.
            - 0\: No operation permission
            - 2\: Allow modifying graphic elements created by others
            - 4\: Allow erasing graphic elements created by others
            - 8\: Allow moving graphic elements created by others
            - 16\: Allow clearing graphic elements
            - 32\: Allow creating graphic elements

            Example\: GraphicAuth[]=32&GraphicAuth[]=2
          required: true
          schema:
            type: array
            items:
              type: number
              enum: [0, 2, 4, 8, 16, 32]
          style: form
          explode: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetWhiteboardUserAuthResponse'

components:
  schemas:
    SetWhiteboardUserAuthResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            Only business-related return codes are listed below. For common return codes, please refer to [Common error codes](/super-board-server/common-error-codes).

            <table>
            <tbody><tr>
            <th>Return code</th>
            <th>Description</th>
            </tr>
            <tr>
            <td>120000001</td>
            <td>Signature authentication failed.</td>
            </tr>
            <tr>
            <td>120000002</td>
            <td>Invalid input parameters.</td>
            </tr>
            <tr>
            <td>120000101</td>
            <td>Failed to set user permissions.</td>
            </tr>
            <tr>
            <td>120000105</td>
            <td>Failed because an empty array was passed for the permission set.</td>
            </tr>
            <tr>
            <td>120000106</td>
            <td>Invalid permission value set in the permission collection.</td>
            </tr>
            <tr>
            <td>120000201</td>
            <td>User does not exist.</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: Details.
          example: "SUCCESS"
        RequestId:
          type: string
          description: Unique request ID generated by ZEGOCLOUD.
          example: "2237080460466033406"

