openapi: 3.0.0
info:
  title: Super Board Server API - Shared Components
  version: 1.0.0

# Shared server configuration (Super Board service)
servers:
  - url: https://docs-api.zego.im
    description: File transcoding service unified access address (region-independent)
  - url: https://docs-api-sha.zego.im
    description: File transcoding service - Mainland China (Shanghai)
  - url: https://docs-api-hkg.zego.im
    description: File transcoding service - Hong Kong, Macao and Taiwan (Hong Kong)
  - url: https://docs-api-fra.zego.im
    description: File transcoding service - Europe (Frankfurt)
  - url: https://docs-api-lax.zego.im
    description: File transcoding service - US West (California)
  - url: https://docs-api-bom.zego.im
    description: File transcoding service - Asia Pacific (Mumbai)
  - url: https://docs-api-sgp.zego.im
    description: File transcoding service - Southeast Asia (Singapore)
  - url: https://whiteboard-api.zego.im
    description: Whiteboard permission service unified access address (region-independent)
  - url: https://whiteboard-api-sha.zego.im
    description: Whiteboard permission service - Mainland China (Shanghai)
  - url: https://whiteboard-api-hkg.zego.im
    description: Whiteboard permission service - Hong Kong, Macao and Taiwan (Hong Kong)
  - url: https://whiteboard-api-fra.zego.im
    description: Whiteboard permission service - Europe (Frankfurt)
  - url: https://whiteboard-api-lax.zego.im
    description: Whiteboard permission service - US West (California)
  - url: https://whiteboard-api-bom.zego.im
    description: Whiteboard permission service - Asia Pacific (Mumbai)
  - url: https://whiteboard-api-sgp.zego.im
    description: Whiteboard permission service - Southeast Asia (Singapore)

components:
  parameters:
    # Re-export ZEGOCLOUD global shared parameters for convenient local reference
    AppId:
      $ref: "../../../../snippets/common/en/openapi/zego-shared-components.yaml#/components/parameters/AppId"
    SignatureNonce:
      name: SignatureNonce
      in: query
      description: 💡Public parameter. A 16-character hexadecimal random string (hex encoding of 8-byte random number). Refer to <a href="/super-board-server/accessing-server-apis#signature-sample-code">Signature sample code</a> for how to generate.
      required: true
      schema:
        type: string

    Timestamp:
      name: Timestamp
      in: query
      description: 💡Public parameter. Current Unix timestamp, in seconds. Refer to <a href="/super-board-server/accessing-server-apis#signature-sample-code">Signature sample code</a> for how to generate, with a maximum error of 10 minutes.
      required: true
      schema:
        type: integer
        format: int64
    SignatureVersion:
      $ref: "../../../../snippets/common/en/openapi/zego-shared-components.yaml#/components/parameters/SignatureVersion"
    Signature:
      name: Signature
      in: query
      description: 💡Public parameter. Signature, used to verify the legitimacy of the request. Refer to [Signing the requests](/super-board-server/accessing-server-apis#signature-mechanism) for how to generate.
      required: true
      schema:
        type: string

