openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: Real-time Voice/Video API Support
    email: support@zegocloud.com

tags:
  - name: room

servers:
  $ref: '../../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags:
        - room
      summary: DelForbidUserRule
      description: |
        Delete prohibition rules for users entering the Room. When certain user prohibition rules become invalid, are no longer needed, or the total number of rules exceeds the limit, you can delete user prohibition rules through this interface.

        After deletion, you can use [Query User Prohibition Rules](./describe-forbid-user-rules.mdx) to verify whether the corresponding user prohibition rules have been successfully deleted.

        <Note title="Call Frequency Limit">All rooms under the same AppID are limited to 10 times/second.</Note>

        <Warning title="Notice">
        The maximum number of rules supported varies by RuleType. If you no longer need certain rules, please call this interface to clean them up in a timely manner. Additionally, ZEGOCLOUD will periodically clean up **invalid** prohibition rules in the database.
        </Warning>
      operationId: del-forbid-user-rule
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameters
            >
            > https://rtc-api.zego.im?Action=DelForbidUserRule
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DelForbidUserRule]
          style: form
          explode: true
        # 公共参数
        - $ref: '../../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../../shared-components.yaml#/components/parameters/SignatureVersion'
        # 业务参数
        - name: RuleType
          in: query
          description: |
            The type of prohibition rule to delete:
            - 1: Prohibit users by IP address;
            - 2: Prohibit users by RoomId;
            - 3: Prohibit users by UserId;
            - 4: Prohibit users by both RoomId and UserId.

          required: true
          schema:
            type: integer
            format: int32
            enum: [1, 2, 3, 4]
        - name: IP
          in: query
          description: IP address. Required when RuleType is 1.
          required: false
          schema:
            type: string
        - name: RoomId
          in: query
          description: Room ID. Required when RuleType is 2 or 4.
          required: false
          schema:
            type: string
        - name: UserId
          in: query
          description: User ID. Required when RuleType is 3 or 4.
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DelForbidUserRuleResponse'

components:
  schemas:
    DelForbidUserRuleResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          example: 0
          description: |
            Return code. The following only lists some return codes related to API business logic. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).

            <table>
              <thead>
                <tr>
                  <th>Return Code</th>
                  <th>Description</th>
                  <th>Suggested Action</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>0</td>
                  <td>Request successful.</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>Request failed.</td>
                  <td>Please contact ZEGOCLOUD technical support.</td>
                </tr>
                <tr>
                  <td>2</td>
                  <td>Input parameter error.</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>9</td>
                  <td>Permission to use this interface has not been granted.</td>
                  <td>Please contact ZEGOCLOUD technical support.</td>
                </tr>
                <tr>
                  <td>206</td>
                  <td>App request QPS too high and was limited.</td>
                  <td>Reduce request frequency, or contact ZEGOCLOUD technical support to increase the QPS limit threshold.</td>
                </tr>
                <tr>
                  <td>50123</td>
                  <td>The number of currently valid prohibition rules exceeds the limit.</td>
                  <td>Please reduce the number of rules.</td>
                </tr>
              </tbody>
            </table>
        Message:
          type: string
          example: success
          description: Description of the operation result.
        RequestId:
          type: string
          example: TestRequestId1675674022729915000
          description: Request ID.
