openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: moderation

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    post:
      tags: [moderation]
      summary: StartCensorAudioV2
      description: |
        音频流审核是 ZEGO 实时音视频产品的互动扩展服务。开发者通过音频流审核接口，可以调用实时音频审核，包含音频语义识别和音频特征（音调、音色、声纹、旋律等）识别，ZEGO 会通过 [音频流审核回调](/real-time-video-server/callback/moderation/audio) 或配置的自定义回调地址，把识别结果发送给开发者，开始音频流审核功能与 [结束音频流审核功能](/real-time-video-server/api-reference/moderation/stop-censor-audio) 请结合使用。

        <Warning title="注意">
        使用该接口前，请参考 [控制台 - 云市场 - 数美内容审核](/console/cloud-market/shumei-moderation)，按照页面指引，自助开通 `数美内容审核` 相关权限。
        </Warning>

        <Note title="说明">
        使用 POST 请求方法传递参数时：
        - Body 中的参数直接传 JsonObject 格式即可，无需序列化为 String 格式。
        - Headers 中，设置 “Content-type” 为 “application/json”。
  
        </Note>
        <Note title="调用频率限制">同一个 AppID 下所有房间：100 次/秒</Note>
        
        以下请求参数列表仅列出了接口请求参数和部分公共参数，完整公共参数列表请参考 [调用方式](./../accessing-server-apis.mdx#公共请求参数) 中的 “公共请求参数”。
      operationId: start-censor-audio
      parameters:
        - name: Action
          in: query
          required: true
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=StartCensorAudioV2
          schema: { type: string, enum: [StartCensorAudioV2] }
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartCensorAudioRequest'
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartCensorAudioResponse'

components:
  schemas:
    StartCensorAudioRequest:
      type: object
      required: [RoomId, EventId, AudioLanguage, RiskTypeList]
      properties:
        RoomId:
          type: string
          description: |
            需要进行音频审核的房间 ID。
            默认会将该房间内的所有流送审，如果房间内有流不需要送审（比如受信任的用户所推的流），请在调用客户端 SDK 'startPublishingStream' 推流时，将 'ZegoPulisherConfig.streamCensorshipFlag' 设置为不允许送审。
          example: "room_1"
        EventId:
          type: string
          description: |
            场景标识。
            通过该参数标识音频流对应的场景。审核策略可以根据场景进行调整，从而实现不同的场景审核尺度的控制。
            - 直播：live_streaming
            - 语聊房：audio_room
            - 1v1：private_chat

            如果以上可选值不能完全满足您的使用诉求，请联系 ZEGO 技术支持。
          example: "live_streaming"
        ResultCallbackUrl:
          type: string
          description: |
            自定义审核结果的回调地址。
            如果您需要将此次审核任务的审核结果，通过其他的回调地址抛出，可以通过本参数实现。如果不需要，可以在 ZEGO 控制台配置统一的回调地址，详情请参考 [控制台 - 云市场 - 数美内容审核](/console/cloud-market/shumei-moderation#配置音频视频流审核回调地址)。
          example: ""
        StatusCallbackUrl:
          type: string
          description: |
            自定义审核状态回调地址。
            如果您需要将此次审核任务的审核状态，通过其他的回调地址抛出，可以通过本参数实现。如果不需要，可以在 ZEGO 后台配置统一的回调地址，详情请参考 [控制台 - 云市场 - 数美内容审核](/console/cloud-market/shumei-moderation#配置音频视频流审核回调地址)。
          example: ""
        IsMixingEnabled:
          type: integer
          format: int32
          enum: [0,1]
          default: 0
          description: |
            是否通过混流方式送审：
            - 0：默认值，不混流送审，即单流送审。房间内每条音频流独立审核。
            - 1：混流送审，房间内所有音频流混成一路流。

            混流送审可以节省音频审核的费用，但是相应地不容易准确区分违规的流和用户，请根据业务的实际情况选择合适的送审方式。
          example: 0
        AudioLanguage:
          type: string
          enum: [zh,ja,ko,th,vi,ms,tl,id,hi,ar,tr,en,es,pt,it,fr,de,ru]
          description: |
            音频流语种。在需要识别音频流的语义时，请准确传入该值。若以下语种无法满足需求请联系技术支持进行配置：
            - zh：中文
            - ja：日语
            - ko：韩语
            - th：泰语
            - vi：越南语
            - ms：马来语
            - tl：菲律宾语
            - id：印尼语
            - hi：印地语
            - ar：阿拉伯语
            - tr：土耳其语
            - en：英文
            - es：西班牙语
            - pt：葡萄牙语
            - it：意大利语
            - fr：法语
            - de：德语
            - ru：俄语
          example: "zh"
        RiskTypeList:
          type: array
          items: { type: string }
          minItems: 1
          description: |
            风险类型列表。RiskTypeList 与 BusinessTypeList 至少一个不为空，数组中可添加的值如下：

            音频语义：
            - ADLAW：违反广告法
            - EROTIC：色情
            - DIRTY：辱骂
            - POLITY：涉政
            - BAN：违禁
            - VIOLENT：暴恐
            - ADVERT：广告

            音频特征：
            - MOAN：娇喘
            - ANTHEN：国歌识别
            - BANDAUDIO：违禁歌曲
            - AUDIOPOLITICAL：详情请联系 ZEGO 技术支持
          example: ["ADLAW", "ADVERT", "AUDIOPOLITICAL", "BAN", "DIRTY", "EROTIC", "MOAN", "POLITY", "VIOLENT"]
        BusinessTypeList:
          type: array
          items: { type: string }
          description: |
            业务识别类别。
            
            RiskTypeList 与 BusinessTypeList 至少一个不为空，数组中可添加的值如下：

            音频语义：
            - MOINIR：未成年人

            音频特征：
            - SING：唱歌
            - LANGUAGE：语种识别
            - VOICE：人声属性识别

            音频流的识别并不仅限于违规内容，也可以辅助开发者进行业务运营。
            如果以上可选值无法满足您的业务诉求，请联系 ZEGO 技术支持。
        LabelLanguage:
          type: string
          enum: [zh,en]
          description: |
            回调信息中标签的语种类型（Label 相关）：
            - zh：中文
            - en：英文
          example: "zh"
        ReturnAllText:
          type: integer
          format: int32
          enum: [0,1]
          default: 0
          description: |
            是否返回当前 10s 片段的所有文本。审核结果的风险等级将分为以下三类：

            PASS：正常内容，建议直接放行。

            REVIEW：可疑内容，建议人工审核。
            
            REJECT：违规内容，建议直接拦截。
            - 0：返回风险等级为非 pass 的音频片段文本（默认值）
            - 1：返回所有风险等级的音频文本片段
          example: 1
        ReturnPreText:
          type: integer
          format: int32
          enum: [0,1]
          default: 0
          description: |
            是否返回违规片段的前一个片段语义：
            - 0：不返回违规片段前一个片段文字
            - 1：返回违规片段前一个片段文字
          example: 1
        ReturnPreAudio:
          type: integer
          format: int32
          enum: [0,1]
          default: 0
          description: |
            是否返回违规片段的前一个音频片段链接：
            - 0：不返回违规片段的前一个音频片段链接，只返回违规片段音频链接（默认值）
            - 1：返回违规片段前一个片段音频链接
          example: 1
        ReturnFinishInfo:
          type: integer
          format: int32
          enum: [0,1]
          default: 0
          description: |
            审核任务结束时，是否进行"审核任务状态"回调：
            - 0：审核结束时不发送结束通知
            - 1：审核结束时发起结束通知
          example: 1
    StartCensorAudioResponse:
      type: object
      properties:
        Code: 
          type: integer
          format: int32
          description: |
            返回码。
            以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。
            <table>
              <thead>
                <tr><th>返回码</th><th>说明</th><th>处理建议</th></tr>
              </thead>
              <tbody>
                <tr><td>50006、50007</td><td>HTTP 请求失败。</td><td>请稍后重试（建议 300s），或联系 ZEGO 技术支持。</td></tr>
                <tr><td>50009</td><td>审核失败。</td><td>请稍后重试（建议 300s），或联系 ZEGO 技术支持。</td></tr>
                <tr><td>50117</td><td>配置错误，未开通数美权限。</td><td>请参考 <a href="/console/cloud-market/shumei-moderation">控制台 - 云市场 - 数美内容审核</a>，按照页面指引，自助开通数美内容审核相关权限。</td></tr>
              </tbody>
            </table>
          example: 0
        Message: 
          type: string
          description: 操作结果描述
          example: "success"
        RequestId: 
          type: string
          description: 请求 ID
          example: "TestRequestId1635941437248027000"
        Data:
          type: object
          description: 响应数据
          properties:
            TaskId:
              type: string
              description: 审核任务 ID，用于结束审核任务
              example: "15515d8fef61801b05c22e0ebbe8681f"

