openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: moderation

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    post:
      tags: [moderation]
      summary: StartCensorVideoV2
      description: |
        视频流审核是 ZEGO 实时音视频产品的互动扩展服务。开发者通过视频流审核接口，可以调用实时视频审核对视频中的音频和画面进行审核，包括音频的语义和特征（音调、音色、声纹、旋律等）识别，视频画面中的文字语义和内容的识别。ZEGO 会通过 [视频流审核回调](/real-time-video-server/callback/moderation/video) 或配置的自定义回调地址，把识别结果发送给开发者，开始视频流审核功能与 [结束视频流审核](/real-time-video-server/api-reference/moderation/stop-censor-video) 请结合使用。

        <Warning title="注意">
        使用该接口前，请参考 [控制台 - 云市场 - 数美内容审核](/console/cloud-market/shumei-moderation)，按照页面指引，自助开通 `数美内容审核` 相关权限。
        
        </Warning>

        <Note title="调用频率限制">同一个 AppID 下所有房间：100 次/秒</Note>
        ## 常见问题

        1. **开始音频/视频流审核 api，若不调用结束音频/视频流审核的api会怎么样？**

            在拉空流 5min 左右会自动结束，建议在结束审核的时候，主动调用接口结束。
        2. **音频/视频流审核结果的回调中怎么获取到是哪条流违规呢？**

            数美在完成审核后会将审核结果按照 10s 音频片段 AudioUrl 的方式返回多个回调，在目前的返回结果中没有直接暴露 streamID 信息，可以通过截取 resultTaskId 中的信息获取。
            
            示例（假设 streamID 为 0001，可以看到 AudioUrl 中包含 streamID 0001）：
            <Frame width="auto" height="auto" >
            <img src="https://media-resource.spreading.io/docuo/workspace741/896bc39e2e65b82d5670b01b7c131c30/5852a1ffcc.png" />
            </Frame>
      operationId: start-censor-video
      parameters:
        - name: Action
          in: query
          required: true
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=StartCensorVideoV2
          schema: { type: string, enum: [StartCensorVideoV2] }
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartCensorVideoRequest'
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartCensorVideoResponse'

components:
  schemas:
    StartCensorVideoRequest:
      type: object
      required: [RoomId, EventId, VideoParam]
      properties:
        RoomId:
          type: string
          description: |
            需要进行音频审核的房间 ID。
            默认会将该房间内的所有流送审，如果房间内有流不需要送审（比如受信任的用户所推的流），请在调用客户端 SDK 'startPublishingStream' 推流时，将 'ZegoPulisherConfig.streamCensorshipFlag' 设置为不允许送审。
          example: "room_1"
        EventId:
          type: string
          description: |
            场景标识。

            通过该参数标识音频流对应的场景。审核策略可以根据场景进行调整，从而实现不同的场景审核尺度的控制。
            - 直播：live_streaming
            - 1v1：private_chat

            如果以上可选值不能完全满足您的使用诉求，请联系 ZEGO 技术支持。
          example: "live_streaming"
        Language:
          type: string
          enum: [zh,en,ar]
          description: |
            语言类型，对音频和截帧识别的语种类型：
            - zh：中文（默认值）
            - en：英文
            - ar：阿拉伯语
          example: "zh"
        AudioParam:
          type: object
          description: 音频的参数，不传则不审核音频流
          properties:
            RiskTypeList:
              type: array
              items: { type: string }
              description: |
                风险审核类别。
                
                RiskTypeList 与 BusinessTypeList 至少一个不为空，如果二者同时为空，则不审核音频，仅审核视频。数组中可添加的值如下：
                音频语义：
                - EROTIC：色情
                - DIRTY：辱骂
                - POLITY：涉政
                - BAN：违禁
                - VIOLENT：暴恐
                - ADVERT：广告

                音频特征：
                - MOAN：娇喘
                - ANTHEN：国歌识别
                - BANEDAUDIO：违禁歌曲

                如需其他特征，请联系 ZEGO 技术支持。
              example: ["ADLAW", "ADVERT", "AUDIOPOLITICAL", "DIRTY", "EROTIC", "MOAN", "POLITY"]
            BusinessTypeList:
              type: array
              items: { type: string }
              description: |
                业务识别类别。
                
                RiskTypeList 与 BusinessTypeList 至少一个不为空，如果二者同时为空，则不审核音频，仅审核视频。数组中可添加的值如下：
                音频语义:
                - MOINIR：未成年人

                音频特征：
                - SING：唱歌
                - LANGUAGE：语种识别
                - VOICE：人声属性识别

                如需其他特征，请联系 ZEGO 技术支持。
                音频流的识别并不仅限于违规内容，也可以辅助开发者进行业务运营。
                如果以上可选值无法满足您的业务诉求，请联系 ZEGO 技术支持。
            AudioLanguage:
              type: array
              items: { type: string, enum: [zh,ja,ko,th,vi,ms,tl,id,hi,ar,tr,en,es,pt,it,fr,de,ru] }
              description: |
                视频流中的音频语种。
                
                在需要识别音频的语义时，请准确传入该值。可选值：
                - zh：中文、ja：日语、ko：韩语、th：泰语
                - vi：越南语、ms：马来语、tl：菲律宾语、id：印尼语
                - hi：印地语中、ar：阿拉伯语、tr：土耳其语、en：英文
                - es：西班牙语、pt：葡萄牙语、it：意大利语、fr：法语
                - de：德语、ru：俄语
            ReturnAllText:
              type: integer
              format: int32
              enum: [0,1]
              default: 0
              description: |
                是否返回当前 10s 片段的所有文本：
                - 0：（默认值）返回风险等级为非 PASS 的音频片段文本
                - 1：返回所有风险等级的音频文本片段

                审核结果的风险等级将分为以下三类：

                PASS：正常内容，建议直接放行。

                REVIEW：可疑内容，建议人工审核。

                REJECT：违规内容，建议直接拦截。
              example: 1
            ReturnPreText:
              type: integer
              format: int32
              enum: [0,1]
              default: 0
              description: |
                是否返回违规片段的前一个片段文本：
                - 0：（默认值）不返回违规片段前一个 10s 片段文字
                - 1：返回违规片段前一个 10s 片段文字
              example: 1
            ReturnPreAudio:
              type: integer
              format: int32
              enum: [0,1]
              default: 0
              description: |
                是否返回违规片段的前一个音频片段链接：
                - 0：（默认值）不返回违规片段前一个 10s 片段音频，只返回违规片段音频链接
                - 1：返回违规片段前一个 10s 片段音频链接
              example: 1
            ResultCallbackUrl:
              type: string
              description: |
                自定义审核结果的回调地址。
                如果您需要将此次审核任务的审核结果，通过其他的回调地址抛出，可以通过本参数实现。如果不需要，可以在 ZEGO 控制台配置统一的回调地址，详情请参考 [控制台 - 云市场 - 数美内容审核](/console/cloud-market/shumei-moderation#配置音频视频流审核回调地址)。
              example: ""
            StatusCallbackUrl:
              type: string
              description: |
                自定义审核状态回调地址。
                如果您需要将此次审核任务的审核状态，通过其他的回调地址抛出，可以通过本参数实现。如果不需要，可以在 ZEGO 后台配置统一的回调地址，详情请参考 [控制台 - 云市场 - 数美内容审核](/console/cloud-market/shumei-moderation#配置音频视频流审核回调地址)。
              example: ""
        VideoParam:
          type: object
          description: 视频审核相关参数
          properties:
            RiskTypeList:
              type: array
              items: { type: string }
              description: |
                风险审核类别。
                
                RiskTypeList 与 BusinessTypeList 至少一个不为空。数组中可添加的值如下：

                画面文字语义：
                - IMGTEXTRISK：基础违规识别，包含多个常见标签（涉政、暴恐、违禁、色情、辱骂、广告、灌水隐私、广告法）

                画面内容：
                - POLITY：涉政
                - EROTIC：色情、性感
                - VIOLENT：暴恐、违禁
                - QRCODE：二维码
                - ADVERT：广告

                如果以上可选值无法满足您的业务诉求，请联系 ZEGO 技术支持。
              example: ["ADVERT", "EROTIC", "IMGTEXTRISK", "POLITY", "QRCODE", "VIOLENT"]
            BusinessTypeList:
              type: array
              items: { type: string }
              description: |
                业务识别类别。
                
                RiskTypeList 与 BusinessTypeList 至少一个不为空。数组中可添加的值：

                画面内容:
                - AGE：未成年人
                - PHOTOMATERIALLOGO：CFP 等版权 LOGO，还支持其他十余种 LOGO，详情请联系技术支持了解。

                画面内容扩展：
                - FACEDETECTION：人脸检测
                - BEAUTY：颜值打分

                视频流的识别并不仅限于违规内容，也可以辅助开发者进行业务运营。如果以上可选值无法满足您的业务诉求，请联系 ZEGO 技术支持。
            ReturnAllImg:
              type: integer
              format: int32
              enum: [0,1]
              default: 0
              description: |
                视频流截帧的风险等级，建议传入 1：
                - 0：（默认值）返回风险等级为非 PASS 的截帧审核信息
                - 1：返回所有风险等级的截帧审核信息

                审核结果的风险等级将分为以下三类：
                - PASS：正常内容，建议直接放行
                - REVIEW：可疑内容，建议人工审核
                - REJECT：违规内容，建议直接拦截
              example: 1
            DetectFrequency:
              type: integer
              format: int32
              description: |
                截帧频率。
                单位：秒。默认为 3s 截帧一次进行审核。
              example: 5
            ResultCallbackUrl:
              type: string
              description: |
                自定义审核结果的回调地址。

                如果您需要将此次审核任务的审核结果，通过其他的回调地址抛出，可以通过本参数实现。如果不需要，可以在 ZEGO 控制台配置统一的回调地址，详情请参考 [控制台 - 云市场 - 数美内容审核](/console/cloud-market/shumei-moderation#配置音频视频流审核回调地址)。
              example: ""
            StatusCallbackUrl:
              type: string
              description: |
                自定义审核状态回调地址。
                
                如果您需要将此次审核任务的审核状态，通过其他的回调地址抛出，可以通过本参数实现。如果不需要，可以在 ZEGO 后台配置统一的回调地址，详情请参考 [控制台 - 云市场 - 数美内容审核](/console/cloud-market/shumei-moderation#配置音频视频流审核回调地址)。
              example: ""
        ReturnFinishInfo:
          type: integer
          format: int32
          enum: [0,1]
          default: 0
          description: |
            审核任务结束时，是否进行"审核任务状态"回调：
            - 0：审核结束时不发送结束通知
            - 1：审核结束时发起结束通知
          example: 1
    StartCensorVideoResponse:
      type: object
      properties:
        Code: 
          type: integer
          format: int32
          description: |
            返回码。
            以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。
            <table>
              <thead>
                <tr><th>返回码</th><th>说明</th><th>处理建议</th></tr>
              </thead>
              <tbody>
                <tr><td>50006、50007</td><td>HTTP 请求失败。</td><td>请稍后重试（建议 300s），或联系 ZEGO 技术支持。</td></tr>
                <tr><td>50009</td><td>审核失败。</td><td>请稍后重试（建议 300s），或联系 ZEGO 技术支持。</td></tr>
                <tr><td>50117</td><td>配置错误，未开通数美权限。</td><td>请参考 <a href="/console/cloud-market/shumei-moderation">控制台 - 云市场 - 数美内容审核</a>，按照页面指引，自助开通 `数美内容审核` 相关权限。</td></tr>
              </tbody>
            </table>
          example: 0
        Message: 
          type: string
          description: 操作结果描述
          example: "success"
        RequestId:
          type: string
          description: 请求 ID
          example: "TestRequestId1722597387688544000"
        Data:
          type: object
          description: 响应数据
          properties:
            TaskId:
              type: string
              description: 审核任务 ID，用于结束审核任务
              example: "05e7a786a5191e8f5eb8e5851b01afcd"


