openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: moderation

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    post:
      tags: [moderation]
      summary: StopCensorVideoV2
      description: |
        调用本接口结束视频流内容审核。

        <Warning title="注意">
        使用该接口前，请参考 [控制台 - 云市场 - 数美内容审核](/console/cloud-market/shumei-moderation)，按照页面指引，自助开通 `数美内容审核` 相关权限。
        </Warning>

        <Note title="调用频率限制">同一个 AppID 下所有房间：100 次/秒</Note>
        ## 常见问题

        1. **开始音频/视频流审核 api，若不调用结束音频/视频流审核的api会怎么样？**

            在拉空流 5min 左右会自动结束，建议在结束审核的时候，主动调用接口结束。
        2. **音频/视频流审核结果的回调中怎么获取到是哪条流违规呢？**

            数美在完成审核后会将审核结果按照10s音频片段 AudioUrl 的方式返回多个回调，在目前的返回结果中没有直接暴露 streamID 信息，可以通过截取 resultTaskId 中的信息获取。
            
            示例（假设 streamID 为 0001，可以看到 AudioUrl 中包含 streamID 0001）：
            <Frame width="auto" height="auto" >
            <img src="https://media-resource.spreading.io/docuo/workspace741/896bc39e2e65b82d5670b01b7c131c30/5852a1ffcc.png" />
            </Frame>
      operationId: stop-censor-video
      parameters:
        - name: Action
          in: query
          required: true
          description: |
            > 接口原型参数
            >
            > https://rtc-api.zego.im?Action=StopCensorVideoV2
          schema: { type: string, enum: [StopCensorVideoV2] }
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/IsTest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StopCensorVideoRequest'
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopCensorVideoResponse'

components:
  schemas:
    StopCensorVideoRequest:
      type: object
      required: [TaskId]
      properties:
        TaskId: 
          type: string
          description: 审核任务 ID，可在[开始视频流审核](/real-time-video-server/api-reference/moderation/start-censor-video)任务的响应参数中获取。 
          example: "9f58178ba8034902c6028c728bc6f6e4"
    StopCensorVideoResponse:
      type: object
      properties:
        Code: 
          type: integer
          format: int32
          description: |
            返回码。
            以下仅列出了接口业务逻辑相关的部分返回码，完整返回码请参考 [全局返回码](/real-time-video-server/api-reference/return-codes)。
            <table>
              <thead>
                <tr><th>返回码</th><th>说明</th><th>处理建议</th></tr>
              </thead>
              <tbody>
                <tr><td>50006、50007</td><td>HTTP 请求失败。</td><td>请稍后重试（建议 300s），或联系 ZEGO 技术支持。</td></tr>
                <tr><td>50009</td><td>审核失败。</td><td>请稍后重试（建议 300s），或联系 ZEGO 技术支持。</td></tr>
                <tr><td>50117</td><td>配置错误，未开通数美权限。</td><td>请联系 ZEGO 技术支持开通数美相关权限。</td></tr>
              </tbody>
            </table>
          example: 0
        Message: 
          type: string
          description: 操作结果描述
          example: "success"
        RequestId: 
          type: string
          description: 请求 ID
          example: "TestRequestId1635941439344723000"

