openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: Unified access address (region-independent)
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: Mainland China (Shanghai)

tags:
  - name: agent-instance-control

paths:
  /:
    post:
      tags:
        - agent-instance-control
      summary: AddAgentInstanceMsg
      description: Used to insert messages into the agent instance context list. This interface does not trigger LLM callbacks, subtitle updates, does not increase dialogue rounds, and does not store messages in ZIM history.
      operationId: add-agent-instance-msg
      parameters:
        - name: Action
          in: query
          description: |
            > Interface prototype parameter
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=AddAgentInstanceMsg
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [AddAgentInstanceMsg]
          style: form
          explode: true
        # Reference shared parameters
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddAgentInstanceMsgRequest"
            example:
              AgentInstanceId: "1907755175297171456"
              Messages:
                - Role: "user"
                  Content: "Hello, I want to learn about product information"
                - Role: "assistant"
                  Content: "You just introduced a skincare product"
      responses:
        "200":
          description: Added successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddAgentInstanceMsgResponse"
              example:
                Code: 0
                Message: "success"
                RequestId: "8916619579948490296"

components:
  schemas:
    AddAgentInstanceMsgRequest:
      type: object
      required:
        - AgentInstanceId
      properties:
        AgentInstanceId:
          type: string
          description: The unique identifier of the agent instance, globally unique. Obtained from the response parameter of the [Create Agent Instance](/aiagent-server/api-reference/agent-instance-management/create-agent-instance) interface.
          example: "1907755175297171456"
        Messages:
          type: array
          description: List of dialogue context messages to be inserted
          items:
            $ref: '../shared-components.yaml#/components/schemas/Message'
          example:
            - Role: "user"
              Content: "Hello, I want to learn about product information"
            - Role: "assistant"
              Content: "You just introduced a skincare product"

    AddAgentInstanceMsgResponse:
      type: object
      properties:
        Code:
          type: integer
          description: Return code, 0 indicates success, other values indicate failure. For details, please refer to [Return Codes](/aiagent-server/api-reference/return-codes).
          example: 0
        Message:
          type: string
          description: Request result description
          example: "success"
        RequestId:
          type: string
          description: Request ID
          example: "8916619579948490296"

