openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - name: agent-instance-control

paths:
  /:
    post:
      tags:
        - agent-instance-control
      summary: StopListening
      description: In walkie-talkie mode, the AI agent stops listening. For enabling walkie-talkie mode, please refer to the AdvancedConfig.CommunicationMode parameter description in [Create Agent Instance](/aiagent-server/api-reference/agent-instance-management/create-agent-instance).
      operationId: stop-listening
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=StopListening
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [StopListening]
          style: form
          explode: true
        # Reference shared parameters
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StopListeningRequest"
            example:
              AgentInstanceId: "1907755175297171456"
              Sequence: 2
      responses:
        "200":
          description: Stopped listening successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StopListeningResponse"

components:
  schemas:
    StopListeningRequest:
      type: object
      required:
        - AgentInstanceId
      properties:
        AgentInstanceId:
          type: string
          description: Unique identifier of the Agent instance, globally unique.
          example: "1907755175297171456"
        Sequence:
          type: integer
          format: int64
          description: Must be the same as the Sequence of the [StartListening](/aiagent-server/api-reference/agent-instance-control/start-listening) API to implement the paired operation of starting and stopping listening.
          example: 2

    StopListeningResponse:
      type: object
      properties:
        Code:
          type: integer
          description: Return code, 0 indicates success, other values indicate failure. For details, please refer to the [Return Codes](/aiagent-server/api-reference/return-codes) description.
          example: 0
        Message:
          type: string
          description: Request result description
          example: "success"
        RequestId:
          type: string
          description: Request ID
          example: "8916619579948490296"

