openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: 统一接入地址（不区分区域）
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: 中国大陆（上海）

tags:
  - name: agent-instance-management

paths:
  /:
    post:
      tags:
        - agent-instance-management
      summary: CreateDigitalHumanAgentInstance
      description: |
        通过本接口，您可以创建数字人智能体实例，并将智能体实例加入到语音（RTC）对话之中。

        <Warning title="注意">
        1. 如果 RTC 房间 120 秒后没有真实用户存在，则智能体实例会自动销毁，并触发 Event 为 AgentInstanceDeleted [回调](/aiagent-server/callbacks/receiving-callback)，Data.Code 为 1202。
        2. 默认情况下一个账号下最多同时存在 10 个数字人智能体实例，超过限制后创建数字人智能体实例会失败，如需调整请联系 ZEGO 商务。
        </Warning>
      operationId: create-digital-human-agent-instance
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=CreateDigitalHumanAgentInstance
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [CreateDigitalHumanAgentInstance]
          style: form
          explode: true
        # 引用共享的参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateDigitalHumanAgentInstanceRequest"
            example:
              AgentId: "xiaozhi"
              UserId: "user_1"
              RTC:
                RoomId: "room_1"
                AgentStreamId: "agent_stream_1"
                AgentUserId: "agent_user_1"
                UserStreamId: "user_stream_1"
              DigitalHuman:
                DigitalHumanId: "xiaozhi"
                ConfigId: "mobile"
                EncodeCode: "H264"
      responses:
        "200":
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateDigitalHumanAgentInstanceResponse"

components:
  schemas:
    CreateDigitalHumanAgentInstanceRequest:
      type: object
      required:
        - AgentId
        - UserId
        - RTC
        - DigitalHuman
      properties:
        AgentId:
          type: string
          description: 已注册的智能体唯一标识符
          example: "xiaozhi"
        UserId:
          type: string
          description: 用于登录 RTC 房间的真实用户 ID。 仅支持数字、英文字符、'-'、'_'。
          example: "user_1"
          maxLength: 32
        # 引用共享的Schema
        RTC:
          $ref: '../shared-components.yaml#/components/schemas/RTC'
        LLM:
          $ref: '../shared-components.yaml#/components/schemas/LLM'
        TTS:
          $ref: '../shared-components.yaml#/components/schemas/TTS'
        ASR:
          $ref: '../shared-components.yaml#/components/schemas/ASR'
        MessageHistory:
          $ref: '../shared-components.yaml#/components/schemas/MessageHistory'
        CallbackConfig:
          $ref: '../shared-components.yaml#/components/schemas/CallbackConfig'
        AdvancedConfig:
          $ref: '../shared-components.yaml#/components/schemas/AdvancedConfig'
        DigitalHuman:
          $ref: '../shared-components.yaml#/components/schemas/DigitalHuman'

    CreateDigitalHumanAgentInstanceResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 返回码，0 表示成功，其他值表示失败。详情请参考 [返回码](/aiagent-server/api-reference/return-codes) 说明。
          example: 0
        Message:
          type: string
          description: 请求结果说明
          example: "success"
        RequestId:
          type: string
          description: 请求 ID
          example: "3151527792559699732"
        Data:
          type: object
          properties:
            AgentInstanceId:
              type: string
              description: 智能体实例的唯一标识。
              example: "1912122918452641792"
            DigitalHumanConfig:
              type: string
              description: 数字人配置，给数字人移动端 SDK 使用。
              example: "eyJEaWdpdGFsSHVtYW5JZCI6ImU1ODNkMzVmLTk3OTMtNDJiNC1hYjFiLTE4OWEzNWI4OGQxYyIsIlN0cmVhbXMiOlt7IlJvb21JZCI6ImlyXzU1NTd5bDVoIiwiU3RyZWFtSWQiOiJpcl81NTU3eWw1aF8xNzEwMl9hZ2VudCIsIkVuY29kZUNvZGUiOiJIMjY0IiwiQ29uZmlnSWQiOiJ3ZWIifV19"
