openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: 统一接入地址（不区分区域）
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: 中国大陆（上海）

tags:
  - name: agent-instance-management

paths:
  /:
    post:
      tags:
        - agent-instance-management
      summary: DeleteAgentInstance
      description: 通过本接口，您可以删除一个现有的智能体实例。
      operationId: delete-agent-instance
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=DeleteAgentInstance
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DeleteAgentInstance]
          style: form
          explode: true
        # 引用共享的参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteAgentInstanceRequest"
            example:
              AgentInstanceId: "1907755175297171456"
      responses:
        "200":
          description: 删除成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteAgentInstanceResponse"

components:
  schemas:
    DeleteAgentInstanceRequest:
      type: object
      required:
        - AgentInstanceId
      properties:
        AgentInstanceId:
          type: string
          description: 智能体实例的唯一标识，通过 [创建智能体实例](/aiagent-server/api-reference/agent-instance-management/create-agent-instance) 接口的响应参数获取。
          example: "1907755175297171456"
        GracefulShutdown:
          type: boolean
          description: 是否启用优雅销毁智能体实例功能。若为 true，调用本接口删除智能体实例时，会等待智能体处于空闲状态（IDLE）后再销毁。
          default: false
        GracefulShutdownTimeout:
          type: integer
          description: 优雅销毁智能体实例等待超时时间，单位秒。销毁智能体实例时，等待智能体实例进入空闲状态（IDLE）的最长时间。超出该时间后，即使智能体实例未处于 IDLE 状态，也会立即销毁。仅在 GracefulShutdown 为 true 时生效。
          default: 30
          minimum: 1
          maximum: 120

    DeleteAgentInstanceResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 返回码，0 表示成功，其他值表示失败。详情请参考 [返回码](/aiagent-server/api-reference/return-codes) 说明。
          example: 0
        Message:
          type: string
          description: 请求结果说明
          example: "success"
        RequestId:
          type: string
          description: 请求 ID
          example: "3151527792559699732"
