openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: media-service

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [media-service]
      summary: ClearCDNTransferRule
      description: |
        Call this API to clear all relay tasks for the specified AppId. This API only clears pending relay tasks and does not stop ongoing relay tasks.
        <Note title="Rate Limit">For all rooms under the same AppID: 10 times/second (test environment: 5 times/second)</Note>



        <Note title="Note">

        In the test environment (see the IsTest common parameter description for details), the Stream ID must be prefixed with "zegotest-AppId-". For example, if the Stream ID is "test" and the AppId is "123456789" in the test environment, the Stream ID should be "zegotest-123456789-test".

        </Note>
      operationId: clear-cdn-transfer-rule
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameters
            >
            > https://rtc-api.zego.im?Action=ClearCDNTransferRule
          required: true
          schema: { type: string, enum: [ClearCDNTransferRule] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - name: StreamId
          in: query
          required: true
          schema: { type: string }
          description: Stream ID.
        - name: Sequence
          in: query
          required: true
          schema: { type: string }
          description: |
            Request sequence number.

            > **Note**
            >
            > For the same StreamId, within 10 consecutive seconds, the request sequence number issued for this StreamId must be strictly increasing; this avoids inconsistent operation order caused by inconsistent request timing received by the server.

            If there is no concurrent scenario, using a timestamp (millisecond level) is recommended.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClearCDNTransferRuleResponse'

components:
  schemas:
    ClearCDNTransferRuleResponse:
      type: object
      properties:
        Code:
          type: integer
          format: number
          description: |
            Return code.
            The following only lists some return codes related to the API business logic. For the complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).
            <table>
              <thead>
                <tr><th>Return Code</th><th>Description</th><th>Suggested Action</th></tr>
              </thead>
              <tbody>
                <tr><td>5000, 5001, 5002, 5006, 30003</td><td>Internal error.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
                <tr><td>5003</td><td>Authentication failed.</td><td>Please check if the Signature is correct.</td></tr>
                <tr><td>5005</td><td>Invalid request.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
                <tr><td>5007, 30002</td><td>API call rate too high.</td><td>Please reduce the API request frequency.</td></tr>
                <tr><td>30004</td><td>Incorrect isTest parameter.</td><td>Please check if the isTest common parameter is correct.</td></tr>
                <tr><td>30005</td><td>Invalid AppId.</td><td>Please check if the AppId is correct.</td></tr>
                <tr><td>30009</td><td>Invalid StreamId, stream name does not conform to specifications.</td><td>Please check if the StreamId conforms to the stream name encoding specifications.</td></tr>
              </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Operation result description
          example: "ok"
        RequestId:
          type: string
          description: Request ID
          example: "4741109603321226039"
        Data:
          type: object
          description: Response data
          example: null

