openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: media-service

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [media-service]
      summary: DescribeRTCStreamState
      description: |
        This API supports querying the real-time status of a specified stream (whether it is active or exists). It only supports querying streams published to the ZEGOCLOUD media server (RTC service), and does not support querying streams published directly to the CDN or output from the stream mixing service.

        It is recommended to prioritize using [stream created callback](/real-time-video-server/callback/stream/created) and [stream destroyed callback](/real-time-video-server/callback/stream/destroyed) to asynchronously obtain current stream publishing information. This API is generally used as an auxiliary interface for stream created callback and stream destroyed callback, or when querying whether a specified single stream is active in the business backend.

        <Note title="Note">
        This API supports querying stream status information after starting stream publishing by default.
        </Note>
        <Note title="Rate Limit">For all rooms under the same AppID: 40 times/second (test environment: 10 times/second)</Note>



        <Note title="Note">
        In the test environment (see the IsTest common parameter description for details), the Stream ID must be prefixed with "zegotest-AppId-". For example, if the Stream ID is "test" and the AppId is "123456789" in the test environment, the Stream ID should be "zegotest-123456789-test".
        </Note>
      operationId: describe-rtc-stream-state
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameters
            >
            > https://rtc-api.zego.im?Action=DescribeRTCStreamState
          required: true
          schema: { type: string, enum: [DescribeRTCStreamState] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - name: StreamId
          in: query
          required: true
          description: Stream ID.
          schema: { type: string }
        - name: Sequence
          in: query
          required: true
          description: |
            Request sequence number, customized by the user.

            > **Note**
            >
            > For the same StreamId, within 10 consecutive seconds, the request sequence number issued for this StreamId must be strictly increasing; this avoids inconsistent operation order caused by inconsistent request timing received by the server.

            If there is no concurrent scenario, using a timestamp (millisecond level) is recommended.
          schema: { type: string }
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeRTCStreamStateResponse'

components:
  schemas:
    DescribeRTCStreamStateResponse:
      type: object
      properties:
        Code:
          type: integer
          format: number
          description: |
            Return code.
            The following only lists some return codes related to the API business logic. For the complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).
            <table>
              <thead>
                <tr><th>Return Code</th><th>Description</th><th>Suggested Action</th></tr>
              </thead>
              <tbody>
                <tr><td>0</td><td>Query succeeded, the queried stream exists and is in active state.</td><td>-</td></tr>
                <tr><td>3000</td><td>Invalid App.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
                <tr><td>3001, 30003</td><td>Internal error.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
                <tr><td>3002</td><td>Timestamp error.</td><td>Please regenerate a new Timestamp.</td></tr>
                <tr><td>3003</td><td>App not configured with Token.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
                <tr><td>30002</td><td>API call rate too high.</td><td>Please reduce the API request frequency.</td></tr>
                <tr><td>30004</td><td>Incorrect isTest parameter.</td><td>Please check if the isTest common parameter is correct.</td></tr>
                <tr><td>30005</td><td>Invalid AppId.</td><td>Please check if the AppId is correct.</td></tr>
                <tr><td>30009</td><td>Invalid StreamId, stream name does not conform to specifications.</td><td>Please check if the StreamId conforms to the stream name encoding specifications.</td></tr>
                <tr><td>40005</td><td>Authentication failed.</td><td>Please check if the Signature is correct.</td></tr>
                <tr><td>41004</td><td>Query failed, StreamId does not exist.</td><td>Please check if the StreamId is correct or if the "query stream status history information permission" has expired.</td></tr>
                <tr><td>41006</td><td>Query succeeded, the queried stream exists but is in closed state. This is only returned within the validity period of the "query stream status history information permission".</td><td>-</td></tr>
              </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Operation result description
          example: "ok"
        RequestId:
          type: string
          description: Request ID
          example: "98004"
        Data:
          type: object
          description: Response data
          properties:
            create_time:
              type: string
              description: Stream creation time, UTC time
              example: "1673334117"
            close_time:
              type: string
              description: Stream close time, UTC time
              example: ""

