openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: media-service

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [media-service]
      summary: ForbidRTCStream
      description: |
        Call this API to forbid RTC stream publishing. You can forbid the specified Stream ID from publishing to the RTC service. The forbidding operation sends a notification to publishing clients and playing clients that the stream has been forbidden.

        Publishing clients receive notifications that stream publishing has been forbidden by the server using ZEGO Express SDK callback interfaces:

        <table>

          <tbody><tr>
            <th rowspan="2">Platform</th>
            <th colspan="2">ZegoExpress SDK</th>
            <th colspan="2">LiveRoom SDK</th>
          </tr>
          <tr>
            <th>Interface</th>
            <th>Error Code</th>
            <th>Interface</th>
            <th>Error Code</th>
          </tr>
          <tr>
            <td>iOS/macOS</td>
            <td>onPublisherStateUpdate</td>
            <td>1003025</td>
            <td>onPublishStateUpdate</td>
            <td>12301011</td>
          </tr>
          <tr>
            <td>Android</td>
            <td>onPublisherStateUpdate</td>
            <td>1003025</td>
            <td>onPublishStateUpdate</td>
            <td>12301011</td>
          </tr>
          <tr>
            <td>Windows</td>
            <td>onPublisherStateUpdate</td>
            <td>1003025</td>
            <td>OnPublishStateUpdate</td>
            <td>12301011</td>
          </tr>
        </tbody></table>

        Playing clients receive notifications that the played stream has been forbidden by the server using ZEGO Express SDK callback interfaces:

        <table>

        <tbody><tr>
        <th rowspan="2">Platform</th>
        <th colspan="2">ZegoExpress SDK</th>
        <th colspan="2">LiveRoom SDK</th>
        </tr>
        <tr>
        <th>Interface</th>
        <th>Error Code</th>
        <th>Interface</th>
        <th>Error Code</th>
        </tr>
        <tr>
        <td>iOS/macOS</td>
        <td>onPlayerStateUpdate</td>
        <td>1004025</td>
        <td>onPlayStateUpdate</td>
        <td>12301011</td>
        </tr>
        <tr>
        <td>Android</td>
        <td>onPlayerStateUpdate</td>
        <td>1004025</td>
        <td>onPlayStateUpdate</td>
        <td>12301011</td>
        </tr>
        <tr>
        <td>Windows</td>
        <td>onPlayerStateUpdate</td>
        <td>1004025</td>
        <td>OnPlayStateUpdate</td>
        <td>12301011</td>
        </tr>
        </tbody></table>
        <Note title="Rate Limit">For all rooms under the same AppID: 20 times/second (test environment: 5 times/second)</Note>



        <Note title="Note">

        In the test environment (see the IsTest common parameter description for details), the Stream ID must be prefixed with "zegotest-AppId-". For example, if the Stream ID is "test" and the AppId is "123456789" in the test environment, the Stream ID should be "zegotest-123456789-test".

        </Note>
      operationId: forbid-rtc-stream
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameters
            >
            > https://rtc-api.zego.im?Action=ForbidRTCStream
          required: true
          schema: { type: string, enum: [ForbidRTCStream] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - name: StreamId
          in: query
          required: true
          schema: { type: string }
          description: Stream ID.
        - name: Sequence
          in: query
          required: true
          schema: { type: string }
          description: |
            Request sequence number.

            > **Note**
            >
            > For the same StreamId, within 10 consecutive seconds, the request sequence number issued for this StreamId must be strictly increasing; this avoids inconsistent operation order caused by inconsistent request timing received by the server.

            If there is no concurrent scenario, using a timestamp (millisecond level) is recommended.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbidRTCStreamResponse'

components:
  schemas:
    ForbidRTCStreamResponse:
      type: object
      properties:
        Code:
          type: integer
          format: number
          description: |
            Return code.
            The following only lists some return codes related to the API business logic. For the complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).
            <table>
              <thead>
                <tr><th>Return Code</th><th>Description</th><th>Suggested Action</th></tr>
              </thead>
              <tbody>
                <tr><td>3000</td><td>Invalid App.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
                <tr><td>3001, 5006, 30003</td><td>Internal error.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
                <tr><td>3002</td><td>Timestamp error.</td><td>Please regenerate a new Timestamp.</td></tr>
                <tr><td>3003</td><td>App not configured with Token.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
                <tr><td>30002</td><td>API call rate too high.</td><td>Please reduce the API request frequency.</td></tr>
                <tr><td>30004</td><td>Incorrect isTest parameter.</td><td>Please check if the isTest common parameter is correct.</td></tr>
                <tr><td>30005</td><td>Invalid AppId.</td><td>Please check if the AppId is correct.</td></tr>
                <tr><td>30009</td><td>Invalid StreamId, stream name does not conform to specifications.</td><td>Please check if the StreamId conforms to the stream name encoding specifications.</td></tr>
                <tr><td>40005</td><td>Authentication failed.</td><td>Please check if the Signature is correct.</td></tr>
              </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Operation result description
          example: "ok"
        RequestId:
          type: string
          description: Request ID
          example: "1929203990360298509"

