openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: media-service

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [media-service]
      summary: ForbidCDNLiveStream
      description: |
        Call this API to forbid CDN stream publishing. This is applicable to direct CDN publishing scenarios. For relay to CDN scenarios, please use the [stop relaying streams to CDN](/real-time-video-server/api-reference/media-service/delete-cdn-transfer-rule) API.

        <Warning title="Note">
        For first-time use of this API, please contact ZEGOCLOUD Technical Support for configuration.
        </Warning>
        <Note title="Rate Limit">For all rooms under the same AppID: 20 times/second</Note>
      operationId: forbid-cdn-live-stream
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameters
            >
            > https://rtc-api.zego.im?Action=ForbidCDNLiveStream
          required: true
          schema: { type: string, enum: [ForbidCDNLiveStream] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - name: StreamId
          in: query
          required: true
          schema: { type: string }
          description: Stream ID.
        - name: ResumeTime
          in: query
          required: false
          schema: { type: string }
          description: |
            The time to resume the stream. UTC format, for example: 2018-11-29T19:00:00Z.<br />
            Note: Only WangSu (ws) supports this parameter. The default banning duration is 1 day, and the maximum supported banning duration is 30 days. For example, if banning for 30 days, the banning duration will be set to: current time + 30 days.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbidCDNLiveStreamResponse'

components:
  schemas:
    ForbidCDNLiveStreamResponse:
      type: object
      properties:
        Code:
          type: integer
          format: number
          description: |
            Return code.
            The following only lists some return codes related to the API business logic. For the complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).
            <table>
              <thead>
                <tr><th>Return Code</th><th>Description</th><th>Suggested Action</th></tr>
              </thead>
              <tbody>
                <tr><td>0</td><td>Request succeeded.</td><td>-</td></tr>
                <tr><td>1</td><td>Request failed.</td><td>-</td></tr>
                <tr><td>2</td><td>Parameter error.</td><td>-</td></tr>
                <tr><td>3</td><td>Authentication failed.</td><td>Please check if the authentication parameters are correct.</td></tr>
              </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Operation result description
          example: "success"
        RequestId:
          type: string
          description: Request ID
          example: "4113829426153229963"
        Data:
          type: array
          description: Response data
          items:
            type: object
            properties:
              CdnType:
                type: string
                description: |
                  CDN type:
                  - ws: WangSu
                  - aliyun: Alibaba Cloud
                  - tencent: Tencent Cloud
                  - huawei: Huawei Cloud
                example: "ws"
              CdnResult:
                type: string
                description: CDN processing result
                example: "success append purge tasks"

