openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: media-service

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [media-service]
      summary: ForbidRTCStreams
      description: |
        Call this interface to batch-forbid RTC streams, which can batch-forbid specified stream IDs from being pushed to the RTC service. Forbidding stream operations will send notifications to clients that are currently publishing streams and clients that are playing streams. It is typically used when developers need to temporarily interrupt a terminal's stream publishing through the server.

        Publishing clients receive notifications of stream publishing being forbidden by the server using ZEGOCLOUD Express SDK callback interfaces:

        <table>

          <tbody><tr>
            <th rowspan="2">Platform</th>
            <th colspan="2">ZegoExpress SDK</th>
            <th colspan="2">LiveRoom SDK</th>
          </tr>
          <tr>
            <th>Interface</th>
            <th>Error Code</th>
            <th>Interface</th>
            <th>Error Code</th>
          </tr>
          <tr>
            <td>iOS/macOS</td>
            <td>onPublisherStateUpdate</td>
            <td>1003025</td>
            <td>onPublishStateUpdate</td>
            <td>12301011</td>
          </tr>
          <tr>
            <td>Android</td>
            <td>onPublisherStateUpdate</td>
            <td>1003025</td>
            <td>onPublishStateUpdate</td>
            <td>12301011</td>
          </tr>
          <tr>
            <td>Windows</td>
            <td>onPublisherStateUpdate</td>
            <td>1003025</td>
            <td>OnPublishStateUpdate</td>
            <td>12301011</td>
          </tr>
        </tbody></table>



        Playing clients receive notifications of their played streams being forbidden by the server using ZEGOCLOUD Express SDK callback interfaces:


        <table>

          <tbody><tr>
            <th rowspan="2">Platform</th>
            <th colspan="2">ZegoExpress SDK</th>
            <th colspan="2">LiveRoom SDK</th>
          </tr>
          <tr>
            <th>Interface</th>
            <th>Error Code</th>
            <th>Interface</th>
            <th>Error Code</th>
          </tr>
          <tr>
            <td>iOS/macOS</td>
            <td>onPlayerStateUpdate</td>
            <td>1004025</td>
            <td>onPlayStateUpdate</td>
            <td>12301011</td>
          </tr>
          <tr>
            <td>Android</td>
            <td>onPlayerStateUpdate</td>
            <td>1004025</td>
            <td>onPlayStateUpdate</td>
            <td>12301011</td>
          </tr>
          <tr>
            <td>Windows</td>
            <td>onPlayerStateUpdate</td>
            <td>1004025</td>
            <td>OnPlayStateUpdate</td>
            <td>12301011</td>
          </tr>
        </tbody></table>

        <Warning title="Note">
        After calling this interface, the audio and video streams that are currently being pushed will be forbidden from pushing, and the stream IDs will be recorded in the background database; non-existent streams will be directly recorded in the background database, and the interface will normally return successfully.
        </Warning>

        <Note title="Call frequency limit">All rooms under the same AppID are limited to 20 times/second (Test environment: 5 times/second)</Note>



        <Note title="Description">
        In the test environment (see the IsTest common parameter description for details), the stream ID needs to be prefixed with "zegotest-AppId-". For example, if the stream ID is "test", and the AppId is "123456789" in the test environment, the stream ID should be "zegotest-123456789-test".
        </Note>
      operationId: forbid-rtc-streams
      parameters:
        - name: Action
          in: query
          description: |
            > Interface prototype parameters
            >
            > https://rtc-api.zego.im?Action=ForbidRTCStreams
          required: true
          schema: { type: string, enum: [ForbidRTCStreams] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - name: StreamId[]
          in: query
          description: Stream ID list, supports up to 20 stream IDs.
          required: true
          schema:
            type: array
            items: { type: string }
          style: form
          explode: true
        - name: Sequence
          in: query
          required: true
          schema: { type: string }
          description: |
            Request sequence number.

            > **Note**
            >
            > For the same StreamId, within 10 consecutive seconds, you must ensure that the request sequence numbers issued for this StreamId are strictly increasing; avoid operation errors caused by inconsistent timing of requests received by the server.

            If there are no concurrent scenarios, it is recommended to use timestamps (millisecond level).
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbidRTCStreamsResponse'

components:
  schemas:
    ForbidRTCStreamsResponse:
      type: object
      properties:
        Code:
          type: integer
          format: number
          description: |
            Return code.
            Only the return codes related to interface business logic are listed below. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).
            <table>
              <thead>
                <tr><th>Return Code</th><th>Description</th><th>Handling Suggestion</th></tr>
              </thead>
              <tbody>
                <tr><td>30002</td><td>API call rate too high.</td><td>Please reduce the API request frequency.</td></tr>
                <tr><td>30003</td><td>Internal error.</td><td>Please contact ZEGOCLOUD Technical Support for handling.</td></tr>
                <tr><td>30004</td><td>Parameter isTest error.</td><td>Please check if the common request parameter isTest is correct.</td></tr>
                <tr><td>30005</td><td>Invalid AppId.</td><td>Please check if the AppId is correct.</td></tr>
                <tr><td>30006</td><td>Invalid StreamId list.</td><td>Please check if StreamId[] is correct.</td></tr>
                <tr><td>42003</td><td>Batch disabling live stream failed.</td><td>Please retry, if retry is invalid, please contact ZEGOCLOUD Technical Support.</td></tr>
              </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Operation result description
          example: "ok"
        RequestId:
          type: string
          description: Request ID
          example: "1929203990360298509"
        Data:
          type: object
          description: Response data
          example: null

