openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: media-service

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [media-service]
      summary: QueryForbidCDNLiveStream
      description: |
        Call this API to query the list of URLs that are forbidden from publishing streams to the CDN.

        <Warning title="Note">
        For first-time use of this API, please contact ZEGOCLOUD Technical Support for configuration.
        </Warning>
        <Note title="Rate Limit">For all rooms under the same AppID: 20 times/second</Note>
      operationId: query-forbid-cdn-live-stream
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameters
            >
            > https://rtc-api.zego.im?Action=QueryForbidCDNLiveStream
          required: true
          schema: { type: string, enum: [QueryForbidCDNLiveStream] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - name: Vendor
          in: query
          required: true
          schema: { type: string }
          description: |
            CDN provider, ws: WangSu.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryForbidCDNLiveStreamResponse'
              example:
                Code: 0
                Message: "success"
                RequestId: ""
                Data:
                  Ws:
                    ResultDetail:
                      - Channel: "publish-ws.zegotech.cn"
                        Url: "rtmp://publish-ws.zegotech.cn/test/stream001"
                        StartTime: "2024-10-12T03:47:53Z"
                        EndTime: "2024-11-11T03:47:53Z"
                        Ip: ""
                      - Channel: "publish-ws.zegotech.cn"
                        Url: "rtmp://publish-ws.zegotech.cn/test/stream002"
                        StartTime: "2024-10-12T02:48:15Z"
                        EndTime: "2024-10-14T02:22:00Z"
                        Ip: ""

components:
  schemas:
    QueryForbidCDNLiveStreamResponse:
      type: object
      properties:
        Code:
          type: integer
          format: number
          description: |
            Return code.
            The following only lists some return codes related to the API business logic. For the complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).
            <table>
              <thead>
                <tr><th>Return Code</th><th>Description</th><th>Suggested Action</th></tr>
              </thead>
              <tbody>
                <tr><td>0</td><td>Request succeeded.</td><td>-</td></tr>
                <tr><td>1</td><td>Request failed.</td><td>-</td></tr>
                <tr><td>2</td><td>Parameter error.</td><td>-</td></tr>
                <tr><td>3</td><td>Authentication failed.</td><td>Please check if the authentication parameters are correct.</td></tr>
              </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Operation result description
          example: "success"
        RequestId:
          type: string
          description: Request ID
          example: ""
        Data:
          type: object
          description: Response data
          properties:
            Ws:
              type: object
              description: Query results returned by WangSu
              properties:
                ResultDetail:
                  type: array
                  description: Collection of query results
                  items:
                    type: object
                    properties:
                      Channel:
                        type: string
                        description: Acceleration domain name
                        example: "publish-ws.zegotech.cn"
                      Url:
                        type: string
                        description: |
                          The complete URL of the CDN live address that is forbidden from publishing streams, for example, rtmp://publish-ws.zegotech.cn/test/Stream ID
                        example: "rtmp://publish-ws.zegotech.cn/test/stream001"
                      StartTime:
                        type: string
                        description: The time when stream publishing forbidding starts, UTC time
                        example: "2024-10-12T03:47:53Z"
                      EndTime:
                        type: string
                        description: The time when stream publishing resumes, UTC time
                        example: "2024-10-14T02:22:00Z"
                      Ip:
                        type: string
                        deprecated: true
                        description: User IP forbidden from watching live streams (deprecated)
                        example: ""
