openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact: { name: Real-time Voice/Video API Support, email: support@zegocloud.com }

tags:
  - name: media-service

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      tags: [media-service]
      summary: ResumeCDNLiveStream
      description: |
        Call this interface to resume CDN streaming, applicable to direct push CDN scenarios. If you need to apply it to transfer push CDN scenarios, please use the [Enable Bypass Streaming](/real-time-video-server/api-reference/media-service/create-cdn-transfer-rule) interface.

        <Warning title="Note">
        When using this interface for the first time, you need to contact ZEGOCLOUD Technical Support for configuration.
        </Warning>
        <Note title="Call frequency limit">All rooms under the same AppID are limited to 20 times/second</Note>
      operationId: resume-cdn-live-stream
      parameters:
        - name: Action
          in: query
          description: |
            > Interface prototype parameters
            >
            > https://rtc-api.zego.im?Action=ResumeCDNLiveStream
          required: true
          schema: { type: string, enum: [ResumeCDNLiveStream] }
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - name: StreamId
          in: query
          required: true
          schema: { type: string }
          description: Stream ID.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResumeCDNLiveStreamResponse'

components:
  schemas:
    ResumeCDNLiveStreamResponse:
      type: object
      properties:
        Code:
          type: integer
          format: number
          description: |
            Return code.
            Only the return codes related to interface business logic are listed below. For complete return codes, please refer to [Global Return Codes](/real-time-video-server/api-reference/return-codes).
            <table>
              <thead>
                <tr><th>Return Code</th><th>Description</th><th>Handling Suggestion</th></tr>
              </thead>
              <tbody>
                <tr><td>0</td><td>Request successful.</td><td>-</td></tr>
                <tr><td>1</td><td>Request failed.</td><td>-</td></tr>
                <tr><td>2</td><td>Parameter error.</td><td>-</td></tr>
                <tr><td>3</td><td>Authentication failed.</td><td>Please check if the authentication parameters are correct.</td></tr>
              </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Operation result description
          example: "success"
        RequestId:
          type: string
          description: Request ID
          example: "3162938795049910659"
        Data:
          type: array
          description: Response data
          items:
            type: object
            properties:
              CdnType:
                type: string
                description: |
                  CDN Type:
                  - ws: Wangsu
                  - aliyun: Alibaba Cloud
                  - tencent: Tencent Cloud
                  - huawei: Huawei Cloud
                example: "ws"
              CdnResult:
                type: string
                description: CDN processing result
                example: "success append purge tasks"

