openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - room

paths:
  /:
    post:
      tags: [room]
      summary: Update room attributes
      description: |
       Update custom room attributes based on the room ID. A room can have a maximum of 20 room attributes. If you need to increase the limit, please contact ZEGOCLOUD Technical Support.

       After the room attributes are updated, you can receive notifications of room attribute updates through the following ZIM SDK callbacks:
       | iOS-25% | Android-25% | macOS-25% |Windows-25% |
       |-----|---------|-------|-------|
       |[roomAttributesUpdated](https://www.zegocloud.com/docs/api?doc=zim_API~objective-c_ios~protocol~ZIMEventHandler#zim-room-attributes-updated-room-id)|[onRoomAttributesUpdated](https://www.zegocloud.com/docs/api?doc=zim_API~java_android~class~ZIMEventHandler#on-room-attributes-updated)|[roomAttributesUpdated](https://www.zegocloud.com/docs/api?doc=zim_API~objective-c_macos~protocol~ZIMEventHandler#zim-room-attributes-updated-room-id)|[onRoomAttributesUpdated](https://www.zegocloud.com/docs/api?doc=zim_API~cpp_windows~class~ZIMEventHandler#on-room-attributes-updated)|

       | Web-25% | Mini Program-25% |Flutter-25% | React Native-25% |
       |---------|-----|--------|---------|
       |[roomAttributesUpdated](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_web~interface~ZIMEventHandler#room-attributes-updated)|[roomAttributesUpdated](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_wxxcx~interface~ZIMEventHandler#room-attributes-updated)|[onRoomAttributesUpdated](https://pub.dev/documentation/zego_zim/latest/zego_zim/ZIMEventHandler/onRoomAttributesUpdated.html)|[roomAttributesUpdated](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_react-native~interface~ZIMEventHandler#room-attributes-updated)|

       | Unity3D-25% | uni-app \| uni-app x-25% | HarmonyOS-25% |
       |--------------|---------|---------|
       |[OnRoomAttributesUpdated](https://www.zegocloud.com/docs/api?doc=zim_API~cs_unity3d~class~ZIMEventHandler#on-room-attributes-updated)|[roomAttributesUpdated](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_uni-app~interface~ZIMEventHandler#room-attributes-updated)|[roomAttributesUpdated](https://www.zegocloud.com/docs/api?doc=zim_API~javascript_harmony~interface~ZIMEventHandler#room-attributes-updated)|

        <Note title="QPS Limit"> 20 times/s</Note>
      operationId: update-room-attributes
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=ModifyRoomAttribute
          required: true
          schema:
            type: string
            enum: [ModifyRoomAttribute]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModifyRoomAttributeRequest'
            example:
              RoomId: "room123"
              FromUserId: "fromUserId"
              Attributes:
                - Action: 0
                  Key: "attribute1"
                  Value: "value1"
                  AutoDelete: 1
                - Action: 1
                  Key: "attribute2"
                  Value: ""
                  AutoDelete: 0
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModifyRoomAttributeResponse'
              example:
                Code: 0
                Message: success
                RequestId: "req-123456789"
                AttributeSeq: 3
                SuccKeyList:
                  - Key: "key1"
                    Seq: 3
                  - Key: "key2"
                    Seq: 2
                ErrKeyList:
                  - SubCode: 1
                    Key: "attr1"
                  - SubCode: 2
                    Key: "attr2"

components:
  schemas:
    ModifyRoomAttributeRequest:
      type: object
      required: [FromUserId, RoomId, Attributes]
      properties:
        FromUserId:
          type: string
          description: Operator, must be in registered status. This user will not automatically join the room. Only supports numbers, English characters, and '!', '#', '$', '%', '&', '(', ')', '+', '-', ':', ';', '<', '=', '.', '>', '?', '@', '[', ']', '^', '_', ' ', ',', '{'
          maxLength: 32
          example: "fromUserId"
        RoomId:
          type: string
          description: Room ID. Only supports numbers, English characters, and '!', '#', '$', '%', '&', '(', ')', '+', '-', ':', ';', '<', '=', '.', '>', '?', '@', '[', ']', '^', '_', ',', '{'
          maxLength: 32
          example: "room123"
        Attributes:
          type: array
          description: Room attribute information to be updated.
          items:
            $ref: '#/components/schemas/ModifyRoomAttribute'
    ModifyRoomAttribute:
      type: object
      required: [Action, Key]
      properties:
        Action:
          type: number
          description: |
            Delete or set.
            <ul><li>0: Set;</li><li>1: Delete.</li></ul>
          enum: [0, 1]
        Key:
          type: string
          description: |
            Room attribute key.

            > **Note**
            >
            > If the passed Key already exists, the existing attribute information will be modified.
          example: "attribute1"
        Value:
          type: string
          description: Room attribute value.
          example: "value1"
        AutoDelete:
          type: number
          description: |
            Whether to automatically delete when the user exits.
            <ul><li>0: Do not automatically delete;</li><li>1: Automatically delete.</li></ul>
            If FromUserId is not in the room, the deletion operation will be triggered when the user first enters the room and then exits.
          enum: [0, 1]
          example: 1
        StopOnError:
          type: integer
          description: |
            Whether to enable fast failure, disabled by default.
            - 0: Disable fast failure. When an error is encountered during execution, record the current attribute and continue with subsequent update operations. After execution, return all recorded attributes.
            - 1: Enable fast failure. When an error is encountered during execution, stop the update operation and return the attributes of this update. Successfully executed update operations will be retained.
          enum: [0, 1]
    ModifyRoomAttributeResponse:
      type: object
      properties:
        Code:
          type: integer
          description: |
            Return status code (0 indicates success).

            The following only lists the Code and SubCode related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            <table>
            <thead><tr><th>Code / SubCode</th><th>Description</th><th>Solution</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>Parameter error.</td><td>Please check the parameters.</td></tr>
            <tr><td>660300005</td><td>Frequency limit.</td><td>Please try again later.</td></tr>
            </tbody>
            </table>
        Message:
          type: string
          description: Return status information.
          example: "success"
        RequestId:
          type: string
          description: Unique request identifier.
          example: "req-123456789"
        AttributeSeq:
          type: int32
          description: |
            Records the total number of changes to all attributes (create, modify, delete) in the room, used to calibrate attributes and calculate the order of attribute changes. The AttributeSeq value increases by 1 each time an attribute changes.
            > Note: When multiple attributes change at once, the AttributeSeq value will increase multiple times. For example, if 3 attributes are modified at once, the AttributeSeq value will increase by 3.
          example: 3
        SuccKeyList:
          type: array
          description: List of successful keys (returned only on success)
          items:
            type: object
            properties:
              Key:
                type: string
                description: Successfully modified key.
                example: "key1"
              Seq:
                type: int32
                description: Sequence number of the room attribute Key, used to calibrate attributes and calculate the order of attribute changes. When each attribute is successfully created or modified, the Seq value equals the current AttributeSeq.
                example: 3
        ErrKeyList:
          type: array
          description: List of error keys (returned only on failure).
          items:
            type: object
            properties:
              SubCode:
                type: number
                description: |
                  Specific return code. For the complete return codes, please refer to the Code description or [Return codes](/zim-server/return-codes).
                example: 1
              Key:
                type: string
                description: Key value that encountered an error.
                example: "attr1"