openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: './shared-components.yaml#/servers'

paths:
  /:
    post:
      tags:
        - player
      summary: DeletePlayer
      description: |
        Call this API to destroy the specified cloud player.

        <Note title="Note">Call frequency limit: 20 times/second</Note>
      operationId: delete-player
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://cloud-player-api.zego.im?Action=DeletePlayer
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DeletePlayer]
          style: form
          explode: true
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeletePlayerRequest'
      responses:
        '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/DeletePlayerResponse'

components:
  schemas:
    DeletePlayerRequest:
      type: object
      required: [PlayerId]
      properties:
        PlayerId:
          type: string
          description: Cloud player unique identifier ID, returned by [CreatePlayer](/cloud-player-server/create-player). <b>When calling this API, please ensure that the PlayerId exists, otherwise an error may occur.</b>
          example: "player_1"

    DeletePlayerResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Error code.

            The following only lists the return codes related to the API business logic. For the complete return codes, please refer to [Global Return Codes](/cloud-player-server/return-codes).
            <table>
            <thead>
            <tr><th>Return Code</th><th>Description</th><th>Handling Suggestion</th></tr>
            </thead>
            <tbody>
            <tr><td>0</td><td>Success.</td><td>-</td></tr>
            <tr><td>100000004</td><td>Signature expired.</td><td>Please regenerate the signature.</td></tr>
            <tr><td>100000005</td><td>Signature error.</td><td>Please confirm whether the parameters for generating the signature are correct.</td></tr>
            <tr><td>350006001</td><td>API request frequency exceeds the limit.</td><td>Please confirm the QPS limit of the corresponding API and reduce the request frequency.</td></tr>
            <tr><td>350006002</td><td>Gateway verification failed.</td><td>Please contact ZEGOCLOUD Technical Support for assistance.</td></tr>
            <tr><td>350006003</td><td>Invalid input parameter.</td><td>Please adjust the value of the corresponding parameter according to the Message prompt.</td></tr>
            <tr><td>350006006</td><td>Service not activated.</td><td>Please contact ZEGOCLOUD Technical Support to activate the service permission.</td></tr>
            <tr><td>350006009</td><td>Cloud player is being created.</td><td>Please retry this operation later.</td></tr>
            <tr><td>350010000</td><td>System error.</td><td>Please contact ZEGOCLOUD Technical Support for assistance.</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Error description.
          example: "succeed"
        RequestId:
          type: string
          description: Request ID.
          example: "abcd123"
      example:
        Code: 0
        Message: "succeed"
        RequestId: "abcd123"

