openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: './shared-components.yaml#/servers'

paths:
  /:
    post:
      tags:
        - player
      summary: DescribePlayers
      description: |
        Call this API to query all cloud player task lists under the AppID, including all statuses such as created, running, destroyed, etc.; or query the task information of a specified cloud player.

        <Note title="Note">Call frequency limit: 20 times/second</Note>
      operationId: describe-players
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://cloud-player-api.zego.im?Action=DescribePlayers
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [DescribePlayers]
          style: form
          explode: true
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DescribePlayersRequest'
      responses:
        '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/DescribePlayersResponse'

components:
  schemas:
    DescribePlayersRequest:
      type: object
      properties:
        RoomId:
          type: string
          maxLength: 128
          description: |
            Query the specified room ID, with a length within 128 bytes.
            <b>If RoomId is filled in, please ensure that the RoomId exists, otherwise the query result may be empty.</b>

            > **Warning**
            >
            > - When neither RoomId nor PlayerId is filled in, calling this API will return all cloud player task lists under the AppId.
            > - When RoomId is filled in and PlayerId is not filled in, calling this API will return all cloud player task lists in the room RoomId under the AppId.
            > - When PlayerId is filled in (RoomId can be filled in or not), calling this API will return the cloud player task information corresponding to the PlayerId.
          example: "room_12"
        PlayerId:
          type: string
          description: |
            Cloud player unique identifier ID, returned by [CreatePlayer](/cloud-player-server/create-player).
            <b>If PlayerId is filled in, please ensure that the PlayerId exists, otherwise the query result may be empty.</b>

            > **Warning**
            >
            > - When neither RoomId nor PlayerId is filled in, calling this API will return all cloud player task lists under the AppId.
            > - When RoomId is filled in and PlayerId is not filled in, calling this API will return all cloud player task lists in the room RoomId under the AppId.
            > - When PlayerId is filled in (RoomId can be filled in or not), calling this API will return the cloud player task information corresponding to the PlayerId.
          example: ""
        PageSize:
          type: number
          description: |
            Page size, value range (0, 50], default is 50 per page, indicating the maximum number of task lists returned by calling this API once.
            <b>For task lists exceeding the PageSize value, you need to call this API again for query based on the NextPageToken (query task list pagination starting position) value in the return result of the previous call to this API.</b>

            For example, if there are currently 123 cloud player tasks and PageSize is 50, when calling this API for query:
            - The first time calling this API, pass empty for the input parameter PageToken, query player tasks 1 to 50; assume the NextPageToken value in the return result is "pagetoken1".
            - The second time calling this API, set the input parameter PageToken to "pagetoken1", query player tasks 51 to 100; assume the NextPageToken value in the return result is "pagetoken2".
            - The third time calling this API, set the input parameter PageToken to "pagetoken2", query player tasks 101 to 123; query completed, NextPageToken in the return result is empty.
          example: 50
        PageToken:
          type: string
          description: |
            Query task list pagination starting position, <b>when this parameter is not filled in, the first page of the queried task list is returned by default.</b>

            Each time this API is called to initiate a request, NextPageToken will be returned in the response result, and developers need to determine whether the last page has been queried.
          example: "XXXXXXXXX"
      example:
        RoomId: "room_12"
        PlayerId: ""
        PageSize: 50
        PageToken: "XXXXXXXXX"

    DescribePlayersResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Error code.

            The following only lists the return codes related to the API business logic. For the complete return codes, please refer to [Global Return Codes](/cloud-player-server/return-codes).
            <table>
            <thead>
            <tr><th>Return Code</th><th>Description</th><th>Handling Suggestion</th></tr>
            </thead>
            <tbody>
            <tr><td>0</td><td>Success.</td><td>-</td></tr>
            <tr><td>100000004</td><td>Signature expired.</td><td>Please regenerate the signature.</td></tr>
            <tr><td>100000005</td><td>Signature error.</td><td>Please confirm whether the parameters for generating the signature are correct.</td></tr>
            <tr><td>350006001</td><td>API request frequency exceeds the limit.</td><td>Please confirm the QPS limit of the corresponding API and reduce the request frequency.</td></tr>
            <tr><td>350006002</td><td>Gateway verification failed.</td><td>Please contact ZEGOCLOUD Technical Support for assistance.</td></tr>
            <tr><td>350006003</td><td>Invalid input parameter.</td><td>Please adjust the value of the corresponding parameter according to the Message prompt.</td></tr>
            <tr><td>350006006</td><td>Service not activated.</td><td>Please contact ZEGOCLOUD Technical Support to activate the service permission.</td></tr>
            <tr><td>350010000</td><td>System error.</td><td>Please contact ZEGOCLOUD Technical Support for assistance.</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Error description.
          example: "succeed"
        RequestId:
          type: string
          description: Request ID.
          example: "abcd123"
        Data:
          type: object
          description: Returned specific information.
          properties:
            TotalSize:
              type: number
              description: Total number of cloud player tasks queried.
              example: 1
            NextPageToken:
              type: string
              description: Page number of the next page of this query. When NextPageToken is empty, it indicates that the last page has been queried.
              example: ""
            Players:
              type: array
              description: Queried cloud player task information.
              items:
                type: object
                properties:
                  PlayerId:
                    type: string
                    description: Cloud player unique identifier ID.
                    example: "player_1"
                  RoomId:
                    type: string
                    description: Room ID.
                    example: "room_12"
                  StreamId:
                    type: string
                    description: Stream ID published to the specified room.
                    example: "stream"
                  CreateTime:
                    type: number
                    description: Player creation time, Unix timestamp, unit is seconds.
                    example: 1681221508
                  PlayTime:
                    type: number
                    description: Time when media resource playback started, Unix timestamp, unit is seconds.
                    example: 1681221508
                  PlayerName:
                    type: string
                    description: Name of the cloud player.
                    example: "player_1"
                  StreamUrl:
                    type: string
                    description: Address of the media resource being played.
                    example: "https://xxx.com/video/test.mp4"
                  Status:
                    type: number
                    description: |
                      Status of the cloud player.
                      - 1: Creating.
                      - 2: Connecting to media resource.
                      - 3: Waiting to play.
                      - 4: Playing.
                      - 5: Paused.
                      - 6: Failed to connect to media resource.
                      - 7: Playback ended.
                      - 8: Destroyed.
                    enum: [1, 2, 3, 4, 5, 6, 7, 8]
                    example: 4
                  DestroyReason:
                    type: number
                    description: |
                      Reason for cloud player destruction.
                      - 1: Actively destroyed by calling the [DeletePlayer](/cloud-player-server/delete-player) API.
                      - 2: Idle state duration exceeded MaxIdleTime.
                      - 3: Media resource playback has ended.
                      - 4: Stream publishing failed.
                      - 5: Failed to enter the room or was kicked out of the room.
                    enum: [1, 2, 3, 4, 5]
                    example: 1
                  StreamUrlList:
                    type: array
                    description: List of media resources being played.
                    items:
                      type: string
                    example:
                      - "https://xxx.com/video/test1.mp4"
                      - "https://xxx.com/video/test2.mp4"
                  PlayIndex:
                    type: number
                    description: Index of the currently playing media resource. Returns 0 after the player is destroyed.
                    example: 0
      example:
        Code: 0
        Message: "succeed"
        RequestId: "abcd123"
        Data:
          TotalSize: 1
          NextPageToken: ""
          Players:
            - PlayerId: "player_1"
              RoomId: "room_12"
              StreamId: "stream"
              CreateTime: 1681221508
              PlayTime: 1681221508
              PlayerName: "player_1"
              StreamUrl: "https://xxx.com/video/test.mp4"
              Status: 4
              DestroyReason: 1
              StreamUrlList: []
              PlayIndex: 0

