openapi: 3.0.0
info:
  title: Cloud Player Server API - Shared Components
  version: 1.0.0

# Shared server configuration
servers:
  - url: https://cloud-player-api.zego.im
    description: Unified access address (region-independent)
  - url: https://cloud-player-api-sha.zego.im
    description: Mainland China (Shanghai)
  - url: https://cloud-player-api-hkg.zego.im
    description: Hong Kong, Macao and Taiwan (Hong Kong)
  - url: https://cloud-player-api-fra.zego.im
    description: Europe (Frankfurt)
  - url: https://cloud-player-api-lax.zego.im
    description: West US (California)
  - url: https://cloud-player-api-bom.zego.im
    description: Asia Pacific (Mumbai)
  - url: https://cloud-player-api-sgp.zego.im
    description: Southeast Asia (Singapore)

# This file is only used to define shared components and does not contain specific API endpoints
paths: {}

components:
  parameters:
    # Common request parameters
    AppId:
      name: AppId
      in: query
      description: 💡Common parameter. Application Id, a unique user credential assigned by ZEGOCLOUD. Can be obtained from <a target="_blank" href="https://console.zegocloud.com/">ZEGOCLOUD Console</a>.
      required: true
      schema:
        type: number
        format: uint32

    SignatureNonce:
      name: SignatureNonce
      in: query
      description: 💡Common parameter. 16-digit hexadecimal random string (hex encoding of 8-byte random number). For the generation algorithm, please refer to <a href="/cloud-player-server/accessing-server-apis#signature-example">Signature Example</a>.
      required: true
      schema:
        type: string

    Timestamp:
      name: Timestamp
      in: query
      description: 💡Common parameter. Current Unix timestamp, unit is seconds. For the generation algorithm, please refer to <a href="/cloud-player-server/accessing-server-apis#signature-example">Signature Example</a>, a maximum error of 10 minutes is allowed.
      required: true
      schema:
        type: number
        format: int64

    SignatureVersion:
      name: SignatureVersion
      in: query
      description: 💡Common parameter. Signature version number.
      required: true
      schema:
        type: string
        default: "2.0"
        enum: ["2.0"]

    Signature:
      name: Signature
      in: query
      description: 💡Common parameter. Signature, used to verify the legitimacy of the request. Please refer to <a href="/cloud-player-server/accessing-server-apis#signature-mechanism">Signature Mechanism</a> for generation.
      required: true
      schema:
        type: string

