openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: './shared-components.yaml#/servers'

paths:
  /:
    post:
      tags:
        - player
      summary: UpdatePlayer
      description: |
        Call this API to update the playback progress, audio transcoding parameters, video transcoding parameters, and other information of the specified cloud player.

        <Note title="Note">Call frequency limit: 20 times/second</Note>
      operationId: update-player
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://cloud-player-api.zego.im?Action=UpdatePlayer
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [UpdatePlayer]
          style: form
          explode: true
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePlayerRequest'
      responses:
        '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/UpdatePlayerResponse'

components:
  schemas:
    UpdatePlayerRequest:
      type: object
      required: [PlayerId,Sequence]
      properties:
        PlayerId:
          type: string
          description: |
            Cloud player unique identifier ID, returned by [CreatePlayer](/cloud-player-server/create-player).
            <b>When calling this API, please ensure that the PlayerId exists, otherwise an error may occur.</b>
          example: "player_1"
        Sequence:
          type: number
          description: |
            Request sequence number, used to ensure timing. Parameter modifications for the same player task need to ensure the sequence number is incremented. For example, "Sequence": 1. The ZEGOCLOUD server will update the cloud player according to the latest configuration.
          example: 100
        StreamUrl:
          type: string
          maxLength: 1024
          description: |
            Address of the media resource, must be a valid HTTP/HTTPS address with a length within 1024 bytes.
            > **Warning**
            >
            > This needs to be selected based on whether a single player or a list player was created when [creating a cloud player](/cloud-player-server/create-player).
            >
            > - When creating a single player, the `StreamUrl` parameter is optional, `StreamUrlList` is not optional;
            > - When creating a list player, the `StreamUrlList` parameter is optional, `StreamUrl` is not optional.
            >
            > <b>If `StreamUrl` or `StreamUrlList` is filled in here, other parameters will be ignored.</b>
          example: "https://xxx.com/video/test111.mp4"
        StreamUrlList:
          type: array
          description: |
            Media resource list address. Updating the list will reset the media resource list and immediately start playing from the first resource in the new list.
            > **Warning**
            >
            > This needs to be selected based on whether a single player or a list player was created when [creating a cloud player](/cloud-player-server/create-player).
            >
            > - When creating a single player, the `StreamUrl` parameter is optional, `StreamUrlList` is not optional;
            > - When creating a list player, the `StreamUrlList` parameter is optional, `StreamUrl` is not optional.
            >
            > <b>If `StreamUrl` or `StreamUrlList` is filled in here, other parameters will be ignored.</b>
          items:
            type: string
          example:
            - "https://xxx.com/video/test1.mp4"
            - "https://xxx.com/video/test2.mp4"
        BackupStreamUrl:
          type: string
          maxLength: 1024
          description: Backup address of the media resource, must be a valid HTTP/HTTPS address with a length within 1024 bytes. When the address in the StreamUrl parameter fails to access, the cloud player will attempt to access the backup address.
          example: ""
        VideoOptions:
          type: object
          description: |
            Video transcoding parameter configuration.
            <b>Please note that when this parameter is not filled in, the configuration from the last call to this API or when the cloud player was created will be used by default.</b>
          properties:
            Width:
              type: number
              description: |
                Video width, value range is [1, 3000], unit is px, default value is the width of the original media resource.
                > **Note**
                >
                > <ul><li>When an odd value is passed in the range, it will be automatically rounded up to an even number.</li><li>When either Width or Height parameter is set to 1, it means audio-only stream publishing.</li></ul>
              minimum: 1
              maximum: 3000
              example: 360
            Height:
              type: number
              description: |
                Video height, value range is [1, 3000], unit is px, default value is the height of the original media resource.
                > **Note**
                >
                > <ul><li>When an odd value is passed in the range, it will be automatically rounded up to an even number.</li><li>When either Width or Height parameter is set to 1, it means audio-only stream publishing.</li></ul>
              minimum: 1
              maximum: 3000
              example: 640
            ShortEdge:
              type: number
              format: int
              description: |
                Video short edge length, value range is [0,2160], unit is px. Default value is 0, indicating that the short edge adaptive feature is not enabled.
                > **Note**
                >
                > <ul><li>When an odd value is passed in the range, it will be automatically rounded up to an even number.</li><li>Once the short edge adaptive feature is enabled, it can only be updated, and cannot be cancelled.</li><li>When both ShortEdge and Width/Height are set, Width/Height takes precedence.</li><li>After calculating the short edge, the resolution cannot exceed 4k(3840*2160), otherwise the original media resource width and height will be used.</li></ul>
              minimum: 0
              maximum: 2160
              example: 360
            VideoBitrate:
              type: number
              description: |
                Video bitrate, value range is [1, 50000], unit is kbps.
                <b>Please note that when this parameter is not filled in, the configuration from the last call to this API or when the cloud player was created will be used by default.</b>
              minimum: 1
              maximum: 50000
              example: 1200
          example:
            Width: 360
            Height: 640
            VideoBitrate: 1200
        AudioOptions:
          type: object
          description: |
            Audio transcoding parameter configuration.
            <b>Please note that when this parameter is not filled in, the configuration from the last call to this API or when the cloud player was created will be used by default.</b>
          properties:
            AudioBitrate:
              type: number
              description: |
                Audio bitrate, range is [1, 192], unit is kbps.
                <b>Please note that when this parameter is not filled in, the configuration from the last call to this API or when the cloud player was created will be used by default.</b>
              minimum: 1
              maximum: 192
              example: 48
            Volume:
              type: number
              description: |
                Volume value, range is [0, 200].
                <b>Please note that when this parameter is not filled in, the configuration from the last call to this API or when the cloud player was created will be used by default.</b>
              minimum: 0
              maximum: 200
              example: 150
          example:
            AudioBitrate: 48
            Volume: 150
        SeekTo:
          type: number
          description: |
            Specify playback progress (seconds).
            <b>Please note that when this parameter is not filled in, the configuration from the last call to this API or when the cloud player was created will be used by default.</b>
          example: 10
        IsPause:
          type: number
          enum: [0, 1]
          description: |
            Whether to pause playback.
            - 0: Play source file normally.
            - 1: Pause playing source file.
            > **Warning**
            >
            > When setting pause playback, the StreamUrl parameter cannot be passed, otherwise other parameter configurations will be ignored, causing pause playback to fail.
          example: 1
        RepeatTimes:
          type: number
          description: |
            Number of playbacks.
            - 1: Play media stream 1 time.
            - -1: Automatically loop playback.
            - n: Custom number of media stream playbacks, must be greater than 0.

            <b>Please note that when this parameter is not filled in or the value is 0, the configuration from the last call to this API or when the cloud player was created will be used by default.</b>
          example: 1
      example:
        PlayerId: "player_1"
        Sequence: 100
        StreamUrl: "https://xxx.com/video/test111.mp4"
        BackupStreamUrl: ""
        VideoOptions:
          Width: 360
          Height: 640
          VideoBitrate: 1200
        AudioOptions:
          AudioBitrate: 48
          Volume: 150
        SeekTo: 10
        IsPause: 1
        RepeatTimes: 1

    UpdatePlayerResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Error code.

            The following only lists the return codes related to the API business logic. For the complete return codes, please refer to [Global Return Codes](/cloud-player-server/return-codes).
            <table>
            <thead>
            <tr><th>Return Code</th><th>Description</th><th>Handling Suggestion</th></tr>
            </thead>
            <tbody>
            <tr><td>0</td><td>Success.</td><td>-</td></tr>
            <tr><td>100000004</td><td>Signature expired.</td><td>Please regenerate the signature.</td></tr>
            <tr><td>100000005</td><td>Signature error.</td><td>Please confirm whether the parameters for generating the signature are correct.</td></tr>
            <tr><td>350006001</td><td>API request frequency exceeds the limit.</td><td>Please confirm the QPS limit of the corresponding API and reduce the request frequency.</td></tr>
            <tr><td>350006002</td><td>Gateway verification failed.</td><td>Please contact ZEGOCLOUD Technical Support for assistance.</td></tr>
            <tr><td>350006003</td><td>Invalid input parameter.</td><td>Please adjust the value of the corresponding parameter according to the Message prompt.</td></tr>
            <tr><td>350006006</td><td>Service not activated.</td><td>Please contact ZEGOCLOUD Technical Support to activate the service permission.</td></tr>
            <tr><td>350010000</td><td>System error.</td><td>Please contact ZEGOCLOUD Technical Support for assistance.</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Error description.
          example: "succeed"
        RequestId:
          type: string
          description: Request ID.
          example: "abcd123"
      example:
        Code: 0
        Message: "succeed"
        RequestId: "abcd123"

