openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: './shared-components.yaml#/servers'

tags:
  - docs

paths:
  /:
    post:
      tags: [docs]
      summary: StopTranscode
      description: |
        <Warning title="注意">
          1. 本文档 API 接口均为最新服务端 API v2 接口，后续相关功能的新增都会在此更新。为了给开发者带来更好的体验，ZEGO 推荐开发者使用最新 API v2 接口。
          2. 文件转码旧版 API 仅供 **2021-09-10** 前接入的旧用户维护使用。旧版接口文档请参考 [旧版服务端 API](https://doc-zh.zego.im/article/11997)。
        </Warning>

        ## 描述

        通过本接口取消未开始的文件转码任务，如果转码任务开始后调用此接口会返回错误。

        <Note title="说明">调用频率限制：10 次/秒。</Note>
      operationId: cancel-cvt
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://docs-api.zego.im/?Action=StopTranscode
          required: true
          schema:
            type: string
            enum: [StopTranscode]
          style: form
          explode: true
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StopTranscodeRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopTranscodeResponse'

components:
  schemas:
    StopTranscodeRequest:
      type: object
      required: [TaskId]
      properties:
        TaskId:
          type: string
          description: 文件转码任务 ID。
          example: "task"
    StopTranscodeResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int64
          description: |
            错误码。

            以下仅列出了接口业务相关的返回码，公共返回码请参考 [公共返回码](/super-board-server/common-error-codes)。

            <table>
            <tbody><tr>
            <th>返回码</th>
            <th>说明</th>
            </tr>
            <tr>
            <td>60013</td>
            <td>文件已经完成转码。</td>
            </tr>
            <tr>
            <td>60014</td>
            <td>不存在的文件转码任务 ID。</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: 错误描述。
          example: "succeed"
        RequestId:
          type: string
          description: 请求 ID。
          example: "abcd123"

