openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  - url: https://whiteboard-api.zego.im
    description: 白板权限服务统一接入地址（不区分区域）
  - url: https://whiteboard-api-sha.zego.im
    description: 白板权限服务中国大陆（上海）
  - url: https://whiteboard-api-hkg.zego.im
    description: 白板权限服务港澳台（香港）
  - url: https://whiteboard-api-fra.zego.im
    description: 白板权限服务欧洲（法兰克福）
  - url: https://whiteboard-api-lax.zego.im
    description: 白板权限服务美西（加州）
  - url: https://whiteboard-api-bom.zego.im
    description: 白板权限服务亚太（孟买）
  - url: https://whiteboard-api-sgp.zego.im
    description: 白板权限服务东南亚（新加坡）

tags:
  - whiteboard

paths:
  /:
    get:
      tags: [whiteboard]
      summary: 查询用户权限
      description: |
        调用本接口用来查询用户的白板权限，每次最多允许查询 10 个用户的权限。
        如果查询的用户中没有设置过权限，服务端不会返回该用户的权限数据。
        
        <Note title="说明">调用频率限制：50 次/秒（测试环境：1 次/秒）。</Note>
      operationId: get-white-board-user-auth
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://whiteboard-api.zego.im/?Action=GetWhiteboardUserAuth
          required: true
          schema:
            type: string
            enum: [GetWhiteboardUserAuth]
          style: form
          explode: true
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
        - name: RoomId
          in: query
          description: 需要查询的房间 ID。
          required: true
          schema:
            type: string
          style: form
          explode: true
        - name: UserId
          in: query
          description: 需要查询的用户 ID 集合, 一次最多允许查询 10 个用户。
          required: true
          schema:
            type: array
            items:
              type: string
            maxItems: 10
          style: form
          explode: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetWhiteboardUserAuthResponse'

components:
  schemas:
    GetWhiteboardUserAuthResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            返回码。
            
            以下仅列出了接口业务相关的返回码，公共返回码请参考 [公共返回码](/super-board-server/common-error-codes)。

            <table>
            <tbody><tr>
            <th>返回码</th>
            <th>说明</th>
            </tr>
            <tr>
            <td>120000001</td>
            <td>签名鉴权失败。</td>
            </tr>
            <tr>
            <td>120000002</td>
            <td>输入参数错误。</td>
            </tr>
            <tr>
            <td>120000102</td>
            <td>查询用户权限失败。</td>
            </tr>
            <tr>
            <td>120000107</td>
            <td>获取用户数量超过限制。</td>
            </tr>
            <tr>
            <td>120000301</td>
            <td>房间不存在。</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: 明细。
          example: "SUCCESS"
        RequestId:
          type: string
          description: ZEGO 生成的唯一请求 ID。
          example: "2237080460466033406"
        Data:
          type: array
          description: 如果 Data 为空, 说明该房间没有设置过白板权限。
          items:
            type: object
            properties:
              UserId:
                type: string
                description: 用户 ID。
                example: "jack"
              ModuleAuth:
                type: array
                description: |
                  白板操作权限集合。
                  - 0：没有权限
                  - 1：允许缩放白板
                  - 2：允许滚动白板
                items:
                  type: integer
                  enum: [0, 1, 2]
                example: [1, 2]
              GraphicAuth:
                type: array
                description: |
                  图元操作权限集合。
                  - 0：没有任何操作权限
                  - 2：允许修改其他人创建的图元
                  - 4：允许擦除其他人创建的图元
                  - 8：允许移动其他人创建的图元
                  - 16：允许清空图元
                  - 32：允许创建图元
                items:
                  type: integer
                  enum: [0, 2, 4, 8, 16, 32]
                example: [32, 2]

