openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: './shared-components.yaml#/servers'

tags:
  - docs

paths:
  /:
    post:
      tags: [docs]
      summary: DescribeTranscodeStatus
      description: |

        <Warning title="注意">
          1. 本文档 API 接口均为最新服务端 API v2 接口，后续相关功能的新增都会在此更新。为了给开发者带来更好的体验，ZEGO 推荐开发者使用最新 API v2 接口。
          2. 文件转码旧版 API 仅供 **2021-09-10** 前接入的旧用户维护使用。旧版接口文档请参考 [旧版服务端 API](https://doc-zh.zego.im/article/11997)。
        </Warning>

        ## 描述

        通过本接口查询文件转码任务状态。

        <Note title="说明">调用频率限制：10 次/秒。</Note>
      operationId: query-status
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://docs-api.zego.im/?Action=DescribeTranscodeStatus
          required: true
          schema:
            type: string
            enum: [DescribeTranscodeStatus]
          style: form
          explode: true
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DescribeTranscodeStatusRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeTranscodeStatusResponse'

components:
  schemas:
    DescribeTranscodeStatusRequest:
      type: object
      required: [TaskId]
      properties:
        TaskId:
          type: string
          description: 文件转码任务 ID。
          example: "task"
    DescribeTranscodeStatusResponse:
      type: object
      properties:
        Code:
          type: integer
          format: int64
          description: |
            错误码。

            以下仅列出了接口业务相关的返回码，公共返回码请参考 [公共返回码](/super-board-server/common-error-codes)。

            <table>
            <tbody><tr>
            <th>返回码</th>
            <th>说明</th>
            </tr>
            <tr>
            <td>60013</td>
            <td>文件已经完成转码。</td>
            </tr>
            <tr>
            <td>60014</td>
            <td>不存在的文件转码任务 ID。</td>
            </tr>
            <tr>
            <td>60015</td>
            <td>不支持的源文件类型。</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: 错误描述。
          example: "succeed"
        RequestId:
          type: string
          description: 请求 ID。
          example: "abcd123"
        Data:
          type: object
          description: 响应对象。
          properties:
            FileHash:
              type: string
              description: 源文件哈希。
              example: "abc"
            FileType:
              type: integer
              format: int64
              description: |
                源文件类型参数，可设置为 1、2、4、8、16、32，各参数值说明如下：
                - 1：ppt/pptx（静态文件，目标文件类型对应 256；动态文件，目标文件类型对应 512）
                - 2：doc/docx（目标文件类型对应 256）
                - 4：xls/xlsx（目标文件类型对应 256）
                - 8：PDF（目标文件类型对应 256）
                - 16：jpg/jpeg/png/bmp（目标文件类型对应 16）
                - 32：txt（目标文件类型对应 256）
              example: 1
            DestinationFileType:
              type: integer
              format: int64
              description: |
                目标文件类型参数，可设置为 16、256、512，各参数值说明如下：
                - 16：jpg/jpeg/png/bmp
                - 256：向量和图片
                - 512：动态 PPT
              example: 256
            FileName:
              type: string
              description: 源文件名称。
              example: "demo.pptx"
            FileSize:
              type: integer
              format: int64
              description: 源文件大小，单位为字节。
              example: 1024
            Status:
              type: integer
              format: int64
              description: |
                文件转码状态，详情请参考 status 字段说明表。

                <b>Status 字段取值说明如下</b>
                <table>
                <tbody><tr>
                <th>状态码</th>
                <th>描述</th>
                </tr>
                <tr>
                <td>1</td>
                <td>未上传。</td>
                </tr>
                <tr>
                <td>2</td>
                <td>已上传。</td>
                </tr>
                <tr>
                <td>4</td>
                <td>排队中。</td>
                </tr>
                <tr>
                <td>8</td>
                <td>转码中。</td>
                </tr>
                <tr>
                <td>16</td>
                <td>转码成功。</td>
                </tr>
                <tr>
                <td>32</td>
                <td>转码失败。</td>
                </tr>
                <tr>
                <td>64</td>
                <td>转码任务已取消。</td>
                </tr>
                <tr>
                <td>128</td>
                <td>受密码保护的文档。</td>
                </tr>
                <tr>
                <td>256</td>
                <td>文件内容过大，例如文档页数过多。</td>
                </tr>
                <tr>
                <td>512</td>
                <td>Excel 文件标签数过多。</td>
                </tr>
                <tr>
                <td>1024</td>
                <td>文件内容为空。例如：PPT 内无幻灯片。</td>
                </tr>
                <tr>
                <td>2048</td>
                <td>转码服务器打开文件失败。</td>
                </tr>
                <tr>
                <td>4096</td>
                <td>不支持的目标文件类型。</td>
                </tr>
                <tr>
                <td>8192</td>
                <td>源文件为只读文件。</td>
                </tr>
                <tr>
                <td>16384</td>
                <td>转码服务器下载源文件失败。 可能的原因如下：<ul><li>无法从请求参数中的源文件 URL 下载文件。</li><li>请求参数中的文件哈希值不是 32 位的 MD5 哈希值。</li><li>请求参数中的文件哈希值和根据文件计算的哈希值不匹配。</li></ul></td>
                </tr>
                <tr>
                <td>32768</td>
                <td>检测到源文件中包含了转码工具无法处理的元素，如墨迹涂鸦等，请去掉这些元素后再进行转码。</td>
                </tr>
                <tr>
                <td>32769</td>
                <td>检测到 Word、Excel 和 PowerPoint 文件格式不合法，请确保源文件可以使用 Office 打开再进行转码。</td>
                </tr>
                <tr>
                <td>32770</td>
                <td>要转码的文件存在安全隐患，无法正常打开转码。请确保使用 Office 打开文件时不会提示编辑此文件可能会损害您的计算机</td>
                </tr>
                <tr>
                <td>32771</td>
                <td>动态 PPT 转码结束后，检测到有图片、音视频文件未正常导出，转码服务器将重试转码。</td>
                </tr>
                <tr>
                <td>32772</td>
                <td>文件大小过大，无法转码，请确保文件大小在限制的范围之内。</td>
                </tr>
                <tr>
                <td>32773</td>
                <td>打开文件时弹需要修复文件提示框（文件损坏）。</td>
                </tr>
                <tr>
                <td>32774</td>
                <td>EOF 错误（文件内容不完整）。</td>
                </tr>
                </tbody></table>
              example: 8
            FileId:
              type: string
              description: 转码成功后返回的文件 ID。
              example: "fiaaaa"

