openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  - url: https://whiteboard-api.zego.im）

tags:
  - whiteboard

paths:
  /:
    get:
      tags: [whiteboard]
      summary: 设置房间权限
      description: |
        调用本接口用来设置房间的默认白板权限。
        - 设置成功后，在当前房间的用户使用白板时，默认以这次设置的房间权限为准。
        - 如果单独 [设置了用户的权限](/super-board-server/set-white-board-user-auth)，这个用户使用白板以用户权限为准。
        - 房间销毁时，房间权限也会被清理。房间销毁后，用户后续登录相同 RoomId 的房间，如果要使用房间权限功能，也需要重新设置房间权限。
        
        设置房间默认权限为：

        - 白板可缩放，可滚动翻页。
        - 可以创建图元，可以修改别人的图元。
        <Note title="说明">调用频率限制：50 次/秒（测试环境：1 次/秒）。</Note>
      operationId: set-white-board-room-auth
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://whiteboard-api.zego.im/?Action=SetWhiteboardRoomAuth
          required: true
          schema:
            type: string
            enum: [SetWhiteboardRoomAuth]
          style: form
          explode: true
        - $ref: './shared-components.yaml#/components/parameters/AppId'
        - $ref: './shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: './shared-components.yaml#/components/parameters/Timestamp'
        - $ref: './shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: './shared-components.yaml#/components/parameters/Signature'
        - name: RoomId
          in: query
          description: 需要设置的房间 ID。
          required: true
          schema:
            type: string
          style: form
          explode: true
        - name: ModuleAuth
          in: query
          description: |
            白板操作权限集合，不允许传空数组。
            - 0：没有权限
            - 1：允许缩放白板
            - 2：允许滚动白板

            示例：ModuleAuth[]=1&ModuleAuth[]=2
          required: true
          schema:
            type: array
            items:
              type: number
              enum: [0, 1, 2]
          style: form
          explode: true
        - name: GraphicAuth
          in: query
          description: |
            图元操作权限集合，不允许传空数组。
            - 0：没有任何操作权限
            - 2：允许修改其他人创建的图元
            - 4：允许擦除其他人创建的图元
            - 8：允许移动其他人创建的图元
            - 16：允许清空图元
            - 32：允许创建图元

            示例：GraphicAuth[]=32&GraphicAuth[]=2
          required: true
          schema:
            type: array
            items:
              type: number
              enum: [0, 2, 4, 8, 16, 32]
          style: form
          explode: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetWhiteboardRoomAuthResponse'

components:
  schemas:
    SetWhiteboardRoomAuthResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            返回码。
            
            以下仅列出了接口业务相关的返回码，公共返回码请参考 [公共返回码](/super-board-server/common-error-codes)。

            <table>
            <tbody><tr>
            <th>返回码</th>
            <th>说明</th>
            </tr>
            <tr>
            <td>120000001</td>
            <td>签名鉴权失败。</td>
            </tr>
            <tr>
            <td>120000002</td>
            <td>输入参数错误。</td>
            </tr>
            <tr>
            <td>120000103</td>
            <td>设置房间权限失败。</td>
            </tr>
            <tr>
            <td>120000105</td>
            <td>权限集合传了空数组导致失败。</td>
            </tr>
            <tr>
            <td>120000106</td>
            <td>权限集合设置了不合法的权限数字。</td>
            </tr>
            <tr>
            <td>120000301</td>
            <td>房间不存在。</td>
            </tr>
            </tbody></table>
          example: 0
        Message:
          type: string
          description: 明细。
          example: "SUCCESS"
        RequestId:
          type: string
          description: ZEGO 生成的唯一请求 ID。
          example: "2237080460466033406"

