openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: Unified access address (no regional distinction)
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: Mainland China (Shanghai)
  - url: https://aigc-aiagent-api-hkg.zegotech.cn
    description: Hong Kong, Macao, and Taiwan (Hong Kong)
  - url: https://aigc-aiagent-api-fra.zegotech.cn
    description: Europe (Frankfurt)
  - url: https://aigc-aiagent-api-lax.zegotech.cn
    description: Western United States (California)
  - url: https://aigc-aiagent-api-bom.zegotech.cn
    description: Asia-Pacific (Mumbai)
  - url: https://aigc-aiagent-api-sgp.zegotech.cn
    description: Southeast Asia (Singapore)

tags:
  - name: agent-instance-management

paths:
  /:
    post:
      tags:
        - agent-instance-management
      summary: CreateDigitalHumanAgentInstance
      description: |
        With this interface, you can create a digital human agent instance and join the agent instance into a voice (RTC) conversation. 
        
        <Warning title="Note">  
        1. If the RTC room is not occupied by a real user after 120 seconds, the agent instance will be automatically destroyed, and the Event will be AgentInstanceDeleted [callback](/aiagent-server/callbacks/receiving-callback), and the Data.Code will be 1202.
        2. By default, each account can have at most 10 digital human agent instances. If you need to adjust this limit, please contact ZEGOCLOUD Technical Support.
        </Warning>
      operationId: create-digital-human-agent-instance
      parameters:
        - name: Action
          in: query
          description: |
            > Interface prototype parameters
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=CreateDigitalHumanAgentInstance
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [CreateDigitalHumanAgentInstance]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateDigitalHumanAgentInstanceRequest"
            example:
              AgentId: "Jacky"
              UserId: "user_1"
              RTC:
                RoomId: "room_1"
                AgentStreamId: "agent_stream_1"
                AgentUserId: "agent_user_1"
                UserStreamId: "user_stream_1"
              DigitalHuman:
                DigitalHumanId: "xiaozhi"
                ConfigId: "mobile"
                EncodeCode: "H264"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateDigitalHumanAgentInstanceResponse"

components:
  schemas:
    CreateDigitalHumanAgentInstanceRequest:
      type: object
      required:
        - AgentId
        - UserId
        - RTC
        - DigitalHuman
      properties:
        AgentId:
          type: string
          description: The unique identifier of the registered AI agent.
          example: "Jacky"
        UserId:
          type: string
          description: The real user ID used to log in to the RTC room. Only numbers, English characters, '-', and '_' are supported.
          example: "user_1"
          maxLength: 32
        RTC:
          $ref: '../shared-components.yaml#/components/schemas/RTC'
        LLM:
          $ref: '../shared-components.yaml#/components/schemas/LLM'
        TTS:
          $ref: '../shared-components.yaml#/components/schemas/TTS'
        ASR:
          $ref: '../shared-components.yaml#/components/schemas/ASR'
        MessageHistory:
          $ref: '../shared-components.yaml#/components/schemas/MessageHistory'
        CallbackConfig:
          $ref: '../shared-components.yaml#/components/schemas/CallbackConfig'
        AdvancedConfig:
          $ref: '../shared-components.yaml#/components/schemas/AdvancedConfig'
        DigitalHuman:
          $ref: '../shared-components.yaml#/components/schemas/DigitalHuman'

    CreateDigitalHumanAgentInstanceResponse:
      type: object
      properties:
        Code:
          type: integer
          description: Return code. 0 indicates success, other values indicate failure. For more information on error codes and response handling recommendations, please refer to [Return Codes](/aiagent-server/api-reference/return-codes).
          example: 0
        Message:
          type: string
          description: Explanation of the request result
          example: "Success"
        RequestId:
          type: string
          description: Request ID
          example: "8825223157230377926"
        Data:
          type: object
          properties:
            AgentInstanceId:
              type: string
              description: The unique identifier of the AI agent instance.
              example: "1912122918452641792"
            DigitalHumanConfig:
              type: string
              description: Digital human configuration, used by the digital human mobile SDK.
              example: "eyJEaWdpdGFsSHVtYW5JZCI6ImU1ODNkMzVmLTk3OTMtNDJiNC1hYjFiLTE4OWEzNWI4OGQxYyIsIlN0cmVhbXMiOlt7IlJvb21JZCI6ImlyXzU1NTd5bDVoIiwiU3RyZWFtSWQiOiJpcl81NTU3eWw1aF8xNzEwMl9hZ2VudCIsIkVuY29kZUNvZGUiOiJIMjY0IiwiQ29uZmlnSWQiOiJ3ZWIifV19"
