openapi: 3.0.0
info:
  title: open-api-desc

  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: Unified access address (no regional distinction)
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: Mainland China (Shanghai)
  - url: https://aigc-aiagent-api-hkg.zegotech.cn
    description: Hong Kong, Macao, and Taiwan (Hong Kong)
  - url: https://aigc-aiagent-api-fra.zegotech.cn
    description: Europe (Frankfurt)
  - url: https://aigc-aiagent-api-lax.zegotech.cn
    description: Western United States (California)
  - url: https://aigc-aiagent-api-bom.zegotech.cn
    description: Asia-Pacific (Mumbai)
  - url: https://aigc-aiagent-api-sgp.zegotech.cn
    description: Southeast Asia (Singapore)

tags:
  - name: agent-instance-management

paths:
  /:
    post:
      tags:
        - agent-instance-management
      summary: CreateAgentInstance
      description: |
        By calling this interface, you can create an AI agent instance and add it to a voice (RTC) conversation.

        <Warning title="Note">
        1. If there is no real user in the RTC room after 120 seconds, the AI agent instance will automatically be destroyed, and the Event will be AgentInstanceDeleted [callback](/aiagent-server/callbacks/receiving-callback), and the Data.Code will be 1202.
        2. By default, each account can have at most 10 AI agent instances. If the limit is exceeded, the creation of an AI agent instance will fail. If you need to adjust this limit, please contact ZEGOCLOUD Technical Support.
        </Warning>
      operationId: create-agent-instance
      parameters:
        - name: Action
          in: query
          description: |
            > API Prototype Parameter
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=CreateAgentInstance
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [CreateAgentInstance]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAgentInstanceRequest"
            example:
              AgentId: "Jacky"
              UserId: "user_1"
              RTC:
                RoomId: "room_1"
                AgentStreamId: "agent_stream_1"
                AgentUserId: "agent_user_1"
                UserStreamId: "user_stream_1"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateAgentInstanceResponse"

components:
  schemas:
    CreateAgentInstanceRequest:
      type: object
      required:
        - AgentId
        - UserId
        - RTC
      properties:
        AgentId:
          type: string
          description: The unique identifier of the registered AI agent.
          example: "Jacky"
        UserId:
          type: string
          description: The real user ID used to log in to the RTC room. Only numbers, English characters, '-', and '_' are supported.
          example: "user_1"
          maxLength: 32
        RTC:
          $ref: '../shared-components.yaml#/components/schemas/RTC'
        LLM:
          $ref: '../shared-components.yaml#/components/schemas/LLM'
        TTS:
          $ref: '../shared-components.yaml#/components/schemas/TTS'
        ASR:
          $ref: '../shared-components.yaml#/components/schemas/ASR'
        MessageHistory:
          $ref: '../shared-components.yaml#/components/schemas/MessageHistory'
        CallbackConfig:
          $ref: '../shared-components.yaml#/components/schemas/CallbackConfig'
        AdvancedConfig:
          $ref: '../shared-components.yaml#/components/schemas/AdvancedConfig'

    CreateAgentInstanceResponse:
      type: object
      properties:
        Code:
          type: integer
          description: Return code. 0 indicates success, other values indicate failure. For more information on error codes and response handling recommendations, please refer to [Return Codes](/aiagent-server/api-reference/return-codes).
          example: 0
        Message:
          type: string
          description: Explanation of the request result
          example: "Success"
        RequestId:
          type: string
          description: Request ID
          example: "8825223157230377926"
        Data:
          type: object
          properties:
            AgentInstanceId:
              type: string
              description: The unique identifier of the AI agent instance.
              example: "1912122918452641792"
