openapi: 3.0.0
info:
  title: ZIM Server API - 共享组件
  version: 1.0.0

# 共享的服务器配置（ZIM 与鉴权服务）
servers:
  - url: https://zim-api.zego.im
    description: 统一接入地址（不区分区域）
  - url: https://zim-api-sha.zego.im
    description: 中国大陆（上海）
  - url: https://zim-api-hkg.zego.im
    description: 港澳台（香港）
  - url: https://zim-api-fra.zego.im
    description: 欧洲（法兰克福）
  - url: https://zim-api-lax.zego.im
    description: 美西（加州）
  - url: https://zim-api-bom.zego.im
    description: 亚太（孟买）
  - url: https://zim-api-sgp.zego.im
    description: 东南亚（新加坡）
  - url: https://auth-api.zego.im
    description: 鉴权服务统一接入地址

components:
  parameters:
    AppId:
      $ref: "../../../../snippets/common/zh/openapi/zego-shared-components.yaml#/components/parameters/AppId"
    SignatureNonce:
      $ref: "../../../../snippets/common/zh/openapi/zego-shared-components.yaml#/components/parameters/SignatureNonce"
    Timestamp:
      $ref: "../../../../snippets/common/zh/openapi/zego-shared-components.yaml#/components/parameters/Timestamp"
    SignatureVersion:
      $ref: "../../../../snippets/common/zh/openapi/zego-shared-components.yaml#/components/parameters/SignatureVersion"
    Signature:
      $ref: "../../../../snippets/common/zh/openapi/zego-shared-components.yaml#/components/parameters/Signature"

