openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

paths:
  /:
    get:
      summary: Obtain a license
      description: Obtain the ZIM Audio license file.
      operationId: obtain-a-license
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=CgiDescribeZIMAudioLicense
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [CgiDescribeZIMAudioLicense]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/obtain-a-license'

components:
  schemas:
    obtain-a-license:
      type: object
      properties:
        Code:
          type: integer
          description: |
            Return code.

            The following only lists the return codes related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            <table>
            <thead>
            <tr><th>Return code</th><th>Description</th><th>Suggested Solution</th></tr>
            </thead>
            <tbody>
            <tr><td>910001</td><td>Parameter error.</td><td>Please check the parameters.</td></tr>
            <tr><td>910002</td><td>Invalid certificate.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
            <tr><td>910003</td><td>Internal service issue.</td><td>Please contact technical support.</td></tr>
            <tr><td>910004</td><td>Authorization information error.</td><td>Please check the authentication information in the public parameters.</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Description of the request result.
          example: "Success."
        Data:
          type: object
          description: 'When "Code" is 0, this parameter is the license file.'
          properties:
            License:
              type: string
              description: Content of the license file, which can be reused within 7 days.
              example: "1234567890QWERTYUIOASDFGHJKLZXCVNM"
      example:
        Code: 0
        Message: "Success."
        Data:
          License: "1234567890QWERTYUIOASDFGHJKLZXCVNM"