openapi: 3.0.0
info:
  title: Real-time Voice/Video Shared Components
  version: 1.0.0

# Shared server configurations (RTC product)
servers:
  - url: https://rtc-api.zego.im
    description: Unified access address (region-independent)
  - url: https://rtc-api-sha.zego.im
    description: China (Shanghai)
  - url: https://rtc-api-hkg.zego.im
    description: Hong Kong, Macao, and Taiwan (Hong Kong)
  - url: https://rtc-api-fra.zego.im
    description: Europe (Frankfurt)
  - url: https://rtc-api-lax.zego.im
    description: West US (California)
  - url: https://rtc-api-bom.zego.im
    description: Asia Pacific (Mumbai)
  - url: https://rtc-api-sgp.zego.im
    description: Southeast Asia (Singapore)

components:
  parameters:
    # Re-export ZEGOCLOUD global shared parameters for convenient local reference
    AppId:
      $ref: "../../../../../snippets/common/en/openapi/zego-shared-components.yaml#/components/parameters/AppId"
    SignatureNonce:
      name: SignatureNonce
      in: query
      description: 💡Common parameter. A 16-character hexadecimal random string (hex-encoded 8-byte random number). For the generation algorithm, refer to the <a href="/real-time-video-server/api-reference/accessing-server-apis#signature-example">signature example</a>.
      required: true
      schema:
        type: string
    Timestamp:
      name: Timestamp
      in: query
      description: 💡Common parameter. Current Unix timestamp in seconds. For the generation algorithm, refer to the <a href="/real-time-video-server/api-reference/accessing-server-apis#signature-example">signature example</a>. A maximum deviation of 10 minutes is allowed.
      required: true
      schema:
        type: integer
        format: int64
    SignatureVersion:
      $ref: "../../../../../snippets/common/en/openapi/zego-shared-components.yaml#/components/parameters/SignatureVersion"
    Signature:
      name: Signature
      in: query
      description: 💡Common parameter. Signature used to verify the legitimacy of the request. Please refer to the [signature mechanism](/real-time-video-server/api-reference/accessing-server-apis#signature-mechanism) to generate it.
      required: true
      schema:
        type: string

